In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Admission_predict.csv")

In [3]:
data

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [4]:
#1.Display all rows where GRE Score is greater than 320.
data[data["GRE Score"]>320]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
3,4,322,110,3,3.5,2.5,8.67,1,0.80
5,6,330,115,5,4.5,3.0,9.34,1,0.90
6,7,321,109,3,3.0,4.0,8.20,1,0.75
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [5]:
#2.Show applicants whose TOEFL Score is less than 100.
data[data['TOEFL Score']<100]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
27,28,298,98,2,1.5,2.5,7.50,1,0.44
28,29,295,93,1,2.0,2.0,7.20,0,0.46
29,30,310,99,2,1.5,2.0,7.30,0,0.54
30,31,300,97,2,3.0,3.0,8.10,1,0.65
50,51,313,98,3,2.5,4.5,8.30,1,0.76
57,58,298,99,2,4.0,2.0,7.60,0,0.46
58,59,300,99,1,3.0,2.0,6.80,1,0.36
77,78,301,99,2,3.0,2.0,8.22,0,0.64
78,79,296,95,2,3.0,2.0,7.54,1,0.44
79,80,294,93,1,1.5,2.0,7.36,0,0.46
91,92,299,97,3,5.0,3.5,7.66,0,0.38
92,93,298,98,2,4.0,3.0,8.03,0,0.34
93,94,301,97,2,3.0,3.0,7.88,1,0.44
94,95,303,99,3,2.0,2.5,7.66,0,0.36
118,119,296,99,2,3.0,3.5,7.28,0,0.47
161,162,298,99,1,1.5,3.0,7.46,0,0.53
168,169,293,97,2,2.0,4.0,7.80,1,0.64
169,170,311,99,2,2.5,3.0,7.98,0,0.65
205,206,295,99,2,2.5,3.0,7.65,0,0.57
206,207,315,99,2,3.5,3.0,7.89,0,0.63
225,226,296,99,2,2.5,2.5,8.03,0,0.61
251,252,316,99,2,2.5,3.0,9.00,0,0.70
256,257,309,99,3,4.0,4.0,8.56,0,0.76
271,272,299,96,2,1.5,2.0,7.86,0,0.54
272,273,294,95,1,1.5,1.5,7.64,0,0.49
273,274,312,99,1,1.0,1.5,8.01,1,0.52
292,293,302,99,2,1.0,2.0,7.97,0,0.56
293,294,312,98,1,3.5,3.0,8.18,1,0.64
317,318,300,99,1,1.0,2.5,8.01,0,0.58
329,330,297,96,2,2.5,1.5,7.89,0,0.43
344,345,295,96,2,1.5,2.0,7.34,0,0.47
345,346,316,98,1,1.5,2.0,7.43,0,0.49
346,347,304,97,2,1.5,2.0,7.64,0,0.47
347,348,299,94,1,1.0,1.0,7.34,0,0.42
348,349,302,99,1,2.0,2.0,7.25,0,0.57
354,355,297,98,2,2.5,3.0,7.67,0,0.59
367,368,311,98,1,1.0,2.5,7.46,0,0.57
368,369,298,92,1,2.0,2.0,7.88,0,0.51
369,370,301,98,1,2.0,3.0,8.03,1,0.67
376,377,297,96,2,2.5,2.0,7.43,0,0.34
378,379,303,98,1,2.0,2.5,7.65,0,0.56
379,380,311,99,1,2.5,3.0,8.43,1,0.71
388,389,296,97,2,1.5,2.0,7.80,0,0.49

In [6]:
#3.Get records where University Rating equals 5.
data[data['University Rating']==5]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
5,6,330,115,5,4.5,3.0,9.34,1,0.90
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
24,25,336,119,5,4.0,3.5,9.80,1,0.97
25,26,340,120,5,4.5,4.5,9.60,1,0.94
26,27,322,109,5,4.5,3.5,8.80,0,0.76
33,34,340,114,5,4.0,4.0,9.60,1,0.90
34,35,331,112,5,4.0,5.0,9.80,1,0.94
35,36,320,110,5,5.0,5.0,9.20,1,0.88
44,45,326,113,5,4.5,4.0,9.40,1,0.91
45,46,322,110,5,5.0,4.0,9.10,1,0.88
46,47,329,114,5,4.0,5.0,9.30,1,0.86
47,48,339,119,5,4.5,4.0,9.70,0,0.89
70,71,332,118,5,5.0,5.0,9.64,1,0.94
71,72,336,112,5,5.0,5.0,9.76,1,0.96
72,73,321,111,5,5.0,5.0,9.45,1,0.93
82,83,320,110,5,5.0,4.5,9.22,1,0.92
83,84,322,115,5,4.0,4.5,9.36,1,0.92
84,85,340,115,5,4.5,4.5,9.45,1,0.94
108,109,331,116,5,5.0,5.0,9.38,1,0.93
109,110,304,103,5,5.0,4.0,8.64,0,0.68
110,111,305,108,5,3.0,3.0,8.48,0,0.61
119,120,327,104,5,3.0,3.5,8.84,1,0.71
120,121,335,117,5,5.0,5.0,9.56,1,0.94
121,122,334,119,5,4.5,4.5,9.48,1,0.94
129,130,333,118,5,5.0,5.0,9.35,1,0.92
130,131,339,114,5,4.0,4.5,9.76,1,0.96
131,132,303,105,5,5.0,4.5,8.65,0,0.77
132,133,309,105,5,3.5,3.5,8.56,0,0.71
133,134,323,112,5,4.0,4.5,8.78,0,0.79
134,135,333,113,5,4.0,4.0,9.28,1,0.89
142,143,331,115,5,4.0,3.5,9.44,1,0.92
151,152,332,116,5,5.0,5.0,9.28,1,0.94
152,153,321,112,5,5.0,5.0,9.06,1,0.86
165,166,322,110,5,4.5,4.0,8.97,0,0.78
171,172,334,117,5,4.0,4.5,9.07,1,0.89
187,188,335,118,5,4.5,3.5,9.44,1,0.93
188,189,331,115,5,4.5,3.5,9.36,1,0.93
189,190,324,112,5,5.0,5.0,9.08,1,0.88
190,191,324,111,5,4.5,4.0,9.16,1,0.90
191,192,323,110,5,4.0,5.0,8.98,1,0.87
192,193,322,114,5,4.5,4.0,8.94,1,0.86
193,194,336,118,5,4.5,5.0,9.53,1,0.94
202,203,340,120,5,4.5,4.5,9.91,1,0.97
203,204,334,120,5,4.0,5.0,9.87,1,0.97
213,214,333,119,5,5.0,4.5,9.78,1,0.96
215,216,330,116,5,5.0,4.5,9.36,1,0.93
234,235,330,113,5,5.0,4.0,9.31,1,0.91
235,236,326,111,5,4.5,4.0,9.23,1,0.88
237,238,329,114,5,4.5,5.0,9.19,1,0.86
260,261,327,108,5,5.0,3.5,9.13,1,0.87
276,277,329,113,5,5.0,4.5,9.45,1,0.89
285,286,331,116,5,4.0,4.0,9.26,1,0.93
286,287,336,118,5,4.5,4.0,9.19,1,0.92
287,288,324,114,5,5.0,4.5,9.08,1,0.89
337,338,332,118,5,5.0,5.0,9.47,1,0.94
338,339,323,108,5,4.0,4.0,8.74,1,0.81
339,340,324,107,5,3.5,4.0,8.66,1,0.81
362,363,338,115,5,4.5,5.0,9.23,1,0.91
385,386,335,117,5,5.0,5.0,9.82,1,0.96

In [7]:
#4.Select all students who have done Research (value 1).
data[data["Research"]==1]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
5,6,330,115,5,4.5,3.0,9.34,1,0.90
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [8]:
#5.Display students who have not done Research (value 0).
data[data["Research"]==0]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
4,5,314,103,2,2.0,3.0,8.21,0,0.65
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
9,10,323,108,3,3.5,3.0,8.60,0,0.45
15,16,314,105,3,3.5,2.5,8.30,0,0.54
...,...,...,...,...,...,...,...,...,...
388,389,296,97,2,1.5,2.0,7.80,0,0.49
390,391,314,102,2,2.0,2.5,8.24,0,0.64
391,392,318,106,3,2.0,3.0,8.65,0,0.71
393,394,317,104,2,3.0,3.0,8.76,0,0.77
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [9]:
#6.Find applicants with CGPA greater than 9.0.
data[data['CGPA']>9.0]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
5,6,330,115,5,4.5,3.0,9.34,1,0.90
12,13,328,112,4,4.0,4.5,9.10,1,0.78
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [10]:
#7.Retrieve records where both GRE Score &gt; 320 and CGPA &gt; 9.0.
data[(data['GRE Score']>320) & (data["CGPA"]>9.0)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
5,6,330,115,5,4.5,3.0,9.34,1,0.90
12,13,328,112,4,4.0,4.5,9.10,1,0.78
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
...,...,...,...,...,...,...,...,...,...
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [11]:
#8.Display records where either SOP or LOR rating is 5.0.
data[(data['SOP']==5.0)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
35,36,320,110,5,5.0,5.0,9.20,1,0.88
45,46,322,110,5,5.0,4.0,9.10,1,0.88
70,71,332,118,5,5.0,5.0,9.64,1,0.94
71,72,336,112,5,5.0,5.0,9.76,1,0.96
72,73,321,111,5,5.0,5.0,9.45,1,0.93
81,82,340,120,4,5.0,5.0,9.50,1,0.96
82,83,320,110,5,5.0,4.5,9.22,1,0.92
91,92,299,97,3,5.0,3.5,7.66,0,0.38
98,99,332,119,4,5.0,4.5,9.24,1,0.90
108,109,331,116,5,5.0,5.0,9.38,1,0.93
109,110,304,103,5,5.0,4.0,8.64,0,0.68
120,121,335,117,5,5.0,5.0,9.56,1,0.94
129,130,333,118,5,5.0,5.0,9.35,1,0.92
131,132,303,105,5,5.0,4.5,8.65,0,0.77
136,137,312,103,3,5.0,4.0,8.45,0,0.76
151,152,332,116,5,5.0,5.0,9.28,1,0.94
152,153,321,112,5,5.0,5.0,9.06,1,0.86
189,190,324,112,5,5.0,5.0,9.08,1,0.88
211,212,328,110,4,5.0,4.0,9.14,1,0.82
212,213,338,120,4,5.0,5.0,9.66,1,0.95
213,214,333,119,5,5.0,4.5,9.78,1,0.96
215,216,330,116,5,5.0,4.5,9.36,1,0.93
234,235,330,113,5,5.0,4.0,9.31,1,0.91
258,259,326,102,4,5.0,5.0,8.76,1,0.77
259,260,331,119,4,5.0,4.5,9.34,1,0.90
260,261,327,108,5,5.0,3.5,9.13,1,0.87
276,277,329,113,5,5.0,4.5,9.45,1,0.89
284,285,340,112,4,5.0,4.5,9.66,1,0.94
287,288,324,114,5,5.0,4.5,9.08,1,0.89
288,289,314,104,4,5.0,5.0,9.02,0,0.82
337,338,332,118,5,5.0,5.0,9.47,1,0.94
384,385,340,113,4,5.0,5.0,9.74,1,0.96
385,386,335,117,5,5.0,5.0,9.82,1,0.96
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [12]:
#9.Get rows where Chance of Admit is above 0.8 and University Rating ≥ 4.
#data[(data['Chance of Admit'] > 0.8)]# & (data["University Rating"] >= 4)]

In [13]:
data[(data["University Rating"] >= 4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
5,6,330,115,5,4.5,3.0,9.34,1,0.90
11,12,327,111,4,4.0,4.5,9.00,1,0.84
12,13,328,112,4,4.0,4.5,9.10,1,0.78
...,...,...,...,...,...,...,...,...,...
385,386,335,117,5,5.0,5.0,9.82,1,0.96
392,393,326,112,4,4.0,3.5,9.12,1,0.84
394,395,329,111,4,4.5,4.0,9.23,1,0.89
397,398,330,116,4,5.0,4.5,9.45,1,0.91
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [14]:
#10.Find all rows where TOEFL Score is between 100 and 110.
data[(data["TOEFL Score"]>100) & (data["TOEFL Score"]<110)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
4,5,314,103,2,2.0,3.0,8.21,0,0.65
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
...,...,...,...,...,...,...,...,...,...
390,391,314,102,2,2.0,2.5,8.24,0,0.64
391,392,318,106,3,2.0,3.0,8.65,0,0.71
393,394,317,104,2,3.0,3.0,8.76,0,0.77
396,397,325,107,3,3.0,3.5,9.11,1,0.84
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [15]:
#11.Display data for students whose GRE Score is not equal to 300.
data[data['TOEFL Score'] != 300]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95

In [16]:
#12.Show all students with CGPA less than 8 and Research = 1.
data[(data["CGPA"]<8) & (data["Research"]==1)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
20,21,312,107,3,3.0,2.0,7.90,1,0.64
27,28,298,98,2,1.5,2.5,7.50,1,0.44
51,52,312,100,2,1.5,3.5,7.90,1,0.56
58,59,300,99,1,3.0,2.0,6.80,1,0.36
78,79,296,95,2,3.0,2.0,7.54,1,0.44
90,91,318,106,2,4.0,4.0,7.92,1,0.64
93,94,301,97,2,3.0,3.0,7.88,1,0.44
168,169,293,97,2,2.0,4.0,7.80,1,0.64
357,358,301,104,2,3.5,3.5,7.89,1,0.68

In [17]:
#13.Retrieve rows where University Rating &lt; 3 and SOP &gt; 4.
data[(data["University Rating"]<3) & (data["SOP"]>4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
103,104,317,104,2,4.5,4.0,8.47,0,0.57
138,139,326,116,2,4.5,3.0,9.08,1,0.80
141,142,332,118,2,4.5,3.5,9.36,1,0.90

In [18]:
#14.Get records of students having TOEFL Score &gt; 105 but GRE Score &lt; 310.
data[(data["TOEFL Score"]>105) & (data["GRE Score"]<310)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
13,14,307,109,3,4.0,3.0,8.00,1,0.62
36,37,299,106,2,4.0,4.0,8.40,0,0.64
39,40,307,108,2,4.0,3.5,7.70,0,0.48
40,41,308,110,3,3.5,3.0,8.00,1,0.46
110,111,305,108,5,3.0,3.0,8.48,0,0.61
112,113,301,107,3,3.5,3.5,8.34,1,0.62
123,124,308,108,3,3.5,3.5,8.22,0,0.61
124,125,301,106,4,2.5,3.0,8.47,0,0.57
158,159,306,106,2,2.0,2.5,8.14,0,0.61
178,179,309,108,3,2.5,3.0,8.12,0,0.72
181,182,305,107,2,2.5,2.5,8.42,0,0.71
195,196,307,107,2,3.0,3.5,8.52,1,0.78
208,209,305,106,2,3.0,3.0,8.16,0,0.64
223,224,308,109,2,3.0,4.0,8.45,0,0.71
226,227,306,110,2,3.5,4.0,8.45,0,0.63
255,256,307,110,4,4.0,4.5,8.37,0,0.79
269,270,308,108,4,4.5,5.0,8.34,0,0.77
299,300,305,112,3,3.0,3.5,8.65,0,0.71
300,301,309,106,2,2.5,2.5,8.00,0,0.62
309,310,308,110,4,3.5,3.0,8.60,0,0.70
332,333,308,106,3,3.5,2.5,8.21,1,0.75
342,343,308,106,3,3.0,3.0,8.24,0,0.58

In [19]:
#15.Display records where Chance of Admit &lt; 0.6 or GRE Score &lt; 300.
#data[(data["Chance of Admit"]<0.6) or (data["GRE Score"]<300)]

In [20]:
#16.Find the top 10 students with the highest GRE Score.
data["GRE Score"].nlargest(10)

25     340
33     340
81     340
84     340
143    340
202    340
284    340
384    340
47     339
130    339
Name: GRE Score, dtype: int64

In [21]:
data.nlargest(10,"GRE Score")

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
25,26,340,120,5,4.5,4.5,9.60,1,0.94
33,34,340,114,5,4.0,4.0,9.60,1,0.90
81,82,340,120,4,5.0,5.0,9.50,1,0.96
84,85,340,115,5,4.5,4.5,9.45,1,0.94
143,144,340,120,4,4.5,4.0,9.92,1,0.97
202,203,340,120,5,4.5,4.5,9.91,1,0.97
284,285,340,112,4,5.0,4.5,9.66,1,0.94
384,385,340,113,4,5.0,5.0,9.74,1,0.96
47,48,339,119,5,4.5,4.0,9.70,0,0.89
130,131,339,114,5,4.0,4.5,9.76,1,0.96

In [22]:
data["GRE Score"].unique()

array([337, 324, 316, 322, 314, 330, 321, 308, 302, 323, 325, 327, 328,
       307, 311, 317, 319, 318, 303, 312, 334, 336, 340, 298, 295, 310,
       300, 338, 331, 320, 299, 304, 313, 332, 326, 329, 339, 309, 315,
       301, 296, 294, 306, 305, 290, 335, 333, 297, 293])

In [23]:
#17.Display applicants who scored exactly 4.5 in LOR.
#data[data["LOR"]==4.5]

In [24]:
#18.Select students whose SOP rating lies between 3 and 4 (inclusive).
data[(data['SOP']>3) & (data['SOP']<4)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
3,4,322,110,3,3.5,2.5,8.67,1,0.80
9,10,323,108,3,3.5,3.0,8.60,0,0.45
10,11,325,106,3,3.5,4.0,8.40,1,0.52
14,15,311,104,3,3.5,2.0,8.20,1,0.61
15,16,314,105,3,3.5,2.5,8.30,0,0.54
...,...,...,...,...,...,...,...,...,...
371,372,324,110,3,3.5,3.0,9.22,1,0.89
380,381,322,104,3,3.5,4.0,8.84,1,0.78
389,390,320,108,3,3.5,4.0,8.44,1,0.76
395,396,324,110,3,3.5,3.5,9.04,1,0.82
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [25]:
#19.Display all students whose University Rating is either 2 or 3.
data[(data['University Rating']==2) | (data['University Rating']==3)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
...,...,...,...,...,...,...,...,...,...
391,392,318,106,3,2.0,3.0,8.65,0,0.71
393,394,317,104,2,3.0,3.0,8.76,0,0.77
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [26]:
#20.Filter rows where CGPA is an integer value (e.g., 8.0, 9.0).
data[data["CGPA"] % 1 == 0]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.0,1,0.72
8,9,302,102,1,2.0,1.5,8.0,0,0.50
11,12,327,111,4,4.0,4.5,9.0,1,0.84
13,14,307,109,3,4.0,3.0,8.0,1,0.62
17,18,319,106,3,4.0,3.0,8.0,1,0.65
40,41,308,110,3,3.5,3.0,8.0,1,0.46
52,53,334,116,4,4.0,3.0,8.0,1,0.78
54,55,322,110,3,3.0,3.5,8.0,0,0.70
96,97,306,100,2,3.0,3.0,8.0,0,0.48
251,252,316,99,2,2.5,3.0,9.0,0,0.70
289,290,313,109,3,4.0,3.5,9.0,0,0.79
300,301,309,106,2,2.5,2.5,8.0,0,0.62
307,308,325,112,4,4.0,4.0,9.0,1,0.80
312,313,311,107,4,4.5,4.5,9.0,1,0.78

In [27]:
#21.Retrieve records where Chance of Admit is between 0.5 and 0.7.
#data[(data['Chance of Admit']>0.5) & (data['Chance of Admit']<0.7)]

In [28]:
#22.Select students who scored below average GRE Score.
avg=data["GRE Score"].mean()
data[data['GRE Score']<avg]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
2,3,316,104,3,3.0,3.5,8.00,1,0.72
4,5,314,103,2,2.0,3.0,8.21,0,0.65
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
13,14,307,109,3,4.0,3.0,8.00,1,0.62
...,...,...,...,...,...,...,...,...,...
386,387,302,101,2,2.5,3.5,7.96,0,0.46
387,388,307,105,2,2.0,3.5,8.10,0,0.53
388,389,296,97,2,1.5,2.0,7.80,0,0.49
390,391,314,102,2,2.0,2.5,8.24,0,0.64
398,399,312,103,3,3.5,4.0,8.78,0,0.67

In [29]:
#23.Show all records where TOEFL Score equals the dataset’s maximum TOEFL Score.
max_toefl=data['TOEFL Score'].max()
data[data['TOEFL Score']==max_toefl]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
25,26,340,120,5,4.5,4.5,9.60,1,0.94
81,82,340,120,4,5.0,5.0,9.50,1,0.96
97,98,331,120,3,4.0,4.0,8.96,1,0.86
143,144,340,120,4,4.5,4.0,9.92,1,0.97
202,203,340,120,5,4.5,4.5,9.91,1,0.97
203,204,334,120,5,4.0,5.0,9.87,1,0.97
212,213,338,120,4,5.0,5.0,9.66,1,0.95
297,298,320,120,3,4.0,4.5,9.11,0,0.86

In [30]:
#24.Filter students who have both LOR and SOP less than 3.
data[(data['SOP']<3)]

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
4,5,314,103,2,2.0,3.0,8.21,0,0.65
8,9,302,102,1,2.0,1.5,8.00,0,0.50
27,28,298,98,2,1.5,2.5,7.50,1,0.44
28,29,295,93,1,2.0,2.0,7.20,0,0.46
29,30,310,99,2,1.5,2.0,7.30,0,0.54
...,...,...,...,...,...,...,...,...,...
386,387,302,101,2,2.5,3.5,7.96,0,0.46
387,388,307,105,2,2.0,3.5,8.10,0,0.53
388,389,296,97,2,1.5,2.0,7.80,0,0.49
390,391,314,102,2,2.0,2.5,8.24,0,0.64
391,392,318,106,3,2.0,3.0,8.65,0,0.71

In [31]:
#25.Retrieve students who have GRE Score divisible by 5.  Add a new column named GRE_to_TOEFL_Ratio = GRE Score / TOEFL Score.
div=data[data["GRE Score"]%5==0]

In [32]:
div

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
5,6,330,115,5,4.5,3.0,9.34,1,0.90
10,11,325,106,3,3.5,4.0,8.40,1,0.52
21,22,325,114,4,3.0,2.0,8.40,0,0.70
25,26,340,120,5,4.5,4.5,9.60,1,0.94
28,29,295,93,1,2.0,2.0,7.20,0,0.46
...,...,...,...,...,...,...,...,...,...
384,385,340,113,4,5.0,5.0,9.74,1,0.96
385,386,335,117,5,5.0,5.0,9.82,1,0.96
389,390,320,108,3,3.5,4.0,8.44,1,0.76
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91

In [33]:
data["GRE_to_TOEFL_Ratio"]=div["GRE Score"]/div["TOEFL Score"]

In [34]:
data

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,GRE_to_TOEFL_Ratio
0,1,337,118,4,4.5,4.5,9.65,1,0.92,NaN
1,2,324,107,4,4.0,4.5,8.87,1,0.76,NaN
2,3,316,104,3,3.0,3.5,8.00,1,0.72,NaN
3,4,322,110,3,3.5,2.5,8.67,1,0.80,NaN
4,5,314,103,2,2.0,3.0,8.21,0,0.65,NaN
...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82,NaN
396,397,325,107,3,3.0,3.5,9.11,1,0.84,3.037383
397,398,330,116,4,5.0,4.5,9.45,1,0.91,2.844828
398,399,312,103,3,3.5,4.0,8.78,0,0.67,NaN
399,400,333,117,4,5.0,4.0,9.66,1,0.95,NaN

In [35]:
#26.Create a new column Admission_Chance_% = Chance of Admit × 100.
#data["Admission_Chance_%"]=data['Chance of Admit']*100

In [36]:
#27.Rename the column Chance of Admit to Admit_Probability.
data.rename(columns={"Chance of Admit":"Admit_Probability"},inplace=True)

In [37]:
data

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,GRE_to_TOEFL_Ratio
0,1,337,118,4,4.5,4.5,9.65,1,0.92,NaN
1,2,324,107,4,4.0,4.5,8.87,1,0.76,NaN
2,3,316,104,3,3.0,3.5,8.00,1,0.72,NaN
3,4,322,110,3,3.5,2.5,8.67,1,0.80,NaN
4,5,314,103,2,2.0,3.0,8.21,0,0.65,NaN
...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82,NaN
396,397,325,107,3,3.0,3.5,9.11,1,0.84,3.037383
397,398,330,116,4,5.0,4.5,9.45,1,0.91,2.844828
398,399,312,103,3,3.5,4.0,8.78,0,0.67,NaN
399,400,333,117,4,5.0,4.0,9.66,1,0.95,NaN

In [38]:
#28.Change all column names to lowercase.
data.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit ', 'GRE_to_TOEFL_Ratio'],
      dtype='object')

In [39]:
data.columns=data.columns.str.lower()

In [40]:
data.columns

Index(['serial no.', 'gre score', 'toefl score', 'university rating', 'sop',
       'lor ', 'cgpa', 'research', 'chance of admit ', 'gre_to_toefl_ratio'],
      dtype='object')

In [41]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio
0,1,337,118,4,4.5,4.5,9.65,1,0.92,NaN
1,2,324,107,4,4.0,4.5,8.87,1,0.76,NaN
2,3,316,104,3,3.0,3.5,8.00,1,0.72,NaN
3,4,322,110,3,3.5,2.5,8.67,1,0.80,NaN
4,5,314,103,2,2.0,3.0,8.21,0,0.65,NaN
...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,0.82,NaN
396,397,325,107,3,3.0,3.5,9.11,1,0.84,3.037383
397,398,330,116,4,5.0,4.5,9.45,1,0.91,2.844828
398,399,312,103,3,3.5,4.0,8.78,0,0.67,NaN
399,400,333,117,4,5.0,4.0,9.66,1,0.95,NaN

In [42]:
#29.Drop the column Serial No..
data.drop("serial no.",axis=1)

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio
0,337,118,4,4.5,4.5,9.65,1,0.92,NaN
1,324,107,4,4.0,4.5,8.87,1,0.76,NaN
2,316,104,3,3.0,3.5,8.00,1,0.72,NaN
3,322,110,3,3.5,2.5,8.67,1,0.80,NaN
4,314,103,2,2.0,3.0,8.21,0,0.65,NaN
...,...,...,...,...,...,...,...,...,...
395,324,110,3,3.5,3.5,9.04,1,0.82,NaN
396,325,107,3,3.0,3.5,9.11,1,0.84,3.037383
397,330,116,4,5.0,4.5,9.45,1,0.91,2.844828
398,312,103,3,3.5,4.0,8.78,0,0.67,NaN
399,333,117,4,5.0,4.0,9.66,1,0.95,NaN

In [43]:
#30.Round all values in CGPA to one decimal place.
data["cgpa"]=data["cgpa"].round(decimals=1)

In [44]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio
0,1,337,118,4,4.5,4.5,9.6,1,0.92,NaN
1,2,324,107,4,4.0,4.5,8.9,1,0.76,NaN
2,3,316,104,3,3.0,3.5,8.0,1,0.72,NaN
3,4,322,110,3,3.5,2.5,8.7,1,0.80,NaN
4,5,314,103,2,2.0,3.0,8.2,0,0.65,NaN
...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.0,1,0.82,NaN
396,397,325,107,3,3.0,3.5,9.1,1,0.84,3.037383
397,398,330,116,4,5.0,4.5,9.4,1,0.91,2.844828
398,399,312,103,3,3.5,4.0,8.8,0,0.67,NaN
399,400,333,117,4,5.0,4.0,9.7,1,0.95,NaN

In [45]:
#31.Replace all University Rating values of 5 with 10.
data["university rating"]=data["university rating"].replace(5,10)

In [46]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio
0,1,337,118,4,4.5,4.5,9.6,1,0.92,NaN
1,2,324,107,4,4.0,4.5,8.9,1,0.76,NaN
2,3,316,104,3,3.0,3.5,8.0,1,0.72,NaN
3,4,322,110,3,3.5,2.5,8.7,1,0.80,NaN
4,5,314,103,2,2.0,3.0,8.2,0,0.65,NaN
...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.0,1,0.82,NaN
396,397,325,107,3,3.0,3.5,9.1,1,0.84,3.037383
397,398,330,116,4,5.0,4.5,9.4,1,0.91,2.844828
398,399,312,103,3,3.5,4.0,8.8,0,0.67,NaN
399,400,333,117,4,5.0,4.0,9.7,1,0.95,NaN

In [47]:
data["university rating"].unique()

array([ 4,  3,  2, 10,  1])

In [48]:
#32.Convert Research column values from 0/1 to “No”/“Yes”.
data["research"].unique()

array([1, 0])

In [49]:
data["research"]=data["research"].replace((0,1),("No","Yes"))

In [50]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio
0,1,337,118,4,4.5,4.5,9.6,Yes,0.92,NaN
1,2,324,107,4,4.0,4.5,8.9,Yes,0.76,NaN
2,3,316,104,3,3.0,3.5,8.0,Yes,0.72,NaN
3,4,322,110,3,3.5,2.5,8.7,Yes,0.80,NaN
4,5,314,103,2,2.0,3.0,8.2,No,0.65,NaN
...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.0,Yes,0.82,NaN
396,397,325,107,3,3.0,3.5,9.1,Yes,0.84,3.037383
397,398,330,116,4,5.0,4.5,9.4,Yes,0.91,2.844828
398,399,312,103,3,3.5,4.0,8.8,No,0.67,NaN
399,400,333,117,4,5.0,4.0,9.7,Yes,0.95,NaN

In [51]:
#33.Create a new column GRE_Level = “High” if GRE ≥ 320 else “Low”.
def convert(x):
    if x>=320:
        return "High"
    else:
        return "Low"
data["GRE_Level"]=data["gre score"].apply(convert)

In [52]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level
0,1,337,118,4,4.5,4.5,9.6,Yes,0.92,NaN,High
1,2,324,107,4,4.0,4.5,8.9,Yes,0.76,NaN,High
2,3,316,104,3,3.0,3.5,8.0,Yes,0.72,NaN,Low
3,4,322,110,3,3.5,2.5,8.7,Yes,0.80,NaN,High
4,5,314,103,2,2.0,3.0,8.2,No,0.65,NaN,Low
...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.0,Yes,0.82,NaN,High
396,397,325,107,3,3.0,3.5,9.1,Yes,0.84,3.037383,High
397,398,330,116,4,5.0,4.5,9.4,Yes,0.91,2.844828,High
398,399,312,103,3,3.5,4.0,8.8,No,0.67,NaN,Low
399,400,333,117,4,5.0,4.0,9.7,Yes,0.95,NaN,High

In [53]:
#34.Normalize CGPA column to range 0–1 using min-max scaling (without sklearn).
data["Normalized"]=(data["cgpa"]-data["cgpa"].min())/(data["cgpa"].max()-data["cgpa"].min())

In [54]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized
0,1,337,118,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226
1,2,324,107,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419
2,3,316,104,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097
3,4,322,110,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903
4,5,314,103,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613
...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677
396,397,325,107,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935
397,398,330,116,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710
398,399,312,103,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161
399,400,333,117,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484

In [55]:
#35.Increase all TOEFL Score values by 2 points.
data["toefl score"]=data["toefl score"]+2

In [56]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613
...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484

In [57]:
#36.Add a column Weighted_Score = GRE Score * 0.3 + TOEFL Score * 0.2 + CGPA * 0.5.
data["Weighted_Score"]=data["gre score"]*0.3 + data["toefl score"]*0.2 + data["cgpa"]*0.5

In [58]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized,Weighted_Score
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55

In [59]:
#37.Drop all duplicate rows if any.
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
395    False
396    False
397    False
398    False
399    False
Length: 400, dtype: bool

In [60]:
data.drop_duplicates(inplace=True)

In [61]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized,Weighted_Score
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55

In [62]:
#38.Replace all SOP values less than 2 with the mean SOP.
sop_mean=data["sop"].mean()

In [63]:
sop_mean

np.float64(3.4)

In [64]:
data["sop"].unique()

array([4.5, 4. , 3. , 3.5, 2. , 5. , 1.5, 1. , 2.5])

In [65]:
def sop_re(x):
    if x<2:
        return sop_mean
    else:
        return x

In [66]:
data['sop']=data['sop'].apply(sop_re)

In [67]:
data["sop"].unique()

array([4.5, 4. , 3. , 3.5, 2. , 5. , 3.4, 2.5])

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   serial no.          400 non-null    int64
 1   gre score           400 non-null    int64
 2   toefl score         400 non-null    int64
 3   university rating   400 non-null    int64
 4   sop                 400 non-null    float64
 5   lor                 400 non-null    float64
 6   cgpa                400 non-null    float64
 7   research            400 non-null    object
 8   chance of admit     400 non-null    float64
 9   gre_to_toefl_ratio  84 non-null     float64
 10  GRE_Level           400 non-null    object
 11  Normalized          400 non-null    float64
 12  Weighted_Score      400 non-null    float64
dtypes: float64(7), int64(4), object(2)
memory usage: 40.8+ KB

In [69]:
#39.Create a new column combining University Rating and Research (e.g.,&quot;Rating-Research&quot;).
data["Rating-Research"]=data["university rating"].astype('str') +" "+ data["research"]

In [70]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized,Weighted_Score,Rating-Research
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90,4 Yes
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45,4 Yes
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00,3 Yes
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35,3 Yes
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30,2 No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10,3 Yes
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85,3 Yes
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30,4 Yes
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00,3 No
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55,4 Yes

In [71]:
#40.Convert Chance of Admit to categorical bins: “Low”, “Medium”, “High”.

In [72]:
#41.Add a constant column Country with value “India”.
data["Country"]="India"

In [73]:
data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized,Weighted_Score,Rating-Research,Country
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90,4 Yes,India
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45,4 Yes,India
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00,3 Yes,India
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35,3 Yes,India
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30,2 No,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10,3 Yes,India
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85,3 Yes,India
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30,4 Yes,India
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00,3 No,India
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55,4 Yes,India

In [74]:
#42.Reorder columns so that Chance of Admit comes first.
#new_order=['chance of admit','gre score','toefl score','university rating','sop','lor','research','serial no.']
#new=data[new_order]

In [75]:
#43.Replace values in LOR column where rating is 5 with 4.9.
#data["lor"]=data['lor'].replace(5,4.9)

In [76]:
#44.Convert all float columns to integers (after rounding).
data1=[]
data1=pd.DataFrame(data1)
data1["sop"]=data["sop"].astype("int")
data1["cgpa"]=data["cgpa"].astype("int")
data1["Weighted_Score"]=data["Weighted_Score"].astype("int")

In [77]:
data1

     sop  cgpa  Weighted_Score
0      4     9             129
1      4     8             123
2      3     8             120
3      3     8             123
4      2     8             119
..   ...   ...             ...
395    3     9             124
396    3     9             123
397    5     9             127
398    3     8             119
399    5     9             128

[400 rows x 3 columns]

In [78]:
#45.Replace CGPA values above 9.5 with 9.5.
def cgpa(x):
    if x>9.5:
        return 9.5
    else:
        return x
new_data=data
new_data["cgpa"].apply(cgpa)

0      9.5
1      8.9
2      8.0
3      8.7
4      8.2
      ...
395    9.0
396    9.1
397    9.4
398    8.8
399    9.5
Name: cgpa, Length: 400, dtype: float64

In [79]:
new_data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized,Weighted_Score,Rating-Research,Country
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90,4 Yes,India
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45,4 Yes,India
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00,3 Yes,India
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35,3 Yes,India
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30,2 No,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10,3 Yes,India
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85,3 Yes,India
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30,4 Yes,India
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00,3 No,India
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55,4 Yes,India

In [80]:
#46.Apply a lambda function to square all SOP values.
new_data["sop"].apply(lambda x:x*x)

0      20.25
1      16.00
2       9.00
3      12.25
4       4.00
       ...
395    12.25
396     9.00
397    25.00
398    12.25
399    25.00
Name: sop, Length: 400, dtype: float64

In [81]:
new_data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized,Weighted_Score,Rating-Research,Country
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90,4 Yes,India
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45,4 Yes,India
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00,3 Yes,India
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35,3 Yes,India
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30,2 No,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10,3 Yes,India
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85,3 Yes,India
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30,4 Yes,India
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00,3 No,India
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55,4 Yes,India

In [82]:
#47.Add a column GRE_Category = “Below Avg”, “Avg”, “Above Avg” based on mean GRE.
mean=new_data["gre score"].mean()
def category(x):
    if x<mean:
        return "Below Avg"
    elif x==mean:
        return "Avg"
    else:
        return "Above Avg"
new_data["gre score"].apply(category)

0      Above Avg
1      Above Avg
2      Below Avg
3      Above Avg
4      Below Avg
         ...
395    Above Avg
396    Above Avg
397    Above Avg
398    Below Avg
399    Above Avg
Name: gre score, Length: 400, dtype: object

In [83]:
new_data

,serial no.,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit,gre_to_toefl_ratio,GRE_Level,Normalized,Weighted_Score,Rating-Research,Country
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90,4 Yes,India
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45,4 Yes,India
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00,3 Yes,India
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35,3 Yes,India
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30,2 No,India
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10,3 Yes,India
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85,3 Yes,India
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30,4 Yes,India
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00,3 No,India
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55,4 Yes,India

In [84]:
#48.Standardize column names to snake_case (lowercase, replace spaces with _).
new_data.columns

Index(['serial no.', 'gre score', 'toefl score', 'university rating', 'sop',
       'lor ', 'cgpa', 'research', 'chance of admit ', 'gre_to_toefl_ratio',
       'GRE_Level', 'Normalized', 'Weighted_Score', 'Rating-Research',
       'Country'],
      dtype='object')

In [85]:
new_data.columns=new_data.columns.str.lower()

In [86]:
new_data.columns=new_data.columns.str.replace(" ","_")

In [87]:
#49.Create a new column showing difference between TOEFL Score and GRE Score/4.
new_data["difference"]=data['gre_score'] - new_data["toefl_score"]

In [88]:
data.columns

Index(['serial_no.', 'gre_score', 'toefl_score', 'university_rating', 'sop',
       'lor_', 'cgpa', 'research', 'chance_of_admit_', 'gre_to_toefl_ratio',
       'gre_level', 'normalized', 'weighted_score', 'rating-research',
       'country', 'difference'],
      dtype='object')

In [89]:
new_data.columns

Index(['serial_no.', 'gre_score', 'toefl_score', 'university_rating', 'sop',
       'lor_', 'cgpa', 'research', 'chance_of_admit_', 'gre_to_toefl_ratio',
       'gre_level', 'normalized', 'weighted_score', 'rating-research',
       'country', 'difference'],
      dtype='object')

In [90]:
data['lor_']

0      4.5
1      4.5
2      3.5
3      2.5
4      3.0
      ...
395    3.5
396    3.5
397    4.5
398    4.0
399    4.0
Name: lor_, Length: 400, dtype: float64

In [91]:
#50.Find the average GRE Score for each University Rating.
data["university_rating"].unique()

array([ 4,  3,  2, 10,  1])

In [92]:
data["university_rating"].value_counts()

university_rating
3     133
2     107
4      74
10     60
1      26
Name: count, dtype: int64

In [93]:
for_3=data[data["university_rating"]==3]

In [94]:
for_3["gre_score"].mean()

np.float64(315.9548872180451)

In [95]:
for_2=data[data["university_rating"]==2]
for_2["gre_score"].mean()

np.float64(309.1775700934579)

In [96]:
for_4=data[data["university_rating"]==4]
for_4["gre_score"].mean()

np.float64(324.8243243243243)

In [97]:
for_10=data[data["university_rating"]==10]
for_10["gre_score"].mean()

np.float64(328.3333333333333)

In [98]:
for_1=data[data["university_rating"]==1]
for_1["gre_score"].mean()

np.float64(303.15384615384613)

In [99]:
#51.Get the mean CGPA for students with and without research.
with_research=data[data["research"]=="Yes"]
with_research['cgpa'].mean()

np.float64(8.88082191780822)

In [100]:
without_research=data[data["research"]=="No"]
without_research['cgpa'].mean()

np.float64(8.256906077348066)

In [101]:
#52.Count how many applicants have each University Rating.
data["university_rating"].value_counts()

university_rating
3     133
2     107
4      74
10     60
1      26
Name: count, dtype: int64

In [102]:
#53.Find the total number of students in each Research category.
data["research"].value_counts()

research
Yes    219
No     181
Name: count, dtype: int64

In [103]:
#54.Group by University Rating and show average TOEFL Score.
g=data.groupby("university_rating")['toefl_score'].mean()

In [104]:
g

university_rating
1     101.076923
2     105.523364
3     108.887218
4     113.824324
10    115.666667
Name: toefl_score, dtype: float64

In [105]:
#55.Get the maximum Chance of Admit for each Research group.
r_group=data.groupby("research")['chance_of_admit_'].max()

In [106]:
r_group

research
No     0.89
Yes    0.97
Name: chance_of_admit_, dtype: float64

In [107]:
#56.Find minimum SOP value per University Rating.
u_group=data.groupby("university_rating")['sop'].min()

In [108]:
u_group

university_rating
1     2.0
2     2.0
3     2.0
4     2.0
10    3.0
Name: sop, dtype: float64

In [109]:
gre=data[data["gre_score"]>=320]

In [110]:
#57.Count number of students with GRE Score ≥ 320 for each University Rating.
u_group_gre_score=gre.groupby("university_rating")['university_rating'].value_counts()

In [111]:
u_group_gre_score

university_rating
2     11
3     49
4     59
10    56
Name: count, dtype: int64

In [112]:
#58.Calculate median CGPA grouped by Research.
group_r=data.groupby("research")['cgpa'].median()

In [113]:
group_r

research
No     8.3
Yes    9.0
Name: cgpa, dtype: float64

In [114]:
#59.Get the number of students per combination of University Rating and Research.
group_u_and_r=data.groupby(["university_rating",'research'])["university_rating"].value_counts()

In [115]:
group_u_and_r

university_rating  research
1                  No          21
                   Yes          5
2                  No          75
                   Yes         32
3                  No          62
                   Yes         71
4                  No          15
                   Yes         59
10                 No           8
                   Yes         52
Name: count, dtype: int64

In [116]:
#60.Find the mean GRE Score grouped by both Research and SOP.
group_r_and_s=data.groupby(['research','sop'])["gre_score"].mean()

In [117]:
group_r_and_s

research  sop
No        2.0    308.481481
          2.5    307.696970
          3.0    311.352941
          3.4    301.409091
          3.5    310.925926
          4.0    311.476190
          4.5    320.833333
          5.0    306.400000
Yes       2.0    309.166667
          2.5    315.571429
          3.0    316.800000
          3.4    309.500000
          3.5    319.023256
          4.0    325.653061
          4.5    328.000000
          5.0    330.218750
Name: gre_score, dtype: float64

In [118]:
#61.For each University Rating, find both min and max TOEFL Score.
group_u=data.groupby("university_rating")

In [119]:
group_u['toefl_score'].min()

university_rating
1      94
2      97
3      99
4     102
10    105
Name: toefl_score, dtype: int64

In [120]:
group_u['toefl_score'].max()

university_rating
1     111
2     120
3     122
4     122
10    122
Name: toefl_score, dtype: int64

In [121]:
#62.Display number of unique GRE Score values per University Rating.
group_u["gre_score"].unique()

university_rating
1     [302, 295, 300, 304, 294, 318, 297, 315, 298, ...
2     [314, 308, 298, 310, 300, 299, 307, 316, 313, ...
3     [316, 322, 321, 323, 325, 307, 311, 314, 317, ...
4     [337, 324, 327, 328, 325, 338, 332, 334, 314, ...
10    [330, 328, 334, 336, 340, 322, 331, 320, 326, ...
Name: gre_score, dtype: object

In [122]:
#63.Find the average of all numeric columns grouped by Research.
group_r=data.groupby('research')

In [123]:
group_r["gre_score"].mean()

research
No     309.491713
Yes    322.853881
Name: gre_score, dtype: float64

In [124]:
group_r["toefl_score"].mean()

research
No     106.143646
Yes    112.109589
Name: toefl_score, dtype: float64

In [125]:
group_r["university_rating"].mean()

research
No     2.745856
Yes    4.739726
Name: university_rating, dtype: float64

In [126]:
group_r["sop"].mean()

research
No     3.153591
Yes    3.842922
Name: sop, dtype: float64

In [127]:
group_r["lor_"].mean()

research
No     3.060773
Yes    3.776256
Name: lor_, dtype: float64

In [128]:
group_r["cgpa"].mean()

research
No     8.256906
Yes    8.880822
Name: cgpa, dtype: float64

In [129]:
group_r["chance_of_admit_"].mean()

research
No     0.637680
Yes    0.795982
Name: chance_of_admit_, dtype: float64

In [130]:
data

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
0,1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90,4 Yes,India,217
1,2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45,4 Yes,India,215
2,3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00,3 Yes,India,210
3,4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35,3 Yes,India,210
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30,2 No,India,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10,3 Yes,India,212
396,397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85,3 Yes,India,216
397,398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30,4 Yes,India,212
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00,3 No,India,207
399,400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55,4 Yes,India,214

In [131]:
#64.Get the count of applicants having CGPA &gt; 9 grouped by Research.
data[data["cgpa"]>9].groupby("research")["cgpa"].value_counts()

research  cgpa
No        9.1      5
          9.7      1
Yes       9.1     21
          9.2     21
          9.4     16
          9.3      9
          9.5      7
          9.8      7
          9.6      6
          9.7      6
          9.9      3
Name: count, dtype: int64

In [132]:
#65.For each SOP rating, find mean Chance of Admit.
group_sop=data.groupby("sop")

In [133]:
group_sop["chance_of_admit_"].mean()

sop
2.0    0.602727
2.5    0.651277
3.0    0.683594
3.4    0.525385
3.5    0.713571
4.0    0.778000
4.5    0.843962
5.0    0.883514
Name: chance_of_admit_, dtype: float64

In [134]:
#66.Calculate mean and std deviation of GRE Score per University Rating.
group_u["gre_score"].mean()

university_rating
1     303.153846
2     309.177570
3     315.954887
4     324.824324
10    328.333333
Name: gre_score, dtype: float64

In [135]:
group_u["gre_score"].std()

university_rating
1     7.918042
2     8.503954
3     7.748768
4     9.917962
10    8.524475
Name: gre_score, dtype: float64

In [136]:
group_u["gre_score"].agg(['mean','std'])

                         mean       std
university_rating
1                  303.153846  7.918042
2                  309.177570  8.503954
3                  315.954887  7.748768
4                  324.824324  9.917962
10                 328.333333  8.524475

In [137]:
#67.Get total number of students whose Chance of Admit &gt; 0.8 per Research.
data[data["chance_of_admit_"]>0.8].groupby("research")["chance_of_admit_"].value_counts()

research  chance_of_admit_
No        0.82                 2
          0.81                 1
          0.83                 1
          0.85                 1
          0.86                 1
          0.87                 1
          0.89                 1
Yes       0.94                12
          0.84                 9
          0.93                 9
          0.89                 8
          0.90                 8
          0.81                 7
          0.86                 7
          0.91                 7
          0.96                 7
          0.82                 6
          0.92                 6
          0.85                 5
          0.87                 4
          0.88                 4
          0.95                 4
          0.97                 4
          0.83                 2
Name: count, dtype: int64

In [138]:
#68.Find number of records for each distinct combination of University Rating, SOP, and LOR.
data.groupby(["university_rating",'sop','lor_']).size()

university_rating  sop  lor_
1                  2.0  1.5      1
                        2.0      3
                        2.5      2
                        3.0      1
                   2.5  3.0      2
                                ..
10                 4.5  5.0      3
                   5.0  3.5      1
                        4.0      3
                        4.5      7
                        5.0     13
Length: 121, dtype: int64

In [139]:
#69.Get the highest GRE Score among students with Research = 0.
gre=data[data["research"]=="No"]

In [140]:
gre

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
4,5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30,2 No,India,209
7,8,308,103,2,3.0,4.0,7.9,No,0.68,NaN,Low,0.354839,116.95,2 No,India,205
8,9,302,104,1,2.0,1.5,8.0,No,0.50,NaN,Low,0.387097,115.40,1 No,India,198
9,10,323,110,3,3.5,3.0,8.6,No,0.45,NaN,High,0.580645,123.20,3 No,India,213
15,16,314,107,3,3.5,2.5,8.3,No,0.54,NaN,Low,0.483871,119.75,3 No,India,207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,389,296,99,2,3.4,2.0,7.8,No,0.49,NaN,Low,0.322581,112.50,2 No,India,197
390,391,314,104,2,2.0,2.5,8.2,No,0.64,NaN,Low,0.451613,119.10,2 No,India,210
391,392,318,108,3,2.0,3.0,8.6,No,0.71,NaN,Low,0.580645,121.30,3 No,India,210
393,394,317,106,2,3.0,3.0,8.8,No,0.77,NaN,Low,0.645161,120.70,2 No,India,211
398,399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00,3 No,India,207

In [141]:
gre["gre_score"].max()

339

In [142]:
#70.Find how many students in each Research category have CGPA &gt; 9.
data[data["cgpa"]>9].groupby("research")["cgpa"].value_counts()

research  cgpa
No        9.1      5
          9.7      1
Yes       9.1     21
          9.2     21
          9.4     16
          9.3      9
          9.5      7
          9.8      7
          9.6      6
          9.7      6
          9.9      3
Name: count, dtype: int64

In [143]:
#71.Calculate total GRE Score for each University Rating.
group_u["gre_score"].sum()

university_rating
1      7882
2     33082
3     42022
4     24037
10    19700
Name: gre_score, dtype: int64

In [144]:
#72.Find mean Chance of Admit for each unique LOR score.
group_lor=data.groupby('lor_')

In [145]:
group_lor["chance_of_admit_"].mean()

lor_
1.0    0.420000
1.5    0.567143
2.0    0.563158
2.5    0.632564
3.0    0.674235
3.5    0.721096
4.0    0.776364
4.5    0.858444
5.0    0.883429
Name: chance_of_admit_, dtype: float64

In [146]:
#73.Get number of students with same TOEFL Score grouped by that score.
group_toefl=data.groupby("toefl_score")

In [147]:
group_toefl["toefl_score"].value_counts()

toefl_score
94      1
95      2
96      1
97      2
98      4
99      6
100     9
101    18
102    19
103    11
104    17
105    16
106    25
107    28
108    24
109    26
110    17
111    17
112    37
113    17
114    21
115    14
116    15
117     9
118    11
119     7
120     9
121     9
122     8
Name: count, dtype: int64

In [148]:
#74.Find the group with the maximum average Chance of Admit.
gr=data.groupby('chance_of_admit_')

In [149]:
gr["chance_of_admit_"].mean()

chance_of_admit_
0.34    0.34
0.36    0.36
0.38    0.38
0.39    0.39
0.42    0.42
0.43    0.43
0.44    0.44
0.45    0.45
0.46    0.46
0.47    0.47
0.48    0.48
0.49    0.49
0.50    0.50
0.51    0.51
0.52    0.52
0.53    0.53
0.54    0.54
0.55    0.55
0.56    0.56
0.57    0.57
0.58    0.58
0.59    0.59
0.60    0.60
0.61    0.61
0.62    0.62
0.63    0.63
0.64    0.64
0.65    0.65
0.66    0.66
0.67    0.67
0.68    0.68
0.69    0.69
0.70    0.70
0.71    0.71
0.72    0.72
0.73    0.73
0.74    0.74
0.75    0.75
0.76    0.76
0.77    0.77
0.78    0.78
0.79    0.79
0.80    0.80
0.81    0.81
0.82    0.82
0.83    0.83
0.84    0.84
0.85    0.85
0.86    0.86
0.87    0.87
0.88    0.88
0.89    0.89
0.90    0.90
0.91    0.91
0.92    0.92
0.93    0.93
0.94    0.94
0.95    0.95
0.96    0.96
0.97    0.97
Name: chance_of_admit_, dtype: float64

In [150]:
#75.Sort dataset by GRE Score in descending order.
data.sort_values(by="gre_score",ascending=False)

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
25,26,340,122,10,4.5,4.5,9.6,Yes,0.94,2.833333,High,0.903226,131.20,10 Yes,India,218
33,34,340,116,10,4.0,4.0,9.6,Yes,0.90,2.982456,High,0.903226,130.00,10 Yes,India,224
81,82,340,122,4,5.0,5.0,9.5,Yes,0.96,2.833333,High,0.870968,131.15,4 Yes,India,218
84,85,340,117,10,4.5,4.5,9.4,Yes,0.94,2.956522,High,0.838710,130.10,10 Yes,India,223
284,285,340,114,4,5.0,4.5,9.7,Yes,0.94,3.035714,High,0.935484,129.65,4 Yes,India,226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,273,294,97,1,3.4,1.5,7.6,No,0.49,NaN,Low,0.258065,111.40,1 No,India,197
79,80,294,95,1,3.4,2.0,7.4,No,0.46,NaN,Low,0.193548,110.90,1 No,India,199
168,169,293,99,2,2.0,4.0,7.8,Yes,0.64,NaN,Low,0.322581,111.60,2 Yes,India,194
117,118,290,106,4,2.0,2.5,7.5,No,0.45,2.788462,Low,0.225806,111.95,4 No,India,184
377,378,290,102,1,3.4,2.0,7.6,No,0.47,2.900000,Low,0.258065,111.20,1 No,India,188

In [151]:
#76.Sort by University Rating, then CGPA.
data.sort_values(by="university_rating")

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
28,29,295,95,1,2.0,2.0,7.2,No,0.46,3.172043,Low,0.129032,111.10,1 No,India,200
368,369,298,94,1,2.0,2.0,7.9,No,0.51,NaN,Low,0.354839,112.15,1 No,India,204
369,370,301,100,1,2.0,3.0,8.0,Yes,0.67,NaN,Low,0.387097,114.30,1 Yes,India,201
378,379,303,100,1,2.0,2.5,7.6,No,0.56,NaN,Low,0.258065,114.70,1 No,India,203
377,378,290,102,1,3.4,2.0,7.6,No,0.47,2.900000,Low,0.258065,111.20,1 No,India,188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,132,303,107,10,5.0,4.5,8.6,No,0.77,NaN,Low,0.580645,116.60,10 No,India,196
130,131,339,116,10,4.0,4.5,9.8,Yes,0.96,NaN,High,0.967742,129.80,10 Yes,India,223
129,130,333,120,10,5.0,5.0,9.4,Yes,0.92,NaN,High,0.838710,128.60,10 Yes,India,213
132,133,309,107,10,3.5,3.5,8.6,No,0.71,NaN,Low,0.580645,118.40,10 No,India,202
337,338,332,120,10,5.0,5.0,9.5,Yes,0.94,NaN,High,0.870968,128.35,10 Yes,India,212

In [152]:
data.sort_values(by="cgpa")

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
58,59,300,101,1,3.0,2.0,6.8,Yes,0.36,3.030303,Low,0.000000,113.60,1 Yes,India,199
348,349,302,101,1,2.0,2.0,7.2,No,0.57,NaN,Low,0.129032,114.40,1 No,India,201
28,29,295,95,1,2.0,2.0,7.2,No,0.46,3.172043,Low,0.129032,111.10,1 No,India,200
347,348,299,96,1,3.4,1.0,7.3,No,0.42,NaN,Low,0.161290,112.55,1 No,India,203
344,345,295,98,2,3.4,2.0,7.3,No,0.47,3.072917,Low,0.161290,111.75,2 No,India,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,25,336,121,10,4.0,3.5,9.8,Yes,0.97,NaN,High,0.967742,129.90,10 Yes,India,215
71,72,336,114,10,5.0,5.0,9.8,Yes,0.96,NaN,High,0.967742,128.50,10 Yes,India,222
202,203,340,122,10,4.5,4.5,9.9,Yes,0.97,2.833333,High,1.000000,131.35,10 Yes,India,218
143,144,340,122,4,4.5,4.0,9.9,Yes,0.97,2.833333,High,1.000000,131.35,4 Yes,India,218
203,204,334,122,10,4.0,5.0,9.9,Yes,0.97,NaN,High,1.000000,129.55,10 Yes,India,212

In [153]:
#77.Display top 5 rows with highest Chance of Admit.
data.nlargest(5,"chance_of_admit_")

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
24,25,336,121,10,4.0,3.5,9.8,Yes,0.97,NaN,High,0.967742,129.90,10 Yes,India,215
143,144,340,122,4,4.5,4.0,9.9,Yes,0.97,2.833333,High,1.000000,131.35,4 Yes,India,218
202,203,340,122,10,4.5,4.5,9.9,Yes,0.97,2.833333,High,1.000000,131.35,10 Yes,India,218
203,204,334,122,10,4.0,5.0,9.9,Yes,0.97,NaN,High,1.000000,129.55,10 Yes,India,212
71,72,336,114,10,5.0,5.0,9.8,Yes,0.96,NaN,High,0.967742,128.50,10 Yes,India,222

In [154]:
#78.Sort values by TOEFL Score ascending.
data.sort_values("toefl_score")

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
368,369,298,94,1,2.0,2.0,7.9,No,0.51,NaN,Low,0.354839,112.15,1 No,India,204
79,80,294,95,1,3.4,2.0,7.4,No,0.46,NaN,Low,0.193548,110.90,1 No,India,199
28,29,295,95,1,2.0,2.0,7.2,No,0.46,3.172043,Low,0.129032,111.10,1 No,India,200
347,348,299,96,1,3.4,1.0,7.3,No,0.42,NaN,Low,0.161290,112.55,1 No,India,203
78,79,296,97,2,3.0,2.0,7.5,Yes,0.44,NaN,Low,0.225806,111.95,2 Yes,India,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,203,340,122,10,4.5,4.5,9.9,Yes,0.97,2.833333,High,1.000000,131.35,10 Yes,India,218
212,213,338,122,4,5.0,5.0,9.7,Yes,0.95,NaN,High,0.935484,130.65,4 Yes,India,216
203,204,334,122,10,4.0,5.0,9.9,Yes,0.97,NaN,High,1.000000,129.55,10 Yes,India,212
81,82,340,122,4,5.0,5.0,9.5,Yes,0.96,2.833333,High,0.870968,131.15,4 Yes,India,218
25,26,340,122,10,4.5,4.5,9.6,Yes,0.94,2.833333,High,0.903226,131.20,10 Yes,India,218

In [155]:
#79.Set Serial No. as index.
data.set_index("serial_no.",inplace=True)

In [156]:
data

,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
serial_no.,,,,,,,,,,,,,,,
1,337,120,4,4.5,4.5,9.6,Yes,0.92,NaN,High,0.903226,129.90,4 Yes,India,217
2,324,109,4,4.0,4.5,8.9,Yes,0.76,NaN,High,0.677419,123.45,4 Yes,India,215
3,316,106,3,3.0,3.5,8.0,Yes,0.72,NaN,Low,0.387097,120.00,3 Yes,India,210
4,322,112,3,3.5,2.5,8.7,Yes,0.80,NaN,High,0.612903,123.35,3 Yes,India,210
5,314,105,2,2.0,3.0,8.2,No,0.65,NaN,Low,0.451613,119.30,2 No,India,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,324,112,3,3.5,3.5,9.0,Yes,0.82,NaN,High,0.709677,124.10,3 Yes,India,212
397,325,109,3,3.0,3.5,9.1,Yes,0.84,3.037383,High,0.741935,123.85,3 Yes,India,216
398,330,118,4,5.0,4.5,9.4,Yes,0.91,2.844828,High,0.838710,127.30,4 Yes,India,212
399,312,105,3,3.5,4.0,8.8,No,0.67,NaN,Low,0.645161,119.00,3 No,India,207
400,333,119,4,5.0,4.0,9.7,Yes,0.95,NaN,High,0.935484,128.55,4 Yes,India,214

In [177]:
#80.Reset index to default.
data=data.reset_index()

In [178]:
#81.Sort dataset by multiple columns: Research and Chance of Admit.
data.replace(["Yes","No"],[1,0])

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
0,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,High,0.903226,129.90,4 Yes,India,217
1,2,324,109,4,4.0,4.5,8.9,1,0.76,NaN,High,0.677419,123.45,4 Yes,India,215
2,3,316,106,3,3.0,3.5,8.0,1,0.72,NaN,Low,0.387097,120.00,3 Yes,India,210
3,4,322,112,3,3.5,2.5,8.7,1,0.80,NaN,High,0.612903,123.35,3 Yes,India,210
4,5,314,105,2,2.0,3.0,8.2,0,0.65,NaN,Low,0.451613,119.30,2 No,India,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324,112,3,3.5,3.5,9.0,1,0.82,NaN,High,0.709677,124.10,3 Yes,India,212
396,397,325,109,3,3.0,3.5,9.1,1,0.84,3.037383,High,0.741935,123.85,3 Yes,India,216
397,398,330,118,4,5.0,4.5,9.4,1,0.91,2.844828,High,0.838710,127.30,4 Yes,India,212
398,399,312,105,3,3.5,4.0,8.8,0,0.67,NaN,Low,0.645161,119.00,3 No,India,207
399,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,High,0.935484,128.55,4 Yes,India,214

In [179]:
data.sort_values(by=["research","chance_of_admit_"])

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
92,93,298,100,2,4.0,3.0,8.0,0,0.34,NaN,Low,0.387097,113.40,2 No,India,198
376,377,297,98,2,2.5,2.0,7.4,0,0.34,NaN,Low,0.193548,112.40,2 No,India,199
94,95,303,101,3,2.0,2.5,7.7,0,0.36,NaN,Low,0.290323,114.95,3 No,India,202
91,92,299,99,3,5.0,3.5,7.7,0,0.38,NaN,Low,0.290323,113.35,3 No,India,200
375,376,304,103,2,2.0,2.5,7.7,0,0.38,NaN,Low,0.290323,115.65,2 No,India,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,386,335,119,10,5.0,5.0,9.8,1,0.96,2.863248,High,0.967742,129.20,10 Yes,India,216
24,25,336,121,10,4.0,3.5,9.8,1,0.97,NaN,High,0.967742,129.90,10 Yes,India,215
143,144,340,122,4,4.5,4.0,9.9,1,0.97,2.833333,High,1.000000,131.35,4 Yes,India,218
202,203,340,122,10,4.5,4.5,9.9,1,0.97,2.833333,High,1.000000,131.35,10 Yes,India,218
203,204,334,122,10,4.0,5.0,9.9,1,0.97,NaN,High,1.000000,129.55,10 Yes,India,212

In [180]:
#82.Sort all applicants by CGPA then GRE Score descending.
data.sort_values(by="cgpa")

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
58,59,300,101,1,3.0,2.0,6.8,1,0.36,3.030303,Low,0.000000,113.60,1 Yes,India,199
348,349,302,101,1,2.0,2.0,7.2,0,0.57,NaN,Low,0.129032,114.40,1 No,India,201
28,29,295,95,1,2.0,2.0,7.2,0,0.46,3.172043,Low,0.129032,111.10,1 No,India,200
347,348,299,96,1,3.4,1.0,7.3,0,0.42,NaN,Low,0.161290,112.55,1 No,India,203
344,345,295,98,2,3.4,2.0,7.3,0,0.47,3.072917,Low,0.161290,111.75,2 No,India,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,25,336,121,10,4.0,3.5,9.8,1,0.97,NaN,High,0.967742,129.90,10 Yes,India,215
71,72,336,114,10,5.0,5.0,9.8,1,0.96,NaN,High,0.967742,128.50,10 Yes,India,222
202,203,340,122,10,4.5,4.5,9.9,1,0.97,2.833333,High,1.000000,131.35,10 Yes,India,218
143,144,340,122,4,4.5,4.0,9.9,1,0.97,2.833333,High,1.000000,131.35,4 Yes,India,218
203,204,334,122,10,4.0,5.0,9.9,1,0.97,NaN,High,1.000000,129.55,10 Yes,India,212

In [181]:
data.sort_values(by="gre_score",ascending=False)

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
25,26,340,122,10,4.5,4.5,9.6,1,0.94,2.833333,High,0.903226,131.20,10 Yes,India,218
33,34,340,116,10,4.0,4.0,9.6,1,0.90,2.982456,High,0.903226,130.00,10 Yes,India,224
81,82,340,122,4,5.0,5.0,9.5,1,0.96,2.833333,High,0.870968,131.15,4 Yes,India,218
84,85,340,117,10,4.5,4.5,9.4,1,0.94,2.956522,High,0.838710,130.10,10 Yes,India,223
284,285,340,114,4,5.0,4.5,9.7,1,0.94,3.035714,High,0.935484,129.65,4 Yes,India,226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,273,294,97,1,3.4,1.5,7.6,0,0.49,NaN,Low,0.258065,111.40,1 No,India,197
79,80,294,95,1,3.4,2.0,7.4,0,0.46,NaN,Low,0.193548,110.90,1 No,India,199
168,169,293,99,2,2.0,4.0,7.8,1,0.64,NaN,Low,0.322581,111.60,2 Yes,India,194
117,118,290,106,4,2.0,2.5,7.5,0,0.45,2.788462,Low,0.225806,111.95,4 No,India,184
377,378,290,102,1,3.4,2.0,7.6,0,0.47,2.900000,Low,0.258065,111.20,1 No,India,188

In [182]:
#83.Retrieve bottom 10 rows after sorting by GRE Score.
gre_s=data.sort_values(by="gre_score")

In [183]:
gre_s.tail(10)

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
148,149,339,118,4,4.0,3.5,9.8,1,0.96,NaN,High,0.967742,130.20,4 Yes,India,221
47,48,339,121,10,4.5,4.0,9.7,0,0.89,NaN,High,0.935484,130.75,10 No,India,218
33,34,340,116,10,4.0,4.0,9.6,1,0.90,2.982456,High,0.903226,130.00,10 Yes,India,224
81,82,340,122,4,5.0,5.0,9.5,1,0.96,2.833333,High,0.870968,131.15,4 Yes,India,218
84,85,340,117,10,4.5,4.5,9.4,1,0.94,2.956522,High,0.838710,130.10,10 Yes,India,223
143,144,340,122,4,4.5,4.0,9.9,1,0.97,2.833333,High,1.000000,131.35,4 Yes,India,218
202,203,340,122,10,4.5,4.5,9.9,1,0.97,2.833333,High,1.000000,131.35,10 Yes,India,218
384,385,340,115,4,5.0,5.0,9.7,1,0.96,3.008850,High,0.935484,129.85,4 Yes,India,225
284,285,340,114,4,5.0,4.5,9.7,1,0.94,3.035714,High,0.935484,129.65,4 Yes,India,226
25,26,340,122,10,4.5,4.5,9.6,1,0.94,2.833333,High,0.903226,131.20,10 Yes,India,218

In [184]:
#84.Use .nlargest() to get top 5 CGPA values.
data.nlargest(5,"cgpa")

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
143,144,340,122,4,4.5,4.0,9.9,1,0.97,2.833333,High,1.000000,131.35,4 Yes,India,218
202,203,340,122,10,4.5,4.5,9.9,1,0.97,2.833333,High,1.000000,131.35,10 Yes,India,218
203,204,334,122,10,4.0,5.0,9.9,1,0.97,NaN,High,1.000000,129.55,10 Yes,India,212
24,25,336,121,10,4.0,3.5,9.8,1,0.97,NaN,High,0.967742,129.90,10 Yes,India,215
34,35,331,114,10,4.0,5.0,9.8,1,0.94,NaN,High,0.967742,127.00,10 Yes,India,217

In [185]:
#85.Use .nsmallest() to get lowest 5 TOEFL Score values.
data.nsmallest(5,'toefl_score')

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
368,369,298,94,1,2.0,2.0,7.9,0,0.51,NaN,Low,0.354839,112.15,1 No,India,204
28,29,295,95,1,2.0,2.0,7.2,0,0.46,3.172043,Low,0.129032,111.10,1 No,India,200
79,80,294,95,1,3.4,2.0,7.4,0,0.46,NaN,Low,0.193548,110.90,1 No,India,199
347,348,299,96,1,3.4,1.0,7.3,0,0.42,NaN,Low,0.161290,112.55,1 No,India,203
78,79,296,97,2,3.0,2.0,7.5,1,0.44,NaN,Low,0.225806,111.95,2 Yes,India,199

In [186]:
#86.Add a new DataFrame containing only students with Research = 1 and merge it with main dataset.
new=data[data['research']==1]

In [187]:
merge_data=pd.merge(data,new,left_on="serial_no.",right_on="serial_no.",how="inner")

In [188]:
merge_data

,serial_no.,gre_score_x,toefl_score_x,university_rating_x,sop_x,lor__x,cgpa_x,research_x,chance_of_admit__x,gre_to_toefl_ratio_x,...,cgpa_y,research_y,chance_of_admit__y,gre_to_toefl_ratio_y,gre_level_y,normalized_y,weighted_score_y,rating-research_y,country_y,difference_y
0,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,...,9.6,1,0.92,NaN,High,0.903226,129.90,4 Yes,India,217
1,2,324,109,4,4.0,4.5,8.9,1,0.76,NaN,...,8.9,1,0.76,NaN,High,0.677419,123.45,4 Yes,India,215
2,3,316,106,3,3.0,3.5,8.0,1,0.72,NaN,...,8.0,1,0.72,NaN,Low,0.387097,120.00,3 Yes,India,210
3,4,322,112,3,3.5,2.5,8.7,1,0.80,NaN,...,8.7,1,0.80,NaN,High,0.612903,123.35,3 Yes,India,210
4,6,330,117,10,4.5,3.0,9.3,1,0.90,2.869565,...,9.3,1,0.90,2.869565,High,0.806452,127.05,10 Yes,India,213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,395,329,113,4,4.5,4.0,9.2,1,0.89,NaN,...,9.2,1,0.89,NaN,High,0.774194,125.90,4 Yes,India,216
215,396,324,112,3,3.5,3.5,9.0,1,0.82,NaN,...,9.0,1,0.82,NaN,High,0.709677,124.10,3 Yes,India,212
216,397,325,109,3,3.0,3.5,9.1,1,0.84,3.037383,...,9.1,1,0.84,3.037383,High,0.741935,123.85,3 Yes,India,216
217,398,330,118,4,5.0,4.5,9.4,1,0.91,2.844828,...,9.4,1,0.91,2.844828,High,0.838710,127.30,4 Yes,India,212
218,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,...,9.7,1,0.95,NaN,High,0.935484,128.55,4 Yes,India,214

In [189]:
merge_data["research_x"].unique()

array([1])

In [190]:
#87.Create two DataFrames — one for Research = 0, another for Research = 1 — and concatenate them.

In [191]:
new2=data[data['research']==0]

In [195]:
merge_r_inner=pd.merge(new,new2,left_on="serial_no.",right_on="serial_no.",how="inner")

In [196]:
merge_r_inner

Empty DataFrame
Columns: [serial_no., gre_score_x, toefl_score_x, university_rating_x, sop_x, lor__x, cgpa_x, research_x, chance_of_admit__x, gre_to_toefl_ratio_x, gre_level_x, normalized_x, weighted_score_x, rating-research_x, country_x, difference_x, gre_score_y, toefl_score_y, university_rating_y, sop_y, lor__y, cgpa_y, research_y, chance_of_admit__y, gre_to_toefl_ratio_y, gre_level_y, normalized_y, weighted_score_y, rating-research_y, country_y, difference_y]
Index: []

[0 rows x 31 columns]

In [197]:
merge_r_outer=pd.merge(new,new2,left_on="serial_no.",right_on="serial_no.",how="outer")

In [198]:
merge_r_outer

,serial_no.,gre_score_x,toefl_score_x,university_rating_x,sop_x,lor__x,cgpa_x,research_x,chance_of_admit__x,gre_to_toefl_ratio_x,...,cgpa_y,research_y,chance_of_admit__y,gre_to_toefl_ratio_y,gre_level_y,normalized_y,weighted_score_y,rating-research_y,country_y,difference_y
0,1,337.0,120.0,4.0,4.5,4.5,9.6,1.0,0.92,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,324.0,109.0,4.0,4.0,4.5,8.9,1.0,0.76,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,316.0,106.0,3.0,3.0,3.5,8.0,1.0,0.72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,322.0,112.0,3.0,3.5,2.5,8.7,1.0,0.80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.2,0.0,0.65,NaN,Low,0.451613,119.3,2 No,India,209.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,324.0,112.0,3.0,3.5,3.5,9.0,1.0,0.82,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,397,325.0,109.0,3.0,3.0,3.5,9.1,1.0,0.84,3.037383,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,398,330.0,118.0,4.0,5.0,4.5,9.4,1.0,0.91,2.844828,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.8,0.0,0.67,NaN,Low,0.645161,119.0,3 No,India,207.0
399,400,333.0,119.0,4.0,5.0,4.0,9.7,1.0,0.95,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [199]:
#88.Merge two datasets on University Rating.
new_u=pd.merge(data,merge_data,left_on="university_rating",right_on="university_rating_x",how="inner")

In [200]:
new_u

,serial_no._x,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,...,cgpa_y,research_y,chance_of_admit__y,gre_to_toefl_ratio_y,gre_level_y,normalized_y,weighted_score_y,rating-research_y,country_y,difference_y
0,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,...,9.6,1,0.92,NaN,High,0.903226,129.90,4 Yes,India,217
1,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,...,8.9,1,0.76,NaN,High,0.677419,123.45,4 Yes,India,215
2,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,...,9.0,1,0.84,NaN,High,0.709677,125.20,4 Yes,India,214
3,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,...,9.1,1,0.78,NaN,High,0.741935,125.75,4 Yes,India,214
4,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,...,9.4,1,0.91,NaN,High,0.838710,130.10,4 Yes,India,218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20478,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,...,9.7,1,0.96,3.008850,High,0.935484,129.85,4 Yes,India,225
20479,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,...,9.1,1,0.84,NaN,High,0.741935,125.15,4 Yes,India,212
20480,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,...,9.2,1,0.89,NaN,High,0.774194,125.90,4 Yes,India,216
20481,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,...,9.4,1,0.91,2.844828,High,0.838710,127.30,4 Yes,India,212
20482,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,...,9.7,1,0.95,NaN,High,0.935484,128.55,4 Yes,India,214

In [201]:
#89.Join two DataFrames with same index using .join().
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['X', 'Y', 'Z'])
df2 = pd.DataFrame({'C': [7, 8, 9], 'D': [10, 11, 12]}, index=['X', 'Y', 'Z'])

In [202]:
joined_df=df1.join(df2)

In [203]:
joined_df

   A  B  C   D
X  1  4  7  10
Y  2  5  8  11
Z  3  6  9  12

In [204]:
#90.Use .loc[] to select students with index from 10 to 20.
data.loc[10:20]

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
10,11,325,108,3,3.5,4.0,8.4,1,0.52,3.066038,High,0.516129,123.30,3 Yes,India,217
11,12,327,113,4,4.0,4.5,9.0,1,0.84,NaN,High,0.709677,125.20,4 Yes,India,214
12,13,328,114,4,4.0,4.5,9.1,1,0.78,NaN,High,0.741935,125.75,4 Yes,India,214
13,14,307,111,3,4.0,3.0,8.0,1,0.62,NaN,Low,0.387097,118.30,3 Yes,India,196
14,15,311,106,3,3.5,2.0,8.2,1,0.61,NaN,Low,0.451613,118.60,3 Yes,India,205
15,16,314,107,3,3.5,2.5,8.3,0,0.54,NaN,Low,0.483871,119.75,3 No,India,207
16,17,317,109,3,4.0,3.0,8.7,0,0.66,NaN,Low,0.612903,121.25,3 No,India,208
17,18,319,108,3,4.0,3.0,8.0,1,0.65,NaN,Low,0.387097,121.30,3 Yes,India,211
18,19,318,112,3,4.0,3.0,8.8,0,0.63,NaN,Low,0.645161,122.20,3 No,India,206
19,20,303,104,3,3.5,3.0,8.5,0,0.62,NaN,Low,0.548387,115.95,3 No,India,199
20,21,312,109,3,3.0,2.0,7.9,1,0.64,NaN,Low,0.354839,119.35,3 Yes,India,203

In [206]:
#91.Use .iloc[] to select the first 5 rows and first 3 columns.
data.iloc[:5,:3]

   serial_no.  gre_score  toefl_score
0           1        337          120
1           2        324          109
2           3        316          106
3           4        322          112
4           5        314          105

In [207]:
#92.Display all columns except Serial No..
df_without_serial=data.drop("serial_no.",axis=1)

In [208]:
df_without_serial

,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
0,337,120,4,4.5,4.5,9.6,1,0.92,NaN,High,0.903226,129.90,4 Yes,India,217
1,324,109,4,4.0,4.5,8.9,1,0.76,NaN,High,0.677419,123.45,4 Yes,India,215
2,316,106,3,3.0,3.5,8.0,1,0.72,NaN,Low,0.387097,120.00,3 Yes,India,210
3,322,112,3,3.5,2.5,8.7,1,0.80,NaN,High,0.612903,123.35,3 Yes,India,210
4,314,105,2,2.0,3.0,8.2,0,0.65,NaN,Low,0.451613,119.30,2 No,India,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,324,112,3,3.5,3.5,9.0,1,0.82,NaN,High,0.709677,124.10,3 Yes,India,212
396,325,109,3,3.0,3.5,9.1,1,0.84,3.037383,High,0.741935,123.85,3 Yes,India,216
397,330,118,4,5.0,4.5,9.4,1,0.91,2.844828,High,0.838710,127.30,4 Yes,India,212
398,312,105,3,3.5,4.0,8.8,0,0.67,NaN,Low,0.645161,119.00,3 No,India,207
399,333,119,4,5.0,4.0,9.7,1,0.95,NaN,High,0.935484,128.55,4 Yes,India,214

In [214]:
#93.Select only GRE Score, TOEFL Score, and CGPA columns.
data[["gre_score",'toefl_score','cgpa']]

     gre_score  toefl_score  cgpa
0          337          120   9.6
1          324          109   8.9
2          316          106   8.0
3          322          112   8.7
4          314          105   8.2
..         ...          ...   ...
395        324          112   9.0
396        325          109   9.1
397        330          118   9.4
398        312          105   8.8
399        333          119   9.7

[400 rows x 3 columns]

In [215]:
#94.Sort all rows in reverse alphabetical order of index.
data.sort_index(ascending=False)

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
399,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,High,0.935484,128.55,4 Yes,India,214
398,399,312,105,3,3.5,4.0,8.8,0,0.67,NaN,Low,0.645161,119.00,3 No,India,207
397,398,330,118,4,5.0,4.5,9.4,1,0.91,2.844828,High,0.838710,127.30,4 Yes,India,212
396,397,325,109,3,3.0,3.5,9.1,1,0.84,3.037383,High,0.741935,123.85,3 Yes,India,216
395,396,324,112,3,3.5,3.5,9.0,1,0.82,NaN,High,0.709677,124.10,3 Yes,India,212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,314,105,2,2.0,3.0,8.2,0,0.65,NaN,Low,0.451613,119.30,2 No,India,209
3,4,322,112,3,3.5,2.5,8.7,1,0.80,NaN,High,0.612903,123.35,3 Yes,India,210
2,3,316,106,3,3.0,3.5,8.0,1,0.72,NaN,Low,0.387097,120.00,3 Yes,India,210
1,2,324,109,4,4.0,4.5,8.9,1,0.76,NaN,High,0.677419,123.45,4 Yes,India,215
0,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,High,0.903226,129.90,4 Yes,India,217

In [216]:
#95.Extract rows with even index numbers only.
data.iloc[::2]

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
0,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,High,0.903226,129.90,4 Yes,India,217
2,3,316,106,3,3.0,3.5,8.0,1,0.72,NaN,Low,0.387097,120.00,3 Yes,India,210
4,5,314,105,2,2.0,3.0,8.2,0,0.65,NaN,Low,0.451613,119.30,2 No,India,209
6,7,321,111,3,3.0,4.0,8.2,1,0.75,NaN,High,0.451613,122.60,3 Yes,India,210
8,9,302,104,1,2.0,1.5,8.0,0,0.50,NaN,Low,0.387097,115.40,1 No,India,198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,391,314,104,2,2.0,2.5,8.2,0,0.64,NaN,Low,0.451613,119.10,2 No,India,210
392,393,326,114,4,4.0,3.5,9.1,1,0.84,NaN,High,0.741935,125.15,4 Yes,India,212
394,395,329,113,4,4.5,4.0,9.2,1,0.89,NaN,High,0.774194,125.90,4 Yes,India,216
396,397,325,109,3,3.0,3.5,9.1,1,0.84,3.037383,High,0.741935,123.85,3 Yes,India,216
398,399,312,105,3,3.5,4.0,8.8,0,0.67,NaN,Low,0.645161,119.00,3 No,India,207

In [221]:
#96.Display first and last 3 rows of dataset together.
first_three=data.head(3)
last_three=data.tail(3)

In [223]:
conc=pd.concat([first_three,last_three])

In [224]:
conc

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
0,1,337,120,4,4.5,4.5,9.6,1,0.92,NaN,High,0.903226,129.90,4 Yes,India,217
1,2,324,109,4,4.0,4.5,8.9,1,0.76,NaN,High,0.677419,123.45,4 Yes,India,215
2,3,316,106,3,3.0,3.5,8.0,1,0.72,NaN,Low,0.387097,120.00,3 Yes,India,210
397,398,330,118,4,5.0,4.5,9.4,1,0.91,2.844828,High,0.838710,127.30,4 Yes,India,212
398,399,312,105,3,3.5,4.0,8.8,0,0.67,NaN,Low,0.645161,119.00,3 No,India,207
399,400,333,119,4,5.0,4.0,9.7,1,0.95,NaN,High,0.935484,128.55,4 Yes,India,214

In [225]:
#97.Combine two DataFrames vertically using pd.concat().
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30],
    'City': ['New York', 'London']
})
df2 = pd.DataFrame({
    'Name': ['Charlie', 'David'],
    'Age': [35, 40],
    'City': ['Paris', 'Tokyo']
})

In [226]:
df1

    Name  Age      City
0  Alice   25  New York
1    Bob   30    London

In [227]:
df2

      Name  Age   City
0  Charlie   35  Paris
1    David   40  Tokyo

In [228]:
concat=pd.concat([df1,df2],ignore_index=True)

In [229]:
concat

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo

In [236]:
#98.Sort dataset based on the rounded value of Chance of Admit.

0.09999999999999964

In [244]:
#data.sort_values(by=data["chance_of_admit_"].apply(round),ascending=True)

In [245]:
data.sort_values(by=["chance_of_admit_"],ascending=True)

,serial_no.,gre_score,toefl_score,university_rating,sop,lor_,cgpa,research,chance_of_admit_,gre_to_toefl_ratio,gre_level,normalized,weighted_score,rating-research,country,difference
92,93,298,100,2,4.0,3.0,8.0,0,0.34,NaN,Low,0.387097,113.40,2 No,India,198
376,377,297,98,2,2.5,2.0,7.4,0,0.34,NaN,Low,0.193548,112.40,2 No,India,199
94,95,303,101,3,2.0,2.5,7.7,0,0.36,NaN,Low,0.290323,114.95,3 No,India,202
58,59,300,101,1,3.0,2.0,6.8,1,0.36,3.030303,Low,0.000000,113.60,1 Yes,India,199
375,376,304,103,2,2.0,2.5,7.7,0,0.38,NaN,Low,0.290323,115.65,2 No,India,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,82,340,122,4,5.0,5.0,9.5,1,0.96,2.833333,High,0.870968,131.15,4 Yes,India,218
203,204,334,122,10,4.0,5.0,9.9,1,0.97,NaN,High,1.000000,129.55,10 Yes,India,212
202,203,340,122,10,4.5,4.5,9.9,1,0.97,2.833333,High,1.000000,131.35,10 Yes,India,218
143,144,340,122,4,4.5,4.0,9.9,1,0.97,2.833333,High,1.000000,131.35,4 Yes,India,218
24,25,336,121,10,4.0,3.5,9.8,1,0.97,NaN,High,0.967742,129.90,10 Yes,India,215

In [243]:
data["chance_of_admit_"].unique()

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.63, 0.64, 0.7 , 0.94, 0.95,
       0.97, 0.44, 0.46, 0.74, 0.91, 0.88, 0.58, 0.48, 0.49, 0.53, 0.87,
       0.86, 0.89, 0.82, 0.56, 0.36, 0.42, 0.47, 0.55, 0.57, 0.96, 0.93,
       0.38, 0.34, 0.79, 0.71, 0.69, 0.59, 0.85, 0.77, 0.81, 0.83, 0.67,
       0.73, 0.6 , 0.43, 0.51, 0.39])

In [246]:
#99.Rearrange columns alphabetically.
data.sort_index(axis=1)

,cgpa,chance_of_admit_,country,difference,gre_level,gre_score,gre_to_toefl_ratio,lor_,normalized,rating-research,research,serial_no.,sop,toefl_score,university_rating,weighted_score
0,9.6,0.92,India,217,High,337,NaN,4.5,0.903226,4 Yes,1,1,4.5,120,4,129.90
1,8.9,0.76,India,215,High,324,NaN,4.5,0.677419,4 Yes,1,2,4.0,109,4,123.45
2,8.0,0.72,India,210,Low,316,NaN,3.5,0.387097,3 Yes,1,3,3.0,106,3,120.00
3,8.7,0.80,India,210,High,322,NaN,2.5,0.612903,3 Yes,1,4,3.5,112,3,123.35
4,8.2,0.65,India,209,Low,314,NaN,3.0,0.451613,2 No,0,5,2.0,105,2,119.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,9.0,0.82,India,212,High,324,NaN,3.5,0.709677,3 Yes,1,396,3.5,112,3,124.10
396,9.1,0.84,India,216,High,325,3.037383,3.5,0.741935,3 Yes,1,397,3.0,109,3,123.85
397,9.4,0.91,India,212,High,330,2.844828,4.5,0.838710,4 Yes,1,398,5.0,118,4,127.30
398,8.8,0.67,India,207,Low,312,NaN,4.0,0.645161,3 No,0,399,3.5,105,3,119.00
399,9.7,0.95,India,214,High,333,NaN,4.0,0.935484,4 Yes,1,400,5.0,119,4,128.55