In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Airbnb.csv")

C:\Users\rames\AppData\Local\Temp\ipykernel_1208\4048832735.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv("Airbnb.csv")

In [3]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [4]:
#1. Display the first 10 rows of the dataset.
data.head(10)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN

In [5]:
#2. Show the last 5 rows of the dataset.
data.tail()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [6]:
#3. Get all column names in the dataset.
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [7]:
#4. Display the shape (rows, columns) of the dataset.
data.shape

(102599, 26)

In [8]:
#6. Display only the columns: name, price, and room_type.
data[["NAME","price","room type"]]

,NAME,price,room type
0,Clean & quiet apt home by the park,$966,Private room
1,Skylit Midtown Castle,$142,Entire home/apt
2,THE VILLAGE OF HARLEM....NEW YORK !,$620,Private room
3,NaN,$368,Entire home/apt
4,Entire Apt: Spacious Studio/Loft by central park,$204,Entire home/apt
...,...,...,...
102594,Spare room in Williamsburg,$844,Private room
102595,Best Location near Columbia U,$837,Private room
102596,"Comfy, bright room in Brooklyn",$988,Private room
102597,Big Studio-One Stop from Midtown,$546,Entire home/apt
102598,585 sf Luxury Studio,"$1,032",Entire home/apt

In [9]:
#7. Retrieve all unique values in the room_type column.
data["room type"].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

In [10]:
#8. Count how many unique host IDs exist in the dataset.
data["host id"].unique()

array([80014485718, 52335172823, 78829239556, ..., 23801060917,
       15593031571, 93578954226])

In [11]:
#9. Select all rows where price is greater than 100.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [12]:
data["price"].unique()

array(['$966 ', '$142 ', '$620 ', ..., '$1,184 ', '$905 ', '$309 '],
      dtype=object)

In [13]:
data["price"]=data["price"].str.replace("$","")

In [14]:
data["price"]=data["price"].str.replace(" ","")

In [15]:
data["price"]=data["price"].str.replace(",","")

In [16]:
data["price"]=data["price"].astype("float")

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  float64
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(10), int64(2), object(14)
memory usage: 20.4+ MB

In [18]:
data[data['price']>100]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [19]:
#10. Select all listings where room_type is “Entire home/apt”.
data[data["room type"]=="Entire home/apt"]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,$50,1.0,0.0,NaN,NaN,1.0,1.0,276.0,#NAME?,NaN
102591,6090781,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,...,$228,5.0,17.0,1/4/2019,0.35,5.0,1.0,134.0,#NAME?,NaN
102592,6091333,3BR/1 Ba in TriBeCa w/ outdoor deck,53266862889,unconfirmed,Nick,Manhattan,Tribeca,40.71845,-74.01183,United States,...,$157,1.0,0.0,NaN,NaN,2.0,1.0,177.0,Guests should treat my home as if it were thei...,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [20]:
#11. Show all listings in the city “New York”.
data["country"].unique()

array(['United States', nan], dtype=object)

In [21]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [22]:
#12. Retrieve only the host_name and neighbourhood columns.
data[["host name","neighbourhood"]]

          host name        neighbourhood
0          Madaline           Kensington
1             Jenna              Midtown
2             Elise               Harlem
3             Garry         Clinton Hill
4            Lyndon          East Harlem
...             ...                  ...
102594         Krik         Williamsburg
102595        Mifan  Morningside Heights
102596        Megan           Park Slope
102597  Christopher     Long Island City
102598      Rebecca      Upper West Side

[102599 rows x 2 columns]

In [23]:
#13. Display all listings with more than 2 bedrooms.
data["room type"].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

In [24]:
data[data["room type"]=="Entire home/apt"]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,$50,1.0,0.0,NaN,NaN,1.0,1.0,276.0,#NAME?,NaN
102591,6090781,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,...,$228,5.0,17.0,1/4/2019,0.35,5.0,1.0,134.0,#NAME?,NaN
102592,6091333,3BR/1 Ba in TriBeCa w/ outdoor deck,53266862889,unconfirmed,Nick,Manhattan,Tribeca,40.71845,-74.01183,United States,...,$157,1.0,0.0,NaN,NaN,2.0,1.0,177.0,Guests should treat my home as if it were thei...,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [25]:
#14. Retrieve all listings that have a minimum_nights less than 3.
data["minimum nights"].unique()

array([ 1.000e+01,  3.000e+01,  3.000e+00,  4.500e+01,  2.000e+00,
        1.000e+00,  5.000e+00,  4.000e+00,  9.000e+01,  7.000e+00,
        1.400e+01,  6.000e+01,        nan,  1.800e+02,  9.000e+00,
        3.100e+01,  6.000e+00,  1.500e+01,  2.900e+01,  8.000e+00,
        4.700e+01,  8.100e+01,  1.440e+02,  3.710e+02,  1.490e+02,
        2.730e+02,  1.310e+02,  2.750e+02,  3.230e+02,  5.900e+01,
        9.900e+01,  2.680e+02, -1.000e+01,  1.890e+02,  3.400e+02,
        1.280e+02,  3.500e+02,  1.660e+02,  1.100e+02,  5.700e+01,
        1.420e+02,  3.660e+02,  2.800e+01,  2.000e+02,  5.000e+01,
        3.990e+02,  1.700e+01,  1.100e+01,  4.520e+02,  2.500e+01,
        1.300e+01,  3.455e+03, -5.000e+00,  2.100e+01,  2.700e+01,
        1.800e+01,  3.650e+02, -1.000e+00,  2.000e+01, -1.200e+01,
        4.000e+01,  4.400e+01,  3.980e+02, -2.000e+00,  6.500e+01,
       -3.000e+00,  5.500e+01,  1.200e+02,  1.220e+02,  1.900e+01,
        2.400e+02,  8.800e+01,  1.150e+02,  1.500e+02,  3.700e+02,
        1.600e+01,  8.000e+01,  1.810e+02,  2.600e+01,  2.650e+02,
        3.000e+02,  1.850e+02,  3.600e+02,  5.600e+01,  1.200e+01,
        7.000e+01,  3.900e+01,  2.400e+01,  3.200e+01,  1.000e+03,
        2.700e+02,  2.200e+01,  7.500e+01,  2.500e+02,  6.200e+01,
        2.300e+01,  1.250e+03,  3.640e+02,  7.400e+01,  1.980e+02,
        1.000e+02,  5.000e+02,  4.300e+01,  3.500e+01,  9.100e+01,
        4.800e+02,  5.300e+01,  1.600e+02,  9.990e+02,  1.860e+02,
        6.800e+01,  9.300e+01,  8.700e+01,  1.830e+02,  2.990e+02,
        1.750e+02,  9.800e+01,  1.330e+02,  3.540e+02,  4.200e+01,
        3.300e+01,  3.700e+01,  2.250e+02,  4.000e+02,  1.050e+02,
        1.840e+02,  1.530e+02,  1.340e+02,  2.220e+02,  5.800e+01,
        2.100e+02,  1.820e+02,  9.540e+02,  5.645e+03,  2.645e+03,
       -1.223e+03, -3.650e+02, -2.000e+02,  1.140e+02,  8.500e+01,
        3.600e+01,  4.800e+01,  1.550e+02,  3.070e+02,  1.290e+02,
        1.450e+02,  6.400e+01,  3.330e+02,  1.190e+02, -1.250e+02,
        1.250e+02,  3.400e+01,  4.580e+02,  8.250e+02])

In [26]:
data[data["minimum nights"]<3]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN
12,1007964,Central Manhattan/near Broadway,88136055909,verified,NaN,Manhattan,Hell's Kitchen,40.76076,-73.98867,United States,...,$143,2.0,188.0,6/23/2019,1.50,4.0,1.0,258.0,- One of the bedroom closets is not accessible...,NaN
14,1009068,Wonderful Guest Bedroom in Manhattan for SINGLES,88920244552,verified,Leonardo,Manhattan,Upper West Side,40.79826,-73.96113,United States,...,$30,2.0,113.0,7/5/2019,0.91,3.0,1.0,68.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,$220,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [27]:
#15. Show listings where availability_365 is zero.
data[data["availability 365"]==0]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
154,1086390,NaN,47292670441,unconfirmed,Dainton,Brooklyn,Prospect Heights,40.67410,-73.96595,United States,...,$162,15.0,4.0,8/27/2018,0.05,3.0,1.0,0.0,Events or parties are a separate charge at our...,NaN
243,1135545,Huge Chelsea Loft,27743402115,verified,Thomas,Manhattan,Chelsea,40.74358,-74.00027,United States,...,$119,2.0,35.0,7/27/2017,0.34,1.0,1.0,0.0,- has to be clean!,NaN
862,1477419,Your Own 2 Br Apt Bedford and Grand,98053399694,unconfirmed,Montgomery,Brooklyn,Williamsburg,40.71532,-73.96064,United States,...,$97,3.0,236.0,6/18/2019,2.74,NaN,2.0,0.0,No smoking allowed in the house. No pets. No...,NaN
1541,1852430,"LARGE PRIVATE FLOOR IN BROOKLYN, NY",55884191073,verified,Eric,Brooklyn,Bedford-Stuyvesant,40.69128,-73.93653,United States,...,$74,4.0,239.0,6/26/2019,2.89,1.0,2.0,0.0,NaN,NaN
2408,2331274,Central Park Room/Bath with a View!,84337043060,unconfirmed,William,Manhattan,Upper West Side,40.79631,-73.96152,United States,...,$34,3.0,118.0,1/23/2019,1.61,2.0,1.0,0.0,Please clean up before checking out. Any major...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102462,20404740,New York Apartment,98342871281,unconfirmed,Karen,Manhattan,Civic Center,40.71310,-74.00527,United States,...,$222,15.0,0.0,NaN,NaN,3.0,1.0,0.0,"NO SMOKING, please stop smoking a block away s...",NaN
102463,20405292,Affordable bedroom in Brooklyn townhouse.,78907850230,verified,Julie,Brooklyn,East Flatbush,40.65040,-73.95011,United States,...,$197,3.0,2.0,2/18/2019,0.19,3.0,2.0,0.0,NaN,NaN
102465,20406397,beautiful modern 1 bed room apt,7095669452,unconfirmed,Alex,Manhattan,Chelsea,40.74813,-74.00478,United States,...,$194,2.0,4.0,5/28/2019,0.45,2.0,1.0,0.0,NaN,NaN
102468,20408053,"Clean, Cozy Home in Perfect Park Slope Location",52339470834,unconfirmed,Young Jean,Brooklyn,Park Slope,40.68178,-73.97957,United States,...,$136,120.0,0.0,NaN,NaN,5.0,1.0,0.0,All guests are expected to be respectful and m...,NaN
102503,6042178,"Perfect for Cat, Book, Park Lovers!",17949645201,verified,Laura,Brooklyn,Flatbush,40.65371,-73.95623,United States,...,$80,2.0,12.0,12/19/2015,0.25,1.0,1.0,0.0,No smoking in the unit or in the building (str...,NaN

In [28]:
#16. Display the top 10 most expensive listings.
expensive=data.sort_values(by="price",ascending=False)

In [29]:
expensive.head(10)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
20343,12236775,Lovely apartment in Williamsburg,11151122860,verified,Harry,Brooklyn,Greenpoint,40.72253,-73.94350,United States,...,$240,7.0,6.0,12/30/2018,0.20,2.0,1.0,62.0,NaN,NaN
64304,36516435,Great 1BD waterfront City Island NY,83460973881,verified,Alex,Bronx,City Island,40.85343,-73.78811,United States,...,$240,30.0,108.0,8/25/2021,1.09,5.0,1.0,31.0,NaN,NaN
67200,38115896,Bright Brooklyn Brownstone,66173822303,unconfirmed,Andrew,Brooklyn,Park Slope,40.67275,-73.97541,United States,...,$240,3.0,9.0,6/30/2020,0.23,2.0,1.0,2.0,NaN,NaN
33902,19725411,Oasis II,59005379313,verified,Angie,Brooklyn,Bedford-Stuyvesant,40.68978,-73.95131,United States,...,$240,30.0,21.0,6/5/2019,2.05,4.0,3.0,365.0,Guests are expected to keep the apartmemt clea...,NaN
7453,5117628,Sun-filled bedroom in East Village / Gramercy NYC,45143137929,unconfirmed,Jeff & TJ,Manhattan,Gramercy,40.73170,-73.98272,United States,...,$240,2.0,136.0,7/3/2019,2.67,2.0,1.0,335.0,"We live on the 3rd floor of a 3-family house, ...",NaN
90165,50799466,Lovely apartment in Williamsburg,90965581979,unconfirmed,Harry,Brooklyn,Greenpoint,40.72253,-73.94350,United States,...,$240,7.0,6.0,12/30/2018,0.20,2.0,1.0,62.0,NaN,NaN
52744,30131847,❤️Couples Retreat/A Road Warriors Dream🌟Perf Loc.,9456551231,verified,B,Manhattan,Hell's Kitchen,40.76349,-73.98949,United States,...,$240,1.0,141.0,2/20/2022,3.09,3.0,1.0,279.0,NaN,NaN
19773,11921964,1.5 BATHRM SUNNY SPACIOUS ROOM BY SUBWAY,51256717787,verified,Golden&Mavy,Manhattan,Harlem,40.82284,-73.95546,United States,...,$240,30.0,4.0,6/15/2019,0.14,4.0,2.0,365.0,No Smoking No Pets,NaN
5207,3877162,Bushwick Room w/ Private Entrance & Bathroom!,45360462434,unconfirmed,Julie,Brooklyn,Bushwick,40.70322,-73.92913,United States,...,$240,1.0,16.0,6/15/2019,0.32,1.0,5.0,30.0,No smoking in the apartment.,NaN
42446,24444262,"Cozy room in bright, spacious apartment",84040511136,verified,Steven,Bronx,Hunts Point,40.81731,-73.89052,United States,...,$240,-1223.0,0.0,NaN,NaN,2.0,4.0,341.0,Smoking is strictly prohibited. Your pets are ...,NaN

In [30]:
#17. Sort the dataset by price in descending order.
data.sort_values(by="price",ascending=False)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
20343,12236775,Lovely apartment in Williamsburg,11151122860,verified,Harry,Brooklyn,Greenpoint,40.72253,-73.94350,United States,...,$240,7.0,6.0,12/30/2018,0.20,2.0,1.0,62.0,NaN,NaN
64304,36516435,Great 1BD waterfront City Island NY,83460973881,verified,Alex,Bronx,City Island,40.85343,-73.78811,United States,...,$240,30.0,108.0,8/25/2021,1.09,5.0,1.0,31.0,NaN,NaN
67200,38115896,Bright Brooklyn Brownstone,66173822303,unconfirmed,Andrew,Brooklyn,Park Slope,40.67275,-73.97541,United States,...,$240,3.0,9.0,6/30/2020,0.23,2.0,1.0,2.0,NaN,NaN
33902,19725411,Oasis II,59005379313,verified,Angie,Brooklyn,Bedford-Stuyvesant,40.68978,-73.95131,United States,...,$240,30.0,21.0,6/5/2019,2.05,4.0,3.0,365.0,Guests are expected to keep the apartmemt clea...,NaN
7453,5117628,Sun-filled bedroom in East Village / Gramercy NYC,45143137929,unconfirmed,Jeff & TJ,Manhattan,Gramercy,40.73170,-73.98272,United States,...,$240,2.0,136.0,7/3/2019,2.67,2.0,1.0,335.0,"We live on the 3rd floor of a 3-family house, ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102046,57361342,Sunny budget friendly room in Bushwick,29964876857,verified,NaN,Brooklyn,Bushwick,40.69370,-73.91006,United States,...,NaN,5.0,3.0,4/9/2018,0.11,1.0,1.0,0.0,Please be mindful that I live in the same buil...,NaN
102047,57361894,"Cozy Apartment on Bedford Ave, Brooklyn",92852058426,unconfirmed,NaN,Brooklyn,Williamsburg,40.71284,-73.96284,United States,...,NaN,7.0,15.0,1/1/2018,0.55,4.0,1.0,0.0,NaN,NaN
102048,57362446,Your 1 bedroom home away from home!,95572379802,verified,NaN,Manhattan,Upper West Side,40.79563,-73.97634,United States,...,NaN,3.0,38.0,6/10/2019,1.40,3.0,1.0,31.0,NaN,NaN
102049,57362999,MASTER Cozy Bedroom Queen size 2 blocks Timesq...,80154173698,verified,NaN,Manhattan,Hell's Kitchen,40.76125,-73.98945,United States,...,NaN,1.0,81.0,3/5/2019,2.96,2.0,2.0,0.0,- I work at home and prefer to rent to folks w...,NaN
102050,57363551,Sunny Brownstone Studio in BedStuy Brooklyn,11145329848,unconfirmed,Jamal,Brooklyn,Bedford-Stuyvesant,40.68221,-73.94618,United States,...,NaN,2.0,104.0,6/12/2019,3.69,5.0,1.0,268.0,NaN,NaN

In [31]:
#18. Sort listings first by city, then by price ascending.
data.sort_values(by="price",ascending=True)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
8495,5693125,Private Room in Williamsburg Apt,7170817633,unconfirmed,Emeka,Brooklyn,Williamsburg,40.71145,-73.95302,United States,...,$10,2.0,1.0,6/16/2015,0.02,2.0,1.0,7.0,NaN,NaN
60981,34681142,Charming Greenwich Village Artist’s Haven,71941078154,verified,Kate,Manhattan,Greenwich Village,40.73235,-73.99791,United States,...,$10,30.0,18.0,12/18/2021,0.67,4.0,1.0,225.0,NaN,NaN
50592,28943298,Artists' Studio in the heart of Williamsburg,50733960481,verified,Oxana,Brooklyn,Williamsburg,40.71499,-73.95223,United States,...,$10,30.0,2.0,2/28/2022,0.56,3.0,1.0,1.0,NaN,NaN
28308,16635844,Sunny bedroom on Bed-Stuy/Bushwick boarder,59006149047,verified,Stephanie,Brooklyn,Bedford-Stuyvesant,40.69004,-73.92793,United States,...,$10,10.0,0.0,NaN,NaN,3.0,1.0,0.0,There will be a contract exchange for this pro...,NaN
17390,10605833,Cozy Little Italy Apartment,55050420759,verified,Haley,Manhattan,Lower East Side,40.71880,-73.99458,United States,...,$10,3.0,10.0,1/1/2017,0.28,2.0,1.0,0.0,Please remember that this is a residential bui...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102046,57361342,Sunny budget friendly room in Bushwick,29964876857,verified,NaN,Brooklyn,Bushwick,40.69370,-73.91006,United States,...,NaN,5.0,3.0,4/9/2018,0.11,1.0,1.0,0.0,Please be mindful that I live in the same buil...,NaN
102047,57361894,"Cozy Apartment on Bedford Ave, Brooklyn",92852058426,unconfirmed,NaN,Brooklyn,Williamsburg,40.71284,-73.96284,United States,...,NaN,7.0,15.0,1/1/2018,0.55,4.0,1.0,0.0,NaN,NaN
102048,57362446,Your 1 bedroom home away from home!,95572379802,verified,NaN,Manhattan,Upper West Side,40.79563,-73.97634,United States,...,NaN,3.0,38.0,6/10/2019,1.40,3.0,1.0,31.0,NaN,NaN
102049,57362999,MASTER Cozy Bedroom Queen size 2 blocks Timesq...,80154173698,verified,NaN,Manhattan,Hell's Kitchen,40.76125,-73.98945,United States,...,NaN,1.0,81.0,3/5/2019,2.96,2.0,2.0,0.0,- I work at home and prefer to rent to folks w...,NaN
102050,57363551,Sunny Brownstone Studio in BedStuy Brooklyn,11145329848,unconfirmed,Jamal,Brooklyn,Bedford-Stuyvesant,40.68221,-73.94618,United States,...,NaN,2.0,104.0,6/12/2019,3.69,5.0,1.0,268.0,NaN,NaN

In [32]:
#19. Check how many rows belong to each city.
data["country code"].unique()

array(['US', nan], dtype=object)

In [33]:
#20. Display only listings whose name contains the word “Cozy”.
data[data['NAME'].str.contains('Cozy', case=False, na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN
52,1030056,Cozy 1BD on Central Park West in New York City,50562514538,unconfirmed,Madaline,Manhattan,Upper West Side,40.78635,-73.97008,United States,...,$180,NaN,73.0,7/7/2019,0.63,3.0,1.0,NaN,No smoking anywhere on the property. Quiet and...,NaN
90,1051043,Cozy Bedroom in Williamsburg 3 BR,14067827221,unconfirmed,Lilianna,NaN,Williamsburg,40.71156,-73.96218,United States,...,$53,3.0,174.0,6/22/2019,1.54,5.0,4.0,NaN,Dryer and Washing Machine are in Basement (1.0...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102538,6061509,Cozy Bedroom in Renovated Harlem Apartment,75674201040,unconfirmed,Delesia,Manhattan,Harlem,40.81435,-73.94588,United States,...,$65,2.0,1.0,7/20/2016,0.03,3.0,1.0,106.0,NaN,NaN
102543,6064270,Nice and Cozy Room,6402191466,verified,Melissa,Manhattan,East Village,40.72294,-73.98570,United States,...,$54,1.0,0.0,NaN,NaN,4.0,1.0,237.0,NaN,NaN
102547,6066479,"Safe,quiet,cozy,Washington Hts Apt",92398842230,verified,Lynn,Manhattan,Washington Heights,40.84454,-73.94188,United States,...,$82,1.0,0.0,NaN,NaN,4.0,1.0,44.0,NaN,NaN
102553,6069793,"Custom Designed Cozy Garden Apt,",7756381071,unconfirmed,Jean& Toney,Brooklyn,Canarsie,40.64574,-73.90781,United States,...,$41,7.0,0.0,NaN,NaN,4.0,3.0,95.0,"- Absolutely no smoking in, on or near the pro...",NaN
102564,6075868,Clean & Cozy- Private Room by Park and Subway!,33983881137,verified,Jayanthi,Brooklyn,Flatbush,40.65452,-73.95960,United States,...,$121,2.0,55.0,6/14/2018,1.12,5.0,1.0,192.0,NaN,NaN

In [34]:
#21. Display all listings where price is between 100 and 200.
data[(data["price"]>100) & (data["price"]<200)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
14,1009068,Wonderful Guest Bedroom in Manhattan for SINGLES,88920244552,verified,Leonardo,Manhattan,Upper West Side,40.79826,-73.96113,United States,...,$30,2.0,113.0,7/5/2019,0.91,3.0,1.0,68.0,NaN,NaN
22,1013487,CBG CtyBGd HelpsHaiti rm#1:1-4,53754237010,verified,Mary,Brooklyn,Park Slope,40.68069,-73.97706,United States,...,$27,2.0,130.0,7/1/2019,1.09,4.0,6.0,54.0,Arrival time can be no later than 10:00PM. No ...,NaN
35,1020667,Large B&B Style rooms,57938703679,unconfirmed,Jared,Brooklyn,Bedford-Stuyvesant,40.68310,-73.95473,United States,...,$38,1.0,74.0,5/12/2019,0.66,NaN,2.0,76.0,"No smoking, this is non-negotiable. No illega...",NaN
77,1043863,Manhattan Room,11468499446,verified,Sofia,NaN,Upper East Side,40.76865,-73.95058,United States,...,$23,1.0,142.0,7/6/2019,1.50,4.0,1.0,NaN,I'm a semi kosher vegetarian which means that ...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102500,6040521,*TERRA GARDEN* 1 Bedroom Garden Apartment,67984530373,verified,Juliana,Manhattan,Upper West Side,40.78180,-73.98483,United States,...,$39,30.0,7.0,10/31/2018,0.19,3.0,34.0,22.0,"No smoking please, no pets to protect our hard...",NaN
102534,6059299,Upper East Side - 1 Bedroom Queen,28301379386,verified,Dani,Manhattan,Upper East Side,40.77734,-73.95779,United States,...,$30,7.0,0.0,NaN,NaN,4.0,1.0,188.0,Please Note: This unit was just renovated in M...,NaN
102546,6065927,LG Bright Apartment,10408461200,verified,Katie,Manhattan,Morningside Heights,40.80481,-73.96375,United States,...,$26,21.0,4.0,1/6/2018,0.09,4.0,1.0,313.0,#NAME?,NaN
102563,6075316,Large 1Br Apt + Balcony in LES!,59240106692,unconfirmed,Elena,Manhattan,Lower East Side,40.72115,-73.98308,United States,...,$32,5.0,1.0,9/16/2015,0.02,2.0,1.0,133.0,NaN,NaN
102578,6083601,Sunny & Spacious near Central Park,41624631525,verified,Guida,Manhattan,East Harlem,40.79674,-73.94449,United States,...,$35,5.0,4.0,1/6/2016,0.08,1.0,1.0,323.0,NaN,NaN

In [35]:
#22. Show all listings that are either in “Los Angeles” or “San Francisco”.
#data["neighbourhood"].unique()

In [36]:
#23. Retrieve listings whose number_of_reviews is greater than 50.
data[data["number of reviews"]>50]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102579,6084153,Alexander's 2BR Luxury Quarters,32736284559,verified,Juan,Brooklyn,Bedford-Stuyvesant,40.68740,-73.93830,United States,...,$59,3.0,123.0,6/26/2019,2.53,4.0,1.0,203.0,NaN,NaN
102580,6084705,"Near LGA, Citifield, US Open Tennis",97606085736,verified,Carmen,Queens,East Elmhurst,40.76578,-73.86424,United States,...,$122,1.0,209.0,6/11/2019,4.38,3.0,1.0,270.0,House Rules 1. Check-in is 4 pm local time. If...,NaN
102584,6086914,2 block walk from the beach in NYC,70051719594,verified,Vladimir,Queens,Arverne,40.59270,-73.78990,United States,...,$113,2.0,89.0,5/26/2019,1.82,2.0,1.0,394.0,NaN,NaN
102587,6088571,Adorable One-Bed in Williamsburg!,20914678851,verified,Taylor,Brooklyn,Williamsburg,40.71687,-73.94656,United States,...,$78,1.0,66.0,6/16/2019,1.35,2.0,1.0,352.0,• Check-in time is 2PM. Check-out time is 11am...,NaN
102588,6089124,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,...,$124,1.0,177.0,6/29/2019,3.78,4.0,1.0,410.0,Keep the apartment clean and damage free please.,NaN

In [37]:
#24. Show all listings whose room_type is not “Private room”.
data["room type"].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

In [38]:
data[data["room type"]=="Private room"]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102589,6089676,Lrg room 1 block from Prospect Park,74549151787,unconfirmed,Dave,Brooklyn,Flatbush,40.65231,-73.96189,United States,...,$61,3.0,0.0,NaN,NaN,1.0,1.0,200.0,House Rules 1. Check-in is 4 pm local time. If...,NaN
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,$220,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN

In [39]:
#25. Get listings where host_name starts with the letter “A”.
data[data["host name"].str[0]=="A"]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
11,1007411,Beautiful 1br on Upper West Side,18824631834,verified,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,...,$121,5.0,53.0,6/22/2019,0.43,4.0,1.0,163.0,"My ideal guests would be warm, friendly, and r...",NaN
18,1011277,Chelsea Perfect,73862528370,verified,Alberta,manhatan,Chelsea,40.74192,-73.99501,United States,...,NaN,1.0,260.0,7/1/2019,2.12,3.0,1.0,325.0,NaN,NaN
20,1012382,Huge 2 BR Upper East Cental Park,79805143117,verified,Audrey,Manhattan,East Harlem,40.79685,-73.94872,United States,...,$56,7.0,0.0,NaN,NaN,3.0,2.0,347.0,"No smoking, No pets. No shoes in the house. V...",NaN
21,1012934,Sweet and Spacious Brooklyn Loft,86554611512,verified,Alissa,Brooklyn,Williamsburg,40.71842,-73.95718,United States,...,$95,3.0,9.0,12/28/2021,0.07,3.0,1.0,193.0,- No smoking or open flames on the property - ...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102508,6044940,3BR Gramercy Apt in heart of NYC,59749079462,verified,Alissa,Manhattan,Kips Bay,40.73912,-73.98250,United States,...,$85,1.0,0.0,NaN,NaN,5.0,1.0,368.0,"We only ask that you have a ton of fun, and th...",NaN
102521,6052120,Must Love Dogs / Bushwick Brooklyn,22301937174,unconfirmed,Ange,Brooklyn,Bushwick,40.68802,-73.91474,United States,...,$167,2.0,4.0,6/1/2019,0.19,5.0,1.0,407.0,Don't make noise in apt after 10pm. keep doors...,NaN
102522,6052672,Sunny studio in the Upper East Side,16962195392,verified,Allie,Manhattan,Upper East Side,40.77138,-73.94809,United States,...,$98,14.0,2.0,9/16/2017,0.06,5.0,1.0,350.0,Please Note: This unit was just renovated last...,NaN
102573,6080839,2BR apt. in converted church with large terrace,38845651458,verified,Annika,Brooklyn,Cobble Hill,40.68836,-73.99763,United States,...,$159,6.0,6.0,10/27/2018,0.13,5.0,1.0,89.0,NaN,NaN
102581,6085258,Bright Bedroom in Bustling Bed Stuy Brooklyn,17339949163,unconfirmed,Amber,Brooklyn,Bedford-Stuyvesant,40.68742,-73.92825,United States,...,$15,2.0,34.0,7/1/2019,0.70,5.0,3.0,299.0,It is a residential building so all of the res...,NaN

In [40]:
#26. Retrieve listings whose name ends with “Suite”.
data[data["host name"].str.contains("Suite",case=False,na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
8195,5527435,Cozy Room in Super Convenient Area,48083055178,verified,Sho-Boo Of Sho-Boo Suite,Brooklyn,Prospect-Lefferts Gardens,40.660830,-73.962470,United States,...,$237,1.0,26.0,7/31/2018,0.52,3.0,3.0,40.0,Events and parties YES... but NON SMOKERS on...,NaN
8232,5547870,Private Room Right by Subway to Manhattan *alt*,97894790174,unconfirmed,Sho-Boo Of Sho-Boo Suite,Brooklyn,Prospect-Lefferts Gardens,40.661170,-73.960830,United States,...,$159,1.0,54.0,10/25/2017,1.10,5.0,3.0,291.0,No smoking allowed in property or on roof deck...,NaN
13702,8568951,The Mahogany Suite(Private Studio Apartment),83263405331,verified,The Mahogany Suite(Studio Apartment,Brooklyn,Crown Heights,40.664040,-73.933340,United States,...,$18,2.0,110.0,6/30/2019,2.81,3.0,3.0,416.0,No cigarette smoking inside the house. Happy t...,NaN
18078,10985815,The Mahogany Suite- The Solo Adventurer l,86256211401,unconfirmed,The Mahogany Suite(Studio Apartment,Brooklyn,East Flatbush,40.662800,-73.933970,United States,...,$164,2.0,24.0,6/17/2019,0.71,2.0,3.0,290.0,NaN,NaN
18240,11075288,Middle Size Room Super Convenient Area: ♥of Bklyn,29929137262,unconfirmed,Sho-Boo Of Sho-Boo Suite,Brooklyn,Prospect-Lefferts Gardens,40.662910,-73.962570,United States,...,$200,1.0,42.0,5/26/2019,1.19,5.0,3.0,337.0,We take great care of our home and want our gu...,NaN
18575,11260309,The Mahogany Suite-The Solo Adventurer-ll,41871309276,verified,The Mahogany Suite(Studio Apartment,Brooklyn,East Flatbush,40.662710,-73.934980,United States,...,$150,32.0,32.0,5/13/2019,0.93,5.0,3.0,345.0,NaN,NaN
37489,21706511,"Comfortable- JFK,LGA Best Value",48992030362,verified,Shared Stay-JFK The Hugh Suite,Queens,Springfield Gardens,40.661020,-73.770350,United States,...,$147,1.0,57.0,6/21/2019,7.28,3.0,3.0,342.0,We will try to always treat you with loving ki...,NaN
37703,21824703,"Clean , Safe, Cozy 3min to JFK , LGA Best Value",50915561866,verified,Shared Stay-JFK The Hugh Suite,Queens,Springfield Gardens,40.661990,-73.772000,United States,...,$137,1.0,73.0,7/1/2019,9.09,2.0,3.0,340.0,No smoking. No pets. No parties.,NaN
39687,22920466,The Den - 3 mins to JFK,13285621163,verified,Shared Stay-JFK The Hugh Suite,Queens,Springfield Gardens,40.662840,-73.769620,United States,...,$19,1.0,17.0,6/11/2019,2.60,4.0,3.0,0.0,No candles. Close and lock windows when you le...,NaN
53941,30792950,Private Queen Suite | Kitchenette | Gym | near...,88098738864,unconfirmed,Global Luxury Suites,Bronx,Port Morris,40.808850,-73.930930,United States,...,$165,5.0,22.0,2/15/2022,10.31,2.0,58.0,364.0,NaN,NaN
54222,30948147,Hotel Style Suite w Kitchenette+Balcony | near...,59966417205,verified,Global Luxury Suites,Bronx,Port Morris,40.810150,-73.932280,United States,...,$125,5.0,2.0,2/14/2022,2.00,2.0,58.0,364.0,NaN,NaN
54591,31151945,"Spacious Suite,2 King Beds+ Kitchenette | near...",52832960262,unconfirmed,Global Luxury Suites,Bronx,Mott Haven,40.812430,-73.932410,United States,...,$95,5.0,4.0,2/13/2022,1.52,4.0,58.0,362.0,NaN,NaN
55199,31487744,Modern Queen Suite | close to NYC | Parking | Gym,87694178234,unconfirmed,Global Luxury Suites,Bronx,Port Morris,40.809110,-73.929600,United States,...,$224,5.0,19.0,2/7/2022,4.32,3.0,58.0,364.0,NaN,NaN
55636,31729099,New! Queen Suite | Kitchenette | Gym |near Sta...,33139472849,unconfirmed,Global Luxury Suites,Bronx,Port Morris,40.809891,-73.930595,United States,...,$190,5.0,3.0,2/3/2022,0.82,2.0,58.0,364.0,NaN,NaN
56202,32041701,Luxury King Studio | Mott Haven | Hotel Amenities,93900152496,unconfirmed,Global Luxury Suites,Bronx,Mott Haven,40.811020,-73.931030,United States,...,$188,5.0,4.0,1/30/2022,0.97,2.0,58.0,364.0,NaN,NaN
56451,32179223,Modern Studio | Upscale | Kitchen + W/D | Midtown,83063610163,verified,Global Luxury Suites,Manhattan,Hell's Kitchen,40.760570,-73.998920,United States,...,$102,30.0,3.0,1/25/2022,0.05,5.0,58.0,349.0,NaN,NaN
56506,32209600,Modern 1BR Midtown West| Kitchen | Work Desk,75120842584,verified,Global Luxury Suites,Manhattan,Hell's Kitchen,40.760220,-73.998810,United States,...,$44,30.0,2.0,1/24/2022,0.04,3.0,58.0,363.0,NaN,NaN
56864,32407323,The Mahogany Suite(Private Studio Apartment),41510969344,unconfirmed,The Mahogany Suite(Studio Apartment,Brooklyn,Crown Heights,40.665390,-73.931790,United States,...,$213,30.0,142.0,1/19/2022,1.99,4.0,2.0,122.0,NaN,NaN
57078,32525515,Gorgeous 2BR | Close to Hospitals | Heart of NYC,19340545623,unconfirmed,Global Luxury Suites,Manhattan,Hell's Kitchen,40.762280,-73.997760,United States,...,$171,30.0,2.0,1/16/2022,0.05,5.0,58.0,359.0,NaN,NaN
57493,32754720,Queen Suite w Balcony| Kitchenette| Desk| near...,2190584799,verified,Global Luxury Suites,Bronx,Mott Haven,40.810800,-73.931090,United States,...,$157,5.0,2.0,1/11/2022,0.85,2.0,58.0,364.0,NaN,NaN
57669,32851925,*Luxury 1BR at 8th & Broadway | Hells Kitchen NYC,43714975652,unconfirmed,Global Luxury Suites,Manhattan,Hell's Kitchen,40.765100,-73.984370,United States,...,$62,30.0,1.0,1/9/2022,0.54,2.0,58.0,364.0,NaN,NaN
57699,32868494,The Mahogany Suite- The Solo Adventurer l,16193776186,verified,The Mahogany Suite(Studio Apartment,Brooklyn,East Flatbush,40.661120,-73.934200,United States,...,$194,30.0,30.0,1/8/2022,0.45,5.0,2.0,247.0,NaN,NaN
57829,32940293,Luxury 1BR | Upscale Building | Gym | Mott Haven,21878406084,verified,Global Luxury Suites,Bronx,Port Morris,40.808900,-73.930830,United States,...,$174,30.0,1.0,1/7/2022,0.52,2.0,58.0,364.0,NaN,NaN
57989,33028661,*NYC Midtown 1BR | Work Desk + WiFi | Doorman,2810519827,unconfirmed,Global Luxury Suites,Manhattan,Midtown,40.765250,-73.981390,United States,...,$198,30.0,2.0,1/5/2022,0.05,4.0,58.0,282.0,NaN,NaN
58646,33391522,"Private, 2 Full Beds, Kitchenette+Work Desk, NYC",9942609016,unconfirmed,Global Luxury Suites,Bronx,Port Morris,40.810390,-73.931440,United States,...,$77,5.0,2.0,1/3/2022,0.85,4.0,58.0,364.0,NaN,NaN
58647,33392074,Modern Suite w 2 Queen Beds+Balcony+Kitchenette,31214536928,unconfirmed,Global Luxury Suites,Bronx,Port Morris,40.810980,-73.932960,United States,...,$96,5.0,1.0,1/3/2022,0.48,4.0,58.0,360.0,NaN,NaN
60438,34381243,PRESIDENTIAL SUITE extra large bright 2 bed 2 ...,78413849535,unconfirmed,Paradise Suites,Manhattan,Midtown,40.759300,-73.961530,NaN,...,$33,30.0,1.0,12/24/2021,0.42,4.0,5.0,294.0,NaN,NaN
60489,34409411,111 - Bright 1 BR unit in luxury amenity building,43725558134,verified,Paradise Suites,Manhattan,Upper East Side,40.761130,-73.959890,NaN,...,$154,30.0,10.0,12/23/2021,0.32,5.0,5.0,352.0,NaN,NaN
60534,34434264,Private & Clean NYC 1BR | Kitchen & Washer/D |...,32369802048,verified,Global Luxury Suites,Manhattan,Hell's Kitchen,40.761840,-73.998280,United States,...,$193,30.0,4.0,12/22/2021,0.07,4.0,58.0,294.0,NaN,NaN
61114,34754598,Luxury Double King Studio | Mott Haven Manhattan,5973430419,verified,Global Luxury Suites,Bronx,Mott Haven,40.812150,-73.931070,United States,...,$142,5.0,5.0,12/16/2021,1.14,5.0,58.0,362.0,NaN,NaN
61672,35062782,Beautiful King Suite+Balcony | Kitchenette+Desk,6988668487,verified,Global Luxury Suites,Bronx,Port Morris,40.810560,-73.931340,United States,...,$203,5.0,1.0,12/6/2021,0.33,2.0,58.0,352.0,NaN,NaN
62246,35379802,Gardens Suites Hotel by Affinia,79224588205,verified,Gardens Suites Hotel By Affinia,Manhattan,Upper East Side,40.764420,-73.963030,United States,...,$81,1.0,3.0,11/22/2021,0.14,2.0,1.0,0.0,NaN,NaN
62922,35753157,Clean & Modern Studio | Washer/D | Work Desk |...,98719203335,unconfirmed,Global Luxury Suites,Manhattan,Hell's Kitchen,40.761850,-73.997900,United States,...,$172,30.0,2.0,10/30/2021,0.10,4.0,58.0,164.0,NaN,NaN
64486,36616954,2 BR Apt in luxury amenity building Prime loca...,31714032010,unconfirmed,Paradise Suites,Manhattan,Midtown,40.758900,-73.960850,United States,...,$180,30.0,2.0,8/15/2021,0.07,3.0,5.0,352.0,NaN,NaN
65187,37004116,444 - Bright 2 BR unit in luxury amenity building,49019266100,verified,Paradise Suites,Manhattan,Upper East Side,40.758980,-73.959830,United States,...,$67,30.0,1.0,6/30/2021,0.12,2.0,5.0,352.0,NaN,NaN
65422,37133907,1 BR Apt in luxury amenity building Prime loca...,82050632139,verified,Paradise Suites,Manhattan,Midtown,40.758920,-73.961040,United States,...,$181,30.0,1.0,6/1/2021,0.11,3.0,5.0,352.0,NaN,NaN
65760,37320584,Beautiful 1BR | Hells Kitchen | Furnished | GLS,70824680619,verified,Global Luxury Suites,Manhattan,Hell's Kitchen,40.760510,-73.999620,United States,...,$236,30.0,4.0,4/9/2021,0.08,4.0,58.0,327.0,NaN,NaN
66487,37722106,Spacious Midtown 2BR | Desk | Washer/Dryer | GLS,55245605759,unconfirmed,Global Luxury Suites,Manhattan,Hell's Kitchen,40.762380,-73.998400,United States,...,$218,30.0,1.0,11/15/2020,0.06,3.0,58.0,9.0,NaN,NaN
66801,37895528,Modern Studio | Work Desk/WiFi | by Hudson River,96611053297,verified,Global Luxury Suites,Manhattan,Hell's Kitchen,40.761160,-73.999430,United States,...,$92,30.0,4.0,9/19/2020,0.07,4.0,58.0,337.0,NaN,NaN
67170,38099327,"Fifty Hotel & Suites by Affinia, Guest Room 2 Bed",32634289322,unconfirmed,Fifty Hotel & Suites,Manhattan,Midtown,40.756680,-73.972180,United States,...,$27,1.0,2.0,7/7/2020,0.07,4.0,4.0,96.0,NaN,NaN
67252,38144616,Chic Midtown NYC Studio | Washer | Kitchen | GLS,19941929297,unconfirmed,Global Luxury Suites,Manhattan,Hell's Kitchen,40.760980,-73.999520,United States,...,$79,30.0,2.0,6/12/2020,0.03,2.0,58.0,349.0,NaN,NaN
69141,39187910,*Luxury 1BR at 8th & Broadway | Hells Kitchen NYC,14672747504,unconfirmed,Global Luxury Suites,Manhattan,Hell's Kitchen,40.765100,-73.984370,United States,...,$130,30.0,1.0,1/9/2022,0.54,3.0,58.0,364.0,NaN,NaN
69171,39204479,The Mahogany Suite- The Solo Adventurer l,45508175705,unconfirmed,The Mahogany Suite(Studio Apartment,Brooklyn,East Flatbush,40.661120,-73.934200,United States,...,$104,30.0,30.0,1/8/2022,0.45,4.0,2.0,247.0,NaN,NaN
75739,42831986,The Mahogany Suite-The Solo Adventurer-ll,93868428057,unconfirmed,The Mahogany Suite(Studio Apartment,Brooklyn,East Flatbush,40.662710,-73.934980,United States,...,$150,32.0,32.0,5/13/2019,0.93,5.0,3.0,345.0,NaN,NaN
87900,49548506,The Mahogany Suite- The Solo Adventurer l,2492684595,verified,The Mahogany Suite(Studio Apartment,Brooklyn,East Flatbush,40.662800,-73.933970,United States,...,$164,2.0,24.0,6/17/2019,0.71,2.0,3.0,290.0,NaN,NaN
88062,49637979,Middle Size Room Super Convenient Area: ♥of Bklyn,96393249484,unconfirmed,Sho-Boo Of Sho-Boo Suite,Brooklyn,Prospect-Lefferts Gardens,40.662910,-73.962570,United States,...,$200,1.0,42.0,5/26/2019,1.19,5.0,3.0,337.0,We take great care of our home and want our gu...,NaN
88397,49822999,The Mahogany Suite-The Solo Adventurer-ll,22158167824,unconfirmed,The Mahogany Suite(Studio Apartment,Brooklyn,East Flatbush,40.662710,-73.934980,United States,...,$150,32.0,32.0,5/13/2019,0.93,5.0,3.0,345.0,NaN,NaN

In [41]:
data[data["host name"].str.endswith("Suite",na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
8195,5527435,Cozy Room in Super Convenient Area,48083055178,verified,Sho-Boo Of Sho-Boo Suite,Brooklyn,Prospect-Lefferts Gardens,40.66083,-73.96247,United States,...,$237,1.0,26.0,7/31/2018,0.52,3.0,3.0,40.0,Events and parties YES... but NON SMOKERS on...,NaN
8232,5547870,Private Room Right by Subway to Manhattan *alt*,97894790174,unconfirmed,Sho-Boo Of Sho-Boo Suite,Brooklyn,Prospect-Lefferts Gardens,40.66117,-73.96083,United States,...,$159,1.0,54.0,10/25/2017,1.10,5.0,3.0,291.0,No smoking allowed in property or on roof deck...,NaN
18240,11075288,Middle Size Room Super Convenient Area: ♥of Bklyn,29929137262,unconfirmed,Sho-Boo Of Sho-Boo Suite,Brooklyn,Prospect-Lefferts Gardens,40.66291,-73.96257,United States,...,$200,1.0,42.0,5/26/2019,1.19,5.0,3.0,337.0,We take great care of our home and want our gu...,NaN
37489,21706511,"Comfortable- JFK,LGA Best Value",48992030362,verified,Shared Stay-JFK The Hugh Suite,Queens,Springfield Gardens,40.66102,-73.77035,United States,...,$147,1.0,57.0,6/21/2019,7.28,3.0,3.0,342.0,We will try to always treat you with loving ki...,NaN
37703,21824703,"Clean , Safe, Cozy 3min to JFK , LGA Best Value",50915561866,verified,Shared Stay-JFK The Hugh Suite,Queens,Springfield Gardens,40.66199,-73.77200,United States,...,$137,1.0,73.0,7/1/2019,9.09,2.0,3.0,340.0,No smoking. No pets. No parties.,NaN
39687,22920466,The Den - 3 mins to JFK,13285621163,verified,Shared Stay-JFK The Hugh Suite,Queens,Springfield Gardens,40.66284,-73.76962,United States,...,$19,1.0,17.0,6/11/2019,2.60,4.0,3.0,0.0,No candles. Close and lock windows when you le...,NaN
88062,49637979,Middle Size Room Super Convenient Area: ♥of Bklyn,96393249484,unconfirmed,Sho-Boo Of Sho-Boo Suite,Brooklyn,Prospect-Lefferts Gardens,40.66291,-73.96257,United States,...,$200,1.0,42.0,5/26/2019,1.19,5.0,3.0,337.0,We take great care of our home and want our gu...,NaN

In [42]:
#27. Select listings that have both price &gt; 150 and availability_365 &gt; 200.
data[(data["price"]>150) & (data["availability 365"]>200)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,$50,1.0,0.0,NaN,NaN,1.0,1.0,276.0,#NAME?,NaN
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN

In [43]:
#28. Filter listings where neighbourhood_group equals “Manhattan” and room_type equals “Entire home/apt”.
data["neighbourhood group"].unique()

array(['Brooklyn', 'Manhattan', 'brookln', 'manhatan', 'Queens', nan,
       'Staten Island', 'Bronx'], dtype=object)

In [44]:
data["room type"].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

In [45]:
data[(data['room type']=="Entire home/apt") & (data['neighbourhood group']=='Manhattan')]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,...,$64,1.0,160.0,6/9/2019,1.33,3.0,4.0,1.0,NaN,NaN
11,1007411,Beautiful 1br on Upper West Side,18824631834,verified,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,...,$121,5.0,53.0,6/22/2019,0.43,4.0,1.0,163.0,"My ideal guests would be warm, friendly, and r...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102586,6088019,Patio Oasis in Upper East Side,41141109074,verified,Margaret,Manhattan,Upper East Side,40.77703,-73.94773,United States,...,$42,4.0,8.0,8/8/2016,0.17,5.0,1.0,159.0,- NO SMOKING (You'll have to do that outside i...,NaN
102588,6089124,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,...,$124,1.0,177.0,6/29/2019,3.78,4.0,1.0,410.0,Keep the apartment clean and damage free please.,NaN
102591,6090781,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,...,$228,5.0,17.0,1/4/2019,0.35,5.0,1.0,134.0,#NAME?,NaN
102592,6091333,3BR/1 Ba in TriBeCa w/ outdoor deck,53266862889,unconfirmed,Nick,Manhattan,Tribeca,40.71845,-74.01183,United States,...,$157,1.0,0.0,NaN,NaN,2.0,1.0,177.0,Guests should treat my home as if it were thei...,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [46]:
#29. Show all listings that were last reviewed in the year 2022.
data[data["last review"].str.endswith("2022",na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
103,1058223,Monkey Retreat Manhattan,62028601494,verified,Kelsey,Manhattan,Washington Heights,40.83927,-73.94281,United States,...,$61,NaN,68.0,1/2/2022,0.60,NaN,1.0,393.0,Not many rules except there is no smoking,NaN
189,1105721,"LARGE, COMFY 1BDR W/CHARACTER!!!",5715989004,verified,Edgar,Brooklyn,Bedford-Stuyvesant,40.68237,-73.94150,United States,...,$35,NaN,30.0,3/2/2022,0.29,NaN,1.0,NaN,NaN,NaN
230,1128365,"Nice, clean, safe, convenient 3BR",41153188173,unconfirmed,Fowler,Queens,Ridgewood,40.70411,-73.89934,United States,...,$131,14.0,1.0,4/3/2022,0.01,5.0,5.0,80.0,-Remove shoes -be sure to lock the front door ...,NaN
316,1175863,Luxury 3 bed/ 2 bath apt in Harlem w/ terrace,44227072273,unconfirmed,Henderson,Manhattan,Harlem,40.80276,-73.95670,United States,...,$145,14.0,31.0,3/1/2022,0.31,5.0,1.0,81.0,Please do not smoke in the house. If you smoke...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69193,39216630,Cozy BX Home Away From Home ( 2 nd floor),76770057440,unconfirmed,Paulene,Bronx,Wakefield,40.88990,-73.85871,United States,...,$41,4.0,48.0,1/8/2022,1.34,4.0,1.0,57.0,NaN,NaN
69275,39261919,Large Room w/ Private Entrance,59188125571,unconfirmed,Jacques,Brooklyn,Bedford-Stuyvesant,40.68905,-73.95410,United States,...,$34,7.0,2.0,5/5/2022,0.02,5.0,3.0,0.0,NaN,NaN
69309,39280697,Rent in beautiful Sunnyside Gardens for holidays,25481131720,verified,Jazmin,Queens,Sunnyside,40.74679,-73.91853,United States,...,$69,3.0,1.0,4/4/2022,0.01,2.0,1.0,330.0,NaN,NaN
69365,39311626,"Enjoy a 1 Bedroom to share, NYC",83703261637,unconfirmed,Catherine,Manhattan,Upper East Side,40.77799,-73.95223,United States,...,$80,1.0,1.0,1/2/2022,0.01,2.0,1.0,0.0,NaN,NaN
69381,39320462,"Cozy, Hella Sunny, and Convenient!",76807548267,verified,Dennis,Brooklyn,Prospect Heights,40.67717,-73.96915,United States,...,$162,30.0,1.0,3/1/2022,0.01,1.0,1.0,341.0,NaN,NaN

In [47]:
#30. Display all listings where the name column contains “Downtown”.
data[data["NAME"].str.contains("Downtown",case=False,na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
41,1023980,ENJOY Downtown NYC!,63131487263,unconfirmed,Byron,Manhattan,East Village,40.72290,-73.98199,United States,...,$113,2.0,245.0,6/21/2019,2.08,3.0,2.0,354.0,NaN,NaN
274,1152666,ENJOY Downtown NYC!!,7784280062,verified,Gibson,Manhattan,East Village,40.72321,-73.98157,United States,...,$85,2.0,203.0,6/23/2019,1.96,3.0,2.0,NaN,"No smoking inside. Be tidy, we don't have a ma...",NaN
345,1191880,MODERN SPACIOUS 2 BR APT DOWNTOWN MANHATTAN,41888244194,verified,Higgins,Manhattan,Lower East Side,40.71965,-73.98766,United States,...,$106,2.0,151.0,6/24/2019,1.51,4.0,2.0,NaN,-Remove shoes -be sure to lock the front door ...,NaN
459,1254842,Surfer room 15mins to downtown NYC!,83903389887,verified,Eleanor,Brooklyn,Williamsburg,40.71309,-73.94128,United States,...,$45,6.0,3.0,8/31/2014,0.03,5.0,1.0,231.0,No smoking,NaN
487,1270306,Very close to Downtown Awesome Private Apartment,7445813909,unconfirmed,Antony,Brooklyn,Gravesend,40.60452,-73.97103,United States,...,$152,7.0,0.0,NaN,NaN,NaN,2.0,159.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102129,35546044,The Residences at W New York - Downtown - Apt 27D,43741555866,unconfirmed,Zeus,Manhattan,Financial District,40.71035,-74.01427,United States,...,$32,30.0,2.0,11/9/2021,0.10,NaN,34.0,333.0,NaN,NaN
102162,35564270,20-25 minutes to downtown NYC/30-40 to midtown,60438862057,unconfirmed,Alan,Brooklyn,Bedford-Stuyvesant,40.69566,-73.93546,United States,...,$192,30.0,107.0,11/7/2021,1.59,2.0,3.0,211.0,NaN,NaN
102426,20384857,Charming 3bed/2ba Downtown/LES,55829170118,unconfirmed,Anastasia,Manhattan,Lower East Side,40.71815,-73.98213,United States,...,$166,3.0,6.0,3/31/2019,0.87,5.0,1.0,67.0,- We have a lovable and very social black lab ...,NaN
102429,20386514,Huge Room for Nightly Stays Downtown or Monthly,44994616102,verified,Abbey,Manhattan,Tribeca,40.71810,-74.00999,United States,...,$204,5.0,3.0,5/21/2019,0.30,3.0,1.0,95.0,No pets No alcohol,NaN
102561,6074212,NO FEE RENTAL *Lease Takeover Modern Apt Downtown,60627453207,verified,Monica,Manhattan,Financial District,40.70809,-74.00170,United States,...,$171,1.0,0.0,NaN,NaN,3.0,1.0,286.0,Please don't fiddle around with my stuff or an...,NaN

In [48]:
#31. Retrieve listings where reviews_per_month is greater than 2.
data[data["reviews per month"]>2]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
18,1011277,Chelsea Perfect,73862528370,verified,Alberta,manhatan,Chelsea,40.74192,-73.99501,United States,...,NaN,1.0,260.0,7/1/2019,2.12,3.0,1.0,325.0,NaN,NaN
19,1011830,Hip Historic Brownstone Apartment with Backyard,72145018858,NaN,Martin,Brooklyn,Crown Heights,40.67592,-73.94694,United States,...,NaN,3.0,53.0,6/22/2019,4.44,5.0,1.0,345.0,LAUNDRY - Laundry can be done by the visitor b...,NaN
31,1018457,front room/double bed,69410526955,unconfirmed,Byron,Manhattan,Harlem,40.82245,-73.95104,United States,...,$154,3.0,242.0,6/1/2019,2.04,NaN,3.0,105.0,No loud noises or loud music. Please help us s...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102569,6078630,"Elegant 1BR, Private Bath in Brownstone",37385825013,verified,Emily And Joel,Brooklyn,Park Slope,40.66880,-73.97865,United States,...,$197,1.0,184.0,2/10/2019,3.86,4.0,4.0,407.0,NO Smoking,NaN
102575,6081944,NYC Chauncey 2 .20 min to manhattan,26326930315,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.68237,-73.91977,United States,...,$120,1.0,123.0,3/17/2019,2.95,2.0,4.0,200.0,NO Smoking Pets Allowed with a $375 non refund...,NaN
102579,6084153,Alexander's 2BR Luxury Quarters,32736284559,verified,Juan,Brooklyn,Bedford-Stuyvesant,40.68740,-73.93830,United States,...,$59,3.0,123.0,6/26/2019,2.53,4.0,1.0,203.0,NaN,NaN
102580,6084705,"Near LGA, Citifield, US Open Tennis",97606085736,verified,Carmen,Queens,East Elmhurst,40.76578,-73.86424,United States,...,$122,1.0,209.0,6/11/2019,4.38,3.0,1.0,270.0,House Rules 1. Check-in is 4 pm local time. If...,NaN
102588,6089124,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,...,$124,1.0,177.0,6/29/2019,3.78,4.0,1.0,410.0,Keep the apartment clean and damage free please.,NaN

In [49]:
#32. Select listings where host_id appears more than once.
host_count=data["host id"].value_counts()

In [50]:
list_host=host_count[host_count>1].index

In [51]:
data[data["host id"].isin(list_host)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
9098,6026161,Upper East Side 2 bedroom- close to Hospitals-,65193709566,verified,Juliana,Manhattan,Upper East Side,40.76222,-73.96030,United States,...,$21,30.0,2.0,6/8/2019,0.21,3.0,34.0,157.0,NaN,NaN
9099,6026714,Close to East Side Hospitals- Modern 2 Bedroom...,31072202372,verified,Juliana,Manhattan,Upper East Side,40.76249,-73.96217,United States,...,$57,30.0,6.0,1/31/2019,0.14,3.0,34.0,67.0,"The quieter the better, but otherwise make you...",NaN
9100,6027266,ACADIA Spacious 2 Bedroom Apt - Close to Hospi...,95854111798,verified,Juliana,Manhattan,Upper East Side,40.76021,-73.96157,United States,...,$117,30.0,10.0,11/18/2018,0.22,5.0,34.0,211.0,No Smoking No Pets,NaN
9101,6027818,*ENCHANTMENT* Upper East Side 2 bedroom- Sunny!,73401481508,unconfirmed,Juliana,Manhattan,Upper East Side,40.76244,-73.96031,United States,...,$108,30.0,9.0,9/30/2018,0.20,5.0,34.0,411.0,Please treat it as it were your own home and b...,NaN
9102,6028371,*JAMES* Amazing Spacious 2 Bedroom- Bright!,37678424985,verified,Juliana,Manhattan,Upper East Side,40.76035,-73.96133,United States,...,$161,30.0,8.0,6/11/2019,0.27,4.0,34.0,411.0,Be courteous and respectful to people in the h...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [52]:
#33. Filter all listings not located in “Brooklyn”.
data[~data["NAME"].str.contains("Brooklyn",case=False,na=False)]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,$220,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [53]:
#34. Retrieve listings where city column contains “York”.

In [54]:
#35. Get all listings that have a price greater than the average price.
avg_p=data["price"].mean()

In [55]:
data[data["price"]>avg_p]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
12,1007964,Central Manhattan/near Broadway,88136055909,verified,NaN,Manhattan,Hell's Kitchen,40.76076,-73.98867,United States,...,$143,2.0,188.0,6/23/2019,1.50,4.0,1.0,258.0,- One of the bedroom closets is not accessible...,NaN
16,1010173,Only 2 stops to Manhattan studio,62566345680,unconfirmed,Heather,Brooklyn,Williamsburg,40.70837,-73.95352,United States,...,NaN,2.0,148.0,6/29/2019,1.20,3.0,1.0,197.0,"Absolutely no smoking in the building, handlin...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,$220,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [56]:
#36. Display listings with minimum_nights exactly equal to 7.
data[data["minimum nights"]==7]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
20,1012382,Huge 2 BR Upper East Cental Park,79805143117,verified,Audrey,Manhattan,East Harlem,40.79685,-73.94872,United States,...,$56,7.0,0.0,NaN,NaN,3.0,2.0,347.0,"No smoking, No pets. No shoes in the house. V...",NaN
43,1025085,1bdr w private bath. in lofty apt,45597582469,NaN,Charlie,Brooklyn,Fort Greene,40.69673,-73.97584,United States,...,$137,7.0,25.0,9/30/2018,0.23,1.0,1.0,405.0,"No smoking, No pets. No shoes in the house. Vi...",NaN
45,1026190,BEST BET IN HARLEM,2107606817,unconfirmed,Chester,Manhattan,Harlem,40.81175,-73.94478,United States,...,$12,7.0,97.0,6/13/2019,0.84,NaN,1.0,152.0,- Quiet hours between 10pm-6am - Visitors in c...,NaN
65,1037236,Double Room w Private Deck Clinton Hill Best Area,71078326464,unconfirmed,William,Brooklyn,Clinton Hill,40.69000,-73.96788,United States,...,$165,7.0,27.0,9/30/2017,0.23,2.0,2.0,NaN,NaN,NaN
73,1041654,Cool Room in Hell's Kitchen,44843744875,verified,Charlie,Manhattan,Hell's Kitchen,40.76342,-73.98865,United States,...,$121,7.0,23.0,6/1/2019,0.43,3.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102545,6065375,Loft rental off of Graham!,24747380997,unconfirmed,Frances,Brooklyn,Williamsburg,40.71303,-73.94063,United States,...,$188,7.0,2.0,8/23/2016,0.04,2.0,1.0,374.0,NaN,NaN
102553,6069793,"Custom Designed Cozy Garden Apt,",7756381071,unconfirmed,Jean& Toney,Brooklyn,Canarsie,40.64574,-73.90781,United States,...,$41,7.0,0.0,NaN,NaN,4.0,3.0,95.0,"- Absolutely no smoking in, on or near the pro...",NaN
102555,6070898,Sublet entire apt in Brooklyn,83573592009,unconfirmed,Laszlo Jakab,Brooklyn,Brooklyn Heights,40.69382,-73.99334,United States,...,$111,7.0,1.0,6/29/2015,0.02,4.0,1.0,299.0,No smoking in the unit or in the building (str...,NaN
102568,6078078,Furnished Bedroom in 2 Bedroom apt.,43698780331,verified,Etkin,Queens,Long Island City,40.75600,-73.92050,United States,...,$210,7.0,0.0,NaN,NaN,4.0,1.0,34.0,NaN,NaN
102582,6085810,Private room in the best part of BK,4746552394,verified,Brad,Brooklyn,Crown Heights,40.66743,-73.94712,United States,...,$103,7.0,49.0,6/1/2019,1.01,2.0,1.0,425.0,No Smoking. Pets Allowed with fee.,NaN

In [57]:
#37. Select listings with an even number of minimum_nights.
data[data["minimum nights"] %2==0]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102577,6083048,Gigantic Private Brooklyn Apartment,55330806381,verified,Nikki,Brooklyn,Greenpoint,40.72442,-73.93957,United States,...,$139,10.0,2.0,7/6/2016,0.04,1.0,1.0,33.0,NaN,NaN
102581,6085258,Bright Bedroom in Bustling Bed Stuy Brooklyn,17339949163,unconfirmed,Amber,Brooklyn,Bedford-Stuyvesant,40.68742,-73.92825,United States,...,$15,2.0,34.0,7/1/2019,0.70,5.0,3.0,299.0,It is a residential building so all of the res...,NaN
102584,6086914,2 block walk from the beach in NYC,70051719594,verified,Vladimir,Queens,Arverne,40.59270,-73.78990,United States,...,$113,2.0,89.0,5/26/2019,1.82,2.0,1.0,394.0,NaN,NaN
102586,6088019,Patio Oasis in Upper East Side,41141109074,verified,Margaret,Manhattan,Upper East Side,40.77703,-73.94773,United States,...,$42,4.0,8.0,8/8/2016,0.17,5.0,1.0,159.0,- NO SMOKING (You'll have to do that outside i...,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN

In [58]:
#38. Retrieve all listings whose host name length is more than 10 characters.
data[data["host name"].str.len()>10]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
1073,1593954,Serene Room...,49750343850,verified,Maria Luiza,Brooklyn,Sunset Park,40.63970,-74.01620,United States,...,$95,7.0,28.0,5/12/2019,0.32,2.0,2.0,160.0,For Your CarYup! IT'S JUST THE PARKING SPACE. ...,NaN
1091,1603895,"Cozy private room, williamsburg NYC",71939962014,verified,Javier & Jorge,Brooklyn,Williamsburg,40.70610,-73.94531,United States,...,$140,4.0,132.0,6/10/2019,1.51,3.0,2.0,407.0,*Please share with other guests in your reserv...,NaN
1100,1608866,Sunny plant-filled apartment with 2 balconies,81188620051,unconfirmed,Ora & Scout,Brooklyn,Crown Heights,40.67615,-73.95441,United States,...,$80,2.0,35.0,1/1/2018,0.54,4.0,3.0,277.0,House Rules 1. Check-in is 4 pm local time. If...,NaN
1102,1609971,"Bright, Bedstuy Gem",14399757070,verified,Nicole Lavonne,Brooklyn,Bedford-Stuyvesant,40.68944,-73.93760,United States,...,$30,3.0,182.0,7/1/2019,2.15,4.0,1.0,-1.0,House Rules 1. Check-in is 4 pm local time. If...,NaN
1113,1616046,Gorgeous Summer Duplex/Yard sublet,9729014487,unconfirmed,Verena And Dylan,Brooklyn,Bedford-Stuyvesant,40.68229,-73.94287,United States,...,$191,14.0,3.0,9/1/2013,0.04,4.0,1.0,338.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102518,6050463,Beautiful apartment in awesome Clinton Hill!,18401849962,unconfirmed,Xristina&Keith,Brooklyn,Bedford-Stuyvesant,40.69213,-73.95869,United States,...,$12,15.0,5.0,5/20/2019,0.26,4.0,1.0,421.0,No smoking. No pets. Children under 18 to be s...,NaN
102553,6069793,"Custom Designed Cozy Garden Apt,",7756381071,unconfirmed,Jean& Toney,Brooklyn,Canarsie,40.64574,-73.90781,United States,...,$41,7.0,0.0,NaN,NaN,4.0,3.0,95.0,"- Absolutely no smoking in, on or near the pro...",NaN
102555,6070898,Sublet entire apt in Brooklyn,83573592009,unconfirmed,Laszlo Jakab,Brooklyn,Brooklyn Heights,40.69382,-73.99334,United States,...,$111,7.0,1.0,6/29/2015,0.02,4.0,1.0,299.0,No smoking in the unit or in the building (str...,NaN
102569,6078630,"Elegant 1BR, Private Bath in Brownstone",37385825013,verified,Emily And Joel,Brooklyn,Park Slope,40.66880,-73.97865,United States,...,$197,1.0,184.0,2/10/2019,3.86,4.0,4.0,407.0,NO Smoking,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN

In [59]:
#39. Filter listings where price is a multiple of 50.
data[data["price"]%50==0]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
23,1014039,CBG Helps Haiti Room#2.5,87668933180,NaN,William,Brooklyn,Park Slope,40.67989,-73.97798,United States,...,$210,1.0,39.0,1/1/2019,0.37,3.0,6.0,9.0,NaN,NaN
107,1060432,Large 2 Bedroom Great for Groups!,94662871331,unconfirmed,Tess,Brooklyn,Bedford-Stuyvesant,40.68373,-73.92377,United States,...,$100,90.0,162.0,6/28/2019,1.46,3.0,2.0,189.0,- Thanks for not smoking and leaving your pets...,NaN
165,1092466,Charming & Cozy midtown loft any WEEK ENDS !!!,3310140241,verified,Luke,Manhattan,Upper East Side,40.76123,-73.96420,United States,...,$190,81.0,4.0,9/23/2016,NaN,1.0,1.0,335.0,Please be respectful. Keep noise to a minimum...,NaN
183,1102407,Couldn't Be Closer To Columbia Uni,44580630332,unconfirmed,Bruce,Manhattan,Morningside Heights,40.80549,-73.95924,United States,...,$90,110.0,122.0,5/14/2019,1.18,4.0,2.0,425.0,NaN,NaN
278,1154875,CHARMING EAST VILLAGE 2 (or 1) BR,18425219763,unconfirmed,Chapman,Manhattan,East Village,40.72956,-73.98158,United States,...,$170,7.0,5.0,1/3/2019,0.15,4.0,1.0,33.0,Thanks for not smoking and leaving your pets a...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102320,20326313,Spacious room in awesome Bushwick townhouse,31263630543,unconfirmed,Sebastien,Brooklyn,Bushwick,40.69194,-73.92352,United States,...,$110,3.0,1.0,8/29/2018,0.10,3.0,1.0,0.0,NaN,NaN
102394,20367183,Sonder | Madison Ave | Modern 1BR + Gym,94899572175,verified,Sonder,Manhattan,Midtown,40.74705,-73.98268,United States,...,$200,29.0,0.0,NaN,NaN,2.0,96.0,328.0,I'll guide you with everything upon check-in,NaN
102414,20378229,Morningside Heights Cozy & Clean Modern Apt.,20091049290,verified,Krystalee,Manhattan,Harlem,40.80624,-73.95622,United States,...,$100,1.0,1.0,8/31/2018,0.10,3.0,1.0,0.0,"Respect yourself, respect others, clean up aft...",NaN
102503,6042178,"Perfect for Cat, Book, Park Lovers!",17949645201,verified,Laura,Brooklyn,Flatbush,40.65371,-73.95623,United States,...,$80,2.0,12.0,12/19/2015,0.25,1.0,1.0,0.0,No smoking in the unit or in the building (str...,NaN
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,$50,1.0,0.0,NaN,NaN,1.0,1.0,276.0,#NAME?,NaN

In [60]:
#40. Show listings with names having more than 3 words.
def length(x):
    sp=x.split(" ")
    if len(sp)>3:
        return x
    else:
        return "N"

In [61]:
data["new"]=data["NAME"].astype("str").apply(length)

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 27 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  float64
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
 26  new                             102599 non-null  object
dtypes: float64(10), int64(2), object(15)
memory usage: 21.1+ MB

In [63]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,new
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,N
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,N
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn"
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN,585 sf Luxury Studio

In [64]:
data[data["new"]!="N"]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,new
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN,Large Cozy 1 BR Apartment In Midtown East
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN,Large Furnished Room Near B'way
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn"
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN,585 sf Luxury Studio

In [65]:
#41. Rename the column neighbourhood_group to region.
data.rename(columns={"neighbourhood group":"region"})

,id,NAME,host id,host_identity_verified,host name,region,neighbourhood,lat,long,country,...,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,new
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,N
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,N
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn"
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN,585 sf Luxury Studio

In [66]:
#42. Add a new column price_per_review = price / number_of_reviews.
data["price_per_review"]=data["price"]/data["number of reviews"]

In [67]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,new,price_per_review
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,N,1.362963
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN,585 sf Luxury Studio,inf

In [68]:
#43. Create a column price_category as “Low”, “Medium”, or “High” based on price ranges.
avg_p

np.float64(625.2935360325152)

In [69]:
def price(x):
    if x<avg_p:
        return "Low"
    elif x>avg_p:
        return "High"
    else:
        return "Medium"

In [70]:
data["price_category"]=data["price"].apply(price)

In [71]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,new,price_per_review,price_category
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN,N,1.362963,Low
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,NaN,NaN,5.0,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,NaN,NaN,3.0,1.0,69.0,NaN,NaN,585 sf Luxury Studio,inf,High

In [72]:
#44. Add a column showing the length of each listing’s name.
data["name_len"]=data["NAME"].astype('str').apply(lambda x:len(x))

In [73]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license,new,price_per_review,price_category,name_len
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High,34
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low,21
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,4.64,4.0,1.0,322.0,NaN,NaN,N,1.362963,Low,3
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High,26
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High,29
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,NaN,5.0,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High,30
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,0.10,3.0,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,NaN,3.0,1.0,69.0,NaN,NaN,585 sf Luxury Studio,inf,High,20

In [74]:
#45. Combine city and neighbourhood into a new column full_location.

In [75]:
def year(x):
    sp=x.split("/")
    return sp[-1]

In [76]:
#46. Extract the year from last_review into a new column review_year.
data["review_year"]=data["last review"].astype("str").apply(year)

In [77]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,review rate number,calculated host listings count,availability 365,house_rules,license,new,price_per_review,price_category,name_len,review_year
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High,34,2021
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low,21,2022
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35,nan
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,4.0,1.0,322.0,NaN,NaN,N,1.362963,Low,3,2019
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High,26,nan
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High,29,2015
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,5.0,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High,30,nan
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,3.0,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32,2015
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,3.0,1.0,69.0,NaN,NaN,585 sf Luxury Studio,inf,High,20,nan

In [78]:
#47. Round all values in the reviews_per_month column to 2 decimal places.
data["reviews per month"]=data["reviews per month"].round(2)

In [79]:
#48. Replace all spaces in column names with underscores.
data.columns.str.replace(" ","_")

Index(['id', 'NAME', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'Construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license', 'new', 'price_per_review',
       'price_category', 'name_len', 'review_year'],
      dtype='object')

In [80]:
#49. Create a column is_available that is True if availability_365 &gt; 0, else False.
data["is_available"]=data["availability 365"].apply(lambda x:True if x>0 else False)

In [81]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,calculated host listings count,availability 365,house_rules,license,new,price_per_review,price_category,name_len,review_year,is_available
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High,34,2021,True
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low,21,2022,True
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35,nan,True
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,1.0,322.0,NaN,NaN,N,1.362963,Low,3,2019,True
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48,2018,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High,26,nan,True
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High,29,2015,True
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High,30,nan,True
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32,2015,True
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1.0,69.0,NaN,NaN,585 sf Luxury Studio,inf,High,20,nan,True

In [82]:
#50. Change all text in room_type to uppercase.
data["room type"]=data["room type"].str.upper()

In [83]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,calculated host listings count,availability 365,house_rules,license,new,price_per_review,price_category,name_len,review_year,is_available
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High,34,2021,True
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low,21,2022,True
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35,nan,True
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,1.0,322.0,NaN,NaN,N,1.362963,Low,3,2019,True
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48,2018,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High,26,nan,True
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,2.0,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High,29,2015,True
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,1.0,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High,30,nan,True
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,1.0,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32,2015,True
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1.0,69.0,NaN,NaN,585 sf Luxury Studio,inf,High,20,nan,True

In [84]:
#51. Create a column price_in_inr assuming 1 USD = 83 INR.
data["price_in_inr"]=data["price"]*83

In [85]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,availability 365,house_rules,license,new,price_per_review,price_category,name_len,review_year,is_available,price_in_inr
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High,34,2021,True,80178.0
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low,21,2022,True,11786.0
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35,nan,True,51460.0
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,322.0,NaN,NaN,N,1.362963,Low,3,2019,True,30544.0
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48,2018,True,16932.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High,26,nan,True,70052.0
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High,29,2015,True,69471.0
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High,30,nan,True,82004.0
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32,2015,True,45318.0
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,69.0,NaN,NaN,585 sf Luxury Studio,inf,High,20,nan,True,85656.0

In [86]:
#52. Reorder columns so that price comes first.
price_column=data.pop("price")
data.insert(0,"price",price_column)

In [87]:
data

,price,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,availability 365,house_rules,license,new,price_per_review,price_category,name_len,review_year,is_available,price_in_inr
0,966.0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High,34,2021,True,80178.0
1,142.0,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low,21,2022,True,11786.0
2,620.0,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,...,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35,nan,True,51460.0
3,368.0,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,...,322.0,NaN,NaN,N,1.362963,Low,3,2019,True,30544.0
4,204.0,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48,2018,True,16932.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844.0,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,...,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High,26,nan,True,70052.0
102595,837.0,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,...,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High,29,2015,True,69471.0
102596,988.0,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,...,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High,30,nan,True,82004.0
102597,546.0,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,...,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32,2015,True,45318.0
102598,1032.0,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,...,69.0,NaN,NaN,585 sf Luxury Studio,inf,High,20,nan,True,85656.0

In [88]:
#53. Drop the id column from the dataset.
data.drop("id",axis=1)

,price,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,availability 365,house_rules,license,new,price_per_review,price_category,name_len,review_year,is_available,price_in_inr
0,966.0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,286.0,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High,34,2021,True,80178.0
1,142.0,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,228.0,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low,21,2022,True,11786.0
2,620.0,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,352.0,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35,nan,True,51460.0
3,368.0,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,322.0,NaN,NaN,N,1.362963,Low,3,2019,True,30544.0
4,204.0,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,289.0,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48,2018,True,16932.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844.0,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High,26,nan,True,70052.0
102595,837.0,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,395.0,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High,29,2015,True,69471.0
102596,988.0,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,342.0,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High,30,nan,True,82004.0
102597,546.0,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,386.0,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32,2015,True,45318.0
102598,1032.0,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,69.0,NaN,NaN,585 sf Luxury Studio,inf,High,20,nan,True,85656.0

In [89]:
#54. Change the data type of price to integer.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   price                           102352 non-null  float64
 1   id                              102599 non-null  int64
 2   NAME                            102349 non-null  object
 3   host id                         102599 non-null  int64
 4   host_identity_verified          102310 non-null  object
 5   host name                       102193 non-null  object
 6   neighbourhood group             102570 non-null  object
 7   neighbourhood                   102583 non-null  object
 8   lat                             102591 non-null  float64
 9   long                            102591 non-null  float64
 10  country                         102067 non-null  object
 11  country code                    102468 non-null  object
 12  instant_bookable                102494 non-null  object
 13  cancellation_policy             102523 non-null  object
 14  room type                       102599 non-null  object
 15  Construction year               102385 non-null  float64
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
 26  new                             102599 non-null  object
 27  price_per_review                102169 non-null  float64
 28  price_category                  102599 non-null  object
 29  name_len                        102599 non-null  int64
 30  review_year                     102599 non-null  object
 31  is_available                    102599 non-null  bool
 32  price_in_inr                    102352 non-null  float64
dtypes: bool(1), float64(12), int64(3), object(17)
memory usage: 25.1+ MB

In [90]:
import numpy as np

In [91]:
data["price"]=data["price"].replace([np.inf,-np.inf],0)

In [92]:
data["price"]=data["price"].astype("Int64")

In [93]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   price                           102352 non-null  Int64
 1   id                              102599 non-null  int64
 2   NAME                            102349 non-null  object
 3   host id                         102599 non-null  int64
 4   host_identity_verified          102310 non-null  object
 5   host name                       102193 non-null  object
 6   neighbourhood group             102570 non-null  object
 7   neighbourhood                   102583 non-null  object
 8   lat                             102591 non-null  float64
 9   long                            102591 non-null  float64
 10  country                         102067 non-null  object
 11  country code                    102468 non-null  object
 12  instant_bookable                102494 non-null  object
 13  cancellation_policy             102523 non-null  object
 14  room type                       102599 non-null  object
 15  Construction year               102385 non-null  float64
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
 26  new                             102599 non-null  object
 27  price_per_review                102169 non-null  float64
 28  price_category                  102599 non-null  object
 29  name_len                        102599 non-null  int64
 30  review_year                     102599 non-null  object
 31  is_available                    102599 non-null  bool
 32  price_in_inr                    102352 non-null  float64
dtypes: Int64(1), bool(1), float64(11), int64(3), object(17)
memory usage: 25.2+ MB

In [94]:
#55. Create a new column showing price per night: price / minimum_nights.
data["price_per_night"]=data["price"]/data["minimum nights"]

In [95]:
data

,price,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,house_rules,license,new,price_per_review,price_category,name_len,review_year,is_available,price_in_inr,price_per_night
0,966,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,Clean up and treat the home the way you'd like...,NaN,Clean & quiet apt home by the park,107.333333,High,34,2021,True,80178.0,96.6
1,142,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,Pet friendly but please confirm with me if the...,NaN,N,3.155556,Low,21,2022,True,11786.0,4.733333
2,620,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,...,"I encourage you to use my kitchen, cooking and...",NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35,nan,True,51460.0,206.666667
3,368,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,...,NaN,NaN,N,1.362963,Low,3,2019,True,30544.0,12.266667
4,204,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,"Please no smoking in the house, porch or on th...",NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48,2018,True,16932.0,20.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,...,No Smoking No Parties or Events of any kind Pl...,NaN,Spare room in Williamsburg,inf,High,26,nan,True,70052.0,844.0
102595,837,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,...,House rules: Guests agree to the following ter...,NaN,Best Location near Columbia U,837.000000,High,29,2015,True,69471.0,837.0
102596,988,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,...,NaN,NaN,"Comfy, bright room in Brooklyn",inf,High,30,nan,True,82004.0,329.333333
102597,546,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,...,NaN,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32,2015,True,45318.0,273.0
102598,1032,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,...,NaN,NaN,585 sf Luxury Studio,inf,High,20,nan,True,85656.0,1032.0

In [96]:
#56. Add a Boolean column indicating if the name contains the word “Luxury”.
data["bool"]=data["NAME"].str.contains("Luxury",case=False,na=False)

In [97]:
data

,price,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,license,new,price_per_review,price_category,name_len,review_year,is_available,price_in_inr,price_per_night,bool
0,966,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,NaN,Clean & quiet apt home by the park,107.333333,High,34,2021,True,80178.0,96.6,False
1,142,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,NaN,N,3.155556,Low,21,2022,True,11786.0,4.733333,False
2,620,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,...,NaN,THE VILLAGE OF HARLEM....NEW YORK !,inf,Low,35,nan,True,51460.0,206.666667,False
3,368,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,...,NaN,N,1.362963,Low,3,2019,True,30544.0,12.266667,False
4,204,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,NaN,Entire Apt: Spacious Studio/Loft by central park,22.666667,Low,48,2018,True,16932.0,20.4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,...,NaN,Spare room in Williamsburg,inf,High,26,nan,True,70052.0,844.0,False
102595,837,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,...,NaN,Best Location near Columbia U,837.000000,High,29,2015,True,69471.0,837.0,False
102596,988,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,...,NaN,"Comfy, bright room in Brooklyn",inf,High,30,nan,True,82004.0,329.333333,False
102597,546,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,...,NaN,Big Studio-One Stop from Midtown,109.200000,Low,32,2015,True,45318.0,273.0,False
102598,1032,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,...,NaN,585 sf Luxury Studio,inf,High,20,nan,True,85656.0,1032.0,True

In [98]:
#57. Create a column for total estimated revenue = price * number_of_reviews.
data["total_est_revenue"]=data["price"]*data["number of reviews"]

In [99]:
data.columns

Index(['price', 'id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'new', 'price_per_review',
       'price_category', 'name_len', 'review_year', 'is_available',
       'price_in_inr', 'price_per_night', 'bool', 'total_est_revenue'],
      dtype='object')

In [100]:
#58. Replace “Entire home/apt” with “Whole Apartment” in the room_type column.
data['room type'].unique()

array(['PRIVATE ROOM', 'ENTIRE HOME/APT', 'SHARED ROOM', 'HOTEL ROOM'],
      dtype=object)

In [101]:
data["room type"].replace('ENTIRE HOME/APT',"Whole Apartment",inplace=True)

C:\Users\rames\AppData\Local\Temp\ipykernel_1208\3381271164.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["room type"].replace('ENTIRE HOME/APT',"Whole Apartment",inplace=True)

In [102]:
#59. Change all city names to lowercase.

In [103]:
#60. Split the listing name into two columns: first word and remaining words.

In [114]:
list1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   index   102599 non-null  int64
 1   NAME    102349 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.6+ MB

In [120]:
split=data["NAME"].str.split(" ",n=1,expand=True)

In [121]:
split

             0                                          1
0        Clean               & quiet apt home by the park
1       Skylit                             Midtown Castle
2          THE            VILLAGE OF HARLEM....NEW YORK !
3          NaN                                        NaN
4       Entire  Apt: Spacious Studio/Loft by central park
...        ...                                        ...
102594   Spare                       room in Williamsburg
102595    Best                   Location near Columbia U
102596  Comfy,                    bright room in Brooklyn
102597     Big               Studio-One Stop from Midtown
102598     585                           sf Luxury Studio

[102599 rows x 2 columns]

In [122]:
data["first_word"]=split[0]

In [123]:
data["second_column"]=split[1]

In [124]:
data

,price,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,price_category,name_len,review_year,is_available,price_in_inr,price_per_night,bool,total_est_revenue,first_word,second_column
0,966,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,High,34,2021,True,80178.0,96.6,False,8694.0,Clean,& quiet apt home by the park
1,142,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,Low,21,2022,True,11786.0,4.733333,False,6390.0,Skylit,Midtown Castle
2,620,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,...,Low,35,nan,True,51460.0,206.666667,False,0.0,THE,VILLAGE OF HARLEM....NEW YORK !
3,368,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,...,Low,3,2019,True,30544.0,12.266667,False,99360.0,NaN,NaN
4,204,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,Low,48,2018,True,16932.0,20.4,False,1836.0,Entire,Apt: Spacious Studio/Loft by central park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,...,High,26,nan,True,70052.0,844.0,False,0.0,Spare,room in Williamsburg
102595,837,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,...,High,29,2015,True,69471.0,837.0,False,837.0,Best,Location near Columbia U
102596,988,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,...,High,30,nan,True,82004.0,329.333333,False,0.0,"Comfy,",bright room in Brooklyn
102597,546,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,...,Low,32,2015,True,45318.0,273.0,False,2730.0,Big,Studio-One Stop from Midtown
102598,1032,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,...,High,20,nan,True,85656.0,1032.0,True,0.0,585,sf Luxury Studio

In [125]:
#61.  Find the average price for each room_type.
data.groupby("room type")["price"].mean()

room type
HOTEL ROOM         668.465517
PRIVATE ROOM       625.007363
SHARED ROOM        634.132101
Whole Apartment    625.082232
Name: price, dtype: Float64

In [126]:
#62.  Find the total number of listings per neighbourhood_group.
data.groupby("neighbourhood group")["id"].count()

neighbourhood group
Bronx             2712
Brooklyn         41842
Manhattan        43792
Queens           13267
Staten Island      955
brookln              1
manhatan             1
Name: id, dtype: int64

In [127]:
#63.  Compute the maximum and minimum price for each city.

In [129]:
#64.  Find which host has the maximum number of listings.
data.groupby('host name')['id'].count().idxmax()

'Michael'

In [130]:
#65.  Calculate the mean availability_365 for each room_type.
data.groupby('room type')['availability 365'].mean()

room type
HOTEL ROOM         218.310345
PRIVATE ROOM       137.557126
SHARED ROOM        172.666214
Whole Apartment    142.760376
Name: availability 365, dtype: float64

In [131]:
#66.  Get the count of unique host names per city.

In [132]:
data.columns

Index(['price', 'id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'new', 'price_per_review',
       'price_category', 'name_len', 'review_year', 'is_available',
       'price_in_inr', 'price_per_night', 'bool', 'total_est_revenue',
       'first_word', 'second_column'],
      dtype='object')

In [134]:
data["neighbourhood"].unique()

array(['Kensington', 'Midtown', 'Harlem', 'Clinton Hill', 'East Harlem',
       'Murray Hill', 'Bedford-Stuyvesant', "Hell's Kitchen",
       'Upper West Side', 'Chinatown', 'South Slope', 'West Village',
       'Williamsburg', 'Fort Greene', 'Chelsea', 'Crown Heights',
       'Park Slope', 'Windsor Terrace', 'Inwood', 'East Village',
       'Greenpoint', 'Bushwick', 'Flatbush', 'Lower East Side',
       'Prospect-Lefferts Gardens', 'Long Island City', 'Kips Bay',
       'SoHo', 'Upper East Side', 'Prospect Heights',
       'Washington Heights', 'Woodside', 'Brooklyn Heights',
       'Carroll Gardens', 'Gowanus', 'Flatlands', 'Cobble Hill',
       'Flushing', 'Boerum Hill', 'Sunnyside', 'DUMBO', 'St. George',
       'Highbridge', 'Financial District', 'Ridgewood',
       'Morningside Heights', 'Jamaica', 'Middle Village', 'NoHo',
       'Ditmars Steinway', 'Flatiron District', 'Roosevelt Island',
       'Greenwich Village', 'Little Italy', 'East Flatbush',
       'Tompkinsville', 'Astoria', 'Clason Point', 'Eastchester',
       'Kingsbridge', 'Two Bridges', 'Queens Village', 'Rockaway Beach',
       'Forest Hills', 'Nolita', 'Woodlawn', 'University Heights',
       'Gravesend', 'Gramercy', 'Allerton', nan, 'East New York',
       'Theater District', 'Concourse Village', 'Sheepshead Bay',
       'Emerson Hill', 'Fort Hamilton', 'Bensonhurst', 'Tribeca',
       'Shore Acres', 'Sunset Park', 'Concourse', 'Elmhurst',
       'Brighton Beach', 'Jackson Heights', 'Cypress Hills', 'St. Albans',
       'Arrochar', 'Rego Park', 'Wakefield', 'Clifton', 'Bay Ridge',
       'Graniteville', 'Spuyten Duyvil', 'Stapleton', 'Briarwood',
       'Ozone Park', 'Columbia St', 'Vinegar Hill', 'Mott Haven',
       'Longwood', 'Canarsie', 'Battery Park City', 'Civic Center',
       'East Elmhurst', 'New Springville', 'Morris Heights', 'Arverne',
       'Cambria Heights', 'Tottenville', 'Mariners Harbor', 'Concord',
       'Borough Park', 'Bayside', 'Downtown Brooklyn', 'Port Morris',
       'Fieldston', 'Kew Gardens', 'Midwood', 'College Point',
       'Mount Eden', 'City Island', 'Glendale', 'Port Richmond',
       'Red Hook', 'Richmond Hill', 'Bellerose', 'Maspeth',
       'Williamsbridge', 'Soundview', 'Woodhaven', 'Woodrow',
       'Co-op City', 'Stuyvesant Town', 'Parkchester', 'North Riverdale',
       'Dyker Heights', 'Bronxdale', 'Sea Gate', 'Riverdale',
       'Kew Gardens Hills', 'Bay Terrace', 'Norwood', 'Claremont Village',
       'Whitestone', 'Fordham', 'Bayswater', 'Navy Yard', 'Brownsville',
       'Eltingville', 'Fresh Meadows', 'Mount Hope', 'Lighthouse Hill',
       'Springfield Gardens', 'Howard Beach', 'Belle Harbor',
       'Jamaica Estates', 'Van Nest', 'Morris Park', 'West Brighton',
       'Far Rockaway', 'South Ozone Park', 'Tremont', 'Corona',
       'Great Kills', 'Manhattan Beach', 'Marble Hill', 'Dongan Hills',
       'Castleton Corners', 'East Morrisania', 'Hunts Point', 'Neponsit',
       'Pelham Bay', 'Randall Manor', 'Throgs Neck', 'Todt Hill',
       'West Farms', 'Silver Lake', 'Morrisania', 'Laurelton',
       'Grymes Hill', 'Holliswood', 'Pelham Gardens', 'Belmont',
       'Rosedale', 'Edgemere', 'New Brighton', 'Midland Beach',
       'Baychester', 'Melrose', 'Bergen Beach', 'Richmondtown',
       'Howland Hook', 'Schuylerville', 'Coney Island', 'New Dorp Beach',
       "Prince's Bay", 'South Beach', 'Bath Beach', 'Jamaica Hills',
       'Oakwood', 'Castle Hill', 'Hollis', 'Douglaston', 'Huguenot',
       'Olinville', 'Edenwald', 'Grant City', 'Westerleigh',
       'Bay Terrace, Staten Island', 'Westchester Square', 'Little Neck',
       'Fort Wadsworth', 'Rosebank', 'Unionport', 'Mill Basin',
       'Arden Heights', "Bull's Head", 'New Dorp', 'Rossville',
       'Breezy Point', 'Willowbrook', 'Glen Oaks', 'Gerritsen Beach',
       'Chelsea, Staten Island'], dtype=object)

In [135]:
data[data["neighbourhood"]=="New York"]

Empty DataFrame
Columns: [price, id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, service fee, minimum nights, number of reviews, last review, reviews per month, review rate number, calculated host listings count, availability 365, house_rules, license, new, price_per_review, price_category, name_len, review_year, is_available, price_in_inr, price_per_night, bool, total_est_revenue, first_word, second_column]
Index: []

[0 rows x 38 columns]

In [137]:
#67.  For each city, find the average number of reviews.
data.groupby('neighbourhood')['number of reviews'].mean()

neighbourhood
Allerton           56.618557
Arden Heights      15.555556
Arrochar           25.346154
Arverne            34.098655
Astoria            26.816239
                     ...
Windsor Terrace    35.118541
Woodhaven          38.468750
Woodlawn           50.275862
Woodrow             7.000000
Woodside           21.692967
Name: number of reviews, Length: 224, dtype: float64

In [138]:
#68.  Identify the city with the highest average price.
data.groupby('neighbourhood')["price"].mean().idxmax()

'New Dorp'

In [139]:
#69.  Find the total revenue per host (price × number_of_reviews).
data.groupby('host name')["total_est_revenue"].sum()

host name
#NAME?                       85596.0
'Cil                        198581.0
(Ari) HENRY LEE               7074.0
(Email hidden by Airbnb)     16197.0
(Mary) Haiy                 349680.0
                              ...
단비                               0.0
빈나                            1836.0
소정                             836.0
진                                0.0
현선                               0.0
Name: total_est_revenue, Length: 13190, dtype: Float64

In [144]:
#70.  Group listings by region and show their average price.
data.groupby('new')['price'].mean()

new
 Private 1 bdrm Lefferts Gr, BK apt                    325.0
! ! ! Coliving: live, work, create                      88.0
!! CLASSIC, LUXURY & CHARM !! By Central Park UWS      985.5
!!! Beautiful private room with backyard.              780.0
!!! Outpost Coliving . Shared twin room                864.0
                                                       ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare       1152.0
🧑🏼‍✈️Private Room LGA ✈️                               122.0
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST       666.0
🪴XL dojo 🌾 shared green yogi palace apt 🌿               64.0
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor     583.0
Name: price, Length: 55715, dtype: Float64

In [141]:
data.columns

Index(['price', 'id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'new', 'price_per_review',
       'price_category', 'name_len', 'review_year', 'is_available',
       'price_in_inr', 'price_per_night', 'bool', 'total_est_revenue',
       'first_word', 'second_column'],
      dtype='object')

In [145]:
#71.  Count how many listings exist for each minimum_nights value.
data.groupby('minimum nights')['id'].count()

minimum nights
-1223.0    1
-365.0     1
-200.0     1
-125.0     1
-12.0      1
          ..
 1000.0    2
 1250.0    1
 2645.0    1
 3455.0    1
 5645.0    1
Name: id, Length: 153, dtype: int64

In [146]:
#72.  Group by room_type and get the total number_of_reviews.
data.groupby("room type")["number of reviews"].sum()

room type
HOTEL ROOM            9679.0
PRIVATE ROOM       1291669.0
SHARED ROOM          45368.0
Whole Apartment    1468059.0
Name: number of reviews, dtype: float64

In [149]:
#73.  Find the top 5 hosts with the highest average price.
host_avg=data.groupby('host name')["price"].mean().reset_index()

In [150]:
host_avg

                      host name       price
0                        #NAME?       378.0
1                          'Cil       569.0
2               (Ari) HENRY LEE      1179.0
3      (Email hidden by Airbnb)       343.0
4                   (Mary) Haiy       465.0
...                         ...         ...
13185                        단비       822.0
13186                        빈나       918.0
13187                        소정  665.333333
13188                         진       992.0
13189                        현선       703.0

[13190 rows x 2 columns]

In [151]:
host_avg.sort_values(by="price",ascending=False).head()

      host name   price
9966       Rema  1200.0
5446  Jeff & TJ  1200.0
917     Antonin  1200.0
3563      Esaie  1200.0
4897      Ilean  1200.0

In [153]:
#74.  For each neighbourhood_group, find the listing with maximum price.
data.groupby('neighbourhood group')["price"].max()

neighbourhood group
Bronx            1200
Brooklyn         1200
Manhattan        1200
Queens           1200
Staten Island    1200
brookln           580
manhatan          460
Name: price, dtype: Int64

In [155]:
#75.  Group listings by both city and room_type, and compute average price.
data.groupby(["neighbourhood",'room type'])['price'].mean()

neighbourhood  room type
Allerton       PRIVATE ROOM       709.269231
               Whole Apartment    550.159091
Arden Heights  PRIVATE ROOM            604.0
               Whole Apartment    862.285714
Arrochar       PRIVATE ROOM          594.625
                                     ...
Woodlawn       Whole Apartment         510.8
Woodrow        Whole Apartment    709.333333
Woodside       PRIVATE ROOM       638.981567
               SHARED ROOM             644.5
               Whole Apartment    621.482993
Name: price, Length: 574, dtype: Float64

In [156]:
#76.  Get the standard deviation of price for each room_type.
data.groupby('room type')["price"].std()

room type
HOTEL ROOM         310.866487
PRIVATE ROOM       331.332129
SHARED ROOM        338.701626
Whole Apartment    331.713213
Name: price, dtype: Float64

In [157]:
#77.  Find how many listings were reviewed in each year.
data.groupby('review_year')["number of reviews"].sum()

review_year
2012         66.0
2013        347.0
2014       1310.0
2015       7647.0
2016      23107.0
2017      51597.0
2018     130250.0
2019    1806152.0
2020      81125.0
2021     169716.0
2022     540721.0
2024         21.0
2025         41.0
2026          1.0
2040         41.0
2058        124.0
nan        2509.0
Name: number of reviews, dtype: float64

In [159]:
#78.  Group listings by region and count how many have price &gt; 100.
price=data[data['price']>100]

In [160]:
price.groupby('new')['price'].count()

new
 Private 1 bdrm Lefferts Gr, BK apt                   2
!! CLASSIC, LUXURY & CHARM !! By Central Park UWS     2
!!! Beautiful private room with backyard.             4
!!! Outpost Coliving . Shared twin room               4
!!!Co-Housing taken to the Next Level /Flatbush/2     4
                                                     ..
😸Cirilo's G. Nice Private Room🪴🐈‍⬛                    1
🥰Lovely 1 bedroom/5 minutes walk to timessquare       1
🧑🏼‍✈️Private Room LGA ✈️                              1
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST      1
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor    1
Name: price, Length: 53398, dtype: Int64

In [163]:
#79.  Identify which region has the most total reviews.
data.groupby("new")["number of reviews"].sum().idxmax()

'N'

In [164]:
#80.  For each host_id, calculate the total availability days.
data.groupby('host id')['availability 365'].sum()

host id
123600518        0.0
124039648        0.0
124472619        0.0
129756565      348.0
130349612      205.0
               ...
98758136270    117.0
98760968631      0.0
98762661810     71.0
98762683230     17.0
98763129024      0.0
Name: availability 365, Length: 102057, dtype: float64

In [165]:
#81.  Split the dataset into two DataFrames: one with price, one with reviews, then merge them back on id.
d1=data[['id','price']]
d2=data[['id','number of reviews']]

In [166]:
merge_d=pd.merge(d1,d2,left_on='id',right_on='id',how='inner')

In [167]:
merge_d

             id  price  number of reviews
0       1001254    966                9.0
1       1002102    142               45.0
2       1002403    620                0.0
3       1002755    368              270.0
4       1003689    204                9.0
...         ...    ...                ...
103676  6093542    988                0.0
103677  6094094    546                5.0
103678  6094094    546                5.0
103679  6094647   1032                0.0
103680  6094647   1032                0.0

[103681 rows x 3 columns]

In [169]:
#82.  Create a pivot table showing average price by city and room_type.
data.pivot_table(index="neighbourhood",values="price",columns="room type",aggfunc=np.mean)

C:\Users\rames\AppData\Local\Temp\ipykernel_1208\3889929656.py:2: FutureWarning: The provided callable <function mean at 0x000001FE21953A60> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  data.pivot_table(index="neighbourhood",values="price",columns="room type",aggfunc=np.mean)

room type        HOTEL ROOM  PRIVATE ROOM  SHARED ROOM  Whole Apartment
neighbourhood
Allerton               <NA>    709.269231         <NA>       550.159091
Arden Heights          <NA>         604.0         <NA>       862.285714
Arrochar               <NA>       594.625         <NA>       653.444444
Arverne                <NA>    653.959459       988.25       641.917241
Astoria                <NA>    656.797932   652.130435       613.408673
...                     ...           ...          ...              ...
Windsor Terrace        <NA>    498.010417         <NA>       613.333333
Woodhaven              <NA>     647.59542        625.0       590.345455
Woodlawn               <NA>    618.529412        702.0            510.8
Woodrow                <NA>          <NA>         <NA>       709.333333
Woodside               <NA>    638.981567        644.5       621.482993

[224 rows x 4 columns]

In [170]:
#83.  Unstack a groupby result of room_type vs neighbourhood_group.
data.pivot_table(index="neighbourhood group",columns="room type",aggfunc='size',fill_value=0)

room type            HOTEL ROOM  PRIVATE ROOM  SHARED ROOM  Whole Apartment
neighbourhood group
Bronx                         0          1573          117             1022
Brooklyn                      8         20434          825            20575
Manhattan                   100         16312          907            26473
Queens                        8          7751          362             5146
Staten Island                 0           466           15              474
brookln                       0             1            0                0
manhatan                      0             1            0                0

In [174]:
#84.  Melt columns related to reviews into a long format.
data.melt(id_vars=['id'],value_vars=['number of reviews','last review','reviews per month','review rate number','price_per_review','review_year'],var_name="review_number",value_name="review_content")

             id      review_number review_content
0       1001254  number of reviews            9.0
1       1002102  number of reviews           45.0
2       1002403  number of reviews            0.0
3       1002755  number of reviews          270.0
4       1003689  number of reviews            9.0
...         ...                ...            ...
615589  6092437        review_year            nan
615590  6092990        review_year           2015
615591  6093542        review_year            nan
615592  6094094        review_year           2015
615593  6094647        review_year            nan

[615594 rows x 3 columns]

In [171]:
data

,price,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,price_category,name_len,review_year,is_available,price_in_inr,price_per_night,bool,total_est_revenue,first_word,second_column
0,966,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,...,High,34,2021,True,80178.0,96.6,False,8694.0,Clean,& quiet apt home by the park
1,142,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,...,Low,21,2022,True,11786.0,4.733333,False,6390.0,Skylit,Midtown Castle
2,620,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,...,Low,35,nan,True,51460.0,206.666667,False,0.0,THE,VILLAGE OF HARLEM....NEW YORK !
3,368,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,...,Low,3,2019,True,30544.0,12.266667,False,99360.0,NaN,NaN
4,204,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,...,Low,48,2018,True,16932.0,20.4,False,1836.0,Entire,Apt: Spacious Studio/Loft by central park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,844,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,...,High,26,nan,True,70052.0,844.0,False,0.0,Spare,room in Williamsburg
102595,837,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,...,High,29,2015,True,69471.0,837.0,False,837.0,Best,Location near Columbia U
102596,988,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,...,High,30,nan,True,82004.0,329.333333,False,0.0,"Comfy,",bright room in Brooklyn
102597,546,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,...,Low,32,2015,True,45318.0,273.0,False,2730.0,Big,Studio-One Stop from Midtown
102598,1032,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,...,High,20,nan,True,85656.0,1032.0,True,0.0,585,sf Luxury Studio

In [172]:
data.columns

Index(['price', 'id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license', 'new', 'price_per_review',
       'price_category', 'name_len', 'review_year', 'is_available',
       'price_in_inr', 'price_per_night', 'bool', 'total_est_revenue',
       'first_word', 'second_column'],
      dtype='object')

In [178]:
#85.  Concatenate two subsets of listings (top 10 expensive + top 10 cheapest).
price_g=data.sort_values(by="price",ascending=False)

In [181]:
g1=price_g.head(10)

In [182]:
g2=price_g.tail(10)

In [184]:
pd.concat([g1,g2])

,price,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,...,price_category,name_len,review_year,is_available,price_in_inr,price_per_night,bool,total_est_revenue,first_word,second_column
20343,1200,12236775,Lovely apartment in Williamsburg,11151122860,verified,Harry,Brooklyn,Greenpoint,40.72253,-73.94350,...,High,32,2018,True,99600.0,171.428571,False,7200.0,Lovely,apartment in Williamsburg
64304,1200,36516435,Great 1BD waterfront City Island NY,83460973881,verified,Alex,Bronx,City Island,40.85343,-73.78811,...,High,35,2021,True,99600.0,40.0,False,129600.0,Great,1BD waterfront City Island NY
67200,1200,38115896,Bright Brooklyn Brownstone,66173822303,unconfirmed,Andrew,Brooklyn,Park Slope,40.67275,-73.97541,...,High,26,2020,True,99600.0,400.0,False,10800.0,Bright,Brooklyn Brownstone
33902,1200,19725411,Oasis II,59005379313,verified,Angie,Brooklyn,Bedford-Stuyvesant,40.68978,-73.95131,...,High,8,2019,True,99600.0,40.0,False,25200.0,Oasis,II
7453,1200,5117628,Sun-filled bedroom in East Village / Gramercy NYC,45143137929,unconfirmed,Jeff & TJ,Manhattan,Gramercy,40.73170,-73.98272,...,High,49,2019,True,99600.0,600.0,False,163200.0,Sun-filled,bedroom in East Village / Gramercy NYC
90165,1200,50799466,Lovely apartment in Williamsburg,90965581979,unconfirmed,Harry,Brooklyn,Greenpoint,40.72253,-73.94350,...,High,32,2018,True,99600.0,171.428571,False,7200.0,Lovely,apartment in Williamsburg
52744,1200,30131847,❤️Couples Retreat/A Road Warriors Dream🌟Perf Loc.,9456551231,verified,B,Manhattan,Hell's Kitchen,40.76349,-73.98949,...,High,49,2022,True,99600.0,1200.0,False,169200.0,❤️Couples,Retreat/A Road Warriors Dream🌟Perf Loc.
19773,1200,11921964,1.5 BATHRM SUNNY SPACIOUS ROOM BY SUBWAY,51256717787,verified,Golden&Mavy,Manhattan,Harlem,40.82284,-73.95546,...,High,40,2019,True,99600.0,40.0,False,4800.0,1.5,BATHRM SUNNY SPACIOUS ROOM BY SUBWAY
5207,1200,3877162,Bushwick Room w/ Private Entrance & Bathroom!,45360462434,unconfirmed,Julie,Brooklyn,Bushwick,40.70322,-73.92913,...,High,45,2019,True,99600.0,1200.0,False,19200.0,Bushwick,Room w/ Private Entrance & Bathroom!
42446,1200,24444262,"Cozy room in bright, spacious apartment",84040511136,verified,Steven,Bronx,Hunts Point,40.81731,-73.89052,...,High,39,nan,True,99600.0,-0.981194,False,0.0,Cozy,"room in bright, spacious apartment"
97775,<NA>,55002469,"Studio at Upper East Side Manhattan, New York",59846872035,unconfirmed,Тest,Manhattan,Upper East Side,40.77713,-73.95309,...,Medium,45,2018,False,NaN,<NA>,False,<NA>,Studio,"at Upper East Side Manhattan, New York"
97776,<NA>,55003021,Spacious Harlem Room,11251026866,verified,Silvia,Manhattan,Harlem,40.82923,-73.93764,...,Medium,20,2019,True,NaN,<NA>,False,<NA>,Spacious,Harlem Room
97777,<NA>,55003573,Flatiron Penthouse,77242696688,unconfirmed,Ben,Manhattan,Gramercy,40.73801,-73.98815,...,Medium,18,2018,False,NaN,<NA>,False,<NA>,Flatiron,Penthouse
97778,<NA>,55004125,New York Condominium,64973756767,unconfirmed,Ken,Manhattan,SoHo,40.72060,-74.00330,...,Medium,20,2018,True,NaN,<NA>,False,<NA>,New,York Condominium
102045,<NA>,57360790,Private Bedroom in Rego Park / Forest Hills,15978912806,unconfirmed,NaN,Queens,Rego Park,40.72460,-73.85688,...,Medium,43,nan,False,NaN,<NA>,False,<NA>,Private,Bedroom in Rego Park / Forest Hills
102046,<NA>,57361342,Sunny budget friendly room in Bushwick,29964876857,verified,NaN,Brooklyn,Bushwick,40.69370,-73.91006,...,Medium,38,2018,False,NaN,<NA>,False,<NA>,Sunny,budget friendly room in Bushwick
102047,<NA>,57361894,"Cozy Apartment on Bedford Ave, Brooklyn",92852058426,unconfirmed,NaN,Brooklyn,Williamsburg,40.71284,-73.96284,...,Medium,39,2018,False,NaN,<NA>,False,<NA>,Cozy,"Apartment on Bedford Ave, Brooklyn"
102048,<NA>,57362446,Your 1 bedroom home away from home!,95572379802,verified,NaN,Manhattan,Upper West Side,40.79563,-73.97634,...,Medium,35,2019,True,NaN,<NA>,False,<NA>,Your,1 bedroom home away from home!
102049,<NA>,57362999,MASTER Cozy Bedroom Queen size 2 blocks Timesq...,80154173698,verified,NaN,Manhattan,Hell's Kitchen,40.76125,-73.98945,...,Medium,50,2019,False,NaN,<NA>,False,<NA>,MASTER,Cozy Bedroom Queen size 2 blocks Timesquare
102050,<NA>,57363551,Sunny Brownstone Studio in BedStuy Brooklyn,11145329848,unconfirmed,Jamal,Brooklyn,Bedford-Stuyvesant,40.68221,-73.94618,...,Medium,43,2019,True,NaN,<NA>,False,<NA>,Sunny,Brownstone Studio in BedStuy Brooklyn

In [185]:
#86.  Merge two DataFrames: one with host info, one with listing info (based on host_id).
d1=data[['host id','host name','host_identity_verified']]
d2=data[['host id','room type','country']]

In [186]:
pd.merge(d1,d2,left_on="host id",right_on='host id',how='inner')

,host id,host name,host_identity_verified,room type,country
0,80014485718,Madaline,unconfirmed,PRIVATE ROOM,United States
1,52335172823,Jenna,verified,Whole Apartment,United States
2,78829239556,Elise,NaN,PRIVATE ROOM,United States
3,85098326012,Garry,unconfirmed,Whole Apartment,United States
4,92037596077,Lyndon,verified,Whole Apartment,United States
...,...,...,...,...,...
103678,69050334417,Megan,unconfirmed,PRIVATE ROOM,United States
103679,11160591270,Christopher,unconfirmed,Whole Apartment,United States
103680,11160591270,Christopher,unconfirmed,Whole Apartment,United States
103681,68170633372,Rebecca,unconfirmed,Whole Apartment,United States
103682,68170633372,Rebecca,unconfirmed,Whole Apartment,United States

In [188]:
#87.  Create a MultiIndex DataFrame grouped by city and region.
index=data.set_index(['new','neighbourhood'])

In [189]:
index.sort_index()

                                                                              price  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens    325
                                                   Prospect-Lefferts Gardens    325
! ! ! Coliving: live, work, create                 East Flatbush                 88
                                                   East Flatbush                 88
                                                   East Flatbush                 88
...                                                                             ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side             1152
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                122
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                     666
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                  64
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant           583

                                                                                    id  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens   2221367
                                                   Prospect-Lefferts Gardens  39874972
! ! ! Coliving: live, work, create                 East Flatbush              12715619
                                                   East Flatbush              44287296
                                                   East Flatbush              51278310
...                                                                                ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side            30586390
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst              37217304
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                   37907679
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village               34539201
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant         29350343

                                                                                                                           NAME  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens                 Private 1 bdrm Lefferts Gr, BK apt
                                                   Prospect-Lefferts Gardens                 Private 1 bdrm Lefferts Gr, BK apt
! ! ! Coliving: live, work, create                 East Flatbush                             ! ! ! Coliving: live, work, create
                                                   East Flatbush                             ! ! ! Coliving: live, work, create
                                                   East Flatbush                             ! ! ! Coliving: live, work, create
...                                                                                                                         ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side              🥰Lovely 1 bedroom/5 minutes walk to timessquare
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                                       🧑🏼‍✈️Private Room LGA ✈️
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                    🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                       🪴XL dojo 🌾 shared green yogi palace apt 🌿
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant         🪴🛋🌞 Unique sunny clean brownstone studio 1st f...

                                                                                  host id  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens   7920546536
                                                   Prospect-Lefferts Gardens  80470112741
! ! ! Coliving: live, work, create                 East Flatbush              14328744539
                                                   East Flatbush              11894009433
                                                   East Flatbush              72952532583
...                                                                                   ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side            72313716360
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst              29442678011
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                   51214814188
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village               42245663617
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant         56502061113

                                                                             host_identity_verified  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens            unconfirmed
                                                   Prospect-Lefferts Gardens               verified
! ! ! Coliving: live, work, create                 East Flatbush                           verified
                                                   East Flatbush                           verified
                                                   East Flatbush                        unconfirmed
...                                                                                             ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side                      unconfirmed
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                           verified
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                             unconfirmed
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                            verified
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant                   unconfirmed

                                                                               host name  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens     Rachael
                                                   Prospect-Lefferts Gardens     Rachael
! ! ! Coliving: live, work, create                 East Flatbush                Valentin
                                                   East Flatbush                Valentin
                                                   East Flatbush                Valentin
...                                                                                  ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side               Madison
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst              Joe Jobana
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                         Alan
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                   Haffro
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant              Hardy

                                                                             neighbourhood group  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens            Brooklyn
                                                   Prospect-Lefferts Gardens            Brooklyn
! ! ! Coliving: live, work, create                 East Flatbush                        Brooklyn
                                                   East Flatbush                        Brooklyn
                                                   East Flatbush                        Brooklyn
...                                                                                          ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side                     Manhattan
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                          Queens
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                               Queens
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                        Manhattan
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant                   Brooklyn

                                                                                    lat  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens  40.657430
                                                   Prospect-Lefferts Gardens  40.657430
! ! ! Coliving: live, work, create                 East Flatbush              40.651510
                                                   East Flatbush              40.651510
                                                   East Flatbush              40.651510
...                                                                                 ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side            40.761766
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst              40.768580
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                   40.760910
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village               40.721470
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant         40.689260

                                                                                   long  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens -73.961550
                                                   Prospect-Lefferts Gardens -73.961550
! ! ! Coliving: live, work, create                 East Flatbush             -73.949570
                                                   East Flatbush             -73.949570
                                                   East Flatbush             -73.949570
...                                                                                 ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           -73.962442
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             -73.877890
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  -73.822710
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              -73.982700
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        -73.931070

                                                                                    country  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens  United States
                                                   Prospect-Lefferts Gardens  United States
! ! ! Coliving: live, work, create                 East Flatbush              United States
                                                   East Flatbush              United States
                                                   East Flatbush              United States
...                                                                                     ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side            United States
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst              United States
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                   United States
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village               United States
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant         United States

                                                                              ...  \
new                                                neighbourhood              ...
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens  ...
                                                   Prospect-Lefferts Gardens  ...
! ! ! Coliving: live, work, create                 East Flatbush              ...
                                                   East Flatbush              ...
                                                   East Flatbush              ...
...                                                                           ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side            ...
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst              ...
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                   ...
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village               ...
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant         ...

                                                                             price_category  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens            Low
                                                   Prospect-Lefferts Gardens            Low
! ! ! Coliving: live, work, create                 East Flatbush                        Low
                                                   East Flatbush                        Low
                                                   East Flatbush                        Low
...                                                                                     ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side                     High
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                        Low
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                            High
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                         Low
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant                   Low

                                                                             name_len  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens       35
                                                   Prospect-Lefferts Gardens       35
! ! ! Coliving: live, work, create                 East Flatbush                   34
                                                   East Flatbush                   34
                                                   East Flatbush                   34
...                                                                               ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side                 47
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                   24
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                        48
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                    41
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant              50

                                                                             review_year  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens        2019
                                                   Prospect-Lefferts Gardens        2019
! ! ! Coliving: live, work, create                 East Flatbush                     nan
                                                   East Flatbush                     nan
                                                   East Flatbush                     nan
...                                                                                  ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side                  2022
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                    2021
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                         2020
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                     2021
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant               2022

                                                                             is_available  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens         True
                                                   Prospect-Lefferts Gardens         True
! ! ! Coliving: live, work, create                 East Flatbush                     True
                                                   East Flatbush                     True
                                                   East Flatbush                     True
...                                                                                   ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side                   True
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                     True
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                          True
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                      True
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant                True

                                                                              price_in_inr  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens       26975.0
                                                   Prospect-Lefferts Gardens       26975.0
! ! ! Coliving: live, work, create                 East Flatbush                    7304.0
                                                   East Flatbush                    7304.0
                                                   East Flatbush                    7304.0
...                                                                                    ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side                 95616.0
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                   10126.0
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                        55278.0
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                     5312.0
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant              48389.0

                                                                             price_per_night  \
new                                                neighbourhood
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens           162.5
                                                   Prospect-Lefferts Gardens           162.5
! ! ! Coliving: live, work, create                 East Flatbush                    2.933333
                                                   East Flatbush                    2.933333
                                                   East Flatbush                    2.933333
...                                                                                      ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side                    1152.0
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst                       122.0
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                             22.2
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village                         64.0
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant             194.333333


In [190]:
#88.  Sort index after grouping by multiple columns.
index1=data.set_index(['new','neighbourhood','host name'])
index1.sort_index()

                                                                                         price  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael       325
                                                                             Rachael       325
! ! ! Coliving: live, work, create                 East Flatbush             Valentin       88
                                                                             Valentin       88
                                                                             Valentin       88
...                                                                                        ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison      1152
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana    122
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan          666
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro         64
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy         583

                                                                                               id  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael      2221367
                                                                             Rachael     39874972
! ! ! Coliving: live, work, create                 East Flatbush             Valentin    12715619
                                                                             Valentin    44287296
                                                                             Valentin    51278310
...                                                                                           ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison     30586390
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana  37217304
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan        37907679
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro      34539201
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy       29350343

                                                                                                                                      NAME  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael                    Private 1 bdrm Lefferts Gr, BK apt
                                                                             Rachael                    Private 1 bdrm Lefferts Gr, BK apt
! ! ! Coliving: live, work, create                 East Flatbush             Valentin                   ! ! ! Coliving: live, work, create
                                                                             Valentin                   ! ! ! Coliving: live, work, create
                                                                             Valentin                   ! ! ! Coliving: live, work, create
...                                                                                                                                    ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison       🥰Lovely 1 bedroom/5 minutes walk to timessquare
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana                           🧑🏼‍✈️Private Room LGA ✈️
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan         🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro              🪴XL dojo 🌾 shared green yogi palace apt 🌿
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy       🪴🛋🌞 Unique sunny clean brownstone studio 1st f...

                                                                                             host id  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael      7920546536
                                                                             Rachael     80470112741
! ! ! Coliving: live, work, create                 East Flatbush             Valentin    14328744539
                                                                             Valentin    11894009433
                                                                             Valentin    72952532583
...                                                                                              ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison     72313716360
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana  29442678011
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan        51214814188
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro      42245663617
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy       56502061113

                                                                                        host_identity_verified  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael               unconfirmed
                                                                             Rachael                  verified
! ! ! Coliving: live, work, create                 East Flatbush             Valentin                 verified
                                                                             Valentin                 verified
                                                                             Valentin              unconfirmed
...                                                                                                        ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison               unconfirmed
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana               verified
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan                  unconfirmed
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro                   verified
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy                 unconfirmed

                                                                                        neighbourhood group  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael               Brooklyn
                                                                             Rachael               Brooklyn
! ! ! Coliving: live, work, create                 East Flatbush             Valentin              Brooklyn
                                                                             Valentin              Brooklyn
                                                                             Valentin              Brooklyn
...                                                                                                     ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison              Manhattan
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana              Queens
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan                    Queens
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro               Manhattan
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy                 Brooklyn

                                                                                               lat  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael     40.657430
                                                                             Rachael     40.657430
! ! ! Coliving: live, work, create                 East Flatbush             Valentin    40.651510
                                                                             Valentin    40.651510
                                                                             Valentin    40.651510
...                                                                                            ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison     40.761766
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana  40.768580
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan        40.760910
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro      40.721470
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy       40.689260

                                                                                              long  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael    -73.961550
                                                                             Rachael    -73.961550
! ! ! Coliving: live, work, create                 East Flatbush             Valentin   -73.949570
                                                                             Valentin   -73.949570
                                                                             Valentin   -73.949570
...                                                                                            ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison    -73.962442
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana -73.877890
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan       -73.822710
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro     -73.982700
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy      -73.931070

                                                                                               country  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael     United States
                                                                             Rachael     United States
! ! ! Coliving: live, work, create                 East Flatbush             Valentin    United States
                                                                             Valentin    United States
                                                                             Valentin    United States
...                                                                                                ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison     United States
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana  United States
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan        United States
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro      United States
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy       United States

                                                                                        country code  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael              US
                                                                             Rachael              US
! ! ! Coliving: live, work, create                 East Flatbush             Valentin             US
                                                                             Valentin             US
                                                                             Valentin             US
...                                                                                              ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison              US
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana           US
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan                 US
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro               US
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy                US

                                                                                         ...  \
new                                                neighbourhood             host name   ...
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael     ...
                                                                             Rachael     ...
! ! ! Coliving: live, work, create                 East Flatbush             Valentin    ...
                                                                             Valentin    ...
                                                                             Valentin    ...
...                                                                                      ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison     ...
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana  ...
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan        ...
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro      ...
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy       ...

                                                                                        price_category  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael               Low
                                                                             Rachael               Low
! ! ! Coliving: live, work, create                 East Flatbush             Valentin              Low
                                                                             Valentin              Low
                                                                             Valentin              Low
...                                                                                                ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison              High
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana            Low
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan                 High
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro                Low
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy                 Low

                                                                                        name_len  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael          35
                                                                             Rachael          35
! ! ! Coliving: live, work, create                 East Flatbush             Valentin         34
                                                                             Valentin         34
                                                                             Valentin         34
...                                                                                          ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison          47
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana       24
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan             48
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro           41
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy            50

                                                                                        review_year  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael           2019
                                                                             Rachael           2019
! ! ! Coliving: live, work, create                 East Flatbush             Valentin           nan
                                                                             Valentin           nan
                                                                             Valentin           nan
...                                                                                             ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison           2022
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana        2021
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan              2020
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro            2021
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy             2022

                                                                                         is_available  \
new                                                neighbourhood             host name
 Private 1 bdrm Lefferts Gr, BK apt                Prospect-Lefferts Gardens Rachael             True
                                                                             Rachael             True
! ! ! Coliving: live, work, create                 East Flatbush             Valentin            True
                                                                             Valentin            True
                                                                             Valentin            True
...                                                                                               ...
🥰Lovely 1 bedroom/5 minutes walk to timessquare    Upper East Side           Madison             True
🧑🏼‍✈️Private Room LGA ✈️                           East Elmhurst             Joe Jobana          True
🪁LARGE PRIVATE TERRACE 🚶‍♂️8 MIN WALK TO MAIN ST   Flushing                  Alan                True
🪴XL dojo 🌾 shared green yogi palace apt 🌿          East Village              Haffro              True
🪴🛋🌞 Unique sunny clean brownstone studio 1st floor Bedford-Stuyvesant        Hardy               True


In [191]:
#89.  Pivot table showing count of listings per room_type across cities.
data.pivot_table(index="neighbourhood",columns="room type",values='id',aggfunc='count',fill_value=0)

room type        HOTEL ROOM  PRIVATE ROOM  SHARED ROOM  Whole Apartment
neighbourhood
Allerton                  0            53            0               44
Arden Heights             0             2            0                7
Arrochar                  0            24            0               28
Arverne                   0            74            4              145
Astoria                   0          1067           46              763
...                     ...           ...          ...              ...
Windsor Terrace           0            96            0              235
Woodhaven                 0           132            5               55
Woodlawn                  0            17            2               10
Woodrow                   0             0            0                3
Woodside                  0           438            2              148

[224 rows x 4 columns]

In [194]:
#90.  Reshape the dataset so each host has one row with average metrics per city.
data.groupby(['host name','neighbourhood'])['price'].mean()

host name                 neighbourhood
#NAME?                    Queens Village              378.0
'Cil                      Astoria                     569.0
(Ari) HENRY LEE           East Harlem                1179.0
(Email hidden by Airbnb)  Clinton Hill                168.0
                          Midtown                492.333333
                                                    ...
빈나                        Stuyvesant Town             918.0
소정                        Bedford-Stuyvesant          418.0
                          Hell's Kitchen             1160.0
진                         Upper West Side             992.0
현선                        Morningside Heights         703.0
Name: price, Length: 34412, dtype: Float64