In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('House_data.csv')

In [3]:
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [4]:
data.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [5]:
#1. Display all rows where the price is greater than 1 crore.
data[data["price"]>1]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [6]:
#2. Retrieve all properties located in the area “Whitefield”.
data[data["location"]=='Whitefield']

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
10,Super built-up Area,18-Feb,Whitefield,3 BHK,NaN,1800,2.0,2.0,70.00
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00
27,Built-up Area,20-Dec,Whitefield,3 BHK,NaN,1610,3.0,2.0,81.00
47,Super built-up Area,20-Sep,Whitefield,2 BHK,Goted U,1459,2.0,1.0,94.82
...,...,...,...,...,...,...,...,...,...
13235,Super built-up Area,Ready To Move,Whitefield,3 BHK,SJces R,1730,3.0,2.0,125.00
13257,Super built-up Area,Ready To Move,Whitefield,3 BHK,SLiritn,1453,2.0,2.0,58.00
13258,Super built-up Area,19-Dec,Whitefield,1 BHK,Oreldhi,877,1.0,1.0,59.00
13299,Super built-up Area,18-Dec,Whitefield,4 BHK,Prtates,2830 - 2882,5.0,0.0,154.50
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00

In [7]:
#3.Show houses that have more than 3 bedrooms.
bed=data["size"].str.split(" ",n=1,expand=True)

In [8]:
data['bedroom']=bed[0]

In [9]:
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
 9   bedroom       13304 non-null  object
dtypes: float64(3), object(7)
memory usage: 1.0+ MB

In [11]:
data['bedroom']=data['bedroom'].astype('Int64')

In [12]:
data[data['bedroom']>3]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.0,4
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.0,4
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.0,4
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.0,6
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.0,4
...,...,...,...,...,...,...,...,...,...,...
13306,Plot Area,Ready To Move,Rajarajeshwari Nagara,4 Bedroom,NaN,1200,5.0,NaN,325.0,4
13311,Plot Area,Ready To Move,Ramamurthy Nagar,7 Bedroom,NaN,1500,9.0,2.0,250.0,7
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0,5
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0,4
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0,4

In [13]:
#4. Select rows where bath is greater than balcony.
data[data['bath']>data['balcony']]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2
...,...,...,...,...,...,...,...,...,...,...
13311,Plot Area,Ready To Move,Ramamurthy Nagar,7 Bedroom,NaN,1500,9.0,2.0,250.00,7
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00,3
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4

In [14]:
#5.Display all houses with total square feet greater than 2000.

In [15]:
data["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [16]:
sp=data["total_sqft"].str.split("-",n=1,expand=True)

In [17]:
sp

          0     1
0      1056  None
1      2600  None
2      1440  None
3      1521  None
4      1200  None
...     ...   ...
13315  3453  None
13316  3600  None
13317  1141  None
13318  4689  None
13319   550  None

[13320 rows x 2 columns]

In [18]:
sp[0].unique()

array(['1056', '2600', '1440', ..., '1133 ', '774', '4689'], dtype=object)

In [19]:
import re
def change_dt(x):
    #y=x.str()
    p="\d+"
    a=re.findall(p,x)
    return a[0]

In [20]:
sp[0]=sp[0].apply(change_dt)

In [21]:
sp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       13320 non-null  object
 1   1       201 non-null    object
dtypes: object(2)
memory usage: 208.3+ KB

In [22]:
sp[0].astype('float')

0        1056.0
1        2600.0
2        1440.0
3        1521.0
4        1200.0
          ...
13315    3453.0
13316    3600.0
13317    1141.0
13318    4689.0
13319     550.0
Name: 0, Length: 13320, dtype: float64

In [23]:
data['total_sq']=sp[0]

In [24]:
data['total_sq']=data['total_sq'].astype('float')

In [25]:
data[data['total_sq']>2000]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.0,4,2600.0
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.0,4,2732.0
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.0,4,3300.0
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.0,4,2785.0
14,Plot Area,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250,3.0,2.0,148.0,3,2250.0
...,...,...,...,...,...,...,...,...,...,...,...
13294,Super built-up Area,Ready To Move,Sultan Palaya,4 BHK,RSntsAp,2200,3.0,3.0,80.0,4,2200.0
13299,Super built-up Area,18-Dec,Whitefield,4 BHK,Prtates,2830 - 2882,5.0,0.0,154.5,4,2830.0
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0,5,3453.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0,4,3600.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0,4,4689.0

In [26]:
#6.Get all properties with more than 2 bathrooms and located in “Electronic City”.
data[(data["location"]=='Electronic City') & (data["bath"]>2)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq
245,Plot Area,Ready To Move,Electronic City,3 Bedroom,NaN,1200,3.0,1.0,90.00,3,1200.0
378,Super built-up Area,Ready To Move,Electronic City,3 BHK,ShstaAl,1800,3.0,2.0,95.00,3,1800.0
522,Super built-up Area,18-Apr,Electronic City,3 BHK,Prarkun,1599,3.0,2.0,125.00,3,1599.0
543,Super built-up Area,18-Apr,Electronic City,3 BHK,Prarkun,1599,3.0,2.0,99.00,3,1599.0
1191,Built-up Area,Ready To Move,Electronic City,3 BHK,Suashen,1620,3.0,2.0,62.00,3,1620.0
1325,Plot Area,Ready To Move,Electronic City,4 Bedroom,NaN,2000,4.0,0.0,120.00,4,2000.0
2089,Super built-up Area,18-Jan,Electronic City,3 BHK,Prarkun,1571,3.0,2.0,89.00,3,1571.0
2111,Super built-up Area,18-Dec,Electronic City,3 BHK,NaN,1111,3.0,1.0,50.00,3,1111.0
3020,Plot Area,18-Dec,Electronic City,4 Bedroom,Janaala,4000,5.0,1.0,150.00,4,4000.0
3131,Super built-up Area,21-Dec,Electronic City,3 BHK,KonteiT,1563,3.0,2.0,91.84,3,1563.0
3149,Super built-up Area,Ready To Move,Electronic City,3 BHK,Briumri,1652,3.0,2.0,70.00,3,1652.0
3303,Super built-up Area,Ready To Move,Electronic City,3 BHK,Palleon,1350,3.0,2.0,58.00,3,1350.0
3535,Super built-up Area,Ready To Move,Electronic City,3 BHK,Naireru,1700,3.0,2.0,75.00,3,1700.0
3760,Super built-up Area,Ready To Move,Electronic City,3 BHK,Prarkun,1571,3.0,2.0,105.00,3,1571.0
3839,Built-up Area,18-Jan,Electronic City,3 BHK,Prarkun,1600,3.0,2.0,104.00,3,1600.0
4337,Super built-up Area,18-Dec,Electronic City,3 BHK,S2oveat,1225,3.0,0.0,45.03,3,1225.0
4869,Super built-up Area,Ready To Move,Electronic City,3 BHK,Goty E,1575,3.0,2.0,90.00,3,1575.0
4893,Built-up Area,Ready To Move,Electronic City,3 BHK,Goty E,1449,3.0,2.0,100.00,3,1449.0
5043,Super built-up Area,Ready To Move,Electronic City,3 BHK,Goty E,1575,3.0,3.0,101.00,3,1575.0
5690,Built-up Area,18-Apr,Electronic City,3 BHK,NaN,1650,3.0,2.0,100.00,3,1650.0
5755,Super built-up Area,Ready To Move,Electronic City,3 BHK,Goty E,1449,3.0,2.0,90.00,3,1449.0
6013,Super built-up Area,20-Dec,Electronic City,4 BHK,KonteiT,2435,4.0,3.0,119.00,4,2435.0
6909,Super built-up Area,20-Dec,Electronic City,4 BHK,KonteiT,2093,4.0,1.0,104.00,4,2093.0
6989,Super built-up Area,Ready To Move,Electronic City,3 BHK,Goty E,1631,3.0,2.0,80.00,3,1631.0
8264,Super built-up Area,17-Oct,Electronic City,3 BHK,Prarkun,1571,3.0,2.0,83.00,3,1571.0
8300,Super built-up Area,Ready To Move,Electronic City,3 BHK,Palleon,1350,3.0,2.0,66.00,3,1350.0
8337,Super built-up Area,Ready To Move,Electronic City,3 BHK,SJityVe,1652,3.0,3.0,110.00,3,1652.0
9007,Super built-up Area,Ready To Move,Electronic City,3 BHK,SJityVe,1609,3.0,3.0,115.00,3,1609.0
9686,Plot Area,Ready To Move,Electronic City,5 Bedroom,NaN,717,5.0,1.0,78.00,5,717.0
9959,Plot Area,Ready To Move,Electronic City,4 Bedroom,Aroveth,1800,3.0,2.0,190.00,4,1800.0
10476,Built-up Area,Ready To Move,Electronic City,3 Bedroom,NaN,1400,3.0,1.0,90.00,3,1400.0
10513,Built-up Area,Ready To Move,Electronic City,3 BHK,DSgmax,1287,3.0,1.0,55.00,3,1287.0
10570,Plot Area,Ready To Move,Electronic City,4 Bedroom,Aroveth,1800,3.0,2.0,700.00,4,1800.0
10695,Plot Area,18-Feb,Electronic City,9 Bedroom,NaN,1200,13.0,NaN,150.00,9,1200.0
10747,Built-up Area,Ready To Move,Electronic City,3 BHK,Emodsel,1275,3.0,1.0,70.00,3,1275.0
10812,Super built-up Area,17-Jun,Electronic City,3 BHK,Prarkun,1644,3.0,2.0,92.59,3,1644.0
11248,Super built-up Area,Ready To Move,Electronic City,3 BHK,Pao 3ow,1275,3.0,3.0,63.43,3,1275.0
11289,Super built-up Area,Ready To Move,Electronic City,3 BHK,Briumri,1518,3.0,3.0,75.00,3,1518.0
11604,Built-up Area,Ready To Move,Electronic City,3 BHK,BrnoxEq,1700,3.0,2.0,90.00,3,1700.0
12056,Plot Area,Ready To Move,Electronic City,4 Bedroom,NaN,1200,4.0,1.0,125.00,4,1200.0
12083,Super built-up Area,18-Jul,Electronic City,3 BHK,Prarkun,1615,3.0,2.0,97.00,3,1615.0
12338,Plot Area,Ready To Move,Electronic City,3 Bedroom,EmrchAn,1200,3.0,2.0,150.00,3,1200.0
12399,Built-up Area,Ready To Move,Electronic City,3 Bedroom,NaN,1500,3.0,1.0,73.00,3,1500.0
12766,Super built-up Area,Ready To Move,Electronic City,3 BHK,Goty E,1575,3.0,1.0,94.50,3,1575.0
13129,Super built-up Area,21-Dec,Electronic City,4 BHK,KonteiT,2093,4.0,2.0,134.00,4,2093.0
13269,Plot Area,Ready To Move,Electronic City,3 Bedroom,SJovest,2010,3.0,2.0,201.00,3,2010.0

In [27]:
#6.Retrieve all listings whose location contains “Indiranagar”.
data["location"].str.contains("Indiranagar",case=True,na=False)

0        False
1        False
2        False
3        False
4        False
         ...
13315    False
13316    False
13317    False
13318    False
13319    False
Name: location, Length: 13320, dtype: bool

In [28]:
#7.Filter properties where price_per_sqft is between 4000 and 7000.
data["price_per_sqft"]=(data["price"]*10000000)/data["total_sq"]

In [29]:
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,1056.0,3.699811e+05
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,2600.0,4.615385e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,1440.0,4.305556e+05
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,1521.0,6.245891e+05
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,1200.0,4.250000e+05
...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,3453.0,6.689835e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,3600.0,1.111111e+06
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,1141.0,5.258545e+05
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,4689.0,1.040734e+06
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,550.0,3.090909e+05

In [30]:
data[(data["price_per_sqft"]>4000) & (data["price_per_sqft"]<7000)]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price, bedroom, total_sq, price_per_sqft]
Index: []

In [31]:
#8.Show all rows where availability equals “Ready To Move”.
data[data["availability"]=="Ready To Move"]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.0,4,2600.0,4.615385e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.0,3,1440.0,4.305556e+05
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.0,3,1521.0,6.245891e+05
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.0,2,1200.0,4.250000e+05
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.0,2,1170.0,3.247863e+05
...,...,...,...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.0,3,1715.0,6.530612e+05
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0,5,3453.0,6.689835e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0,4,3600.0,1.111111e+06
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.0,2,1141.0,5.258545e+05
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.0,1,550.0,3.090909e+05

In [32]:
#9.Get listings that are available “Immediately”.
data["availability"].unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '19-Sep', '20-Sep', '18-Mar', '20-Feb',
       '18-Apr', '20-Aug', '18-Oct', '19-Mar', '17-Sep', '18-Dec',
       '17-Aug', '19-Apr', '18-Jun', '22-Dec', '22-Jan', '18-Aug',
       '19-Jan', '17-Jul', '18-Jul', '21-Jun', '20-May', '19-Aug',
       '18-Sep', '17-May', '17-Jun', '21-May', '18-Jan', '20-Mar',
       '17-Dec', '16-Mar', '19-Jun', '22-Jun', '19-Jul', '21-Feb',
       'Immediate Possession', '19-May', '17-Nov', '20-Oct', '20-Jun',
       '19-Feb', '21-Oct', '21-Jan', '17-Mar', '17-Apr', '22-May',
       '19-Oct', '21-Jul', '21-Nov', '21-Mar', '16-Dec', '22-Mar',
       '20-Jan', '21-Sep', '21-Aug', '14-Nov', '19-Nov', '15-Nov',
       '16-Jul', '15-Jun', '17-Feb', '20-Nov', '20-Jul', '16-Sep',
       '15-Oct', '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan',
       '16-Nov', '20-Apr', '16-Jan', '14-Jul'], dtype=object)

In [33]:
data[data["availability"]=="Immediate Possession"]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
579,Plot Area,Immediate Possession,Sarjapur Road,NaN,Asiss B,1200 - 2400,NaN,NaN,34.185,<NA>,1200.0,2.848750e+05
1775,Plot Area,Immediate Possession,IVC Road,NaN,Orana N,2000 - 5634,NaN,NaN,124.000,<NA>,2000.0,6.200000e+05
2264,Plot Area,Immediate Possession,Banashankari,NaN,NaN,2400,NaN,NaN,460.000,<NA>,2400.0,1.916667e+06
2809,Plot Area,Immediate Possession,Sarjapur Road,NaN,AsdiaAr,1200 - 2400,NaN,NaN,28.785,<NA>,1200.0,2.398750e+05
2862,Plot Area,Immediate Possession,Devanahalli,NaN,Ajleyor,1500 - 2400,NaN,NaN,46.800,<NA>,1500.0,3.120000e+05
5333,Plot Area,Immediate Possession,Devanahalli,NaN,Emngs S,2100 - 5405,NaN,NaN,177.115,<NA>,2100.0,8.434048e+05
6423,Plot Area,Immediate Possession,Whitefield,NaN,SRniaGa,2324,NaN,NaN,26.730,<NA>,2324.0,1.150172e+05
6636,Plot Area,Immediate Possession,Jigani,NaN,S2enste,1500,NaN,NaN,25.490,<NA>,1500.0,1.699333e+05
6719,Plot Area,Immediate Possession,Hoskote,NaN,SJowsn,800 - 2660,NaN,NaN,28.545,<NA>,800.0,3.568125e+05
7680,Plot Area,Immediate Possession,Kasavanhalli,NaN,NaN,5000,NaN,NaN,400.000,<NA>,5000.0,8.000000e+05
8306,Plot Area,Immediate Possession,Anekal,NaN,Vaensnd,1453,NaN,NaN,16.500,<NA>,1453.0,1.135582e+05
8565,Plot Area,Immediate Possession,Carmelaram,NaN,Ocezes,2000,NaN,NaN,120.000,<NA>,2000.0,6.000000e+05
8703,Plot Area,Immediate Possession,Mysore Road,NaN,Naoden,1200 - 2400,NaN,NaN,42.300,<NA>,1200.0,3.525000e+05
10634,Plot Area,Immediate Possession,Rajankunte,NaN,NaN,1575,NaN,NaN,31.110,<NA>,1575.0,1.975238e+05
11019,Plot Area,Immediate Possession,Yelahanka,NaN,Saaveha,1200 - 1800,NaN,NaN,12.750,<NA>,1200.0,1.062500e+05
11569,Plot Area,Immediate Possession,Hosur Road,NaN,AVeldun,1350,NaN,NaN,8.440,<NA>,1350.0,6.251852e+04

In [34]:
#10.Display houses where the size column contains “4 BHK”.
data[data["size"]=="4 BHK"]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.0,4,2732.0,7.467057e+05
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.0,4,3300.0,1.818182e+06
30,Super built-up Area,19-Dec,Yelahanka,4 BHK,LedorSa,2100 - 2850,4.0,0.0,186.0,4,2100.0,8.857143e+05
122,Super built-up Area,18-Mar,Hebbal,4 BHK,SNontle,3067 - 8156,4.0,0.0,477.0,4,3067.0,1.555266e+06
123,Built-up Area,Ready To Move,Shampura,4 BHK,NaN,2650,4.0,2.0,150.0,4,2650.0,5.660377e+05
...,...,...,...,...,...,...,...,...,...,...,...,...
13293,Super built-up Area,Ready To Move,Sarjapur Road,4 BHK,Puallhi,2425,5.0,1.0,195.0,4,2425.0,8.041237e+05
13294,Super built-up Area,Ready To Move,Sultan Palaya,4 BHK,RSntsAp,2200,3.0,3.0,80.0,4,2200.0,3.636364e+05
13299,Super built-up Area,18-Dec,Whitefield,4 BHK,Prtates,2830 - 2882,5.0,0.0,154.5,4,2830.0,5.459364e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0,4,3600.0,1.111111e+06
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0,4,4689.0,1.040734e+06

In [35]:
#11.Select properties where balcony equals zero.
data[data["balcony"]==0]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
24,Super built-up Area,18-Nov,Thanisandra,1 RK,Bhe 2ko,510,1.0,0.0,25.250,1,510.0,495098.039216
30,Super built-up Area,19-Dec,Yelahanka,4 BHK,LedorSa,2100 - 2850,4.0,0.0,186.000,4,2100.0,885714.285714
42,Super built-up Area,Ready To Move,Ganga Nagar,1 BHK,Ceove G,600,1.0,0.0,38.000,1,600.0,633333.333333
43,Plot Area,Ready To Move,Yelahanka,1 Bedroom,NaN,660,1.0,0.0,48.000,1,660.0,727272.727273
46,Super built-up Area,Ready To Move,Doddathoguru,2 BHK,LancyRe,970,2.0,0.0,33.000,2,970.0,340206.185567
...,...,...,...,...,...,...,...,...,...,...,...,...
13260,Built-up Area,Ready To Move,Frazer Town,2 BHK,Saentpa,1420,2.0,0.0,120.000,2,1420.0,845070.422535
13265,Super built-up Area,20-Sep,Hoodi,2 BHK,Ranuetz,1133 - 1384,2.0,0.0,59.135,2,1133.0,521932.921447
13291,Plot Area,18-Jan,Weavers Colony,1 Bedroom,NaN,812,1.0,0.0,26.000,1,812.0,320197.044335
13299,Super built-up Area,18-Dec,Whitefield,4 BHK,Prtates,2830 - 2882,5.0,0.0,154.500,4,2830.0,545936.395760
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.000,5,3453.0,668983.492615

In [36]:
#12.Filter rows where area_type is “Super built-up Area”.
data[data["area_type"]=='Super built-up  Area']

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,1056.0,3.699811e+05
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,1521.0,6.245891e+05
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,1200.0,4.250000e+05
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2,1170.0,3.247863e+05
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00,4,2732.0,7.467057e+05
...,...,...,...,...,...,...,...,...,...,...,...,...
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00,3,1345.0,4.237918e+05
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00,3,1715.0,6.530612e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,3600.0,1.111111e+06
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,4689.0,1.040734e+06
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,550.0,3.090909e+05

In [37]:
data["area_type"].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [38]:
#13.Retrieve all properties where bath &gt; 3 and price &lt; 80.
data[(data['bath']>3) & (data["price"]<80)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
222,Built-up Area,Ready To Move,"Lakshminarayanapura, Electronic City Phase 2",4 BHK,NaN,2000,4.0,1.0,75.5,4,2000.0,3.775000e+05
265,Built-up Area,Ready To Move,Attibele,4 Bedroom,Natic T,1600,4.0,0.0,52.8,4,1600.0,3.300000e+05
308,Super built-up Area,Ready To Move,Begur,4 BHK,Prntsrt,1664,4.0,3.0,65.0,4,1664.0,3.906250e+05
603,Plot Area,Ready To Move,Doddagubbi,3 Bedroom,NaN,1125,4.0,1.0,70.0,3,1125.0,6.222222e+05
617,Built-up Area,Ready To Move,R.T. Nagar,4 Bedroom,NaN,1500,4.0,1.0,70.0,4,1500.0,4.666667e+05
...,...,...,...,...,...,...,...,...,...,...,...,...
13045,Plot Area,Ready To Move,Vasanthpura,6 Bedroom,NaN,600,6.0,2.0,65.0,6,600.0,1.083333e+06
13146,Super built-up Area,Ready To Move,Basavanapura,7 BHK,NaN,1800,5.0,3.0,65.0,7,1800.0,3.611111e+05
13221,Plot Area,Ready To Move,T Dasarahalli,9 Bedroom,NaN,1178,9.0,1.0,75.0,9,1178.0,6.366723e+05
13275,Plot Area,Ready To Move,Kothannur,4 Bedroom,NaN,1600,4.0,2.0,45.0,4,1600.0,2.812500e+05
13303,Plot Area,Ready To Move,Vidyaranyapura,5 Bedroom,NaN,774,5.0,3.0,70.0,5,774.0,9.043928e+05

In [39]:
#14.Get listings where total_sqft column value is a number and greater than 1500.
df=data[data["total_sqft"].str.isnumeric()]

In [40]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '2758', '774', '4689'], dtype=object)

In [41]:
df['total_sqft']=df['total_sqft'].astype('int')

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\2476502196.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_sqft']=df['total_sqft'].astype('int')

In [42]:
df[df['total_sqft']>1500]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,2600.0,4.615385e+05
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,1521.0,6.245891e+05
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00,4,2732.0,7.467057e+05
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.00,4,3300.0,1.818182e+06
10,Super built-up Area,18-Feb,Whitefield,3 BHK,NaN,1800,2.0,2.0,70.00,3,1800.0,3.888889e+05
...,...,...,...,...,...,...,...,...,...,...,...,...
13309,Super built-up Area,Ready To Move,Yeshwanthpur,3 BHK,IBityin,1675,3.0,NaN,92.13,3,1675.0,5.500299e+05
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00,3,1715.0,6.530612e+05
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,3453.0,6.689835e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,3600.0,1.111111e+06
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,4689.0,1.040734e+06

In [43]:
#15.Display houses in “Marathahalli” with a price_per_sqft &gt; 6000.
df[(df["location"]=='Marathahalli') & (df["price_per_sqft"]>6000)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,total_sq,price_per_sqft
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25,3,1310.0,4.828244e+05
67,Super built-up Area,Ready To Move,Marathahalli,2 BHK,NaN,1220,2.0,1.0,57.00,2,1220.0,4.672131e+05
189,Super built-up Area,Ready To Move,Marathahalli,2 BHK,VRave E,1200,2.0,2.0,52.00,2,1200.0,4.333333e+05
194,Super built-up Area,Ready To Move,Marathahalli,2 BHK,Aiitya,1200,2.0,2.0,60.00,2,1200.0,5.000000e+05
322,Plot Area,Ready To Move,Marathahalli,2 Bedroom,NaN,1200,2.0,2.0,128.00,2,1200.0,1.066667e+06
...,...,...,...,...,...,...,...,...,...,...,...,...
12185,Super built-up Area,Ready To Move,Marathahalli,2 BHK,Spsic C,1100,2.0,1.0,50.00,2,1100.0,4.545455e+05
12836,Super built-up Area,Ready To Move,Marathahalli,2 BHK,NaN,1196,2.0,2.0,57.95,2,1196.0,4.845318e+05
12846,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25,3,1310.0,4.828244e+05
12968,Built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1485,2.0,2.0,90.00,3,1485.0,6.060606e+05
13255,Super built-up Area,19-Dec,Marathahalli,2 BHK,PrensKe,1146,2.0,1.0,69.00,2,1146.0,6.020942e+05

In [44]:
df.drop(columns=["total_sq"],inplace=True)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\3311818651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["total_sq"],inplace=True)

In [45]:
#16.Retrieve all properties with 2 BHK or 3 BHK only.
df[(df['size']=="2 BHK") | (df["size"]=="3 BHK")]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,369981.060606
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,430555.555556
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,624589.086128
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,425000.000000
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2,324786.324786
...,...,...,...,...,...,...,...,...,...,...,...
13310,Super built-up Area,Ready To Move,Rachenahalli,2 BHK,NaN,1050,2.0,2.0,52.71,2,502000.000000
13312,Super built-up Area,Ready To Move,Bellandur,2 BHK,NaN,1262,2.0,2.0,47.00,2,372424.722662
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00,3,423791.821561
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00,3,653061.224490
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,525854.513585

In [46]:
#17.Filter houses with an even number of bathrooms.
df[df['bath']%2==0]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2,3.247863e+05
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00,4,7.467057e+05
...,...,...,...,...,...,...,...,...,...,...,...
13312,Super built-up Area,Ready To Move,Bellandur,2 BHK,NaN,1262,2.0,2.0,47.00,2,3.724247e+05
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00,3,4.237918e+05
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,1.040734e+06

In [47]:
#18.Display listings where the number of bathrooms is less than bedrooms.
df[df["bath"]<df["bedroom"]]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05
10,Super built-up Area,18-Feb,Whitefield,3 BHK,NaN,1800,2.0,2.0,70.00,3,3.888889e+05
26,Super built-up Area,Ready To Move,Electronic City,2 BHK,Itelaa,660,1.0,1.0,23.10,2,3.500000e+05
29,Super built-up Area,Ready To Move,Electronic City,3 BHK,KBityo,1025,2.0,1.0,47.00,3,4.585366e+05
31,Super built-up Area,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1075,2.0,1.0,35.00,3,3.255814e+05
...,...,...,...,...,...,...,...,...,...,...,...
13290,Super built-up Area,Ready To Move,Sarjapur Road,4 BHK,Maana E,4050,2.0,1.0,450.00,4,1.111111e+06
13292,Super built-up Area,18-Jul,Udayapur Village,3 BHK,Plowsri,1440,2.0,2.0,63.93,3,4.439583e+05
13294,Super built-up Area,Ready To Move,Sultan Palaya,4 BHK,RSntsAp,2200,3.0,3.0,80.00,4,3.636364e+05
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00,3,4.237918e+05
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05

In [48]:
#19.Show rows where the location starts with “B”.
df[df["location"].str[0]=="B"]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
16,Super built-up Area,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180,3.0,2.0,48.0,3,406779.661017
21,Super built-up Area,19-Dec,Binny Pete,3 BHK,She 2rk,1755,3.0,1.0,122.0,3,695156.695157
23,Super built-up Area,Ready To Move,Bellandur,3 BHK,NaN,1767,3.0,1.0,103.0,3,582908.885116
31,Super built-up Area,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1075,2.0,1.0,35.0,3,325581.395349
51,Super built-up Area,18-Mar,Bhoganhalli,3 BHK,Rosha I,1670,3.0,1.0,99.0,3,592814.371257
...,...,...,...,...,...,...,...,...,...,...,...
13274,Super built-up Area,Ready To Move,Budigere,2 BHK,PrityTr,1153,2.0,2.0,60.0,2,520381.613183
13284,Super built-up Area,Ready To Move,Bannerghatta Road,2 BHK,SNity S,970,2.0,1.0,57.0,2,587628.865979
13307,Built-up Area,Ready To Move,Billekahalli,3 BHK,NaN,1805,3.0,3.0,134.0,3,742382.271468
13308,Built-up Area,Ready To Move,Bannerghatta Road,3 BHK,Baanise,1527,3.0,1.0,142.0,3,929927.963327
13312,Super built-up Area,Ready To Move,Bellandur,2 BHK,NaN,1262,2.0,2.0,47.0,2,372424.722662

In [49]:
#20.Select all rows where the location ends with “Layout”.
df[df['location'].notna() & df["location"].str.endswith("Layout")]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
18,Super built-up Area,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770,4.0,2.0,290.0,3,1.046931e+06
45,Plot Area,Ready To Move,HSR Layout,8 Bedroom,NaN,600,9.0,NaN,200.0,8,3.333333e+06
57,Super built-up Area,Ready To Move,Ramakrishnappa Layout,2 BHK,PeBayle,1500,2.0,2.0,185.0,2,1.233333e+06
79,Built-up Area,Ready To Move,ISRO Layout,6 Bedroom,NaN,4400,6.0,3.0,250.0,6,5.681818e+05
80,Super built-up Area,Ready To Move,Kodanda Reddy Layout,3 BHK,AdentEl,1660,2.0,2.0,105.0,3,6.325301e+05
...,...,...,...,...,...,...,...,...,...,...,...
13262,Built-up Area,Ready To Move,Abshot Layout,2 BHK,Emtat H,1140,1.0,1.0,185.0,2,1.622807e+06
13278,Built-up Area,Ready To Move,Reliaable Tranquil Layout,2 BHK,Sariana,1256,2.0,1.0,65.0,2,5.175159e+05
13285,Super built-up Area,Ready To Move,VHBCS Layout,2 BHK,OlarkLa,1353,2.0,2.0,110.0,2,8.130081e+05
13302,Super built-up Area,Ready To Move,Annaiah Reddy Layout,2 BHK,NaN,1075,2.0,2.0,48.0,2,4.465116e+05
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.0,3,6.530612e+05

In [50]:
#21.Retrieve properties where area_type is not “Plot Area”.
df[df["area_type"]!='Plot  Area']

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,6.245891e+05
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2,3.247863e+05
...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,1.111111e+06
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,1.040734e+06
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,3.090909e+05

In [51]:
#22.Display listings with price greater than the average price of the dataset.
avg_p=df['price'].mean()

In [52]:
df[df["price"]>avg_p]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.0,4,4.615385e+05
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.0,4,7.467057e+05
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.0,4,1.818182e+06
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.0,6,3.627451e+06
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.0,4,1.059246e+06
...,...,...,...,...,...,...,...,...,...,...,...
13308,Built-up Area,Ready To Move,Bannerghatta Road,3 BHK,Baanise,1527,3.0,1.0,142.0,3,9.299280e+05
13311,Plot Area,Ready To Move,Ramamurthy Nagar,7 Bedroom,NaN,1500,9.0,2.0,250.0,7,1.666667e+06
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0,5,6.689835e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0,4,1.111111e+06
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0,4,1.040734e+06

In [53]:
#23.Get all rows where availability contains the word “Soon”.
df[df['availability'].str.contains("Soon",case=False,na=False)]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price, bedroom, price_per_sqft]
Index: []

In [54]:
df['availability'].unique()

array(['19-Dec', 'Ready To Move', '18-May', '18-Feb', '18-Nov', '20-Dec',
       '17-Oct', '21-Dec', '20-Sep', '18-Mar', '18-Apr', '20-Aug',
       '19-Mar', '17-Sep', '18-Dec', '17-Aug', '19-Apr', '18-Jun',
       '22-Dec', '22-Jan', '18-Aug', '19-Jan', '17-Jul', '18-Jul',
       '21-Jun', '20-May', '19-Aug', '18-Sep', '17-May', '17-Jun',
       '18-Oct', '21-May', '18-Jan', '20-Mar', '17-Dec', '16-Mar',
       '19-Jun', '22-Jun', '19-Jul', '21-Feb', '19-May', '17-Nov',
       '20-Oct', '20-Jun', '19-Feb', '21-Oct', '21-Jan', '17-Mar',
       '19-Sep', '17-Apr', '19-Oct', '21-Jul', '21-Nov', '21-Mar',
       '16-Dec', '22-Mar', '20-Jan', '21-Sep', 'Immediate Possession',
       '21-Aug', '14-Nov', '19-Nov', '15-Nov', '16-Jul', '15-Jun',
       '17-Feb', '20-Nov', '20-Jul', '16-Sep', '15-Oct', '20-Feb',
       '15-Dec', '16-Oct', '22-Nov', '15-Aug', '17-Jan', '16-Nov',
       '20-Apr', '16-Jan', '14-Jul'], dtype=object)

In [55]:
#24.Filter houses that have “Penthouse” in their name (if present).
df['society'].unique()

array(['Coomee ', 'Theanmp', nan, ..., 'SJovest', 'ThhtsV ', 'RSntsAp'],
      dtype=object)

In [56]:
df[df['society'].str.contains("Penthouse",case=False,na=False)]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price, bedroom, price_per_sqft]
Index: []

In [57]:
#25.Select properties where total_sqft value lies between 1000 and 2000.
df[(df["total_sqft"]>1000) & (df["total_sqft"]<2000)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,6.245891e+05
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2,3.247863e+05
...,...,...,...,...,...,...,...,...,...,...,...
13311,Plot Area,Ready To Move,Ramamurthy Nagar,7 Bedroom,NaN,1500,9.0,2.0,250.00,7,1.666667e+06
13312,Super built-up Area,Ready To Move,Bellandur,2 BHK,NaN,1262,2.0,2.0,47.00,2,3.724247e+05
13313,Super built-up Area,Ready To Move,Uttarahalli,3 BHK,Aklia R,1345,2.0,1.0,57.00,3,4.237918e+05
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00,3,6.530612e+05
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05

In [58]:
#26.Retrieve listings that have exactly 3 balconies.
df[df["balcony"]==3]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,4.615385e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00,4,1.059246e+06
17,Super built-up Area,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540,3.0,3.0,60.00,3,3.896104e+05
33,Super built-up Area,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1693,3.0,3.0,57.39,3,3.389841e+05
...,...,...,...,...,...,...,...,...,...,...,...
13301,Super built-up Area,Ready To Move,Kothanur,3 BHK,NaN,1454,3.0,3.0,71.50,3,4.917469e+05
13303,Plot Area,Ready To Move,Vidyaranyapura,5 Bedroom,NaN,774,5.0,3.0,70.00,5,9.043928e+05
13305,Carpet Area,Ready To Move,Hulimavu,1 BHK,NaN,500,1.0,3.0,220.00,1,4.400000e+06
13307,Built-up Area,Ready To Move,Billekahalli,3 BHK,NaN,1805,3.0,3.0,134.00,3,7.423823e+05
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00,3,6.530612e+05

In [59]:
#27.Display rows where size column has a missing bedroom count (e.g., “BHK” missing number).
df['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom', nan,
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [60]:
d1=df[~df['size'].str.contains("Bedroom",case=False,na=False)]

In [61]:
d2=d1[~d1['size'].str.contains("BHK",case=False,na=False)]

In [62]:
d2

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
24,Super built-up Area,18-Nov,Thanisandra,1 RK,Bhe 2ko,510,1.0,0.0,25.25,1,4.950980e+05
782,Super built-up Area,Ready To Move,Thanisandra,1 RK,Bhmesy,445,1.0,0.0,28.00,1,6.292135e+05
1363,Super built-up Area,21-Nov,Thanisandra,1 RK,Bhe 2ko,510,1.0,1.0,25.25,1,4.950980e+05
2264,Plot Area,Immediate Possession,Banashankari,NaN,NaN,2400,NaN,NaN,460.00,<NA>,1.916667e+06
2486,Super built-up Area,19-Dec,Bhoganhalli,1 RK,Rosha I,296,1.0,0.0,22.89,1,7.733108e+05
2557,Built-up Area,Ready To Move,Anekal,1 RK,NaN,351,1.0,1.0,16.00,1,4.558405e+05
2788,Super built-up Area,20-Aug,Rachenahalli,1 RK,AsNowre,440,1.0,0.0,28.00,1,6.363636e+05
4876,Built-up Area,Ready To Move,Electronic City,1 RK,GMown E,435,1.0,1.0,19.50,1,4.482759e+05
5079,Built-up Area,17-Jun,Whitefield,1 RK,Prtates,905,1.0,1.0,52.00,1,5.745856e+05
6423,Plot Area,Immediate Possession,Whitefield,NaN,SRniaGa,2324,NaN,NaN,26.73,<NA>,1.150172e+05
6586,Super built-up Area,Ready To Move,Electronics City Phase 1,1 RK,NaN,360,1.0,0.0,16.90,1,4.694444e+05
6636,Plot Area,Immediate Possession,Jigani,NaN,S2enste,1500,NaN,NaN,25.49,<NA>,1.699333e+05
7638,Super built-up Area,Ready To Move,Basavangudi,1 RK,NaN,670,1.0,1.0,50.00,1,7.462687e+05
7680,Plot Area,Immediate Possession,Kasavanhalli,NaN,NaN,5000,NaN,NaN,400.00,<NA>,8.000000e+05
8306,Plot Area,Immediate Possession,Anekal,NaN,Vaensnd,1453,NaN,NaN,16.50,<NA>,1.135582e+05
8385,Super built-up Area,Ready To Move,Banaswadi,1 RK,Krntsee,527,1.0,0.0,35.00,1,6.641366e+05
8565,Plot Area,Immediate Possession,Carmelaram,NaN,Ocezes,2000,NaN,NaN,120.00,<NA>,6.000000e+05
10576,Built-up Area,Ready To Move,Electronic City,1 RK,GMown E,550,1.0,1.0,27.00,1,4.909091e+05
10634,Plot Area,Immediate Possession,Rajankunte,NaN,NaN,1575,NaN,NaN,31.11,<NA>,1.975238e+05
11569,Plot Area,Immediate Possession,Hosur Road,NaN,AVeldun,1350,NaN,NaN,8.44,<NA>,6.251852e+04

In [63]:
#28.Filter properties where the ratio price / total_sqft &gt; 5.
df[(df["price"]/df["total_sqft"])>5]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
349,Plot Area,18-Dec,Suragajakkanahalli,3 Bedroom,PrhyaK,11,3.0,2.0,74.0,3,6.727273e+07
1122,Built-up Area,Ready To Move,Grihalakshmi Layout,5 Bedroom,NaN,24,2.0,2.0,150.0,5,6.250000e+07
4086,Plot Area,Ready To Move,Sarjapur Road,4 Bedroom,NaN,1,4.0,NaN,120.0,4,1.200000e+09
4972,Built-up Area,Ready To Move,Srirampuram,7 BHK,NaN,5,7.0,3.0,115.0,7,2.300000e+08

In [64]:
#29.Get all properties in “BTM Layout” priced below 1 crore.
btm=df[df["location"]=='BTM Layout']

In [65]:
btm[btm["price"]<1]

Empty DataFrame
Columns: [area_type, availability, location, size, society, total_sqft, bath, balcony, price, bedroom, price_per_sqft]
Index: []

In [66]:
#30.Show all properties not located in “Electronic City”.
df[~df["location"].str.contains('Electronic City',case=False,na=False)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.0,4,4.615385e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.0,3,4.305556e+05
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.0,3,6.245891e+05
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.0,2,4.250000e+05
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.0,2,3.247863e+05
...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0,5,6.689835e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0,4,1.111111e+06
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.0,2,5.258545e+05
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0,4,1.040734e+06
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.0,1,3.090909e+05

In [67]:
#31.Display rows where both bath and balcony are greater than or equal to 2.
df[(df['bath']>=2) & (df["balcony"]>=2)]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,4.615385e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05
10,Super built-up Area,18-Feb,Whitefield,3 BHK,NaN,1800,2.0,2.0,70.00,3,3.888889e+05
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00,4,1.059246e+06
13,Built-up Area,Ready To Move,Gottigere,2 BHK,NaN,1100,2.0,2.0,40.00,2,3.636364e+05
...,...,...,...,...,...,...,...,...,...,...,...
13307,Built-up Area,Ready To Move,Billekahalli,3 BHK,NaN,1805,3.0,3.0,134.00,3,7.423823e+05
13310,Super built-up Area,Ready To Move,Rachenahalli,2 BHK,NaN,1050,2.0,2.0,52.71,2,5.020000e+05
13311,Plot Area,Ready To Move,Ramamurthy Nagar,7 Bedroom,NaN,1500,9.0,2.0,250.00,7,1.666667e+06
13312,Super built-up Area,Ready To Move,Bellandur,2 BHK,NaN,1262,2.0,2.0,47.00,2,3.724247e+05
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00,3,6.530612e+05

In [68]:
#32.Retrieve properties where total_sqft is greater than 3 times bath.
df[df["total_sqft"]>3*df['bath']]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,4.615385e+05
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,6.245891e+05
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05
...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,1.111111e+06
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,1.040734e+06
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,3.090909e+05

In [69]:
#33.Select properties whose location name has more than two words.
df["location"].str.split(" ")

0        [Electronic, City, Phase, II]
1                  [Chikka, Tirupathi]
2                        [Uttarahalli]
3                 [Lingadheeranahalli]
4                           [Kothanur]
                     ...
13315                     [Whitefield]
13316                 [Richards, Town]
13317        [Raja, Rajeshwari, Nagar]
13318                [Padmanabhanagar]
13319                   [Doddathoguru]
Name: location, Length: 12986, dtype: object

In [70]:
#34.Create a new column price_in_lakhs = price * 100.
df["price_in_lakhs"]=df["price"]*100

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\3654456425.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["price_in_lakhs"]=df["price"]*100

In [71]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft,price_in_lakhs
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05,3907.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,4.615385e+05,12000.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05,6200.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,6.245891e+05,9500.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05,5100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05,23100.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,1.111111e+06,40000.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05,6000.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,1.040734e+06,48800.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,3.090909e+05,1700.0

In [72]:
#35.Add a new column bedroom_count extracted from the size column.
df['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom', nan,
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [73]:
new=df['size'].str.split(" ",expand=True)

In [74]:
new

       0        1
0      2      BHK
1      4  Bedroom
2      3      BHK
3      3      BHK
4      2      BHK
...   ..      ...
13315  5  Bedroom
13316  4      BHK
13317  2      BHK
13318  4      BHK
13319  1      BHK

[12986 rows x 2 columns]

In [75]:
df["bedroom_count"]=new[0]

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\3678129462.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bedroom_count"]=new[0]

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12986 entries, 0 to 13319
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   area_type       12986 non-null  object
 1   availability    12986 non-null  object
 2   location        12985 non-null  object
 3   size            12978 non-null  object
 4   society         7528 non-null   object
 5   total_sqft      12986 non-null  int64
 6   bath            12970 non-null  float64
 7   balcony         12439 non-null  float64
 8   price           12986 non-null  float64
 9   bedroom         12978 non-null  Int64
 10  price_per_sqft  12986 non-null  float64
 11  price_in_lakhs  12986 non-null  float64
 12  bedroom_count   12978 non-null  object
dtypes: Int64(1), float64(5), int64(1), object(6)
memory usage: 1.4+ MB

In [77]:
df["bedroom_count"]=df['bedroom_count'].astype('float')

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\3935102387.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bedroom_count"]=df['bedroom_count'].astype('float')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12986 entries, 0 to 13319
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   area_type       12986 non-null  object
 1   availability    12986 non-null  object
 2   location        12985 non-null  object
 3   size            12978 non-null  object
 4   society         7528 non-null   object
 5   total_sqft      12986 non-null  int64
 6   bath            12970 non-null  float64
 7   balcony         12439 non-null  float64
 8   price           12986 non-null  float64
 9   bedroom         12978 non-null  Int64
 10  price_per_sqft  12986 non-null  float64
 11  price_in_lakhs  12986 non-null  float64
 12  bedroom_count   12978 non-null  float64
dtypes: Int64(1), float64(6), int64(1), object(5)
memory usage: 1.4+ MB

In [79]:
#36.Create a column sqft_per_bathroom = total_sqft / bath.
df["sqft_per_bathroom"]=df["total_sqft"]/df["bath"]

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\4184083560.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["sqft_per_bathroom"]=df["total_sqft"]/df["bath"]

In [80]:
#37.Convert availability values to lowercase.
df['availability']=df['availability'].str.lower()

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\1448210978.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['availability']=df['availability'].str.lower()

In [81]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft,price_in_lakhs,bedroom_count,sqft_per_bathroom
0,Super built-up Area,19-dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05,3907.0,2.0,528.00
1,Plot Area,ready to move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,4.615385e+05,12000.0,4.0,520.00
2,Built-up Area,ready to move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05,6200.0,3.0,720.00
3,Super built-up Area,ready to move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,6.245891e+05,9500.0,3.0,507.00
4,Super built-up Area,ready to move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05,5100.0,2.0,600.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,ready to move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05,23100.0,5.0,863.25
13316,Super built-up Area,ready to move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,1.111111e+06,40000.0,4.0,720.00
13317,Built-up Area,ready to move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05,6000.0,2.0,570.50
13318,Super built-up Area,18-jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,1.040734e+06,48800.0,4.0,1172.25
13319,Super built-up Area,ready to move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,3.090909e+05,1700.0,1.0,550.00

In [82]:
#38.Add a column is_ready_to_move with True if availability is “Ready To Move”, else False.
df["is_ready_to_move"]=df['availability']=='ready to move'

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\2542527903.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["is_ready_to_move"]=df['availability']=='ready to move'

In [83]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft,price_in_lakhs,bedroom_count,sqft_per_bathroom,is_ready_to_move
0,Super built-up Area,19-dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05,3907.0,2.0,528.00,False
1,Plot Area,ready to move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,4.615385e+05,12000.0,4.0,520.00,True
2,Built-up Area,ready to move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05,6200.0,3.0,720.00,True
3,Super built-up Area,ready to move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,6.245891e+05,9500.0,3.0,507.00,True
4,Super built-up Area,ready to move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05,5100.0,2.0,600.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,ready to move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05,23100.0,5.0,863.25,True
13316,Super built-up Area,ready to move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,1.111111e+06,40000.0,4.0,720.00,True
13317,Built-up Area,ready to move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05,6000.0,2.0,570.50,True
13318,Super built-up Area,18-jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,1.040734e+06,48800.0,4.0,1172.25,False
13319,Super built-up Area,ready to move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,3.090909e+05,1700.0,1.0,550.00,True

In [84]:
#39.Rename the column price to price_in_crores.
df.rename(columns={"price":'price_in_crores'},inplace=True)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\1314600946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"price":'price_in_crores'},inplace=True)

In [85]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price_in_crores,bedroom,price_per_sqft,price_in_lakhs,bedroom_count,sqft_per_bathroom,is_ready_to_move
0,Super built-up Area,19-dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05,3907.0,2.0,528.00,False
1,Plot Area,ready to move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,4.615385e+05,12000.0,4.0,520.00,True
2,Built-up Area,ready to move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05,6200.0,3.0,720.00,True
3,Super built-up Area,ready to move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,6.245891e+05,9500.0,3.0,507.00,True
4,Super built-up Area,ready to move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05,5100.0,2.0,600.00,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,ready to move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05,23100.0,5.0,863.25,True
13316,Super built-up Area,ready to move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,1.111111e+06,40000.0,4.0,720.00,True
13317,Built-up Area,ready to move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05,6000.0,2.0,570.50,True
13318,Super built-up Area,18-jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,1.040734e+06,48800.0,4.0,1172.25,False
13319,Super built-up Area,ready to move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,3.090909e+05,1700.0,1.0,550.00,True

In [86]:
#40.Replace all spaces in column names with underscores.

In [87]:
#41.Extract only the numeric part from total_sqft (if it’s a string like “1200 - 1500”).
df["total_sqft"]

0        1056
1        2600
2        1440
3        1521
4        1200
         ...
13315    3453
13316    3600
13317    1141
13318    4689
13319     550
Name: total_sqft, Length: 12986, dtype: int64

In [88]:
#42.Create a column price_category → “Low”, “Medium”, “High” based on price ranges.
avg_p

np.float64(112.27140458955799)

In [89]:
def p_category(x):
    if x<avg_p:
        return "low"
    elif x>avg_p:
        return "High"
    else:
        return "Medium"

In [90]:
df.rename(columns={"price_in_crores":"price"},inplace=True)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\24621233.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"price_in_crores":"price"},inplace=True)

In [91]:
df["price_category"]=df["price"].apply(p_category)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\1847839521.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["price_category"]=df["price"].apply(p_category)

In [92]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,price_per_sqft,price_in_lakhs,bedroom_count,sqft_per_bathroom,is_ready_to_move,price_category
0,Super built-up Area,19-dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,3.699811e+05,3907.0,2.0,528.00,False,low
1,Plot Area,ready to move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,4.615385e+05,12000.0,4.0,520.00,True,High
2,Built-up Area,ready to move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,4.305556e+05,6200.0,3.0,720.00,True,low
3,Super built-up Area,ready to move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,6.245891e+05,9500.0,3.0,507.00,True,low
4,Super built-up Area,ready to move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,4.250000e+05,5100.0,2.0,600.00,True,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,ready to move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,6.689835e+05,23100.0,5.0,863.25,True,High
13316,Super built-up Area,ready to move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,1.111111e+06,40000.0,4.0,720.00,True,High
13317,Built-up Area,ready to move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,5.258545e+05,6000.0,2.0,570.50,True,low
13318,Super built-up Area,18-jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,1.040734e+06,48800.0,4.0,1172.25,False,High
13319,Super built-up Area,ready to move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,3.090909e+05,1700.0,1.0,550.00,True,low

In [93]:
#43.Add a new column area_sqft by converting total_sqft to float values.
df["area_sqft"]=df["total_sqft"].astype("float")

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\18843765.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["area_sqft"]=df["total_sqft"].astype("float")

In [94]:
#44.Create a column price_per_bath = price / bath.
df["price_per_bath"]=df["price"]/df["bath"]

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\3122534525.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["price_per_bath"]=df["price"]/df["bath"]

In [95]:
#45.Add a column price_per_room = price / bedroom_count.
df["price_per_room"]=df["price"]/df['bedroom_count']

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\3375834680.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["price_per_room"]=df["price"]/df['bedroom_count']

In [96]:
#46.Create a derived column total_cost_in_lakhs = price_in_crores * 100.
df["price_in_lakhs"]

0         3907.0
1        12000.0
2         6200.0
3         9500.0
4         5100.0
          ...
13315    23100.0
13316    40000.0
13317     6000.0
13318    48800.0
13319     1700.0
Name: price_in_lakhs, Length: 12986, dtype: float64

In [97]:
#47.Add a Boolean column large_balcony = True if balcony ≥ 3.
df["large_balcony"]=df["balcony"]>=3

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\796701971.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["large_balcony"]=df["balcony"]>=3

In [98]:
#48.Create a column showing whether the location contains “Road”.
df["contain_road"]=df["location"].str.contains("Road",case=False,na=False)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\4247769626.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["contain_road"]=df["location"].str.contains("Road",case=False,na=False)

In [99]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,...,price_in_lakhs,bedroom_count,sqft_per_bathroom,is_ready_to_move,price_category,area_sqft,price_per_bath,price_per_room,large_balcony,contain_road
0,Super built-up Area,19-dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,...,3907.0,2.0,528.00,False,low,1056.0,19.535000,19.535000,False,False
1,Plot Area,ready to move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,...,12000.0,4.0,520.00,True,High,2600.0,24.000000,30.000000,True,False
2,Built-up Area,ready to move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,...,6200.0,3.0,720.00,True,low,1440.0,31.000000,20.666667,True,False
3,Super built-up Area,ready to move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,...,9500.0,3.0,507.00,True,low,1521.0,31.666667,31.666667,False,False
4,Super built-up Area,ready to move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,...,5100.0,2.0,600.00,True,low,1200.0,25.500000,25.500000,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,ready to move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,...,23100.0,5.0,863.25,True,High,3453.0,57.750000,46.200000,False,False
13316,Super built-up Area,ready to move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,...,40000.0,4.0,720.00,True,High,3600.0,80.000000,100.000000,False,False
13317,Built-up Area,ready to move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,...,6000.0,2.0,570.50,True,low,1141.0,30.000000,30.000000,False,False
13318,Super built-up Area,18-jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,...,48800.0,4.0,1172.25,False,High,4689.0,122.000000,122.000000,False,False
13319,Super built-up Area,ready to move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,...,1700.0,1.0,550.00,True,low,550.0,17.000000,17.000000,False,False

In [100]:
df["contain_road"].unique()

array([False,  True])

In [101]:
#49.Add a new column with the number of words in each location.
df["words_in_location"]=df["location"].apply(lambda x:len(str(x).split()))

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\638978108.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["words_in_location"]=df["location"].apply(lambda x:len(str(x).split()))

In [102]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,...,bedroom_count,sqft_per_bathroom,is_ready_to_move,price_category,area_sqft,price_per_bath,price_per_room,large_balcony,contain_road,words_in_location
0,Super built-up Area,19-dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,...,2.0,528.00,False,low,1056.0,19.535000,19.535000,False,False,4
1,Plot Area,ready to move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,...,4.0,520.00,True,High,2600.0,24.000000,30.000000,True,False,2
2,Built-up Area,ready to move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,...,3.0,720.00,True,low,1440.0,31.000000,20.666667,True,False,1
3,Super built-up Area,ready to move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,...,3.0,507.00,True,low,1521.0,31.666667,31.666667,False,False,1
4,Super built-up Area,ready to move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,...,2.0,600.00,True,low,1200.0,25.500000,25.500000,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,ready to move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,...,5.0,863.25,True,High,3453.0,57.750000,46.200000,False,False,1
13316,Super built-up Area,ready to move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,...,4.0,720.00,True,High,3600.0,80.000000,100.000000,False,False,2
13317,Built-up Area,ready to move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,...,2.0,570.50,True,low,1141.0,30.000000,30.000000,False,False,3
13318,Super built-up Area,18-jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,...,4.0,1172.25,False,High,4689.0,122.000000,122.000000,False,False,1
13319,Super built-up Area,ready to move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,...,1.0,550.00,True,low,550.0,17.000000,17.000000,False,False,1

In [103]:
#50.Combine area_type and availability into a new column property_status.
df["property_status"]=df["area_type"]+" "+df["availability"]

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\2886897517.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["property_status"]=df["area_type"]+" "+df["availability"]

In [104]:
#51.Extract the first word from each location into a column main_area.
df["main_area"]=df["location"].apply(lambda x:str(x).split()[0])

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\3949857795.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["main_area"]=df["location"].apply(lambda x:str(x).split()[0])

In [105]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bedroom,...,is_ready_to_move,price_category,area_sqft,price_per_bath,price_per_room,large_balcony,contain_road,words_in_location,property_status,main_area
0,Super built-up Area,19-dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2,...,False,low,1056.0,19.535000,19.535000,False,False,4,Super built-up Area 19-dec,Electronic
1,Plot Area,ready to move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4,...,True,High,2600.0,24.000000,30.000000,True,False,2,Plot Area ready to move,Chikka
2,Built-up Area,ready to move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3,...,True,low,1440.0,31.000000,20.666667,True,False,1,Built-up Area ready to move,Uttarahalli
3,Super built-up Area,ready to move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3,...,True,low,1521.0,31.666667,31.666667,False,False,1,Super built-up Area ready to move,Lingadheeranahalli
4,Super built-up Area,ready to move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2,...,True,low,1200.0,25.500000,25.500000,False,False,1,Super built-up Area ready to move,Kothanur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,ready to move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,5,...,True,High,3453.0,57.750000,46.200000,False,False,1,Built-up Area ready to move,Whitefield
13316,Super built-up Area,ready to move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00,4,...,True,High,3600.0,80.000000,100.000000,False,False,2,Super built-up Area ready to move,Richards
13317,Built-up Area,ready to move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00,2,...,True,low,1141.0,30.000000,30.000000,False,False,3,Built-up Area ready to move,Raja
13318,Super built-up Area,18-jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00,4,...,False,High,4689.0,122.000000,122.000000,False,False,1,Super built-up Area 18-jun,Padmanabhanagar
13319,Super built-up Area,ready to move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00,1,...,True,low,550.0,17.000000,17.000000,False,False,1,Super built-up Area ready to move,Doddathoguru

In [106]:
#52.Convert all values in area_type to uppercase.
df["area_type"]=df["area_type"].str.upper()

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\103898350.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["area_type"]=df["area_type"].str.upper()

In [107]:
#53.Replace the word “BHK” with “Bedrooms” in the size column.
df["size"]=df["size"].str.replace("BHK","Bedroom",case=False)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\2954445117.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["size"]=df["size"].str.replace("BHK","Bedroom",case=False)

In [108]:
#54.Add a new column price_per_sqft_rounded rounded to 2 decimals.
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price', 'bedroom', 'price_per_sqft',
       'price_in_lakhs', 'bedroom_count', 'sqft_per_bathroom',
       'is_ready_to_move', 'price_category', 'area_sqft', 'price_per_bath',
       'price_per_room', 'large_balcony', 'contain_road', 'words_in_location',
       'property_status', 'main_area'],
      dtype='object')

In [109]:
df["price_per_sqft"]

0        3.699811e+05
1        4.615385e+05
2        4.305556e+05
3        6.245891e+05
4        4.250000e+05
             ...
13315    6.689835e+05
13316    1.111111e+06
13317    5.258545e+05
13318    1.040734e+06
13319    3.090909e+05
Name: price_per_sqft, Length: 12986, dtype: float64

In [110]:
df["price_per_sqft_rounded"]=(df["price"]*100)/df["total_sqft"].round(2)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\4202826235.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["price_per_sqft_rounded"]=(df["price"]*100)/df["total_sqft"].round(2)

In [111]:
#54.Reorder columns so that price appears first.
column=df.pop("price")
df.insert(0,"price",column)

In [112]:
df

,price,area_type,availability,location,size,society,total_sqft,bath,balcony,bedroom,...,price_category,area_sqft,price_per_bath,price_per_room,large_balcony,contain_road,words_in_location,property_status,main_area,price_per_sqft_rounded
0,39.07,SUPER BUILT-UP AREA,19-dec,Electronic City Phase II,2 Bedroom,Coomee,1056,2.0,1.0,2,...,low,1056.0,19.535000,19.535000,False,False,4,Super built-up Area 19-dec,Electronic,3.699811
1,120.00,PLOT AREA,ready to move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,4,...,High,2600.0,24.000000,30.000000,True,False,2,Plot Area ready to move,Chikka,4.615385
2,62.00,BUILT-UP AREA,ready to move,Uttarahalli,3 Bedroom,NaN,1440,2.0,3.0,3,...,low,1440.0,31.000000,20.666667,True,False,1,Built-up Area ready to move,Uttarahalli,4.305556
3,95.00,SUPER BUILT-UP AREA,ready to move,Lingadheeranahalli,3 Bedroom,Soiewre,1521,3.0,1.0,3,...,low,1521.0,31.666667,31.666667,False,False,1,Super built-up Area ready to move,Lingadheeranahalli,6.245891
4,51.00,SUPER BUILT-UP AREA,ready to move,Kothanur,2 Bedroom,NaN,1200,2.0,1.0,2,...,low,1200.0,25.500000,25.500000,False,False,1,Super built-up Area ready to move,Kothanur,4.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,231.00,BUILT-UP AREA,ready to move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,5,...,High,3453.0,57.750000,46.200000,False,False,1,Built-up Area ready to move,Whitefield,6.689835
13316,400.00,SUPER BUILT-UP AREA,ready to move,Richards Town,4 Bedroom,NaN,3600,5.0,NaN,4,...,High,3600.0,80.000000,100.000000,False,False,2,Super built-up Area ready to move,Richards,11.111111
13317,60.00,BUILT-UP AREA,ready to move,Raja Rajeshwari Nagar,2 Bedroom,Mahla T,1141,2.0,1.0,2,...,low,1141.0,30.000000,30.000000,False,False,3,Built-up Area ready to move,Raja,5.258545
13318,488.00,SUPER BUILT-UP AREA,18-jun,Padmanabhanagar,4 Bedroom,SollyCl,4689,4.0,1.0,4,...,High,4689.0,122.000000,122.000000,False,False,1,Super built-up Area 18-jun,Padmanabhanagar,10.407336
13319,17.00,SUPER BUILT-UP AREA,ready to move,Doddathoguru,1 Bedroom,NaN,550,1.0,1.0,1,...,low,550.0,17.000000,17.000000,False,False,1,Super built-up Area ready to move,Doddathoguru,3.090909

In [113]:
#55.Drop the column society if it exists.
df.drop(columns=["society"],inplace=True)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\1435818240.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["society"],inplace=True)

In [114]:
df

,price,area_type,availability,location,size,total_sqft,bath,balcony,bedroom,price_per_sqft,...,price_category,area_sqft,price_per_bath,price_per_room,large_balcony,contain_road,words_in_location,property_status,main_area,price_per_sqft_rounded
0,39.07,SUPER BUILT-UP AREA,19-dec,Electronic City Phase II,2 Bedroom,1056,2.0,1.0,2,3.699811e+05,...,low,1056.0,19.535000,19.535000,False,False,4,Super built-up Area 19-dec,Electronic,3.699811
1,120.00,PLOT AREA,ready to move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,4,4.615385e+05,...,High,2600.0,24.000000,30.000000,True,False,2,Plot Area ready to move,Chikka,4.615385
2,62.00,BUILT-UP AREA,ready to move,Uttarahalli,3 Bedroom,1440,2.0,3.0,3,4.305556e+05,...,low,1440.0,31.000000,20.666667,True,False,1,Built-up Area ready to move,Uttarahalli,4.305556
3,95.00,SUPER BUILT-UP AREA,ready to move,Lingadheeranahalli,3 Bedroom,1521,3.0,1.0,3,6.245891e+05,...,low,1521.0,31.666667,31.666667,False,False,1,Super built-up Area ready to move,Lingadheeranahalli,6.245891
4,51.00,SUPER BUILT-UP AREA,ready to move,Kothanur,2 Bedroom,1200,2.0,1.0,2,4.250000e+05,...,low,1200.0,25.500000,25.500000,False,False,1,Super built-up Area ready to move,Kothanur,4.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,231.00,BUILT-UP AREA,ready to move,Whitefield,5 Bedroom,3453,4.0,0.0,5,6.689835e+05,...,High,3453.0,57.750000,46.200000,False,False,1,Built-up Area ready to move,Whitefield,6.689835
13316,400.00,SUPER BUILT-UP AREA,ready to move,Richards Town,4 Bedroom,3600,5.0,NaN,4,1.111111e+06,...,High,3600.0,80.000000,100.000000,False,False,2,Super built-up Area ready to move,Richards,11.111111
13317,60.00,BUILT-UP AREA,ready to move,Raja Rajeshwari Nagar,2 Bedroom,1141,2.0,1.0,2,5.258545e+05,...,low,1141.0,30.000000,30.000000,False,False,3,Built-up Area ready to move,Raja,5.258545
13318,488.00,SUPER BUILT-UP AREA,18-jun,Padmanabhanagar,4 Bedroom,4689,4.0,1.0,4,1.040734e+06,...,High,4689.0,122.000000,122.000000,False,False,1,Super built-up Area 18-jun,Padmanabhanagar,10.407336
13319,17.00,SUPER BUILT-UP AREA,ready to move,Doddathoguru,1 Bedroom,550,1.0,1.0,1,3.090909e+05,...,low,550.0,17.000000,17.000000,False,False,1,Super built-up Area ready to move,Doddathoguru,3.090909

In [115]:
#56.Change all text in the availability column to title case.
df["availability"]=df["availability"].str.title()

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\3773213857.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["availability"]=df["availability"].str.title()

In [116]:
#57.Create a Boolean column multi_balcony where value is True if balcony &gt; 1.
df["multi_balcony"]=df["balcony"]>1

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\1675305387.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["multi_balcony"]=df["balcony"]>1

In [117]:
df

,price,area_type,availability,location,size,total_sqft,bath,balcony,bedroom,price_per_sqft,...,area_sqft,price_per_bath,price_per_room,large_balcony,contain_road,words_in_location,property_status,main_area,price_per_sqft_rounded,multi_balcony
0,39.07,SUPER BUILT-UP AREA,19-Dec,Electronic City Phase II,2 Bedroom,1056,2.0,1.0,2,3.699811e+05,...,1056.0,19.535000,19.535000,False,False,4,Super built-up Area 19-dec,Electronic,3.699811,False
1,120.00,PLOT AREA,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,4,4.615385e+05,...,2600.0,24.000000,30.000000,True,False,2,Plot Area ready to move,Chikka,4.615385,True
2,62.00,BUILT-UP AREA,Ready To Move,Uttarahalli,3 Bedroom,1440,2.0,3.0,3,4.305556e+05,...,1440.0,31.000000,20.666667,True,False,1,Built-up Area ready to move,Uttarahalli,4.305556,True
3,95.00,SUPER BUILT-UP AREA,Ready To Move,Lingadheeranahalli,3 Bedroom,1521,3.0,1.0,3,6.245891e+05,...,1521.0,31.666667,31.666667,False,False,1,Super built-up Area ready to move,Lingadheeranahalli,6.245891,False
4,51.00,SUPER BUILT-UP AREA,Ready To Move,Kothanur,2 Bedroom,1200,2.0,1.0,2,4.250000e+05,...,1200.0,25.500000,25.500000,False,False,1,Super built-up Area ready to move,Kothanur,4.250000,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,231.00,BUILT-UP AREA,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,5,6.689835e+05,...,3453.0,57.750000,46.200000,False,False,1,Built-up Area ready to move,Whitefield,6.689835,False
13316,400.00,SUPER BUILT-UP AREA,Ready To Move,Richards Town,4 Bedroom,3600,5.0,NaN,4,1.111111e+06,...,3600.0,80.000000,100.000000,False,False,2,Super built-up Area ready to move,Richards,11.111111,False
13317,60.00,BUILT-UP AREA,Ready To Move,Raja Rajeshwari Nagar,2 Bedroom,1141,2.0,1.0,2,5.258545e+05,...,1141.0,30.000000,30.000000,False,False,3,Built-up Area ready to move,Raja,5.258545,False
13318,488.00,SUPER BUILT-UP AREA,18-Jun,Padmanabhanagar,4 Bedroom,4689,4.0,1.0,4,1.040734e+06,...,4689.0,122.000000,122.000000,False,False,1,Super built-up Area 18-jun,Padmanabhanagar,10.407336,False
13319,17.00,SUPER BUILT-UP AREA,Ready To Move,Doddathoguru,1 Bedroom,550,1.0,1.0,1,3.090909e+05,...,550.0,17.000000,17.000000,False,False,1,Super built-up Area ready to move,Doddathoguru,3.090909,False

In [118]:
#58.Add a column indicating if total_sqft &gt; median of the dataset.
med_sqft=df["total_sqft"].mean()

In [119]:
df["total_sqft_bool"]=df["total_sqft"]>med_sqft

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\1004187404.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["total_sqft_bool"]=df["total_sqft"]>med_sqft

In [120]:
#59.Replace all occurrences of “Super built-up Area” with “SuperBuiltUp”.
df['area_type']=df['area_type'].str.replace("Super built-up  Area","SuperBuiltUp",case=False)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\1632302125.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['area_type']=df['area_type'].str.replace("Super built-up  Area","SuperBuiltUp",case=False)

In [121]:
df['area_type'].unique()

array(['SuperBuiltUp', 'PLOT  AREA', 'BUILT-UP  AREA', 'CARPET  AREA'],
      dtype=object)

In [122]:
#60.Create a column bath_to_room_ratio = bath / bedroom_count.
df["bath_to_room_ratio"]=df["bath"]/df["bedroom_count"]

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\1168653080.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bath_to_room_ratio"]=df["bath"]/df["bedroom_count"]

In [123]:
#61.Add a column with the total number of characters in each property’s location name.
df["words_in_location"]

0        4
1        2
2        1
3        1
4        1
        ..
13315    1
13316    2
13317    3
13318    1
13319    1
Name: words_in_location, Length: 12986, dtype: int64

In [124]:
#62.Create a column location_zone by extracting the first two letters of the location.
df["location_zone"]=df['location'].str[:2]

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\862511436.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["location_zone"]=df['location'].str[:2]

In [125]:
df

,price,area_type,availability,location,size,total_sqft,bath,balcony,bedroom,price_per_sqft,...,large_balcony,contain_road,words_in_location,property_status,main_area,price_per_sqft_rounded,multi_balcony,total_sqft_bool,bath_to_room_ratio,location_zone
0,39.07,SuperBuiltUp,19-Dec,Electronic City Phase II,2 Bedroom,1056,2.0,1.0,2,3.699811e+05,...,False,False,4,Super built-up Area 19-dec,Electronic,3.699811,False,False,1.000000,El
1,120.00,PLOT AREA,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,4,4.615385e+05,...,True,False,2,Plot Area ready to move,Chikka,4.615385,True,True,1.250000,Ch
2,62.00,BUILT-UP AREA,Ready To Move,Uttarahalli,3 Bedroom,1440,2.0,3.0,3,4.305556e+05,...,True,False,1,Built-up Area ready to move,Uttarahalli,4.305556,True,False,0.666667,Ut
3,95.00,SuperBuiltUp,Ready To Move,Lingadheeranahalli,3 Bedroom,1521,3.0,1.0,3,6.245891e+05,...,False,False,1,Super built-up Area ready to move,Lingadheeranahalli,6.245891,False,False,1.000000,Li
4,51.00,SuperBuiltUp,Ready To Move,Kothanur,2 Bedroom,1200,2.0,1.0,2,4.250000e+05,...,False,False,1,Super built-up Area ready to move,Kothanur,4.250000,False,False,1.000000,Ko
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,231.00,BUILT-UP AREA,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,5,6.689835e+05,...,False,False,1,Built-up Area ready to move,Whitefield,6.689835,False,True,0.800000,Wh
13316,400.00,SuperBuiltUp,Ready To Move,Richards Town,4 Bedroom,3600,5.0,NaN,4,1.111111e+06,...,False,False,2,Super built-up Area ready to move,Richards,11.111111,False,True,1.250000,Ri
13317,60.00,BUILT-UP AREA,Ready To Move,Raja Rajeshwari Nagar,2 Bedroom,1141,2.0,1.0,2,5.258545e+05,...,False,False,3,Built-up Area ready to move,Raja,5.258545,False,False,1.000000,Ra
13318,488.00,SuperBuiltUp,18-Jun,Padmanabhanagar,4 Bedroom,4689,4.0,1.0,4,1.040734e+06,...,False,False,1,Super built-up Area 18-jun,Padmanabhanagar,10.407336,False,True,1.000000,Pa
13319,17.00,SuperBuiltUp,Ready To Move,Doddathoguru,1 Bedroom,550,1.0,1.0,1,3.090909e+05,...,False,False,1,Super built-up Area ready to move,Doddathoguru,3.090909,False,False,1.000000,Do

In [126]:
#63.Rename multiple columns at once (size→bhk_type, bath→bathrooms).
df.rename(columns={"size":"bhk_type","bath":'bathrooms'},inplace=True)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\2844343397.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"size":"bhk_type","bath":'bathrooms'},inplace=True)

In [127]:
df

,price,area_type,availability,location,bhk_type,total_sqft,bathrooms,balcony,bedroom,price_per_sqft,...,large_balcony,contain_road,words_in_location,property_status,main_area,price_per_sqft_rounded,multi_balcony,total_sqft_bool,bath_to_room_ratio,location_zone
0,39.07,SuperBuiltUp,19-Dec,Electronic City Phase II,2 Bedroom,1056,2.0,1.0,2,3.699811e+05,...,False,False,4,Super built-up Area 19-dec,Electronic,3.699811,False,False,1.000000,El
1,120.00,PLOT AREA,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,4,4.615385e+05,...,True,False,2,Plot Area ready to move,Chikka,4.615385,True,True,1.250000,Ch
2,62.00,BUILT-UP AREA,Ready To Move,Uttarahalli,3 Bedroom,1440,2.0,3.0,3,4.305556e+05,...,True,False,1,Built-up Area ready to move,Uttarahalli,4.305556,True,False,0.666667,Ut
3,95.00,SuperBuiltUp,Ready To Move,Lingadheeranahalli,3 Bedroom,1521,3.0,1.0,3,6.245891e+05,...,False,False,1,Super built-up Area ready to move,Lingadheeranahalli,6.245891,False,False,1.000000,Li
4,51.00,SuperBuiltUp,Ready To Move,Kothanur,2 Bedroom,1200,2.0,1.0,2,4.250000e+05,...,False,False,1,Super built-up Area ready to move,Kothanur,4.250000,False,False,1.000000,Ko
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,231.00,BUILT-UP AREA,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,5,6.689835e+05,...,False,False,1,Built-up Area ready to move,Whitefield,6.689835,False,True,0.800000,Wh
13316,400.00,SuperBuiltUp,Ready To Move,Richards Town,4 Bedroom,3600,5.0,NaN,4,1.111111e+06,...,False,False,2,Super built-up Area ready to move,Richards,11.111111,False,True,1.250000,Ri
13317,60.00,BUILT-UP AREA,Ready To Move,Raja Rajeshwari Nagar,2 Bedroom,1141,2.0,1.0,2,5.258545e+05,...,False,False,3,Built-up Area ready to move,Raja,5.258545,False,False,1.000000,Ra
13318,488.00,SuperBuiltUp,18-Jun,Padmanabhanagar,4 Bedroom,4689,4.0,1.0,4,1.040734e+06,...,False,False,1,Super built-up Area 18-jun,Padmanabhanagar,10.407336,False,True,1.000000,Pa
13319,17.00,SuperBuiltUp,Ready To Move,Doddathoguru,1 Bedroom,550,1.0,1.0,1,3.090909e+05,...,False,False,1,Super built-up Area ready to move,Doddathoguru,3.090909,False,False,1.000000,Do

In [128]:
#64.Replace all “Plot Area” entries with “Land Area” in the area_type column.
df["area_type"]=df["area_type"].str.replace("plot  area","Land Area",case=False)

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\2431467407.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["area_type"]=df["area_type"].str.replace("plot  area","Land Area",case=False)

In [129]:
df["area_type"].unique()

array(['SuperBuiltUp', 'Land Area', 'BUILT-UP  AREA', 'CARPET  AREA'],
      dtype=object)

In [130]:
#65.Create a new column compact_house = True if total_sqft &lt; 1000.
df["compact_house"]=df['total_sqft']<1000

C:\Users\rames\AppData\Local\Temp\ipykernel_16020\229360555.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["compact_house"]=df['total_sqft']<1000

In [131]:
#66.Count how many properties exist per area_type.
df.groupby('area_type')["price"].count()

area_type
BUILT-UP  AREA    2386
CARPET  AREA        71
Land Area         1994
SuperBuiltUp      8535
Name: price, dtype: int64

In [132]:
#67.Find the average price for each area_type.
df.groupby('area_type')["price"].mean()

area_type
BUILT-UP  AREA    103.525704
CARPET  AREA       93.777324
Land Area         209.396028
SuperBuiltUp       92.179292
Name: price, dtype: float64

In [133]:
#68.Group by location and compute the mean price.
df.groupby('location')["price"].mean()

location
 Anekal                  16.000000
 Banaswadi               35.000000
 Basavangudi             50.000000
 Bhoganhalli             22.890000
 Devarabeesana Halli    124.833333
                           ...
t.c palya               160.000000
tc.palya                 60.750000
vinayakanagar           200.000000
white field,kadugodi    275.000000
whitefiled               32.730000
Name: price, Length: 1295, dtype: float64

In [134]:
#69.Find which location has the maximum average price_per_sqft.
df.columns

Index(['price', 'area_type', 'availability', 'location', 'bhk_type',
       'total_sqft', 'bathrooms', 'balcony', 'bedroom', 'price_per_sqft',
       'price_in_lakhs', 'bedroom_count', 'sqft_per_bathroom',
       'is_ready_to_move', 'price_category', 'area_sqft', 'price_per_bath',
       'price_per_room', 'large_balcony', 'contain_road', 'words_in_location',
       'property_status', 'main_area', 'price_per_sqft_rounded',
       'multi_balcony', 'total_sqft_bool', 'bath_to_room_ratio',
       'location_zone', 'compact_house'],
      dtype='object')

In [135]:
df.groupby('location')["price_per_sqft"].mean().idxmax()

'Grihalakshmi Layout'

In [136]:
#70.Compute total number of listings per availability status.
df.groupby('availability')["price"].count()

availability
14-Jul                      1
14-Nov                      1
15-Aug                      1
15-Dec                      1
15-Jun                      1
                        ...
22-Jun                     19
22-Mar                      3
22-Nov                      2
Immediate Possession        8
Ready To Move           10431
Name: price, Length: 80, dtype: int64

In [137]:
#71.Find the average number of bathrooms per area type.
df.groupby('area_type')["bathrooms"].mean()

area_type
BUILT-UP  AREA    2.635600
CARPET  AREA      2.535211
Land Area         3.906848
SuperBuiltUp      2.423045
Name: bathrooms, dtype: float64

In [138]:
#72.Determine how many houses have more than 3 bedrooms per area type.
bed=df[df["bedroom"]>3]

In [139]:
bed.groupby('area_type')['bedroom'].count()

area_type
BUILT-UP  AREA     452
CARPET  AREA         9
Land Area         1199
SuperBuiltUp       520
Name: bedroom, dtype: Int64

In [140]:
#73.For each availability type, get the minimum and maximum price.
df.groupby('availability')['price'].max()

availability
14-Jul                    43.71
14-Nov                    43.71
15-Aug                    62.00
15-Dec                   130.00
15-Jun                    97.00
                         ...
22-Jun                   146.00
22-Mar                    70.00
22-Nov                    79.15
Immediate Possession     460.00
Ready To Move           3600.00
Name: price, Length: 80, dtype: float64

In [141]:
df.groupby('availability')['price'].min()

availability
14-Jul                   43.71
14-Nov                   43.71
15-Aug                   62.00
15-Dec                  130.00
15-Jun                   97.00
                         ...
22-Jun                   41.00
22-Mar                   30.00
22-Nov                   77.59
Immediate Possession      8.44
Ready To Move             8.00
Name: price, Length: 80, dtype: float64

In [142]:
#74.Count the number of unique area_type values per availability group.
df.groupby(['availability','area_type'])['price'].count()

availability          area_type
14-Jul                BUILT-UP  AREA       1
14-Nov                BUILT-UP  AREA       1
15-Aug                BUILT-UP  AREA       1
15-Dec                BUILT-UP  AREA       1
15-Jun                BUILT-UP  AREA       1
                                        ...
Immediate Possession  Land Area            8
Ready To Move         BUILT-UP  AREA    2120
                      CARPET  AREA        61
                      Land Area         1770
                      SuperBuiltUp      6480
Name: price, Length: 147, dtype: int64

In [143]:
#75.Find which area_type has the most properties in “Ready To Move” condition.
av=df[df['availability']=='Ready To Move']

In [144]:
av.groupby('area_type')['price'].count().idxmax()

'SuperBuiltUp'

In [145]:
#76.Compute average price_per_sqft for each bedroom count.
df.groupby('bedroom_count')['price_per_sqft'].mean()

bedroom_count
1.0     6.669415e+05
2.0     5.179276e+05
3.0     6.566016e+05
4.0     1.972834e+06
5.0     1.379025e+06
6.0     1.258832e+06
7.0     3.457453e+06
8.0     1.306683e+06
9.0     1.309501e+06
10.0    1.620051e+06
11.0    9.091667e+05
12.0    1.344086e+06
13.0    5.069124e+05
14.0    1.000000e+06
16.0    5.500000e+05
18.0    1.666667e+06
19.0    2.450000e+06
27.0    2.875000e+05
43.0    2.750000e+06
Name: price_per_sqft, dtype: float64

In [146]:
#77.Group by location and find total number of houses with bath &gt; 2.
bath=df[df["bathrooms"]>2]

In [147]:
bath.groupby('location')['price'].count()

location
 Devarabeesana Halli    4
 Devarachikkanahalli    3
 south                  1
1 Annasandrapalya       1
1 Giri Nagar            1
                       ..
sarjapura main road     1
singapura paradise      1
t.c palya               1
vinayakanagar           1
white field,kadugodi    1
Name: price, Length: 969, dtype: int64

In [148]:
#78.Determine which location has the maximum number of 2 BHK houses.
df['bhk_type'].unique()

array(['2 Bedroom', '4 Bedroom', '3 Bedroom', '6 Bedroom', '1 Bedroom',
       '1 RK', '8 Bedroom', '7 Bedroom', '5 Bedroom', '11 Bedroom',
       '9 Bedroom', '27 Bedroom', '10 Bedroom', nan, '19 Bedroom',
       '16 Bedroom', '43 Bedroom', '14 Bedroom', '12 Bedroom',
       '13 Bedroom', '18 Bedroom'], dtype=object)

In [149]:
bhk=df[df["bhk_type"]=='2 Bedroom']

In [150]:
bhk.groupby('location')['price'].count().idxmax()

'Whitefield'

In [151]:
#79.For each area_type, count how many houses have balconies.
bal_n=df[~df["balcony"].isnull()]

In [152]:
bal=bal_n[bal_n['balcony']!=0]

In [153]:
bal.groupby('area_type')['price'].count()

area_type
BUILT-UP  AREA    1979
CARPET  AREA        57
Land Area         1449
SuperBuiltUp      8084
Name: price, dtype: int64

In [154]:
df.isnull().sum()

price                       0
area_type                   0
availability                0
location                    1
bhk_type                    8
total_sqft                  0
bathrooms                  16
balcony                   547
bedroom                     8
price_per_sqft              0
price_in_lakhs              0
bedroom_count               8
sqft_per_bathroom          16
is_ready_to_move            0
price_category              0
area_sqft                   0
price_per_bath             16
price_per_room              8
large_balcony               0
contain_road                0
words_in_location           0
property_status             0
main_area                   0
price_per_sqft_rounded      0
multi_balcony               0
total_sqft_bool             0
bath_to_room_ratio         16
location_zone               1
compact_house               0
dtype: int64

In [157]:
#80.Find the most common availability for 3 BHK houses.
bhk_3=df[df["bhk_type"]=="3 Bedroom"]

In [158]:
bhk_3

,price,area_type,availability,location,bhk_type,total_sqft,bathrooms,balcony,bedroom,price_per_sqft,...,contain_road,words_in_location,property_status,main_area,price_per_sqft_rounded,multi_balcony,total_sqft_bool,bath_to_room_ratio,location_zone,compact_house
2,62.00,BUILT-UP AREA,Ready To Move,Uttarahalli,3 Bedroom,1440,2.0,3.0,3,430555.555556,...,False,1,Built-up Area ready to move,Uttarahalli,4.305556,True,False,0.666667,Ut,False
3,95.00,SuperBuiltUp,Ready To Move,Lingadheeranahalli,3 Bedroom,1521,3.0,1.0,3,624589.086128,...,False,1,Super built-up Area ready to move,Lingadheeranahalli,6.245891,False,False,1.000000,Li,False
8,63.25,SuperBuiltUp,Ready To Move,Marathahalli,3 Bedroom,1310,3.0,1.0,3,482824.427481,...,False,1,Super built-up Area ready to move,Marathahalli,4.828244,False,False,1.000000,Ma,False
10,70.00,SuperBuiltUp,18-Feb,Whitefield,3 Bedroom,1800,2.0,2.0,3,388888.888889,...,False,1,Super built-up Area 18-feb,Whitefield,3.888889,True,True,0.666667,Wh,False
14,148.00,Land Area,Ready To Move,Sarjapur,3 Bedroom,2250,3.0,2.0,3,657777.777778,...,False,1,Plot Area ready to move,Sarjapur,6.577778,True,True,1.000000,Sa,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13307,134.00,BUILT-UP AREA,Ready To Move,Billekahalli,3 Bedroom,1805,3.0,3.0,3,742382.271468,...,False,1,Built-up Area ready to move,Billekahalli,7.423823,True,True,1.000000,Bi,False
13308,142.00,BUILT-UP AREA,Ready To Move,Bannerghatta Road,3 Bedroom,1527,3.0,1.0,3,929927.963327,...,True,2,Built-up Area ready to move,Bannerghatta,9.299280,False,False,1.000000,Ba,False
13309,92.13,SuperBuiltUp,Ready To Move,Yeshwanthpur,3 Bedroom,1675,3.0,NaN,3,550029.850746,...,False,1,Super built-up Area ready to move,Yeshwanthpur,5.500299,False,True,1.000000,Ye,False
13313,57.00,SuperBuiltUp,Ready To Move,Uttarahalli,3 Bedroom,1345,2.0,1.0,3,423791.821561,...,False,1,Super built-up Area ready to move,Uttarahalli,4.237918,False,False,0.666667,Ut,False
13314,112.00,SuperBuiltUp,Ready To Move,Green Glen Layout,3 Bedroom,1715,3.0,3.0,3,653061.224490,...,False,3,Super built-up Area ready to move,Green,6.530612,True,True,1.000000,Gr,False

In [159]:
bhk_3["availability"].max()

'Ready To Move'

In [161]:
#81.Group by both area_type and availability and find average price.
df.groupby(["area_type","availability"])["price"].mean()

area_type       availability
BUILT-UP  AREA  14-Jul            43.710000
                14-Nov            43.710000
                15-Aug            62.000000
                15-Dec           130.000000
                15-Jun            97.000000
                                    ...
SuperBuiltUp    22-Jan            65.166667
                22-Jun           107.224737
                22-Mar            49.000000
                22-Nov            78.370000
                Ready To Move     91.414941
Name: price, Length: 147, dtype: float64

In [163]:
#82.Count how many houses in each location have a price greater than 1 crore.
price_1=df[df["price"]>1]

In [164]:
price_1.groupby("location")['price'].count()

location
 Anekal                 1
 Banaswadi              1
 Basavangudi            1
 Bhoganhalli            1
 Devarabeesana Halli    6
                       ..
t.c palya               1
tc.palya                4
vinayakanagar           1
white field,kadugodi    1
whitefiled              1
Name: price, Length: 1295, dtype: int64

In [165]:
#83.For each bedroom count, compute average and median price_per_sqft.
df.groupby('bedroom_count')['price_per_sqft'].mean()

bedroom_count
1.0     6.669415e+05
2.0     5.179276e+05
3.0     6.566016e+05
4.0     1.972834e+06
5.0     1.379025e+06
6.0     1.258832e+06
7.0     3.457453e+06
8.0     1.306683e+06
9.0     1.309501e+06
10.0    1.620051e+06
11.0    9.091667e+05
12.0    1.344086e+06
13.0    5.069124e+05
14.0    1.000000e+06
16.0    5.500000e+05
18.0    1.666667e+06
19.0    2.450000e+06
27.0    2.875000e+05
43.0    2.750000e+06
Name: price_per_sqft, dtype: float64

In [166]:
df.groupby('bedroom_count')['price_per_sqft'].median()

bedroom_count
1.0     5.187831e+05
2.0     4.801903e+05
3.0     5.588235e+05
4.0     8.760965e+05
5.0     1.041667e+06
6.0     1.153846e+06
7.0     1.212406e+06
8.0     1.210227e+06
9.0     1.233696e+06
10.0    1.367794e+06
11.0    9.850000e+05
12.0    1.344086e+06
13.0    5.069124e+05
14.0    1.000000e+06
16.0    5.500000e+05
18.0    1.666667e+06
19.0    2.450000e+06
27.0    2.875000e+05
43.0    2.750000e+06
Name: price_per_sqft, dtype: float64

In [168]:
#84.Find which location has the least number of listings.
df.groupby('location')['price'].count().idxmin()

' Anekal'

In [170]:
#85.Find top 5 locations with the highest average price.
df.groupby('location')['price'].mean().sort_values(ascending=False).head()

location
Cubbon Road       1900.000000
Ashok Nagar       1486.000000
Defence Colony    1167.714286
Yemlur            1093.388889
Church Street     1068.000000
Name: price, dtype: float64

In [171]:
#86.Count listings for each combination of (location, area_type).
df.groupby(['location','area_type'])['price'].count()

location              area_type
 Anekal               BUILT-UP  AREA    1
 Banaswadi            SuperBuiltUp      1
 Basavangudi          SuperBuiltUp      1
 Bhoganhalli          SuperBuiltUp      1
 Devarabeesana Halli  BUILT-UP  AREA    1
                                       ..
t.c palya             Land Area         1
tc.palya              Land Area         4
vinayakanagar         SuperBuiltUp      1
white field,kadugodi  Land Area         1
whitefiled            SuperBuiltUp      1
Name: price, Length: 2301, dtype: int64

In [172]:
#87.Get the total sum of price grouped by availability.
df.groupby('availability')['price'].sum()

availability
14-Jul                       43.71
14-Nov                       43.71
15-Aug                       62.00
15-Dec                      130.00
15-Jun                       97.00
                           ...
22-Jun                     2037.27
22-Mar                      147.00
22-Nov                      156.74
Immediate Possession       1088.27
Ready To Move           1198779.87
Name: price, Length: 80, dtype: float64

In [173]:
#88.For each location, calculate the maximum number of balconies.
df.groupby('location')['balcony'].max()

location
 Anekal                 1.0
 Banaswadi              0.0
 Basavangudi            1.0
 Bhoganhalli            0.0
 Devarabeesana Halli    3.0
                       ...
t.c palya               3.0
tc.palya                1.0
vinayakanagar           2.0
white field,kadugodi    NaN
whitefiled              1.0
Name: balcony, Length: 1295, dtype: float64

In [174]:
#89.Determine which area type has the largest total square footage.
df.groupby('area_type')['total_sqft'].sum().idxmax()

'SuperBuiltUp'

In [177]:
#90.Group by availability and count how many listings have more than 2 bathrooms.
bath=df[df['bathrooms']>2]

In [178]:
bath.groupby('availability')['bathrooms'].count()

availability
14-Nov              1
15-Nov              2
15-Oct              2
16-Dec              3
16-Jan              1
                 ...
22-Dec              2
22-Jan              2
22-Jun              8
22-Nov              2
Ready To Move    4441
Name: bathrooms, Length: 71, dtype: int64

In [175]:
df.columns

Index(['price', 'area_type', 'availability', 'location', 'bhk_type',
       'total_sqft', 'bathrooms', 'balcony', 'bedroom', 'price_per_sqft',
       'price_in_lakhs', 'bedroom_count', 'sqft_per_bathroom',
       'is_ready_to_move', 'price_category', 'area_sqft', 'price_per_bath',
       'price_per_room', 'large_balcony', 'contain_road', 'words_in_location',
       'property_status', 'main_area', 'price_per_sqft_rounded',
       'multi_balcony', 'total_sqft_bool', 'bath_to_room_ratio',
       'location_zone', 'compact_house'],
      dtype='object')

In [179]:
#91.For each bedroom count, find the average total_sqft.
df.groupby('bedroom_count')['total_sqft'].mean()

bedroom_count
1.0       754.911960
2.0      1138.333578
3.0      1675.740413
4.0      2695.295252
5.0      2371.904899
6.0      2040.100457
7.0      2309.750000
8.0      1922.056818
9.0      2928.557692
10.0     3411.142857
11.0     3350.000000
12.0     2232.000000
13.0     5425.000000
14.0     1250.000000
16.0    10000.000000
18.0     1200.000000
19.0     2000.000000
27.0     8000.000000
43.0     2400.000000
Name: total_sqft, dtype: float64

In [180]:
#92.Group by location and get the count of unique area_type values.
df.groupby('location')['area_type'].nunique()

location
 Anekal                 1
 Banaswadi              1
 Basavangudi            1
 Bhoganhalli            1
 Devarabeesana Halli    2
                       ..
t.c palya               1
tc.palya                1
vinayakanagar           1
white field,kadugodi    1
whitefiled              1
Name: area_type, Length: 1295, dtype: int64

In [182]:
#93.Find which location has the highest total price sum.
df.groupby('location')['price'].sum().idxmax()

'Whitefield'

In [183]:
#94.For each area_type, find the listing with the highest price_per_sqft.
df.groupby('area_type')['price_per_sqft'].max()

area_type
BUILT-UP  AREA    2.300000e+08
CARPET  AREA      2.000000e+07
Land Area         1.200000e+09
SuperBuiltUp      5.600000e+06
Name: price_per_sqft, dtype: float64

In [185]:
#95.Count number of properties where bath equals bedroom_count for each area type.
bath_bed=df[df['bathrooms']==df['bedroom_count']]

In [186]:
bath_bed.groupby('area_type')['bathrooms'].count()

area_type
BUILT-UP  AREA    1846
CARPET  AREA        56
Land Area         1185
SuperBuiltUp      6764
Name: bathrooms, dtype: int64

In [187]:
df.groupby('area_type')['bathrooms'].apply(lambda x: (x == df.loc[x.index, 'bedroom_count']).sum())

area_type
BUILT-UP  AREA    1846
CARPET  AREA        56
Land Area         1185
SuperBuiltUp      6764
Name: bathrooms, dtype: int64

In [188]:
#96.Group by bedroom count and find average number of balconies.
df.groupby('bedroom_count')['balcony'].mean()

bedroom_count
1.0     0.829146
2.0     1.443745
3.0     1.836909
4.0     1.743913
5.0     1.648464
6.0     1.815789
7.0     1.976471
8.0     1.701493
9.0     1.939394
10.0    3.000000
11.0    2.000000
12.0    2.000000
13.0    0.000000
14.0    0.000000
16.0         NaN
18.0         NaN
19.0         NaN
27.0    0.000000
43.0    0.000000
Name: balcony, dtype: float64

In [189]:
#97.Group by both area_type and location to compute total price.
df.groupby(['area_type','location'])['price'].sum()

area_type       location
BUILT-UP  AREA   Anekal                  16.00
                 Devarabeesana Halli    149.00
                 Devarachikkanahalli     47.00
                 Electronic City         46.50
                 Mysore Highway          17.00
                                         ...
SuperBuiltUp    rr nagar                 60.00
                sapthagiri Layout       115.00
                sarjapura main road     250.00
                vinayakanagar           200.00
                whitefiled               32.73
Name: price, Length: 2301, dtype: float64

In [190]:
#98.Find which availability category contributes the highest overall total price.
df.groupby('availability')['price'].sum().idxmax()

'Ready To Move'