In [309]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv('matches.csv')

In [3]:
df2=pd.read_csv('deliveries.csv')

In [4]:
df1

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [5]:
df2

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [6]:
merge_df=pd.merge(df1,df2,left_on='id',right_on='match_id',how='inner')

In [7]:
merge_df

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [8]:
#1. Join matches and deliveries to find total balls bowled per match.
merge_df.groupby('id')['ball'].count()

id
335982     225
335983     248
335984     219
335985     246
335986     240
          ...
1426307    247
1426309    208
1426310    241
1426311    251
1426312    184
Name: ball, Length: 1095, dtype: int64

In [9]:
#2. For each match, get total runs scored by joining matches and deliveries.
merge_df.groupby('id')['total_runs'].sum()

id
335982     304
335983     447
335984     261
335985     331
335986     222
          ...
1426307    429
1426309    323
1426310    346
1426311    314
1426312    227
Name: total_runs, Length: 1095, dtype: int64

In [10]:
#3. Find the top 10 highest-scoring matches.
merge_df.groupby('id')['total_runs'].sum().sort_values(ascending=False).head(10)

id
1426268    549
1422126    523
1426280    523
1426281    504
419137     469
1426273    465
1136604    459
1359512    458
1082641    453
1216527    449
Name: total_runs, dtype: int64

In [11]:
df1[df1['id']==1426268]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1053,1426268,2024,Bengaluru,2024-04-15,League,TM Head,"M Chinnaswamy Stadium, Bengaluru",Sunrisers Hyderabad,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Sunrisers Hyderabad,runs,25.0,288.0,20.0,N,NaN,AK Chaudhary,R Pandit

In [12]:
#4. Find the number of wickets per match using join.
merge_df['is_wicket'].unique()

array([0, 1])

In [13]:
wic=merge_df[merge_df['is_wicket']==1]

In [14]:
wic.groupby('id')['is_wicket'].count()

id
335982     13
335983      9
335984      9
335985     12
335986     15
           ..
1426307    11
1426309    12
1426310    14
1426311    16
1426312    12
Name: is_wicket, Length: 1095, dtype: int64

In [15]:
#5. List matches where more than 15 wides were bowled.
merge_df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2', 'match_id', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [16]:
merge_df['ball'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
wide=merge_df[merge_df["extras_type"]=='wides']

In [18]:
wide_count=wide.groupby('id')['extras_type'].count().reset_index()

In [19]:
wide_count[wide_count["extras_type"]>15]

           id  extras_type
36     336018           18
66     392190           16
197    501221           16
317    548377           19
473    829737           20
508    829811           16
740   1178423           16
782   1216522           18
823   1254069           16
874   1304049           19
901   1304076           19
909   1304084           17
923   1304098           16
951   1359480           16
987   1359516           19
1020  1422119           17
1035  1422134           18
1049  1426268           24
1050  1426269           18
1069  1426288           18
1084  1426305           18

In [20]:
#6. Find the player with the most deliveries faced across all matches.
merge_df.groupby('batter')['ball'].count().idxmax()

'V Kohli'

In [21]:
#merge_df[merge_df['batter']=='V Kohli']

In [22]:
#7. Find total boundaries (4s &amp; 6s) per match by joining datasets.
merge_df['total_runs'].unique()

array([1, 0, 4, 6, 5, 2, 3, 7])

In [23]:
boundry=merge_df[(merge_df['batsman_runs']==4) | (merge_df['batsman_runs']==6)]

In [24]:
boundry.groupby('id')['batsman_runs'].count()

id
335982     35
335983     63
335984     36
335985     44
335986     21
           ..
1426307    57
1426309    45
1426310    46
1426311    38
1426312    27
Name: batsman_runs, Length: 1095, dtype: int64

In [25]:
#8. Combine matches and deliveries to compute strike rate of each batsman in each match.
g1=merge_df.groupby(['id','batter'])['batsman_runs'].sum().reset_index()

In [26]:
g2=merge_df.groupby(['id','batter'])['ball'].count().reset_index()

In [27]:
no_ext=merge_df[merge_df["extras_type"].isnull()]

In [28]:
no_ext.groupby(['id','batter'])['ball'].count().reset_index()

            id         batter  ball
0       335982      AA Noffke    10
1       335982        B Akhil     2
2       335982    BB McCullum    71
3       335982       CL White    10
4       335982      DJ Hussey    12
...        ...            ...   ...
16455  1426312      SP Narine     2
16456  1426312        SS Iyer     3
16457  1426312  Shahbaz Ahmed     7
16458  1426312        TM Head     1
16459  1426312        VR Iyer    24

[16460 rows x 3 columns]

In [29]:
merg=pd.concat([g1,g2],axis=1)

In [30]:
merg

            id         batter  batsman_runs       id         batter  ball
0       335982      AA Noffke             9   335982      AA Noffke    12
1       335982        B Akhil             0   335982        B Akhil     2
2       335982    BB McCullum           158   335982    BB McCullum    77
3       335982       CL White             6   335982       CL White    10
4       335982      DJ Hussey            12   335982      DJ Hussey    12
...        ...            ...           ...      ...            ...   ...
16510  1426312      SP Narine             6  1426312      SP Narine     2
16511  1426312        SS Iyer             6  1426312        SS Iyer     3
16512  1426312  Shahbaz Ahmed             8  1426312  Shahbaz Ahmed     7
16513  1426312        TM Head             0  1426312        TM Head     1
16514  1426312        VR Iyer            52  1426312        VR Iyer    27

[16515 rows x 6 columns]

In [31]:
merg['st_r']=(merg['batsman_runs']/merg['ball'])*100

In [32]:
merg

,id,batter,batsman_runs,id,batter,ball,st_r
0,335982,AA Noffke,9,335982,AA Noffke,12,75.000000
1,335982,B Akhil,0,335982,B Akhil,2,0.000000
2,335982,BB McCullum,158,335982,BB McCullum,77,205.194805
3,335982,CL White,6,335982,CL White,10,60.000000
4,335982,DJ Hussey,12,335982,DJ Hussey,12,100.000000
...,...,...,...,...,...,...,...
16510,1426312,SP Narine,6,1426312,SP Narine,2,300.000000
16511,1426312,SS Iyer,6,1426312,SS Iyer,3,200.000000
16512,1426312,Shahbaz Ahmed,8,1426312,Shahbaz Ahmed,7,114.285714
16513,1426312,TM Head,0,1426312,TM Head,1,0.000000
16514,1426312,VR Iyer,52,1426312,VR Iyer,27,192.592593

In [33]:
merg[merg['ball'].isnull()].count()

id              0
batter          0
batsman_runs    0
id              0
batter          0
ball            0
st_r            0
dtype: int64

In [34]:
#9. For each season, get total runs scored (join matches → deliveries).
merge_df['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022',
       '2023', '2024'], dtype=object)

In [35]:
merge_df.groupby('season')['total_runs'].sum()

season
2007/08    17937
2009       16353
2009/10    18883
2011       21154
2012       22453
2013       22602
2014       18931
2015       18353
2016       18862
2017       18786
2018       19901
2019       19434
2020/21    19416
2021       18637
2022       24395
2023       25688
2024       25971
Name: total_runs, dtype: int64

In [36]:
#10. For each season, find total wickets taken.
merge_df.groupby('season')['is_wicket'].sum()

season
2007/08    690
2009       698
2009/10    725
2011       813
2012       858
2013       912
2014       674
2015       691
2016       666
2017       711
2018       722
2019       685
2020/21    677
2021       717
2022       912
2023       916
2024       883
Name: is_wicket, dtype: int64

In [37]:
#11. Find bowlers who conceded more than 50 runs in a match.
bowler=merge_df.groupby(['id','bowler'])['total_runs'].sum().reset_index()

In [38]:
bowler

            id         bowler  total_runs
0       335982      AA Noffke          41
1       335982     AB Agarkar          25
2       335982       AB Dinda           9
3       335982       CL White          24
4       335982       I Sharma          13
...        ...            ...         ...
12973  1426312     PJ Cummins          18
12974  1426312      SP Narine          20
12975  1426312  Shahbaz Ahmed          28
12976  1426312    T Natarajan          29
12977  1426312       VG Arora          26

[12978 rows x 3 columns]

In [39]:
bowler[bowler['total_runs']>50]

            id               bowler  total_runs
5       335982            JH Kallis          52
14      335983             JR Hopes          54
87      335989             JDP Oram          53
92      335989           P Amarnath          57
98      335990             MM Patel          55
...        ...                  ...         ...
12827  1426297      Simarjeet Singh          60
12857  1426300        Kuldeep Yadav          53
12875  1426302        Naveen-ul-Haq          51
12913  1426306            SN Thakur          62
12923  1426307  Nithish Kumar Reddy          54

[283 rows x 3 columns]

In [40]:
#12. For each match, find the dismissal types that occurred.
merge_df['dismissal_kind'].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field', 'retired out'], dtype=object)

In [41]:
merge_df.groupby('id')['dismissal_kind'].unique()

id
335982                        [nan, caught, bowled, run out]
335983                            [nan, caught, bowled, lbw]
335984                   [nan, caught, run out, lbw, bowled]
335985     [nan, caught, retired hurt, run out, stumped, ...
335986                   [nan, caught, bowled, run out, lbw]
                                 ...
1426307                       [nan, caught, run out, bowled]
1426309                  [nan, bowled, caught, run out, lbw]
1426310              [nan, caught, bowled, stumped, run out]
1426311                       [nan, caught, bowled, run out]
1426312                           [nan, bowled, caught, lbw]
Name: dismissal_kind, Length: 1095, dtype: object

In [42]:
#13. Find batsmen who scored more than 30 runs in a single over.
merge_df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2', 'match_id', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [43]:
merge_df['inning'].unique()

array([1, 2, 3, 4, 5, 6])

In [44]:
batter_g=merge_df.groupby(['id','batting_team','over','batter'])['total_runs'].sum().reset_index()

In [45]:
batter_g

            id           batting_team  over       batter  total_runs
0       335982  Kolkata Knight Riders     0  BB McCullum           2
1       335982  Kolkata Knight Riders     0   SC Ganguly           1
2       335982  Kolkata Knight Riders     1  BB McCullum          18
3       335982  Kolkata Knight Riders     2  BB McCullum           5
4       335982  Kolkata Knight Riders     2   SC Ganguly           1
...        ...                    ...   ...          ...         ...
89427  1426312    Sunrisers Hyderabad    16   PJ Cummins           9
89428  1426312    Sunrisers Hyderabad    17      B Kumar           0
89429  1426312    Sunrisers Hyderabad    17   JD Unadkat           1
89430  1426312    Sunrisers Hyderabad    17   PJ Cummins           4
89431  1426312    Sunrisers Hyderabad    18   PJ Cummins           0

[89432 rows x 5 columns]

In [46]:
batter_g[batter_g['total_runs']>30]

            id                 batting_team  over      batter  total_runs
12012   419139        Kolkata Knight Riders    12    CH Gayle          31
18093   501247  Royal Challengers Bangalore     2    CH Gayle          37
37065   734047          Chennai Super Kings     5    SK Raina          33
67811  1254076          Chennai Super Kings    19   RA Jadeja          37
72357  1304060        Kolkata Knight Riders    15  PJ Cummins          35
85242  1422138               Mumbai Indians    19  R Shepherd          32
86856  1426278               Delhi Capitals    19     RR Pant          31

In [47]:
#14. For each batting team, compute total runs in each match.
merge_df.groupby(['id','batting_team'])['total_runs'].sum()

id       batting_team
335982   Kolkata Knight Riders          222
         Royal Challengers Bangalore     82
335983   Chennai Super Kings            240
         Kings XI Punjab                207
335984   Delhi Daredevils               132
                                       ...
1426310  Royal Challengers Bengaluru    172
1426311  Rajasthan Royals               139
         Sunrisers Hyderabad            175
1426312  Kolkata Knight Riders          114
         Sunrisers Hyderabad            113
Name: total_runs, Length: 2187, dtype: int64

In [48]:
#15. For each bowling team, compute total runs conceded in each match.
merge_df.groupby(['id','bowling_team'])['total_runs'].sum()

id       bowling_team
335982   Kolkata Knight Riders           82
         Royal Challengers Bangalore    222
335983   Chennai Super Kings            207
         Kings XI Punjab                240
335984   Delhi Daredevils               129
                                       ...
1426310  Royal Challengers Bengaluru    174
1426311  Rajasthan Royals               175
         Sunrisers Hyderabad            139
1426312  Kolkata Knight Riders          113
         Sunrisers Hyderabad            114
Name: total_runs, Length: 2187, dtype: int64

In [49]:
#16. Identify matches where the winning team scored more runs in powerplay (overs 1–6).
power=merge_df[(merge_df['over']<6)]

In [50]:
power.groupby(['id','winner'])['total_runs'].sum().idxmax()

(np.int64(1426273), 'Sunrisers Hyderabad')

In [51]:
#17. For each match, find the bowler with the most dot balls.
dot=merge_df[merge_df["total_runs"]==0]

In [52]:
dot.groupby(['id','bowler'])['ball'].count()

id       bowler
335982   AA Noffke         6
         AB Agarkar       15
         AB Dinda         11
         I Sharma         10
         JH Kallis         8
                          ..
1426312  PJ Cummins        7
         SP Narine         8
         Shahbaz Ahmed     4
         T Natarajan       2
         VG Arora          8
Name: ball, Length: 12649, dtype: int64

In [53]:
#18. For each match, find the batsman with the highest strike rate (min 10 balls).
merg

,id,batter,batsman_runs,id,batter,ball,st_r
0,335982,AA Noffke,9,335982,AA Noffke,12,75.000000
1,335982,B Akhil,0,335982,B Akhil,2,0.000000
2,335982,BB McCullum,158,335982,BB McCullum,77,205.194805
3,335982,CL White,6,335982,CL White,10,60.000000
4,335982,DJ Hussey,12,335982,DJ Hussey,12,100.000000
...,...,...,...,...,...,...,...
16510,1426312,SP Narine,6,1426312,SP Narine,2,300.000000
16511,1426312,SS Iyer,6,1426312,SS Iyer,3,200.000000
16512,1426312,Shahbaz Ahmed,8,1426312,Shahbaz Ahmed,7,114.285714
16513,1426312,TM Head,0,1426312,TM Head,1,0.000000
16514,1426312,VR Iyer,52,1426312,VR Iyer,27,192.592593

In [54]:
merg[(merg['ball']>9)].max()

id                 1426312
batter              Z Khan
batsman_runs           175
id                 1426312
batter              Z Khan
ball                    77
st_r            383.333333
dtype: object

In [55]:
#19. Calculate the economy of each bowler per season (join deliveries → matches).
s1=merge_df.groupby(['season','bowler'])['ball'].count().reset_index()

In [56]:
s1['over']=s1['ball']//6

In [57]:
s1

       season             bowler  ball  over
0     2007/08           A Kumble   236    39
1     2007/08           A Mishra   123    20
2     2007/08            A Nehra   280    46
3     2007/08              A Nel    18     3
4     2007/08          A Symonds    44     7
...       ...                ...   ...   ...
1943     2024  Washington Sundar    30     5
1944     2024          YS Chahal   362    60
1945     2024         Yash Dayal   322    53
1946     2024        Yash Thakur   225    37
1947     2024      Yudhvir Singh    24     4

[1948 rows x 4 columns]

In [58]:
s2=merge_df.groupby(['season','bowler'])['total_runs'].sum().reset_index()

In [59]:
con=pd.concat([s1,s2],axis=1)

In [60]:
con

,season,bowler,ball,over,season,bowler,total_runs
0,2007/08,A Kumble,236,39,2007/08,A Kumble,314
1,2007/08,A Mishra,123,20,2007/08,A Mishra,140
2,2007/08,A Nehra,280,46,2007/08,A Nehra,357
3,2007/08,A Nel,18,3,2007/08,A Nel,31
4,2007/08,A Symonds,44,7,2007/08,A Symonds,106
...,...,...,...,...,...,...,...
1943,2024,Washington Sundar,30,5,2024,Washington Sundar,73
1944,2024,YS Chahal,362,60,2024,YS Chahal,548
1945,2024,Yash Dayal,322,53,2024,Yash Dayal,472
1946,2024,Yash Thakur,225,37,2024,Yash Thakur,405
1947,2024,Yudhvir Singh,24,4,2024,Yudhvir Singh,52

In [61]:
con['economy']=con['total_runs']/con['over']

In [62]:
con

,season,bowler,ball,over,season,bowler,total_runs,economy
0,2007/08,A Kumble,236,39,2007/08,A Kumble,314,8.051282
1,2007/08,A Mishra,123,20,2007/08,A Mishra,140,7.000000
2,2007/08,A Nehra,280,46,2007/08,A Nehra,357,7.760870
3,2007/08,A Nel,18,3,2007/08,A Nel,31,10.333333
4,2007/08,A Symonds,44,7,2007/08,A Symonds,106,15.142857
...,...,...,...,...,...,...,...,...
1943,2024,Washington Sundar,30,5,2024,Washington Sundar,73,14.600000
1944,2024,YS Chahal,362,60,2024,YS Chahal,548,9.133333
1945,2024,Yash Dayal,322,53,2024,Yash Dayal,472,8.905660
1946,2024,Yash Thakur,225,37,2024,Yash Thakur,405,10.945946
1947,2024,Yudhvir Singh,24,4,2024,Yudhvir Singh,52,13.000000

In [63]:
#20. Find bowlers who bowled maiden overs in a match.
merge_df.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [64]:
maiden=merge_df.groupby(['id','batting_team','over','bowler'])['total_runs'].sum().reset_index()

In [65]:
maiden[maiden['total_runs']==0]

            id                 batting_team  over         bowler  total_runs
94      335984             Rajasthan Royals     2     GD McGrath           0
155     335986              Deccan Chargers     3       I Sharma           0
382     335991               Mumbai Indians    19      IK Pathan           0
412     335992  Royal Challengers Bangalore    11       SK Warne           0
583     335997        Kolkata Knight Riders    13  ST Jayasuriya           0
...        ...                          ...   ...            ...         ...
41607  1426292         Lucknow Super Giants    16   Harshit Rana           0
41611  1426293               Mumbai Indians     3     PJ Cummins           0
41883  1426300               Delhi Capitals    19     Yash Dayal           0
42242  1426312          Sunrisers Hyderabad    14   Harshit Rana           0
42246  1426312          Sunrisers Hyderabad    18     AD Russell           0

[331 rows x 5 columns]

In [66]:
#21. For each match, find the over with the most runs.
maiden.groupby(['id'])['total_runs'].max()

id
335982     24
335983     25
335984     14
335985     20
335986     20
           ..
1426307    22
1426309    22
1426310    19
1426311    19
1426312    20
Name: total_runs, Length: 1095, dtype: int64

In [67]:
#22. For each match, identify bowlers who took multiple wickets.
mul_w=merge_df.groupby(['id','bowler'])['is_wicket'].sum().reset_index()

In [68]:
mul_w[mul_w['is_wicket']>1]

            id         bowler  is_wicket
1       335982     AB Agarkar          3
2       335982       AB Dinda          2
9       335982     SC Ganguly          3
12      335983      IK Pathan          2
27      335984    MF Maharoof          2
...        ...            ...        ...
12962  1426311  Shahbaz Ahmed          3
12964  1426311       TA Boult          3
12966  1426312     AD Russell          3
12970  1426312   Harshit Rana          2
12972  1426312       MA Starc          2

[3560 rows x 3 columns]

In [69]:
#23. Get number of balls faced by each batsman in winning matches only.
merge_df.groupby(['id','winner','batter'])['ball'].count().reset_index()

            id                 winner         batter  ball
0       335982  Kolkata Knight Riders      AA Noffke    12
1       335982  Kolkata Knight Riders        B Akhil     2
2       335982  Kolkata Knight Riders    BB McCullum    77
3       335982  Kolkata Knight Riders       CL White    10
4       335982  Kolkata Knight Riders      DJ Hussey    12
...        ...                    ...            ...   ...
16470  1426312  Kolkata Knight Riders      SP Narine     2
16471  1426312  Kolkata Knight Riders        SS Iyer     3
16472  1426312  Kolkata Knight Riders  Shahbaz Ahmed     7
16473  1426312  Kolkata Knight Riders        TM Head     1
16474  1426312  Kolkata Knight Riders        VR Iyer    27

[16475 rows x 4 columns]

In [70]:
#24. Total extras conceded by each team per season.
extras=merge_df[~merge_df['extras_type'].isnull()]

In [71]:
extras.groupby(['season','bowling_team'])['ball'].count()

season   bowling_team
2007/08  Chennai Super Kings            133
         Deccan Chargers                111
         Delhi Daredevils                99
         Kings XI Punjab                114
         Kolkata Knight Riders          112
                                       ...
2024     Mumbai Indians                 124
         Punjab Kings                   104
         Rajasthan Royals               101
         Royal Challengers Bengaluru    119
         Sunrisers Hyderabad            118
Name: ball, Length: 146, dtype: int64

In [72]:
#25. Identify umpires officiating in matches with &gt;200 total runs.
umpire=merge_df.groupby(['id','batting_team','umpire1','umpire2'])['total_runs'].sum().reset_index()

In [73]:
umpire[umpire['total_runs']>200]

,id,batting_team,umpire1,umpire2,total_runs
0,335982,Kolkata Knight Riders,Asad Rauf,RE Koertzen,222
2,335983,Chennai Super Kings,MR Benson,SL Shastri,240
3,335983,Kings XI Punjab,MR Benson,SL Shastri,207
14,335989,Chennai Super Kings,DJ Harper,GA Pratapkumar,208
15,335989,Mumbai Indians,DJ Harper,GA Pratapkumar,202
...,...,...,...,...,...
2169,1426302,Delhi Capitals,A Totre,Vinod Seshan,208
2173,1426305,Lucknow Super Giants,Navdeep Singh,R Pandit,214
2176,1426306,Royal Challengers Bengaluru,A Totre,KN Ananthapadmanabhan,218
2177,1426307,Punjab Kings,Nitin Menon,VK Sharma,214
2178,1426307,Sunrisers Hyderabad,Nitin Menon,VK Sharma,215

In [74]:
#26. Find the batsman who scored the highest runs in matches won by chasing.
merge_df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2', 'match_id', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [75]:
inn_2=merge_df[merge_df['inning']==2]

In [76]:
bat=inn_2.groupby(['id','inning','batting_team','winner','batter'])['total_runs'].sum().reset_index()

In [77]:
win=bat[bat['batting_team']==bat['winner']]

In [78]:
win.loc[win['total_runs'].idxmax()]

id                           1426277
inning                             2
batting_team    Lucknow Super Giants
winner          Lucknow Super Giants
batter                    MP Stoinis
total_runs                       129
Name: 7850, dtype: object

In [79]:
#27. For each match, show total runs in 1st innings vs 2nd innings.
inn_1v2=merge_df[(merge_df['inning']==1) | (merge_df['inning']==2)]

In [80]:
inn_1v2.groupby(['id','inning'])['total_runs'].sum()

id       inning
335982   1         222
         2          82
335983   1         240
         2         207
335984   1         129
                  ...
1426310  2         174
1426311  1         175
         2         139
1426312  1         113
         2         114
Name: total_runs, Length: 2187, dtype: int64

In [81]:
#28. Identify matches where total 6s &gt; total 4s.
boundry4=merge_df[(merge_df['batsman_runs']==4)]

In [82]:
b1=boundry4.groupby(['id'])['batsman_runs'].count().reset_index()

In [83]:
boundry6=merge_df[(merge_df['total_runs']==6)]

In [84]:
b2=boundry6.groupby(['id'])['total_runs'].count().reset_index()

In [85]:
con=pd.concat([b1,b2],axis=1)

In [86]:
con

           id  batsman_runs       id  total_runs
0      335982            18   335982          17
1      335983            38   335983          25
2      335984            32   335984           4
3      335985            33   335985          11
4      335986            11   335986          10
...       ...           ...      ...         ...
1090  1426307            31  1426307          25
1091  1426309            29  1426309          16
1092  1426310            33  1426310          13
1093  1426311            24  1426311          14
1094  1426312            18  1426312           9

[1095 rows x 4 columns]

In [87]:
con[con['total_runs']>con['batsman_runs']]

           id  batsman_runs       id  total_runs
256    548314            14   548314          16
584   1082598            17  1082598          20
617   1082632            24  1082632          31
640   1136565            20  1136565          30
659   1136584            18  1136584          33
760   1216496            18  1216496          31
795   1216531            14  1216531          22
874   1254116            11  1254116          12
878   1304049            20  1304049          27
944   1304115            17  1304115          21
973   1359498            24  1359498          33
982   1359507            28  1359507          30
1026  1422121            25  1422121          28
1031  1422126            31  1422126          38
1033  1422128            20  1422128          24
1038  1422133            21  1422133          22
1065  1426280            37  1426280          42

In [88]:
#29. For each match, find the highest scoring batsman in the last 5 overs.
last5=merge_df[(merge_df['over']>14) & (merge_df['over']<20)]

In [89]:
score=last5.groupby(['id','batter'])['batsman_runs'].sum().reset_index()

In [90]:
score.loc[score.groupby('id')['batsman_runs'].idxmax()]

           id       batter  batsman_runs
0      335982  BB McCullum            59
7      335983   MEK Hussey            42
10     335984   D Salunkhe            18
18     335985   MV Boucher            31
22     335986    DJ Hussey            20
...       ...          ...           ...
8157  1426307    JM Sharma            32
8164  1426309   PJ Cummins            27
8168  1426310    MK Lomror            24
8173  1426311  Dhruv Jurel            32
8182  1426312   PJ Cummins            15

[1083 rows x 3 columns]

In [91]:
#30. Get bowlers who delivered more than 100 balls in a season.
merge_df.groupby(['season','bowler'])['ball'].count()

season   bowler
2007/08  A Kumble             236
         A Mishra             123
         A Nehra              280
         A Nel                 18
         A Symonds             44
                             ...
2024     Washington Sundar     30
         YS Chahal            362
         Yash Dayal           322
         Yash Thakur          225
         Yudhvir Singh         24
Name: ball, Length: 1948, dtype: int64

In [92]:
bowlers=merge_df.groupby(['season','bowler']).size().reset_index(name='balls')

In [93]:
bowlers[bowlers['balls']>100]

       season       bowler  balls
0     2007/08     A Kumble    236
1     2007/08     A Mishra    123
2     2007/08      A Nehra    280
6     2007/08   AB Agarkar    168
7     2007/08     AB Dinda    245
...       ...          ...    ...
1935     2024     UT Yadav    129
1939     2024     VG Arora    201
1944     2024    YS Chahal    362
1945     2024   Yash Dayal    322
1946     2024  Yash Thakur    225

[962 rows x 3 columns]

In [94]:
#31. For each match, list the number of reviews taken (if present in data).
merge_df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2', 'match_id', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [95]:
#32. For each team, find wins where they scored more than 180 runs.
win=merge_df[merge_df['batting_team']==merge_df['winner']]

In [96]:
new=win.groupby(['id','winner'])['total_runs'].sum().reset_index()

In [97]:
new

           id                       winner  total_runs
0      335982        Kolkata Knight Riders         222
1      335983          Chennai Super Kings         240
2      335984             Delhi Daredevils         132
3      335985  Royal Challengers Bangalore         166
4      335986        Kolkata Knight Riders         112
...       ...                          ...         ...
1085  1426307          Sunrisers Hyderabad         215
1086  1426309        Kolkata Knight Riders         164
1087  1426310             Rajasthan Royals         174
1088  1426311          Sunrisers Hyderabad         175
1089  1426312        Kolkata Knight Riders         114

[1090 rows x 3 columns]

In [98]:
one80=new[new['total_runs']>180]

In [99]:
one80.groupby('winner').size()

winner
Chennai Super Kings            46
Deccan Chargers                 5
Delhi Capitals                 20
Delhi Daredevils               21
Gujarat Lions                   4
Gujarat Titans                 12
Kings XI Punjab                29
Kochi Tuskers Kerala            1
Kolkata Knight Riders          33
Lucknow Super Giants           12
Mumbai Indians                 48
Pune Warriors                   1
Punjab Kings                   11
Rajasthan Royals               40
Rising Pune Supergiant          1
Royal Challengers Bangalore    36
Royal Challengers Bengaluru     5
Sunrisers Hyderabad            27
dtype: int64

In [100]:
#33. For each match, find the bowler who conceded most boundaries.
boundry['batsman_runs'].unique()

array([4, 6])

In [101]:
mb=boundry.groupby(['id','bowler']).size().reset_index(name='bound')

In [102]:
mb.loc[mb.groupby(['id'])['bound'].idxmax()]

            id               bowler  bound
3       335982            JH Kallis      8
12      335983             JR Hopes      8
21      335984             B Geeves      8
35      335985            JH Kallis      8
45      335986            DJ Hussey      5
...        ...                  ...    ...
12197  1426307  Nithish Kumar Reddy      8
12210  1426309           PJ Cummins      7
12225  1426310           Yash Dayal      8
12229  1426311              B Kumar      6
12245  1426312          T Natarajan      5

[1095 rows x 3 columns]

In [103]:
#34. Identify matches where first innings score &lt; 120 but team won.
inn1=merge_df[(merge_df['inning']==1) & (merge_df['batting_team']==merge_df['winner'])]

In [104]:
inn1['inning'].unique()

array([1])

In [105]:
total=inn1.groupby(['id','winner'])['total_runs'].sum().reset_index()

In [106]:
total[total['total_runs']>180]

          id                       winner  total_runs
0     335982        Kolkata Knight Riders         222
1     335983          Chennai Super Kings         240
2     335989          Chennai Super Kings         208
3     335991              Kings XI Punjab         182
5     335998             Delhi Daredevils         191
..       ...                          ...         ...
493  1426297               Gujarat Titans         231
495  1426300  Royal Challengers Bengaluru         187
496  1426302               Delhi Capitals         208
497  1426305         Lucknow Super Giants         214
498  1426306  Royal Challengers Bengaluru         218

[239 rows x 3 columns]

In [107]:
#35. For each season, find the total number of matches that went to the last over.
last_over=merge_df[(merge_df['over']==19) & (merge_df['ball']==1)]

In [108]:
last_over

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
118,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,Mohammad Hafeez,6,0,6,NaN,0,NaN,NaN,NaN
343,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,JR Hopes,MEK Hussey,6,0,6,NaN,0,NaN,NaN,NaN
467,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,Joginder Sharma,IK Pathan,1,0,1,NaN,0,NaN,NaN,NaN
589,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,GD McGrath,SK Trivedi,4,0,4,NaN,0,NaN,NaN,NaN
809,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,Z Khan,SM Pollock,1,0,1,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260035,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,Atharva Taide,Abdul Samad,4,0,4,NaN,0,NaN,NaN,NaN
260157,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,AD Russell,PJ Cummins,3,0,3,NaN,0,NaN,NaN,NaN
260360,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,Sandeep Sharma,KV Sharma,1,0,1,NaN,0,NaN,NaN,NaN
260605,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,Avesh Khan,PJ Cummins,0,0,0,NaN,0,NaN,NaN,NaN
260730,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,T Natarajan,TA Boult,0,0,0,NaN,0,NaN,NaN,NaN

In [109]:
data=last_over.groupby(['season','id'])['id'].count().reset_index(name='number')

In [110]:
merge_df['ball'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [111]:
data.groupby(['season']).size()

season
2007/08    51
2009       55
2009/10    59
2011       67
2012       71
2013       75
2014       57
2015       55
2016       57
2017       56
2018       55
2019       58
2020/21    60
2021       59
2022       71
2023       73
2024       68
dtype: int64

In [112]:
#36. For each match, find total leg-byes conceded.
legbyes=merge_df[merge_df['extras_type']=="legbyes"]

In [113]:
merge_df['extras_type'].unique()

array(['legbyes', nan, 'wides', 'byes', 'noballs', 'penalty'],
      dtype=object)

In [114]:
legbyes.groupby(['id']).size()

id
335982     9
335983     6
335984     3
335985     3
335986     9
          ..
1426307    7
1426309    3
1426310    3
1426311    2
1426312    3
Length: 1059, dtype: int64

In [115]:
#37. Find teams that conceded more wides than no-balls.
wides=merge_df[merge_df['extras_type']=="wides"]
noball=merge_df[merge_df['extras_type']=="noballs"]

In [116]:
t_wides=wides.groupby(['bowling_team']).size().reset_index(name='wides')

In [117]:
t_no=noball.groupby(['bowling_team']).size().reset_index(name='noballs')

In [118]:
con=pd.concat([t_wides,t_no],axis=1)

In [119]:
con[con['wides']>con['noballs']]

                   bowling_team  wides                 bowling_team  noballs
0           Chennai Super Kings    946          Chennai Super Kings       97
1               Deccan Chargers    280              Deccan Chargers       49
2                Delhi Capitals    387               Delhi Capitals       47
3              Delhi Daredevils    550             Delhi Daredevils       86
4                 Gujarat Lions     91                Gujarat Lions        7
5                Gujarat Titans    149               Gujarat Titans       12
6               Kings XI Punjab    720              Kings XI Punjab      100
7          Kochi Tuskers Kerala     52         Kochi Tuskers Kerala        7
8         Kolkata Knight Riders    848        Kolkata Knight Riders      135
9          Lucknow Super Giants    193         Lucknow Super Giants       24
10               Mumbai Indians   1090               Mumbai Indians      144
11                Pune Warriors    120                Pune Warriors       26
12                 Punjab Kings    234                 Punjab Kings       24
13             Rajasthan Royals    949             Rajasthan Royals      104
14       Rising Pune Supergiant     62       Rising Pune Supergiant        1
15      Rising Pune Supergiants     56      Rising Pune Supergiants        4
16  Royal Challengers Bangalore    951  Royal Challengers Bangalore      128
17  Royal Challengers Bengaluru     85  Royal Challengers Bengaluru        6
18          Sunrisers Hyderabad    617          Sunrisers Hyderabad       68

In [120]:
#38. For each batsman, find highest runs against a specific team.
spec=merge_df[merge_df['bowling_team']=='Chennai Super Kings']

In [121]:
spec.groupby(['batter'])['total_runs'].sum().idxmax()

'S Dhawan'

In [122]:
batter=merge_df.groupby(['bowling_team','batter'])['batsman_runs'].sum().reset_index()

In [123]:
batter.loc[batter.groupby(['bowling_team'])['batsman_runs'].idxmax()]

                     bowling_team        batter  batsman_runs
319           Chennai Super Kings      S Dhawan          1057
547               Deccan Chargers      R Dravid           339
674                Delhi Capitals  Ishan Kishan           436
1107             Delhi Daredevils       V Kohli           761
1139                Gujarat Lions     DA Warner           336
1324               Gujarat Titans    RD Gaikwad           350
1441              Kings XI Punjab     DA Warner           906
1757         Kochi Tuskers Kerala  SR Tendulkar           100
1859        Kolkata Knight Riders     DA Warner          1093
2209         Lucknow Super Giants  F du Plessis           238
2504               Mumbai Indians      KL Rahul           954
2767                Pune Warriors      CH Gayle           383
3031                 Punjab Kings       V Kohli           349
3400             Rajasthan Royals       V Kohli           764
3477       Rising Pune Supergiant      PA Patel           108
3580      Rising Pune Supergiants       V Kohli           188
3674  Royal Challengers Bangalore     DA Warner           861
4063  Royal Challengers Bengaluru       TM Head           103
4338          Sunrisers Hyderabad     SV Samson           801

In [124]:
#39. List bowlers taking wicket on the first delivery of an over.
bowl=merge_df[(merge_df['ball']==1) & (merge_df['is_wicket']==1)]

In [125]:
bowl.groupby(['bowler']).size().reset_index()

             bowler   0
0    A Ashish Reddy   3
1        A Chandila   1
2       A Choudhary   3
3          A Kamboj   1
4          A Kumble   9
..              ...  ..
328      Yash Dayal   5
329     Yash Thakur   2
330   Yudhvir Singh   2
331    Yuvraj Singh   6
332          Z Khan  15

[333 rows x 2 columns]

In [126]:
#40. For each match, find the over with the most wides.
wides=merge_df[merge_df['extras_type']=="wides"]

In [127]:
total=wides.groupby(['id','inning','over']).size().reset_index(name='wides')

In [128]:
total.loc[total.groupby(['id'])['wides'].idxmax()]

           id  inning  over  wides
6      335982       2     6      2
13     335983       1    12      2
17     335984       1     0      1
30     335985       2    13      2
32     335986       1     1      2
...       ...     ...   ...    ...
7065  1426307       1    13      1
7075  1426309       1     1      1
7084  1426310       2    10      2
7088  1426311       1    14      2
7095  1426312       1     3      3

[1091 rows x 4 columns]

In [129]:
#41. For each match, find the bowler who bowled the final over.
last_over['ball'].unique()

array([1])

In [130]:
last_over.groupby(['id','bowler','inning']).size().reset_index(name='total_over')

           id               bowler  inning  total_over
0      335982              P Kumar       1           1
1      335983             JR Hopes       1           1
2      335983      Joginder Sharma       2           1
3      335984           GD McGrath       1           1
4      335985          DS Kulkarni       2           1
...       ...                  ...     ...         ...
1693  1426307  Nithish Kumar Reddy       1           1
1694  1426309           AD Russell       1           1
1695  1426310       Sandeep Sharma       1           1
1696  1426311           Avesh Khan       1           1
1697  1426311          T Natarajan       2           1

[1698 rows x 4 columns]

In [131]:
#42. Identify the match with the most extras conceded by losing team.
losing=merge_df[(~merge_df['extras_type'].isnull()) & (merge_df['bowling_team']!=merge_df['winner'])]

In [132]:
losing.groupby(['id','bowling_team']).size().reset_index(name='extras_count').max()

id                          1426312
bowling_team    Sunrisers Hyderabad
extras_count                     18
dtype: object

In [133]:
#43. For each venue, find the average match score.
venue=merge_df.groupby(['venue','id','inning'])['total_runs'].sum().reset_index()

In [134]:
venue.groupby(['venue'])['total_runs'].mean()

venue
Arun Jaitley Stadium                                                     151.433333
Arun Jaitley Stadium, Delhi                                              190.343750
Barabati Stadium                                                         162.714286
Barsapara Cricket Stadium, Guwahati                                      169.833333
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow    159.037037
Brabourne Stadium                                                        174.050000
Brabourne Stadium, Mumbai                                                171.294118
Buffalo Park                                                             133.166667
De Beers Diamond Oval                                                    149.500000
Dr DY Patil Sports Academy                                               141.470588
Dr DY Patil Sports Academy, Mumbai                                       164.325000
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                      144.076923
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam       200.000000
Dubai International Cricket Stadium                                      144.500000
Eden Gardens                                                             153.623377
Eden Gardens, Kolkata                                                    190.156250
Feroz Shah Kotla                                                         154.798319
Green Park                                                               162.250000
Himachal Pradesh Cricket Association Stadium                             160.944444
Himachal Pradesh Cricket Association Stadium, Dharamsala                 189.375000
Holkar Cricket Stadium                                                   159.555556
JSCA International Stadium Complex                                       146.857143
Kingsmead                                                                145.100000
M Chinnaswamy Stadium                                                    154.679389
M Chinnaswamy Stadium, Bengaluru                                         190.071429
M.Chinnaswamy Stadium                                                    170.900000
MA Chidambaram Stadium                                                   142.388889
MA Chidambaram Stadium, Chepauk                                          155.887755
MA Chidambaram Stadium, Chepauk, Chennai                                 152.862069
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur       167.500000
Maharashtra Cricket Association Stadium                                  159.250000
Maharashtra Cricket Association Stadium, Pune                            158.000000
Narendra Modi Stadium, Ahmedabad                                         169.791667
Nehru Stadium                                                            136.300000
New Wanderers Stadium                                                    143.250000
Newlands                                                                 112.312500
OUTsurance Oval                                                          132.250000
Punjab Cricket Association IS Bindra Stadium                             173.800000
Punjab Cricket Association IS Bindra Stadium, Mohali                     161.136364
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh         185.600000
Punjab Cricket Association Stadium, Mohali                               156.957143
Rajiv Gandhi International Stadium                                       154.366667
Rajiv Gandhi International Stadium, Uppal                                148.880000
Rajiv Gandhi International Stadium, Uppal, Hyderabad                     182.423077
Sardar Patel Stadium, Motera                                             144.884615
Saurashtra Cricket Association Stadium                                   151.500000
Sawai Mansingh Stadium                                                   151.744681
Sawai Mansingh Stadium, Jaipur                                           171.050000
Shaheed Veer Narayan Singh International Stadium                         145.083333
Sharjah Cricket Stadium                                                  153.267857
Sheikh Zayed Stadium                                                     142.854839
St George's Park                                                         145.214286
Subrata Roy Sahara Stadium                                               141.500000
SuperSport Park                                                          152.208333
Vidarbha Cricket Association Stadium, Jamtha                             147.000000
Wankhede Stadium                                                         158.155405
Wankhede Stadium, Mumbai                                                 173.188889
Zayed Cricket Stadium, Abu Dhabi                                         154.687500
Name: total_runs, dtype: float64

In [135]:
#44. For each match, find the partnership with the most runs.

In [136]:
#45. Get number of players dismissed “caught” in each match.
merge_df['dismissal_kind'].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field', 'retired out'], dtype=object)

In [137]:
caught=merge_df[merge_df['dismissal_kind']=='caught']

In [138]:
caught.groupby(['id']).size()

id
335982      9
335983      6
335984      2
335985      7
335986     11
           ..
1426307     8
1426309     7
1426310    10
1426311    12
1426312     8
Length: 1094, dtype: int64

In [139]:
#46. For each match, find overs without any boundaries.
df2

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [140]:
without_b=merge_df[(merge_df['extras_type'].isnull()) & (merge_df['batsman_runs']!=4) & (merge_df['batsman_runs']!=6)]

In [141]:
dff=without_b.groupby(['id','inning','over']).size().reset_index(name='balls')

In [142]:
count=dff[dff['balls']==6]

In [143]:
count.groupby(['id']).size()

id
335982     11
335983      5
335984      9
335985     10
335986     18
           ..
1426307     7
1426309     6
1426310    13
1426311    14
1426312     9
Length: 1094, dtype: int64

In [144]:
#47. Identify matches with hat-tricks (three wickets in three balls).

In [145]:
#48. For each team, find matches where they defended &lt;150 successfully.
runs=merge_df[(merge_df['result']=='runs') & (merge_df['inning']==1)]

In [146]:
runs['winner']

0         Kolkata Knight Riders
1         Kolkata Knight Riders
2         Kolkata Knight Riders
3         Kolkata Knight Riders
4         Kolkata Knight Riders
                  ...
260607      Sunrisers Hyderabad
260608      Sunrisers Hyderabad
260609      Sunrisers Hyderabad
260610      Sunrisers Hyderabad
260611      Sunrisers Hyderabad
Name: winner, Length: 61766, dtype: object

In [147]:
defend=runs.groupby(['id','batting_team'])['total_runs'].sum().reset_index()

In [148]:
count=defend[defend['total_runs']<150]

In [149]:
count.groupby(['batting_team']).size().reset_index(name='numbers')

                   batting_team  numbers
0           Chennai Super Kings        8
1               Deccan Chargers        6
2                Delhi Capitals        2
3              Delhi Daredevils        2
4                Gujarat Titans        2
5               Kings XI Punjab        9
6          Kochi Tuskers Kerala        1
7         Kolkata Knight Riders        7
8                Mumbai Indians        9
9                 Pune Warriors        1
10                 Punjab Kings        1
11             Rajasthan Royals        3
12       Rising Pune Supergiant        1
13  Royal Challengers Bangalore        6
14          Sunrisers Hyderabad       10

In [150]:
#49. For each bowler, find matches where they took a wicket with a yorker (if subtype exists).

In [151]:
#50. For each match, compare runs scored in odd overs vs even overs.
compare=merge_df.groupby(['id','inning','over'])['total_runs'].sum().reset_index()

In [152]:
even=compare[(compare['over']+1)%2==0]

In [153]:
odd=compare[(compare['over']+1)%2!=0]

In [154]:
d1=even.groupby(['id'])['total_runs'].sum().reset_index(name='even_total')

In [155]:
d2=odd.groupby(['id'])['total_runs'].sum().reset_index(name='odd_total')

In [156]:
pd.concat([d1,d2],axis=1)

           id  even_total       id  odd_total
0      335982         141   335982        163
1      335983         234   335983        213
2      335984         138   335984        123
3      335985         150   335985        181
4      335986         103   335986        119
...       ...         ...      ...        ...
1090  1426307         235  1426307        194
1091  1426309         164  1426309        159
1092  1426310         184  1426310        162
1093  1426311         146  1426311        168
1094  1426312         111  1426312        116

[1095 rows x 4 columns]

In [157]:
pd.merge(d1,d2,left_on='id',right_on='id',how='inner')

           id  even_total  odd_total
0      335982         141        163
1      335983         234        213
2      335984         138        123
3      335985         150        181
4      335986         103        119
...       ...         ...        ...
1090  1426307         235        194
1091  1426309         164        159
1092  1426310         184        162
1093  1426311         146        168
1094  1426312         111        116

[1095 rows x 3 columns]

In [158]:
df1

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [159]:
#51. Count matches per season.
df1.groupby(['season']).size().reset_index(name='matches')

     season  matches
0   2007/08       58
1      2009       57
2   2009/10       60
3      2011       73
4      2012       74
5      2013       76
6      2014       60
7      2015       59
8      2016       60
9      2017       59
10     2018       60
11     2019       60
12  2020/21       60
13     2021       60
14     2022       74
15     2023       74
16     2024       71

In [160]:
#52. Find number of matches each team has won.
df1.groupby('winner').size()

winner
Chennai Super Kings            138
Deccan Chargers                 29
Delhi Capitals                  48
Delhi Daredevils                67
Gujarat Lions                   13
Gujarat Titans                  28
Kings XI Punjab                 88
Kochi Tuskers Kerala             6
Kolkata Knight Riders          131
Lucknow Super Giants            24
Mumbai Indians                 144
Pune Warriors                   12
Punjab Kings                    24
Rajasthan Royals               112
Rising Pune Supergiant          10
Rising Pune Supergiants          5
Royal Challengers Bangalore    116
Royal Challengers Bengaluru      7
Sunrisers Hyderabad             88
dtype: int64

In [161]:
#53. Compute number of toss wins per team.
df1.groupby('toss_winner').size()

toss_winner
Chennai Super Kings            122
Deccan Chargers                 43
Delhi Capitals                  50
Delhi Daredevils                80
Gujarat Lions                   15
Gujarat Titans                  22
Kings XI Punjab                 85
Kochi Tuskers Kerala             8
Kolkata Knight Riders          122
Lucknow Super Giants            19
Mumbai Indians                 143
Pune Warriors                   20
Punjab Kings                    24
Rajasthan Royals               120
Rising Pune Supergiant           6
Rising Pune Supergiants          7
Royal Challengers Bangalore    113
Royal Challengers Bengaluru      8
Sunrisers Hyderabad             88
dtype: int64

In [162]:
#54. Find most frequent “toss_decision” per team.
df1.groupby(['toss_decision','toss_winner']).size().idxmax()

('field', 'Mumbai Indians')

In [163]:
#55. Identify venues with the most matches.
df1.groupby(['venue']).size().idxmax()

'Eden Gardens'

In [164]:
#56. Calculate average margin of victory per season.
df1.groupby(['season'])['result_margin'].mean()

season
2007/08    15.965517
2009       16.857143
2009/10    19.762712
2011       18.930556
2012       16.229730
2013       19.837838
2014       14.728814
2015       17.821429
2016       15.333333
2017       17.103448
2018       14.350000
2019       15.210526
2020/21    22.589286
2021       13.576271
2022       16.972973
2023       19.246575
2024       17.873239
Name: result_margin, dtype: float64

In [165]:
#57. Count matches decided by runs vs wickets per season.
df1['result'].unique()

array(['runs', 'wickets', 'tie', 'no result'], dtype=object)

In [166]:
matches=df1[(df1['result']=='runs') | (df1['result']=='wickets')]

In [167]:
matches.groupby(['result']).size()

result
runs       498
wickets    578
dtype: int64

In [168]:
#58. Find the team winning the most tosses per season.
season=df1.groupby(['season','toss_winner']).size().reset_index(name='num')

In [169]:
season.loc[season.groupby(['season'])['num'].idxmax()]

      season                  toss_winner  num
6    2007/08             Rajasthan Royals   11
9       2009              Deccan Chargers   10
16   2009/10          Chennai Super Kings   10
27      2011              Kings XI Punjab   10
39      2012               Mumbai Indians   11
46      2013        Kolkata Knight Riders   12
52      2014          Chennai Super Kings   10
60      2015          Chennai Super Kings   10
75      2016          Sunrisers Hyderabad   10
80      2017               Mumbai Indians   11
84      2018          Chennai Super Kings   11
92      2019          Chennai Super Kings   12
107  2020/21          Sunrisers Hyderabad   11
114     2021  Royal Challengers Bangalore   10
118     2022               Gujarat Titans   10
126     2023          Chennai Super Kings   10
143     2024             Rajasthan Royals   11

In [170]:
#59. For each venue, get highest number of wins by a single team.
venues=df1.groupby(['venue','winner']).size().reset_index(name='wins')

In [171]:
venues.loc[venues.groupby(['venue'])['wins'].idxmax()]

,venue,winner,wins
1,Arun Jaitley Stadium,Delhi Capitals,4
8,"Arun Jaitley Stadium, Delhi",Delhi Capitals,6
14,Barabati Stadium,Deccan Chargers,3
17,"Barsapara Cricket Stadium, Guwahati",Punjab Kings,2
22,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,7
27,Brabourne Stadium,Mumbai Indians,5
31,"Brabourne Stadium, Mumbai",Delhi Capitals,4
38,Buffalo Park,Chennai Super Kings,1
41,De Beers Diamond Oval,Chennai Super Kings,1
48,Dr DY Patil Sports Academy,Mumbai Indians,5
52,"Dr DY Patil Sports Academy, Mumbai",Chennai Super Kings,3
69,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Sunrisers Hyderabad,3
70,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Delhi Capitals,1
72,Dubai International Cricket Stadium,Chennai Super Kings,9
88,Eden Gardens,Kolkata Knight Riders,45
96,"Eden Gardens, Kolkata",Kolkata Knight Riders,7
104,Feroz Shah Kotla,Delhi Daredevils,23
116,Green Park,Gujarat Lions,2
121,Himachal Pradesh Cricket Association Stadium,Kings XI Punjab,5
122,"Himachal Pradesh Cricket Association Stadium, ...",Chennai Super Kings,1
126,Holkar Cricket Stadium,Kings XI Punjab,4
131,JSCA International Stadium Complex,Chennai Super Kings,3
138,Kingsmead,Delhi Daredevils,3
152,M Chinnaswamy Stadium,Royal Challengers Bangalore,29
159,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bengaluru,4
166,M.Chinnaswamy Stadium,Royal Challengers Bangalore,8
167,MA Chidambaram Stadium,Chennai Super Kings,7
169,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,33
178,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai Super Kings,10
187,Maharaja Yadavindra Singh International Cricke...,Gujarat Titans,1
192,Maharashtra Cricket Association Stadium,Chennai Super Kings,5
202,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,3
210,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,9
218,Nehru Stadium,Kochi Tuskers Kerala,2
224,New Wanderers Stadium,Royal Challengers Bangalore,3
225,Newlands,Deccan Chargers,2
231,OUTsurance Oval,Delhi Daredevils,1
233,Punjab Cricket Association IS Bindra Stadium,Kings XI Punjab,8
237,"Punjab Cricket Association IS Bindra Stadium, ...",Kings XI Punjab,4
242,"Punjab Cricket Association IS Bindra Stadium, ...",Gujarat Titans,1
249,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,18
260,Rajiv Gandhi International Stadium,Sunrisers Hyderabad,10
272,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,20
280,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,6
284,"Sardar Patel Stadium, Motera",Rajasthan Royals,7
288,Saurashtra Cricket Association Stadium,Gujarat Lions,3
300,Sawai Mansingh Stadium,Rajasthan Royals,32
305,"Sawai Mansingh Stadium, Jaipur",Rajasthan Royals,5
308,Shaheed Veer Narayan Singh International Stadium,Delhi Daredevils,4
315,Sharjah Cricket Stadium,Kolkata Knight Riders,5
324,Sheikh Zayed Stadium,Kolkata Knight Riders,6
329,St George's Park,Chennai Super Kings,2
340,Subrata Roy Sahara Stadium,Pune Warriors,4
343,SuperSport Park,Chennai Super Kings,2
350,"Vidarbha Cricket Association Stadium, Jamtha",Deccan Chargers,2
360,Wankhede Stadium,Mumbai Indians,42
372,"Wankhede Stadium, Mumbai",Mumbai Indians,10
379,"Zayed Cricket Stadium, Abu Dhabi",Kolkata Knight Riders,2

In [172]:
#60. Find umpires officiating in the most matches.
u1=df1.groupby(['umpire1']).size().reset_index(name='count1')

In [173]:
u2=df1.groupby(['umpire2']).size().reset_index(name='count2')

In [174]:
total=pd.merge(u1,u2,left_on='umpire1',right_on='umpire2',how='inner')

In [175]:
total['total_matches']=total['count1']+total['count2']

In [176]:
total

,umpire1,count1,umpire2,count2,total_matches
0,A Deshmukh,9,A Deshmukh,3,12
1,A Nand Kishore,24,A Nand Kishore,13,37
2,AK Chaudhary,115,AK Chaudhary,16,131
3,AM Saheba,4,AM Saheba,22,26
4,AV Jayaprakash,2,AV Jayaprakash,4,6
5,AY Dandekar,30,AY Dandekar,2,32
6,BF Bowden,36,BF Bowden,1,37
7,BG Jerling,13,BG Jerling,4,17
8,BNJ Oxenford,36,BNJ Oxenford,28,64
9,BR Doctrove,34,BR Doctrove,8,42
10,C Shamshuddin,28,C Shamshuddin,60,88
11,CB Gaffaney,53,CB Gaffaney,24,77
12,CK Nandan,16,CK Nandan,43,59
13,DJ Harper,9,DJ Harper,18,27
14,GR Sadashiv Iyer,3,GR Sadashiv Iyer,9,12
15,HAS Khalid,8,HAS Khalid,10,18
16,HDPK Dharmasena,79,HDPK Dharmasena,19,98
17,IJ Gould,4,IJ Gould,2,6
18,IL Howell,7,IL Howell,7,14
19,J Madanagopal,20,J Madanagopal,6,26
20,JD Cloete,16,JD Cloete,1,17
21,K Hariharan,10,K Hariharan,11,21
22,K Srinath,2,K Srinath,13,15
23,K Srinivasan,2,K Srinivasan,7,9
24,KN Ananthapadmanabhan,59,KN Ananthapadmanabhan,13,72
25,M Erasmus,42,M Erasmus,25,67
26,MA Gough,9,MA Gough,12,21
27,MR Benson,10,MR Benson,2,12
28,MV Saidharshan Kumar,3,MV Saidharshan Kumar,12,15
29,NA Patwardhan,5,NA Patwardhan,15,20
30,NJ Llong,17,NJ Llong,20,37
31,Navdeep Singh,9,Navdeep Singh,10,19
32,Nitin Menon,50,Nitin Menon,54,104
33,PG Pathak,7,PG Pathak,9,16
34,PR Reiffel,7,PR Reiffel,21,28
35,R Pandit,9,R Pandit,13,22
36,RE Koertzen,20,RE Koertzen,21,41
37,RJ Tucker,9,RJ Tucker,53,62
38,RK Illingworth,14,RK Illingworth,25,39
39,S Asnani,19,S Asnani,11,30
40,S Das,10,S Das,5,15
41,S Ravi,48,S Ravi,83,131
42,SD Fry,5,SD Fry,1,6
43,SJ Davis,6,SJ Davis,1,7
44,SJA Taufel,1,SJA Taufel,54,55
45,SK Tarapore,5,SK Tarapore,26,31
46,SL Shastri,1,SL Shastri,13,14
47,SS Hazare,11,SS Hazare,6,17
48,Tapan Sharma,2,Tapan Sharma,18,20
49,UV Gandhe,4,UV Gandhe,27,31
50,VA Kulkarni,13,VA Kulkarni,44,57
51,VK Sharma,4,VK Sharma,61,65
52,Vinod Seshan,3,Vinod Seshan,11,14
53,YC Barde,6,YC Barde,36,42

In [177]:
#61. Count matches with result “tie”.
df1['result'].unique()

array(['runs', 'wickets', 'tie', 'no result'], dtype=object)

In [178]:
df1[df1['result']=='tie'].count()

id                 14
season             14
city               11
date               14
match_type         14
player_of_match    14
venue              14
team1              14
team2              14
toss_winner        14
toss_decision      14
winner             14
result             14
result_margin       0
target_runs        14
target_overs       14
super_over         14
method              0
umpire1            14
umpire2            14
dtype: int64

In [179]:
#62. For each team, count matches where they batted first.
inning_1=df2[df2['inning']==1]

In [180]:
teams=inning_1.groupby(['match_id','batting_team']).size().reset_index(name='count1')

In [181]:
teams.groupby('batting_team').size().reset_index(name="bat_first")

                   batting_team  bat_first
0           Chennai Super Kings        130
1               Deccan Chargers         43
2                Delhi Capitals         41
3              Delhi Daredevils         72
4                 Gujarat Lions         14
5                Gujarat Titans         21
6               Kings XI Punjab         97
7          Kochi Tuskers Kerala          7
8         Kolkata Knight Riders        120
9          Lucknow Super Giants         23
10               Mumbai Indians        134
11                Pune Warriors         20
12                 Punjab Kings         31
13             Rajasthan Royals        103
14       Rising Pune Supergiant          8
15      Rising Pune Supergiants          7
16  Royal Challengers Bangalore        121
17  Royal Challengers Bengaluru          9
18          Sunrisers Hyderabad         94

In [182]:
#63. For each team, count matches where they chased.

In [183]:
chase=merge_df[(merge_df['inning']==2) & (merge_df['batting_team']==merge_df['winner'])]

In [184]:
new=chase.groupby(['id','winner']).size().reset_index(name='counts')

In [185]:
new.groupby('winner').size().reset_index(name='chased_runs')

                         winner  chased_runs
0           Chennai Super Kings           68
1               Deccan Chargers           11
2                Delhi Capitals           25
3              Delhi Daredevils           42
4                 Gujarat Lions           12
5                Gujarat Titans           17
6               Kings XI Punjab           48
7          Kochi Tuskers Kerala            4
8         Kolkata Knight Riders           78
9          Lucknow Super Giants            8
10               Mumbai Indians           72
11                Pune Warriors            6
12                 Punjab Kings           13
13             Rajasthan Royals           67
14       Rising Pune Supergiant            5
15      Rising Pune Supergiants            5
16  Royal Challengers Bangalore           62
17  Royal Challengers Bengaluru            3
18          Sunrisers Hyderabad           44

In [186]:
#64. Identify teams with most wins at a particular venue.
venue=df1.groupby(['winner','venue']).size().reset_index(name='wins')

In [187]:
venue.loc[venue.groupby('winner')['wins'].idxmax()]

,winner,venue,wins
20,Chennai Super Kings,"MA Chidambaram Stadium, Chepauk",33
38,Deccan Chargers,Barabati Stadium,3
55,Delhi Capitals,"Arun Jaitley Stadium, Delhi",6
81,Delhi Daredevils,Feroz Shah Kotla,23
109,Gujarat Lions,Saurashtra Cricket Association Stadium,3
119,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",9
140,Kings XI Punjab,"Punjab Cricket Association Stadium, Mohali",18
153,Kochi Tuskers Kerala,Nehru Stadium,2
161,Kolkata Knight Riders,Eden Gardens,45
190,Lucknow Super Giants,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,7
235,Mumbai Indians,Wankhede Stadium,42
244,Pune Warriors,Subrata Roy Sahara Stadium,4
259,Punjab Kings,"Wankhede Stadium, Mumbai",4
287,Rajasthan Royals,Sawai Mansingh Stadium,32
300,Rising Pune Supergiant,Maharashtra Cricket Association Stadium,5
303,Rising Pune Supergiants,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,2
319,Royal Challengers Bangalore,M Chinnaswamy Stadium,29
348,Royal Challengers Bengaluru,"M Chinnaswamy Stadium, Bengaluru",4
371,Sunrisers Hyderabad,"Rajiv Gandhi International Stadium, Uppal",20

In [188]:
#65. Find most common man of the match per season.
group=df1.groupby(['season','player_of_match']).size().reset_index(name='count')

In [189]:
df1.groupby(['season'])['player_of_match'].agg(pd.Series.mode)

season
2007/08                                            SE Marsh
2009                                              YK Pathan
2009/10                                        SR Tendulkar
2011                                               CH Gayle
2012                                               CH Gayle
2013                                             MEK Hussey
2014                                             GJ Maxwell
2015                                              DA Warner
2016                                                V Kohli
2017                           [BA Stokes, NM Coulter-Nile]
2018                                            Rashid Khan
2019                                             AD Russell
2020/21    [AB de Villiers, KL Rahul, RD Gaikwad, TA Boult]
2021                                             RD Gaikwad
2022                                          Kuldeep Yadav
2023                            [Shubman Gill, YBK Jaiswal]
2024                  [Abhishek Sharma, SP Narine, TM Head]
Name: player_of_match, dtype: object

In [190]:
group.loc[group.groupby(['season'])['count'].idxmax()]

      season  player_of_match  count
28   2007/08         SE Marsh      5
80      2009        YK Pathan      3
121  2009/10     SR Tendulkar      4
133     2011         CH Gayle      6
188     2012         CH Gayle      5
253     2013       MEK Hussey      5
285     2014       GJ Maxwell      4
319     2015        DA Warner      4
386     2016          V Kohli      5
392     2017        BA Stokes      3
462     2018      Rashid Khan      4
475     2019       AD Russell      4
515  2020/21   AB de Villiers      3
592     2021       RD Gaikwad      4
622     2022    Kuldeep Yadav      4
702     2023     Shubman Gill      4
709     2024  Abhishek Sharma      3

In [191]:
#66. Get count of matches with Duckworth-Lewis method applied.
df1['method'].unique()

array([nan, 'D/L'], dtype=object)

In [192]:
df1[df1['method']=='D/L'].count()

id                 21
season             21
city               21
date               21
match_type         21
player_of_match    21
venue              21
team1              21
team2              21
toss_winner        21
toss_decision      21
winner             21
result             21
result_margin      21
target_runs        21
target_overs       21
super_over         21
method             21
umpire1            21
umpire2            21
dtype: int64

In [193]:
#67. For each season, find total teams participating.
merge_df.groupby(['season'])['batting_team'].nunique()

season
2007/08     8
2009        8
2009/10     8
2011       10
2012        9
2013        9
2014        8
2015        8
2016        8
2017        8
2018        8
2019        8
2020/21     8
2021        8
2022       10
2023       10
2024       10
Name: batting_team, dtype: int64

In [194]:
#68. For each city, count number of matches played.
df1.groupby(['city']).size()

city
Abu Dhabi          37
Ahmedabad          36
Bangalore          65
Bengaluru          29
Bloemfontein        2
Cape Town           7
Centurion          12
Chandigarh         61
Chennai            85
Cuttack             7
Delhi              90
Dharamsala         13
Dubai              13
Durban             15
East London         3
Guwahati            3
Hyderabad          77
Indore              9
Jaipur             57
Johannesburg        8
Kanpur              4
Kimberley           3
Kochi               5
Kolkata            93
Lucknow            14
Mohali              5
Mumbai            173
Nagpur              3
Navi Mumbai         9
Port Elizabeth      7
Pune               51
Raipur              6
Rajkot             10
Ranchi              7
Sharjah            10
Visakhapatnam      15
dtype: int64

In [195]:
#69. For each team, find their win rate per season.
g1=merge_df.groupby(['season','id','batting_team']).size().reset_index(name='sum')

In [196]:
g1

       season       id                 batting_team  sum
0     2007/08   335982        Kolkata Knight Riders  124
1     2007/08   335982  Royal Challengers Bangalore  101
2     2007/08   335983          Chennai Super Kings  124
3     2007/08   335983              Kings XI Punjab  124
4     2007/08   335984             Delhi Daredevils   97
...       ...      ...                          ...  ...
2182     2024  1426310  Royal Challengers Bengaluru  122
2183     2024  1426311             Rajasthan Royals  124
2184     2024  1426311          Sunrisers Hyderabad  127
2185     2024  1426312        Kolkata Knight Riders   67
2186     2024  1426312          Sunrisers Hyderabad  117

[2187 rows x 4 columns]

In [197]:
total=g1.groupby(['season','batting_team']).size().reset_index(name='total')

In [198]:
g2=merge_df.groupby(['season','id','winner']).size().reset_index()

In [199]:
wins=g2.groupby(['season','winner']).size().reset_index(name='wins')

In [200]:
res=pd.concat([total,wins],axis=1)

In [201]:
res['win_rate']=(res['wins']/res['total'])*100

In [202]:
res

,season,batting_team,total,season,winner,wins,win_rate
0,2007/08,Chennai Super Kings,16,2007/08,Chennai Super Kings,9,56.250000
1,2007/08,Deccan Chargers,14,2007/08,Deccan Chargers,2,14.285714
2,2007/08,Delhi Daredevils,14,2007/08,Delhi Daredevils,7,50.000000
3,2007/08,Kings XI Punjab,15,2007/08,Kings XI Punjab,10,66.666667
4,2007/08,Kolkata Knight Riders,13,2007/08,Kolkata Knight Riders,6,46.153846
...,...,...,...,...,...,...,...
141,2024,Mumbai Indians,14,2024,Mumbai Indians,4,28.571429
142,2024,Punjab Kings,14,2024,Punjab Kings,5,35.714286
143,2024,Rajasthan Royals,15,2024,Rajasthan Royals,9,60.000000
144,2024,Royal Challengers Bengaluru,15,2024,Royal Challengers Bengaluru,7,46.666667
145,2024,Sunrisers Hyderabad,16,2024,Sunrisers Hyderabad,9,56.250000

In [203]:
#70. Using groupby, list top 5 match winners at each venue.
winner=df1.groupby(['venue','winner']).size().reset_index(name='wins')

In [204]:
winner=winner.sort_values(['venue','wins'],ascending=[True,False])

In [205]:
winner

                                venue               winner  wins
1                Arun Jaitley Stadium       Delhi Capitals     4
2                Arun Jaitley Stadium     Delhi Daredevils     4
6                Arun Jaitley Stadium  Sunrisers Hyderabad     2
0                Arun Jaitley Stadium  Chennai Super Kings     1
3                Arun Jaitley Stadium      Kings XI Punjab     1
..                                ...                  ...   ...
380  Zayed Cricket Stadium, Abu Dhabi       Mumbai Indians     2
377  Zayed Cricket Stadium, Abu Dhabi  Chennai Super Kings     1
378  Zayed Cricket Stadium, Abu Dhabi       Delhi Capitals     1
381  Zayed Cricket Stadium, Abu Dhabi     Rajasthan Royals     1
382  Zayed Cricket Stadium, Abu Dhabi  Sunrisers Hyderabad     1

[383 rows x 3 columns]

In [206]:
winner.groupby(['venue']).head(5)

                                venue                 winner  wins
1                Arun Jaitley Stadium         Delhi Capitals     4
2                Arun Jaitley Stadium       Delhi Daredevils     4
6                Arun Jaitley Stadium    Sunrisers Hyderabad     2
0                Arun Jaitley Stadium    Chennai Super Kings     1
3                Arun Jaitley Stadium        Kings XI Punjab     1
..                                ...                    ...   ...
379  Zayed Cricket Stadium, Abu Dhabi  Kolkata Knight Riders     2
380  Zayed Cricket Stadium, Abu Dhabi         Mumbai Indians     2
377  Zayed Cricket Stadium, Abu Dhabi    Chennai Super Kings     1
378  Zayed Cricket Stadium, Abu Dhabi         Delhi Capitals     1
381  Zayed Cricket Stadium, Abu Dhabi       Rajasthan Royals     1

[260 rows x 3 columns]

In [207]:
#71. Find total deliveries bowled per bowler.
df2.groupby(['bowler']).size()

bowler
A Ashish Reddy     270
A Badoni            25
A Chandila         234
A Choudhary        108
A Dananjaya         25
                  ...
Yash Dayal         615
Yash Thakur        432
Yudhvir Singh       74
Yuvraj Singh       882
Z Khan            2276
Length: 530, dtype: int64

In [208]:
#72. Find total runs scored by each batsman.
df2.groupby('batter')['batsman_runs'].sum()

batter
A Ashish Reddy     280
A Badoni           634
A Chandila           4
A Chopra            53
A Choudhary         25
                  ...
Yashpal Singh       47
Younis Khan          3
Yudhvir Singh       22
Yuvraj Singh      2754
Z Khan             117
Name: batsman_runs, Length: 673, dtype: int64

In [209]:
#73. Compute number of 4s hit by each batsman.
four=df2[df2['batsman_runs']==4]

In [210]:
four.groupby(['batter']).size()

batter
A Ashish Reddy     16
A Badoni           46
A Chopra            7
A Choudhary         1
A Flintoff          5
                 ...
YV Takawale        26
Yashpal Singh       5
Yudhvir Singh       1
Yuvraj Singh      218
Z Khan             11
Length: 538, dtype: int64

In [211]:
#74. Compute number of 6s hit by each batsman.
six=df2[df2['batsman_runs']==6]

In [212]:
six.groupby(['batter']).size()

batter
A Ashish Reddy     15
A Badoni           24
A Choudhary         1
A Flintoff          2
A Manohar          10
                 ...
YK Pathan         161
YV Takawale         3
Yudhvir Singh       2
Yuvraj Singh      149
Z Khan              2
Length: 451, dtype: int64

In [213]:
#75. Find bowlers with most no-balls.
df2['extras_type'].unique()

array(['legbyes', nan, 'wides', 'byes', 'noballs', 'penalty'],
      dtype=object)

In [214]:
noballs=df2[df2['extras_type']=='noballs']

In [215]:
noballs.groupby(['bowler']).size()

bowler
A Ashish Reddy     2
A Choudhary        1
A Kamboj           2
A Kumble           5
A Mishra          21
                  ..
YS Chahal          9
Yash Dayal         5
Yash Thakur        3
Yuvraj Singh       1
Z Khan             2
Length: 269, dtype: int64

In [216]:
#76. Find batsmen with most dot balls faced.
dot=df2[(df2['total_runs']==0) & (df2['extras_type'].isnull())]

In [217]:
dot.groupby(['batter']).size()

batter
A Ashish Reddy     56
A Badoni          144
A Chandila          3
A Chopra           40
A Choudhary         4
                 ...
Yashpal Singh      37
Younis Khan         4
Yudhvir Singh       8
Yuvraj Singh      864
Z Khan             71
Length: 659, dtype: int64

In [218]:
#77. For each over, compute total runs scored.
df2.groupby(['over'])['total_runs'].sum()

over
0     13651
1     16163
2     17895
3     18415
4     18565
5     18528
6     14839
7     15981
8     16639
9     16353
10    16779
11    17076
12    17205
13    17634
14    18149
15    18472
16    19012
17    19559
18    19076
19    17765
Name: total_runs, dtype: int64

In [219]:
#78. For each match, total runs in each over.
df2.groupby(['match_id','over'])['total_runs'].sum()

match_id  over
335982    0        7
          1       23
          2        9
          3       27
          4       18
                  ..
1426312   14       0
          15       8
          16      10
          17       5
          18       0
Name: total_runs, Length: 21717, dtype: int64

In [220]:
#79. Count wickets per bowler.
wicket=df2[df2['is_wicket']==1]

In [221]:
wicket.groupby(['bowler']).size()

bowler
A Ashish Reddy     19
A Badoni            2
A Chandila         11
A Choudhary         5
A Flintoff          2
                 ...
Yash Dayal         31
Yash Thakur        27
Yudhvir Singh       4
Yuvraj Singh       39
Z Khan            119
Length: 455, dtype: int64

In [222]:
wicket.groupby(['bowler'])['is_wicket'].sum()

bowler
A Ashish Reddy     19
A Badoni            2
A Chandila         11
A Choudhary         5
A Flintoff          2
                 ...
Yash Dayal         31
Yash Thakur        27
Yudhvir Singh       4
Yuvraj Singh       39
Z Khan            119
Name: is_wicket, Length: 455, dtype: int64

In [223]:
#80. Count dismissals of type “caught” per fielder.
df2['dismissal_kind'].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field', 'retired out'], dtype=object)

In [224]:
caught=df2[df2['dismissal_kind']=='caught']

In [225]:
caught.groupby(['fielder']).size()

fielder
A Ashish Reddy     8
A Badoni          13
A Chandila         2
A Chopra           2
A Flintoff         3
                  ..
Yash Thakur        2
Yashpal Singh      3
Younis Khan        1
Yuvraj Singh      29
Z Khan            20
Length: 599, dtype: int64

In [226]:
#81. Find total wides bowled by each bowler.
wides=df2[df2['extras_type']=='wides']

In [227]:
wides.groupby(['bowler']).size()

bowler
A Ashish Reddy     6
A Choudhary        6
A Dananjaya        1
A Kamboj           6
A Kumble          13
                  ..
Yash Dayal        32
Yash Thakur       25
Yudhvir Singh      2
Yuvraj Singh      12
Z Khan            74
Length: 443, dtype: int64

In [228]:
#82. Find total extras conceded by each team.
extras=df2[~df2['extras_type'].isnull()]

In [229]:
extras.groupby(['bowling_team']).size()

bowling_team
Chennai Super Kings            1524
Deccan Chargers                 527
Delhi Capitals                  602
Delhi Daredevils                999
Gujarat Lions                   160
Gujarat Titans                  236
Kings XI Punjab                1234
Kochi Tuskers Kerala             90
Kolkata Knight Riders          1533
Lucknow Super Giants            302
Mumbai Indians                 1810
Pune Warriors                   235
Punjab Kings                    372
Rajasthan Royals               1562
Rising Pune Supergiant          100
Rising Pune Supergiants          82
Royal Challengers Bangalore    1601
Royal Challengers Bengaluru     119
Sunrisers Hyderabad            1037
dtype: int64

In [235]:
#83. Compute batsman strike rate (runs/balls × 100).
total_runs=df2.groupby(['batter'])['batsman_runs'].sum().reset_index()

In [239]:
df=df2[df2['extras_type'].isnull()]

In [240]:
total_balls=df.groupby(['batter']).size().reset_index(name='balls')

In [242]:
batters=pd.merge(total_runs,total_balls,on='batter',how='inner')

In [243]:
batters['strike_rate']=(batters['batsman_runs']/batters['balls'])*100

In [244]:
batters

             batter  batsman_runs  balls  strike_rate
0    A Ashish Reddy           280    191   146.596859
1          A Badoni           634    465   136.344086
2        A Chandila             4      7    57.142857
3          A Chopra            53     70    75.714286
4       A Choudhary            25     20   125.000000
..              ...           ...    ...          ...
667   Yashpal Singh            47     65    72.307692
668     Younis Khan             3      7    42.857143
669   Yudhvir Singh            22     16   137.500000
670    Yuvraj Singh          2754   2089   131.833413
671          Z Khan           117    137    85.401460

[672 rows x 4 columns]

In [264]:
#84. Compute bowler economy rate (runs/overs).
g1=df2.groupby(['bowler'])['total_runs'].sum().reset_index()

In [265]:
g2=df.groupby('bowler').size().reset_index(name='balls')

In [258]:
over=df.groupby(['bowler','match_id','over']).size().reset_index(name='balls')

In [259]:
over['balls'].value_counts()

balls
6     37203
5      4195
4       426
1       147
3       135
2       125
7         4
12        3
11        2
10        1
Name: count, dtype: int64

In [261]:
over.groupby(['bowler']).size()

bowler
A Ashish Reddy     45
A Badoni            5
A Chandila         39
A Choudhary        17
A Dananjaya         4
                 ...
Yash Dayal         97
Yash Thakur        68
Yudhvir Singh      12
Yuvraj Singh      146
Z Khan            371
Length: 530, dtype: int64

In [267]:
bowlers=pd.merge(g1,g2,on='bowler',how='inner')

In [270]:
bowlers['economy']=(bowlers['total_runs']/(bowlers['balls']/6))

In [271]:
bowlers

             bowler  total_runs  balls    economy
0    A Ashish Reddy         400    258   9.302326
1          A Badoni          37     24   9.250000
2        A Chandila         245    232   6.336207
3       A Choudhary         144    101   8.554455
4       A Dananjaya          47     24  11.750000
..              ...         ...    ...        ...
525      Yash Dayal         933    571   9.803853
526     Yash Thakur         702    394  10.690355
527   Yudhvir Singh         125     70  10.714286
528    Yuvraj Singh        1091    858   7.629371
529          Z Khan        2860   2144   8.003731

[530 rows x 4 columns]

In [272]:
#85. Count balls faced by each batsman.
df2.groupby(['batter']).size()

batter
A Ashish Reddy     196
A Badoni           505
A Chandila           7
A Chopra            75
A Choudhary         20
                  ...
Yashpal Singh       67
Younis Khan          7
Yudhvir Singh       16
Yuvraj Singh      2207
Z Khan             141
Length: 673, dtype: int64

In [274]:
#86. Count balls bowled by each bowler.
df.groupby(['bowler']).size()

bowler
A Ashish Reddy     258
A Badoni            24
A Chandila         232
A Choudhary        101
A Dananjaya         24
                  ...
Yash Dayal         571
Yash Thakur        394
Yudhvir Singh       70
Yuvraj Singh       858
Z Khan            2144
Length: 530, dtype: int64

In [275]:
#87. Find batsmen scoring most runs in powerplay (1–6 overs).
powerplay=df2[df2['over']<6]

In [279]:
powerplay.groupby(['batter'])['batsman_runs'].sum().idxmax()

'S Dhawan'

In [280]:
#88. Find batsmen scoring most runs in death overs (16–20).
death_overs=df2[df2['over']>15]

In [284]:
death_overs.groupby(['batter'])['batsman_runs'].sum().idxmax()

'MS Dhoni'

In [286]:
#89. For each batting team, compute total boundaries.
boundry.groupby(['batting_team']).size()

batting_team
Chennai Super Kings            4705
Deccan Chargers                1357
Delhi Capitals                 1902
Delhi Daredevils               2957
Gujarat Lions                   615
Gujarat Titans                  962
Kings XI Punjab                3706
Kochi Tuskers Kerala            223
Kolkata Knight Riders          4956
Lucknow Super Giants            909
Mumbai Indians                 5322
Pune Warriors                   721
Punjab Kings                   1235
Rajasthan Royals               4328
Rising Pune Supergiant          286
Rising Pune Supergiants         239
Royal Challengers Bangalore    4637
Royal Challengers Bengaluru     394
Sunrisers Hyderabad            3447
dtype: int64

In [288]:
#90. For each bowler, compute wickets per season (requires join with matches).
wickets=merge_df[merge_df['is_wicket']==1]

In [289]:
wickets.groupby(['season','bowler'])['is_wicket'].sum()

season   bowler
2007/08  A Kumble              8
         A Mishra             11
         A Nehra              14
         A Nel                 1
         AA Noffke             1
                              ..
2024     Washington Sundar     1
         YS Chahal            19
         Yash Dayal           16
         Yash Thakur          12
         Yudhvir Singh         1
Name: is_wicket, Length: 1625, dtype: int64

In [291]:
#91. For each match, compute number of dot balls.
dot.groupby('match_id').size()

match_id
335982      86
335983      57
335984      85
335985      81
335986     123
          ...
1426307     64
1426309     70
1426310     71
1426311     94
1426312     74
Length: 1095, dtype: int64

In [293]:
#92. For each bowling team, compute wides conceded.
wides.groupby(['bowling_team']).size()

bowling_team
Chennai Super Kings             946
Deccan Chargers                 280
Delhi Capitals                  387
Delhi Daredevils                550
Gujarat Lions                    91
Gujarat Titans                  149
Kings XI Punjab                 720
Kochi Tuskers Kerala             52
Kolkata Knight Riders           848
Lucknow Super Giants            193
Mumbai Indians                 1090
Pune Warriors                   120
Punjab Kings                    234
Rajasthan Royals                949
Rising Pune Supergiant           62
Rising Pune Supergiants          56
Royal Challengers Bangalore     951
Royal Challengers Bengaluru      85
Sunrisers Hyderabad             617
dtype: int64

In [296]:
#93. Identify top scorers in each match.
total_runs=df2.groupby(['match_id','batting_team'])['total_runs'].sum().reset_index()

In [298]:
total_runs.loc[total_runs.groupby(['match_id'])['total_runs'].idxmax()]

      match_id                 batting_team  total_runs
0       335982        Kolkata Knight Riders         222
2       335983          Chennai Super Kings         240
4       335984             Delhi Daredevils         132
7       335985  Royal Challengers Bangalore         166
9       335986        Kolkata Knight Riders         112
...        ...                          ...         ...
2178   1426307          Sunrisers Hyderabad         215
2179   1426309        Kolkata Knight Riders         164
2181   1426310             Rajasthan Royals         174
2184   1426311          Sunrisers Hyderabad         175
2185   1426312        Kolkata Knight Riders         114

[1095 rows x 3 columns]

In [302]:
#94. Compute average runs per wicket for each bowler.
g1=df2.groupby('bowler')['total_runs'].sum()

In [303]:
g2=df2.groupby('bowler')['is_wicket'].sum()

In [305]:
runs_wic=pd.merge(g1,g2,on='bowler',how='inner')

In [306]:
runs_wic['average']=runs_wic['total_runs']/runs_wic['is_wicket']

In [307]:
runs_wic

                total_runs  is_wicket    average
bowler
A Ashish Reddy         400         19  21.052632
A Badoni                37          2  18.500000
A Chandila             245         11  22.272727
A Choudhary            144          5  28.800000
A Dananjaya             47          0        inf
...                    ...        ...        ...
Yash Dayal             933         31  30.096774
Yash Thakur            702         27  26.000000
Yudhvir Singh          125          4  31.250000
Yuvraj Singh          1091         39  27.974359
Z Khan                2860        119  24.033613

[530 rows x 3 columns]

In [310]:
runs_wic.replace([np.inf,-np.inf],np.nan,inplace=True)

In [311]:
runs_wic.dropna(inplace=True)

In [313]:
runs_wic[runs_wic['average'].isnull()]

Empty DataFrame
Columns: [total_runs, is_wicket, average]
Index: []

In [317]:
#95. Compute runs conceded by each bowler to each batsman.
df2.groupby(['bowler','batter'])['batsman_runs'].sum()

bowler          batter
A Ashish Reddy  AB de Villiers     46
                AC Thomas          10
                AD Mathews          3
                AD Russell          1
                AL Menaria          9
                                   ..
Z Khan          WA Mota             1
                WP Saha            39
                Y Venugopal Rao     9
                YK Pathan          34
                Yuvraj Singh       12
Name: batsman_runs, Length: 27881, dtype: int64

In [320]:
#96. For each inning, find cumulative runs over overs.
new=df2[(df2['batsman_runs']!=4) & (df2['batsman_runs']!=6)]

In [321]:
new.groupby(['inning','over'])['total_runs'].sum()

inning  over
1       0       2775
        1       2884
        2       2959
        3       2946
        4       3007
        5       3081
        6       4262
        7       4232
        8       4198
        9       4422
        10      4303
        11      4323
        12      4394
        13      4371
        14      4260
        15      4432
        16      4409
        17      4411
        18      4309
        19      4391
2       0       2729
        1       2901
        2       2937
        3       3027
        4       2910
        5       3003
        6       4173
        7       4302
        8       4196
        9       4239
        10      4139
        11      4243
        12      4178
        13      4095
        14      3934
        15      3947
        16      3760
        17      3526
        18      3120
        19      1999
3       0         48
4       0         46
5       0          7
6       0          1
Name: total_runs, dtype: int64

In [323]:
#97. Find bowlers with most maidens (if maiden can be computed).
maiden=df2[(df2['batsman_runs']==0) & (df2['extras_type'].isnull())]

In [328]:
maid=maiden.groupby(['bowler','match_id','over']).size().reset_index(name='balls')

In [330]:
mai=maid[maid['balls']%6==0]

In [333]:
mai.groupby('bowler').size().idxmax()

'B Kumar'

In [337]:
#98. For each match, find batsmen who faced more than 20 balls.
balls=df2.groupby(['match_id','batter']).size().reset_index(name='balls')

In [338]:
balls[balls['balls']>20]

       match_id              batter  balls
2        335982         BB McCullum     77
18       335983            JR Hopes     34
20       335983       KC Sangakkara     35
21       335983          MEK Hussey     54
31       335984           G Gambhir     49
...         ...                 ...    ...
16498   1426311             TM Head     28
16499   1426311         YBK Jaiswal     22
16500   1426312          AK Markram     25
16509   1426312  Rahmanullah Gurbaz     35
16514   1426312             VR Iyer     27

[4722 rows x 3 columns]

In [343]:
#99. For each match, find strike rate of all batsmen.
runs=df2.groupby(['match_id','batter'])['total_runs'].sum().reset_index()

In [344]:
balls=df2.groupby(['match_id','batter']).size().reset_index(name='balls')

In [347]:
strike=pd.merge(runs,balls,on=['match_id','batter'],how='inner')

In [348]:
strike['st_rate']=strike['total_runs']/strike['balls']*100

In [349]:
strike

       match_id         batter  total_runs  balls     st_rate
0        335982      AA Noffke          11     12   91.666667
1        335982        B Akhil           0      2    0.000000
2        335982    BB McCullum         169     77  219.480519
3        335982       CL White           6     10   60.000000
4        335982      DJ Hussey          12     12  100.000000
...         ...            ...         ...    ...         ...
16510   1426312      SP Narine           6      2  300.000000
16511   1426312        SS Iyer           6      3  200.000000
16512   1426312  Shahbaz Ahmed           8      7  114.285714
16513   1426312        TM Head           0      1    0.000000
16514   1426312        VR Iyer          56     27  207.407407

[16515 rows x 5 columns]

In [351]:
#100. For each match, compute total deliveries that resulted in extra.
extras=df2[~df2['extras_type'].isnull()]

In [352]:
extras.groupby(['match_id']).size()

match_id
335982     24
335983     16
335984     12
335985     13
335986     24
           ..
1426307    19
1426309    12
1426310    10
1426311    13
1426312    16
Length: 1095, dtype: int64