In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Placement.csv")

In [3]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
#1. Display all students who got placed.
data[data["status"]=="Placed"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
7,8,0,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.0,Mkt&Fin,62.14,Placed,252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,0,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0

In [5]:
#2. Show records of students who were not placed.
data[data["status"]=="Not Placed"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
3,4,0,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
5,6,0,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,1,46.0,Others,49.2,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
9,10,0,58.0,Central,70.0,Central,Commerce,61.00,Comm&Mgmt,No,54.00,Mkt&Fin,52.21,Not Placed,NaN
12,13,1,47.0,Central,55.0,Others,Science,65.00,Comm&Mgmt,No,62.00,Mkt&HR,65.04,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,199,1,67.0,Central,70.0,Central,Commerce,65.00,Others,No,88.00,Mkt&HR,71.96,Not Placed,NaN
201,202,0,54.2,Central,63.0,Others,Science,58.00,Comm&Mgmt,No,79.00,Mkt&HR,58.44,Not Placed,NaN
206,207,0,41.0,Central,42.0,Central,Science,60.00,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
208,209,1,43.0,Central,60.0,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
214,215,0,62.0,Central,58.0,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [6]:
#3. Display students with ssc_p (10th percentage) greater than 80.
data[data["ssc_p"]>80]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
7,8,0,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.00,Mkt&Fin,62.14,Placed,252000.0
33,34,1,87.00,Others,65.00,Others,Science,81.00,Comm&Mgmt,Yes,88.00,Mkt&Fin,72.78,Placed,260000.0
39,40,0,81.00,Others,68.00,Others,Science,64.00,Sci&Tech,No,93.00,Mkt&Fin,62.56,Placed,411000.0
43,44,0,87.00,Others,87.00,Others,Commerce,68.00,Comm&Mgmt,No,95.00,Mkt&HR,62.90,Placed,300000.0
61,62,0,84.20,Central,73.40,Central,Commerce,66.89,Comm&Mgmt,No,61.60,Mkt&Fin,62.48,Placed,300000.0
62,63,1,86.50,Others,64.20,Others,Science,67.40,Sci&Tech,No,59.00,Mkt&Fin,59.69,Placed,240000.0
66,67,0,83.00,Others,74.00,Others,Science,66.00,Comm&Mgmt,No,68.92,Mkt&HR,58.46,Placed,275000.0
67,68,0,80.92,Others,78.50,Others,Commerce,67.00,Comm&Mgmt,No,68.71,Mkt&Fin,60.99,Placed,275000.0
70,71,0,82.00,Others,61.00,Others,Science,62.00,Sci&Tech,No,89.00,Mkt&Fin,65.45,Placed,360000.0
72,73,0,84.86,Others,67.00,Others,Science,78.00,Comm&Mgmt,No,95.50,Mkt&Fin,68.53,Placed,240000.0
78,79,0,84.00,Others,90.90,Others,Science,64.50,Sci&Tech,No,86.04,Mkt&Fin,59.42,Placed,270000.0
81,82,0,81.70,Others,63.00,Others,Science,67.00,Comm&Mgmt,Yes,86.00,Mkt&Fin,70.20,Placed,300000.0
83,84,0,84.00,Others,79.00,Others,Science,68.00,Sci&Tech,Yes,84.00,Mkt&Fin,66.69,Placed,300000.0
85,86,1,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
89,90,1,84.00,Others,75.00,Others,Science,69.00,Sci&Tech,Yes,62.00,Mkt&HR,62.36,Placed,210000.0
90,91,1,85.00,Others,90.00,Others,Commerce,82.00,Comm&Mgmt,No,92.00,Mkt&Fin,68.03,Placed,300000.0
107,108,0,82.00,Others,90.00,Others,Commerce,83.00,Comm&Mgmt,No,80.00,Mkt&HR,73.52,Placed,200000.0
125,126,1,84.00,Central,73.00,Central,Commerce,73.00,Comm&Mgmt,No,75.00,Mkt&Fin,73.33,Placed,350000.0
128,129,0,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,Yes,81.20,Mkt&HR,76.26,Placed,400000.0
138,139,1,82.00,Others,64.00,Others,Science,73.00,Sci&Tech,Yes,96.00,Mkt&Fin,71.77,Placed,250000.0
142,143,0,85.00,Central,60.00,Others,Science,73.43,Sci&Tech,Yes,60.00,Mkt&Fin,61.29,Placed,260000.0
145,146,0,89.40,Others,65.66,Others,Science,71.25,Sci&Tech,No,72.00,Mkt&HR,63.23,Placed,400000.0
156,157,0,84.20,Central,69.40,Central,Science,65.00,Sci&Tech,Yes,80.00,Mkt&HR,52.72,Placed,255000.0
160,161,0,87.00,Central,74.00,Central,Science,65.00,Sci&Tech,Yes,75.00,Mkt&HR,72.29,Placed,300000.0
185,186,1,88.00,Central,72.00,Central,Science,78.00,Others,No,82.00,Mkt&HR,71.43,Placed,252000.0
197,198,1,83.96,Others,53.00,Others,Science,91.00,Sci&Tech,No,59.32,Mkt&HR,69.71,Placed,260000.0
207,208,0,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0

In [7]:
#4. Retrieve all students whose hsc_p (12th percentage) is less than 70.
data[data["hsc_p"]<70]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
2,3,0,65.0,Central,68.0,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
3,4,0,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
5,6,0,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,1,46.0,Others,49.2,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
7,8,0,82.0,Central,64.0,Central,Science,66.00,Sci&Tech,Yes,67.00,Mkt&Fin,62.14,Placed,252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,209,1,43.0,Central,60.0,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
211,212,0,58.0,Others,60.0,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.0,Others,67.0,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0
213,214,1,74.0,Others,66.0,Others,Commerce,58.00,Comm&Mgmt,No,70.00,Mkt&HR,60.23,Placed,204000.0
214,215,0,62.0,Central,58.0,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [8]:
#5. Select students who have degree_p greater than 75 and mba_p greater than 60.
data[(data["degree_p"]>75) & (data["mba_p"]>60)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
11,12,0,69.60,Central,68.40,Central,Commerce,78.30,Comm&Mgmt,Yes,60.00,Mkt&Fin,63.70,Placed,250000.0
21,22,1,79.00,Others,76.00,Others,Commerce,85.00,Comm&Mgmt,No,95.00,Mkt&Fin,69.06,Placed,393000.0
24,25,0,76.50,Others,97.70,Others,Science,78.86,Sci&Tech,No,97.40,Mkt&Fin,74.01,Placed,360000.0
33,34,1,87.00,Others,65.00,Others,Science,81.00,Comm&Mgmt,Yes,88.00,Mkt&Fin,72.78,Placed,260000.0
40,41,1,78.00,Central,77.00,Others,Commerce,80.00,Comm&Mgmt,No,60.00,Mkt&Fin,66.72,Placed,287000.0
44,45,1,77.00,Others,73.00,Others,Commerce,81.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,69.70,Placed,200000.0
72,73,0,84.86,Others,67.00,Others,Science,78.00,Comm&Mgmt,No,95.50,Mkt&Fin,68.53,Placed,240000.0
75,76,1,59.00,Central,62.00,Others,Commerce,77.50,Comm&Mgmt,No,74.00,Mkt&HR,67.00,Not Placed,NaN
85,86,1,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
90,91,1,85.00,Others,90.00,Others,Commerce,82.00,Comm&Mgmt,No,92.00,Mkt&Fin,68.03,Placed,300000.0
96,97,1,76.00,Central,70.00,Central,Science,76.00,Comm&Mgmt,Yes,66.00,Mkt&Fin,64.44,Placed,300000.0
107,108,0,82.00,Others,90.00,Others,Commerce,83.00,Comm&Mgmt,No,80.00,Mkt&HR,73.52,Placed,200000.0
118,119,0,76.00,Central,80.00,Central,Science,78.00,Sci&Tech,Yes,97.00,Mkt&HR,70.48,Placed,276000.0
126,127,1,79.00,Others,61.00,Others,Science,75.50,Sci&Tech,Yes,70.00,Mkt&Fin,68.20,Placed,210000.0
128,129,0,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,Yes,81.20,Mkt&HR,76.26,Placed,400000.0
133,134,0,73.00,Central,64.00,Others,Commerce,77.00,Comm&Mgmt,Yes,65.00,Mkt&HR,60.98,Placed,250000.0
152,153,1,75.40,Others,60.50,Central,Science,84.00,Sci&Tech,No,98.00,Mkt&Fin,65.25,Placed,240000.0
162,163,0,74.20,Central,87.60,Others,Commerce,77.25,Comm&Mgmt,Yes,75.20,Mkt&Fin,66.06,Placed,285000.0
177,178,1,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0
185,186,1,88.00,Central,72.00,Central,Science,78.00,Others,No,82.00,Mkt&HR,71.43,Placed,252000.0
197,198,1,83.96,Others,53.00,Others,Science,91.00,Sci&Tech,No,59.32,Mkt&HR,69.71,Placed,260000.0
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0

In [9]:
#6. Display all male students with workex equal to “Yes”.
data[(data["gender"]==1) & (data["workex"]=="Yes")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
15,16,1,65.00,Central,75.00,Central,Commerce,69.00,Comm&Mgmt,Yes,72.00,Mkt&Fin,64.66,Placed,200000.0
23,24,1,77.40,Others,60.00,Others,Science,64.74,Sci&Tech,Yes,92.00,Mkt&Fin,63.62,Placed,300000.0
25,26,1,52.58,Others,54.60,Central,Commerce,50.20,Comm&Mgmt,Yes,76.00,Mkt&Fin,65.33,Not Placed,NaN
33,34,1,87.00,Others,65.00,Others,Science,81.00,Comm&Mgmt,Yes,88.00,Mkt&Fin,72.78,Placed,260000.0
41,42,1,74.00,Others,63.16,Others,Commerce,65.00,Comm&Mgmt,Yes,65.00,Mkt&HR,69.76,Not Placed,NaN
44,45,1,77.00,Others,73.00,Others,Commerce,81.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,69.70,Placed,200000.0
80,81,1,69.00,Others,62.00,Others,Commerce,69.00,Comm&Mgmt,Yes,67.00,Mkt&HR,62.35,Placed,240000.0
85,86,1,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
89,90,1,84.00,Others,75.00,Others,Science,69.00,Sci&Tech,Yes,62.00,Mkt&HR,62.36,Placed,210000.0
96,97,1,76.00,Central,70.00,Central,Science,76.00,Comm&Mgmt,Yes,66.00,Mkt&Fin,64.44,Placed,300000.0
100,101,1,45.00,Others,57.00,Others,Commerce,58.00,Comm&Mgmt,Yes,56.39,Mkt&HR,64.95,Not Placed,NaN
102,103,1,77.00,Others,61.00,Others,Commerce,68.00,Comm&Mgmt,Yes,57.50,Mkt&Fin,61.31,Placed,300000.0
121,122,1,64.00,Central,67.00,Others,Science,69.60,Sci&Tech,Yes,55.67,Mkt&HR,71.49,Placed,250000.0
122,123,1,66.50,Central,66.80,Central,Arts,69.30,Comm&Mgmt,Yes,80.40,Mkt&Fin,71.00,Placed,236000.0
126,127,1,79.00,Others,61.00,Others,Science,75.50,Sci&Tech,Yes,70.00,Mkt&Fin,68.20,Placed,210000.0
131,132,1,74.90,Others,57.00,Others,Science,62.00,Others,Yes,80.00,Mkt&Fin,60.78,Placed,360000.0
134,135,1,77.44,Central,92.00,Others,Commerce,72.00,Comm&Mgmt,Yes,94.00,Mkt&Fin,67.13,Placed,250000.0
138,139,1,82.00,Others,64.00,Others,Science,73.00,Sci&Tech,Yes,96.00,Mkt&Fin,71.77,Placed,250000.0
168,169,1,48.00,Central,51.00,Central,Commerce,58.00,Comm&Mgmt,Yes,60.00,Mkt&HR,58.79,Not Placed,NaN
177,178,1,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0
193,194,1,60.00,Central,63.00,Central,Arts,56.00,Others,Yes,80.00,Mkt&HR,56.63,Placed,300000.0
204,205,1,74.00,Others,73.00,Others,Commerce,73.00,Comm&Mgmt,Yes,80.00,Mkt&Fin,67.69,Placed,210000.0

In [10]:
#7. Show female students with degree_t as “Sci&amp;Tech”.
data[(data["gender"]==0) & (data["degree_t"]=="Sci&Tech")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.00,Mkt&HR,58.80,Placed,270000.0
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
5,6,0,55.00,Others,49.80,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
7,8,0,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.00,Mkt&Fin,62.14,Placed,252000.0
24,25,0,76.50,Others,97.70,Others,Science,78.86,Sci&Tech,No,97.40,Mkt&Fin,74.01,Placed,360000.0
39,40,0,81.00,Others,68.00,Others,Science,64.00,Sci&Tech,No,93.00,Mkt&Fin,62.56,Placed,411000.0
53,54,0,80.00,Others,70.00,Others,Science,72.00,Sci&Tech,No,87.00,Mkt&HR,71.04,Placed,450000.0
59,60,0,52.60,Central,65.58,Others,Science,72.11,Sci&Tech,No,57.60,Mkt&Fin,56.66,Placed,265000.0
69,70,0,73.00,Central,73.00,Central,Science,66.00,Sci&Tech,Yes,70.00,Mkt&Fin,68.07,Placed,275000.0
70,71,0,82.00,Others,61.00,Others,Science,62.00,Sci&Tech,No,89.00,Mkt&Fin,65.45,Placed,360000.0
77,78,0,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,Yes,69.00,Mkt&Fin,57.65,Placed,500000.0
78,79,0,84.00,Others,90.90,Others,Science,64.50,Sci&Tech,No,86.04,Mkt&Fin,59.42,Placed,270000.0
83,84,0,84.00,Others,79.00,Others,Science,68.00,Sci&Tech,Yes,84.00,Mkt&Fin,66.69,Placed,300000.0
84,85,0,70.00,Central,63.00,Others,Science,70.00,Sci&Tech,Yes,55.00,Mkt&Fin,62.00,Placed,300000.0
99,100,0,54.00,Central,82.00,Others,Commerce,63.00,Sci&Tech,No,50.00,Mkt&Fin,59.47,Not Placed,NaN
103,104,0,73.00,Central,78.00,Central,Science,73.00,Sci&Tech,Yes,85.00,Mkt&HR,65.83,Placed,240000.0
105,106,0,59.00,Central,64.00,Others,Science,58.00,Sci&Tech,No,85.00,Mkt&HR,55.30,Not Placed,NaN
106,107,0,61.08,Others,50.00,Others,Science,54.00,Sci&Tech,No,71.00,Mkt&Fin,65.69,Not Placed,NaN
109,110,0,52.00,Central,63.00,Others,Science,65.00,Sci&Tech,Yes,86.00,Mkt&HR,56.09,Not Placed,NaN
111,112,0,51.00,Others,54.00,Others,Science,61.00,Sci&Tech,No,60.00,Mkt&HR,60.64,Not Placed,NaN
117,118,0,77.00,Others,75.00,Others,Science,73.00,Sci&Tech,No,80.00,Mkt&Fin,67.05,Placed,240000.0
118,119,0,76.00,Central,80.00,Central,Science,78.00,Sci&Tech,Yes,97.00,Mkt&HR,70.48,Placed,276000.0
128,129,0,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,Yes,81.20,Mkt&HR,76.26,Placed,400000.0
142,143,0,85.00,Central,60.00,Others,Science,73.43,Sci&Tech,Yes,60.00,Mkt&Fin,61.29,Placed,260000.0
145,146,0,89.40,Others,65.66,Others,Science,71.25,Sci&Tech,No,72.00,Mkt&HR,63.23,Placed,400000.0
150,151,0,71.00,Central,58.66,Central,Science,58.00,Sci&Tech,Yes,56.00,Mkt&Fin,61.30,Placed,690000.0
153,154,0,49.00,Others,59.00,Others,Science,65.00,Sci&Tech,Yes,86.00,Mkt&Fin,62.48,Placed,340000.0
156,157,0,84.20,Central,69.40,Central,Science,65.00,Sci&Tech,Yes,80.00,Mkt&HR,52.72,Placed,255000.0
158,159,0,67.00,Others,63.00,Others,Science,64.00,Sci&Tech,No,60.00,Mkt&Fin,61.87,Not Placed,NaN
160,161,0,87.00,Central,74.00,Central,Science,65.00,Sci&Tech,Yes,75.00,Mkt&HR,72.29,Placed,300000.0
163,164,0,63.00,Others,67.00,Others,Science,64.00,Sci&Tech,No,75.00,Mkt&Fin,66.46,Placed,500000.0
167,168,0,67.90,Others,62.00,Others,Science,67.00,Sci&Tech,Yes,58.10,Mkt&Fin,75.71,Not Placed,NaN
169,170,0,59.96,Others,42.16,Others,Science,61.26,Sci&Tech,No,54.48,Mkt&HR,65.48,Not Placed,NaN
174,175,0,73.24,Others,50.83,Others,Science,64.27,Sci&Tech,Yes,64.00,Mkt&Fin,66.23,Placed,500000.0
175,176,0,63.00,Others,62.00,Others,Science,65.00,Sci&Tech,No,87.50,Mkt&HR,60.69,Not Placed,NaN
178,179,0,68.00,Others,56.00,Others,Science,68.00,Sci&Tech,No,73.00,Mkt&HR,68.07,Placed,350000.0
181,182,0,62.00,Central,60.33,Others,Science,64.21,Sci&Tech,No,63.00,Mkt&HR,60.02,Not Placed,NaN
187,188,0,78.50,Central,65.50,Central,Science,67.00,Sci&Tech,Yes,95.00,Mkt&Fin,64.86,Placed,280000.0
196,197,0,72.00,Others,63.00,Others,Science,77.50,Sci&Tech,Yes,78.00,Mkt&Fin,54.48,Placed,250000.0
202,203,0,70.00,Central,63.00,Central,Science,66.00,Sci&Tech,No,61.28,Mkt&HR,60.11,Placed,240000.0
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0

In [11]:
#8. Get students whose etest_p is between 70 and 90.
data[(data["etest_p"]>70) & (data["etest_p"]<90)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
6,7,1,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
14,15,0,62.00,Central,47.00,Central,Commerce,50.00,Comm&Mgmt,No,76.00,Mkt&HR,54.96,Not Placed,NaN
15,16,1,65.00,Central,75.00,Central,Commerce,69.00,Comm&Mgmt,Yes,72.00,Mkt&Fin,64.66,Placed,200000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,202,0,54.20,Central,63.00,Others,Science,58.00,Comm&Mgmt,No,79.00,Mkt&HR,58.44,Not Placed,NaN
204,205,1,74.00,Others,73.00,Others,Commerce,73.00,Comm&Mgmt,Yes,80.00,Mkt&Fin,67.69,Placed,210000.0
207,208,0,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
214,215,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [12]:
#9. Display students who have hsc_b (HSC board) as “Central” and ssc_b as “Central”.
data[(data["hsc_b"]=="Central") & (data["hsc_b"]=="Central")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
2,3,0,65.0,Central,68.0,Central,Arts,64.0,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
3,4,0,56.0,Central,52.0,Central,Science,52.0,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
4,5,0,85.8,Central,73.6,Central,Commerce,73.3,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
7,8,0,82.0,Central,64.0,Central,Science,66.0,Sci&Tech,Yes,67.00,Mkt&Fin,62.14,Placed,252000.0
8,9,0,73.0,Central,79.0,Central,Commerce,72.0,Comm&Mgmt,No,91.34,Mkt&Fin,61.29,Placed,231000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,0,66.0,Central,76.0,Central,Commerce,72.0,Comm&Mgmt,Yes,84.00,Mkt&HR,58.95,Placed,275000.0
198,199,1,67.0,Central,70.0,Central,Commerce,65.0,Others,No,88.00,Mkt&HR,71.96,Not Placed,NaN
202,203,0,70.0,Central,63.0,Central,Science,66.0,Sci&Tech,No,61.28,Mkt&HR,60.11,Placed,240000.0
206,207,0,41.0,Central,42.0,Central,Science,60.0,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
209,210,0,62.0,Central,72.0,Central,Commerce,65.0,Comm&Mgmt,No,67.00,Mkt&Fin,56.49,Placed,216000.0

In [13]:
#10. Show students with mba_p less than 60 or degree_p less than 60.
data[(data["mba_p"]<60) | (data["degree_p"]<60)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.0,Others,91.0,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
2,3,0,65.0,Central,68.0,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,0,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,0,85.8,Central,73.6,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
5,6,0,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.0,Mkt&Fin,51.58,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,207,0,41.0,Central,42.0,Central,Science,60.00,Comm&Mgmt,No,97.0,Mkt&Fin,53.39,Not Placed,NaN
209,210,0,62.0,Central,72.0,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
211,212,0,58.0,Others,60.0,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
213,214,1,74.0,Others,66.0,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,0,62.0,Central,58.0,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [14]:
#11. Retrieve all students with status equal to “Placed” and salary greater than 400000.
data[(data["status"]=="Placed") | (data["salary"]>400000)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
7,8,0,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,Yes,67.0,Mkt&Fin,62.14,Placed,252000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,0,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0

In [15]:
#12. Display records where degree_t is “Comm&amp;Mgmt”.
data[data["degree_t"]=="Comm&Mgmt"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
2,3,0,65.0,Central,68.0,Central,Arts,64.0,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
4,5,0,85.8,Central,73.6,Central,Commerce,73.3,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
6,7,1,46.0,Others,49.2,Others,Commerce,79.0,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
8,9,0,73.0,Central,79.0,Central,Commerce,72.0,Comm&Mgmt,No,91.34,Mkt&Fin,61.29,Placed,231000.0
9,10,0,58.0,Central,70.0,Central,Commerce,61.0,Comm&Mgmt,No,54.00,Mkt&Fin,52.21,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,0,62.0,Central,72.0,Central,Commerce,65.0,Comm&Mgmt,No,67.00,Mkt&Fin,56.49,Placed,216000.0
210,211,0,80.6,Others,82.0,Others,Commerce,77.6,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
212,213,0,67.0,Others,67.0,Others,Commerce,73.0,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0
213,214,1,74.0,Others,66.0,Others,Commerce,58.0,Comm&Mgmt,No,70.00,Mkt&HR,60.23,Placed,204000.0
214,215,0,62.0,Central,58.0,Others,Science,53.0,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [16]:
#13. Select students whose hsc_p ≥ 85 and workex = “Yes”.
data[(data["hsc_p"]>=85) & (data["workex"]=='Yes')]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
85,86,1,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
129,130,0,76.70,Central,89.70,Others,Commerce,66.00,Comm&Mgmt,Yes,90.00,Mkt&Fin,68.55,Placed,250000.0
134,135,1,77.44,Central,92.00,Others,Commerce,72.00,Comm&Mgmt,Yes,94.00,Mkt&Fin,67.13,Placed,250000.0
162,163,0,74.20,Central,87.60,Others,Commerce,77.25,Comm&Mgmt,Yes,75.20,Mkt&Fin,66.06,Placed,285000.0
177,178,1,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0

In [17]:
#14. Show all students whose gender is “F” and ssc_p &lt; 70.
data[(data["gender"]==0) & (data["ssc_p"]<70)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.0,Others,91.0,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
2,3,0,65.0,Central,68.0,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,0,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
5,6,0,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.0,Mkt&Fin,51.58,Not Placed,NaN
9,10,0,58.0,Central,70.0,Central,Commerce,61.00,Comm&Mgmt,No,54.0,Mkt&Fin,52.21,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,207,0,41.0,Central,42.0,Central,Science,60.00,Comm&Mgmt,No,97.0,Mkt&Fin,53.39,Not Placed,NaN
209,210,0,62.0,Central,72.0,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
211,212,0,58.0,Others,60.0,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.0,Others,67.0,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
214,215,0,62.0,Central,58.0,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [18]:
#15. Find students whose salary is missing (NaN).
data[data["salary"]=='NaN']

Empty DataFrame
Columns: [sl_no, gender, ssc_p, ssc_b, hsc_p, hsc_b, hsc_s, degree_p, degree_t, workex, etest_p, specialisation, mba_p, status, salary]
Index: []

In [19]:
#16. Display top 10 rows where etest_p is highest.
data.sort_values(by="etest_p",ascending=False).head(10)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
152,153,1,75.40,Others,60.5,Central,Science,84.00,Sci&Tech,No,98.00,Mkt&Fin,65.25,Placed,240000.0
24,25,0,76.50,Others,97.7,Others,Science,78.86,Sci&Tech,No,97.40,Mkt&Fin,74.01,Placed,360000.0
118,119,0,76.00,Central,80.0,Central,Science,78.00,Sci&Tech,Yes,97.00,Mkt&HR,70.48,Placed,276000.0
206,207,0,41.00,Central,42.0,Central,Science,60.00,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
4,5,0,85.80,Central,73.6,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
116,117,0,68.20,Central,72.8,Central,Commerce,66.60,Comm&Mgmt,Yes,96.00,Mkt&Fin,70.85,Placed,300000.0
138,139,1,82.00,Others,64.0,Others,Science,73.00,Sci&Tech,Yes,96.00,Mkt&Fin,71.77,Placed,250000.0
189,190,1,54.00,Central,77.6,Others,Commerce,69.20,Comm&Mgmt,No,95.65,Mkt&Fin,66.94,Not Placed,NaN
72,73,0,84.86,Others,67.0,Others,Science,78.00,Comm&Mgmt,No,95.50,Mkt&Fin,68.53,Placed,240000.0
95,96,0,73.00,Central,78.0,Others,Commerce,65.00,Comm&Mgmt,Yes,95.46,Mkt&Fin,62.16,Placed,420000.0

In [20]:
#17. Show all students who have degree_p between 60 and 80.
data[(data["degree_p"]>60) & (data["degree_p"]<80)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
5,6,0,55.00,Others,49.80,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,1,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,209,1,43.00,Central,60.00,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
209,210,0,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.00,Mkt&Fin,56.49,Placed,216000.0
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0

In [21]:
#18. Select students whose specialisation is “Mkt&amp;Fin”.
data[data["specialisation"]=="Mkt&Fin"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.50,Mkt&Fin,66.28,Placed,200000.0
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.00,Mkt&Fin,57.80,Placed,250000.0
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
5,6,0,55.00,Others,49.80,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,1,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,208,0,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
209,210,0,62.00,Central,72.00,Central,Commerce,65.00,Comm&Mgmt,No,67.00,Mkt&Fin,56.49,Placed,216000.0
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0

In [22]:
#19. Retrieve all students with workex = “No” and placed = “No”.
data[(data["workex"]=='No') & (data["status"]=="Not Placed")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.00,Mkt&HR,59.43,Not Placed,NaN
6,7,1,46.00,Others,49.20,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
9,10,0,58.00,Central,70.00,Central,Commerce,61.00,Comm&Mgmt,No,54.00,Mkt&Fin,52.21,Not Placed,NaN
12,13,1,47.00,Central,55.00,Others,Science,65.00,Comm&Mgmt,No,62.00,Mkt&HR,65.04,Not Placed,NaN
14,15,0,62.00,Central,47.00,Central,Commerce,50.00,Comm&Mgmt,No,76.00,Mkt&HR,54.96,Not Placed,NaN
17,18,1,55.00,Central,67.00,Central,Commerce,64.00,Comm&Mgmt,No,60.00,Mkt&Fin,67.28,Not Placed,NaN
18,19,1,63.00,Central,66.00,Central,Commerce,64.00,Comm&Mgmt,No,68.00,Mkt&HR,64.08,Not Placed,NaN
29,30,0,62.00,Central,67.00,Central,Commerce,58.00,Comm&Mgmt,No,77.00,Mkt&Fin,51.29,Not Placed,NaN
31,32,1,67.00,Central,53.00,Central,Science,65.00,Sci&Tech,No,64.00,Mkt&HR,58.32,Not Placed,NaN
34,35,0,62.00,Others,51.00,Others,Science,52.00,Others,No,68.44,Mkt&HR,62.77,Not Placed,NaN
36,37,0,51.00,Central,44.00,Central,Commerce,57.00,Comm&Mgmt,No,64.00,Mkt&Fin,51.45,Not Placed,NaN
42,43,0,49.00,Others,39.00,Central,Science,65.00,Others,No,63.00,Mkt&Fin,51.21,Not Placed,NaN
45,46,1,76.00,Central,64.00,Central,Science,72.00,Sci&Tech,No,58.00,Mkt&HR,66.53,Not Placed,NaN
46,47,1,70.89,Others,71.98,Others,Science,65.60,Comm&Mgmt,No,68.00,Mkt&HR,71.63,Not Placed,NaN
49,50,1,50.00,Others,37.00,Others,Arts,52.00,Others,No,65.00,Mkt&HR,56.11,Not Placed,NaN
51,52,0,54.40,Central,61.12,Central,Commerce,56.20,Comm&Mgmt,No,67.00,Mkt&HR,62.65,Not Placed,NaN
52,53,1,40.89,Others,45.83,Others,Commerce,53.00,Comm&Mgmt,No,71.20,Mkt&HR,65.49,Not Placed,NaN
63,64,0,61.00,Others,70.00,Others,Commerce,64.00,Comm&Mgmt,No,68.50,Mkt&HR,59.50,Not Placed,NaN
65,66,0,54.00,Others,47.00,Others,Science,57.00,Comm&Mgmt,No,89.69,Mkt&HR,57.10,Not Placed,NaN
68,69,1,69.70,Central,47.00,Central,Commerce,72.70,Sci&Tech,No,79.00,Mkt&HR,59.24,Not Placed,NaN
75,76,1,59.00,Central,62.00,Others,Commerce,77.50,Comm&Mgmt,No,74.00,Mkt&HR,67.00,Not Placed,NaN
79,80,1,69.00,Central,62.00,Central,Science,66.00,Sci&Tech,No,75.00,Mkt&HR,67.99,Not Placed,NaN
82,83,0,63.00,Central,67.00,Central,Commerce,74.00,Comm&Mgmt,No,82.00,Mkt&Fin,60.44,Not Placed,NaN
87,88,0,59.60,Central,51.00,Central,Science,60.00,Others,No,75.00,Mkt&HR,59.08,Not Placed,NaN
91,92,0,52.00,Central,57.00,Central,Commerce,50.80,Comm&Mgmt,No,67.00,Mkt&HR,62.79,Not Placed,NaN
93,94,0,52.00,Central,62.00,Central,Commerce,54.00,Comm&Mgmt,No,72.00,Mkt&HR,55.41,Not Placed,NaN
97,98,1,70.50,Central,62.50,Others,Commerce,61.00,Comm&Mgmt,No,93.91,Mkt&Fin,69.03,Not Placed,NaN
99,100,0,54.00,Central,82.00,Others,Commerce,63.00,Sci&Tech,No,50.00,Mkt&Fin,59.47,Not Placed,NaN
105,106,0,59.00,Central,64.00,Others,Science,58.00,Sci&Tech,No,85.00,Mkt&HR,55.30,Not Placed,NaN
106,107,0,61.08,Others,50.00,Others,Science,54.00,Sci&Tech,No,71.00,Mkt&Fin,65.69,Not Placed,NaN
111,112,0,51.00,Others,54.00,Others,Science,61.00,Sci&Tech,No,60.00,Mkt&HR,60.64,Not Placed,NaN
120,121,0,58.00,Others,40.00,Others,Science,59.00,Comm&Mgmt,No,73.00,Mkt&HR,58.81,Not Placed,NaN
130,131,0,62.00,Central,65.00,Others,Commerce,60.00,Comm&Mgmt,No,84.00,Mkt&Fin,64.15,Not Placed,NaN
136,137,1,47.00,Central,59.00,Central,Arts,64.00,Comm&Mgmt,No,78.00,Mkt&Fin,61.58,Not Placed,NaN
141,142,0,66.00,Central,64.00,Central,Science,60.00,Comm&Mgmt,No,60.00,Mkt&HR,61.90,Not Placed,NaN
144,145,0,52.00,Others,50.00,Others,Arts,61.00,Comm&Mgmt,No,60.00,Mkt&Fin,58.52,Not Placed,NaN
158,159,0,67.00,Others,63.00,Others,Science,64.00,Sci&Tech,No,60.00,Mkt&Fin,61.87,Not Placed,NaN
159,160,0,52.00,Central,49.00,Others,Commerce,58.00,Comm&Mgmt,No,62.00,Mkt&HR,60.59,Not Placed,NaN
161,162,0,55.60,Others,51.00,Others,Commerce,57.50,Comm&Mgmt,No,57.63,Mkt&HR,62.72,Not Placed,NaN
165,166,1,63.30,Central,78.33,Others,Commerce,74.00,Comm&Mgmt,No,80.00,Mkt&Fin,74.56,Not Placed,NaN
169,170,0,59.96,Others,42.16,Others,Science,61.26,Sci&Tech,No,54.48,Mkt&HR,65.48,Not Placed,NaN
170,171,1,63.40,Others,67.20,Others,Commerce,60.00,Comm&Mgmt,No,58.06,Mkt&HR,69.28,Not Placed,NaN
173,174,1,52.00,Others,52.00,Others,Science,55.00,Sci&Tech,No,67.00,Mkt&HR,59.32,Not Placed,NaN
175,176,0,63.00,Others,62.00,Others,Science,65.00,Sci&Tech,No,87.50,Mkt&HR,60.69,Not Placed,NaN
179,180,1,77.80,Central,64.00,Central,Science,64.20,Sci&Tech,No,75.50,Mkt&HR,72.14,Not Placed,NaN
181,182,0,62.00,Central,60.33,Others,Science,64.21,Sci&Tech,No,63.00,Mkt&HR,60.02,Not Placed,NaN
184,185,1,56.28,Others,62.83,Others,Commerce,59.79,Comm&Mgmt,No,60.00,Mkt&HR,57.29,Not Placed,NaN
186,187,1,52.00,Central,64.00,Central,Commerce,61.00,Comm&Mgmt,No,55.00,Mkt&Fin,62.93,Not Placed,NaN
188,189,0,61.80,Others,47.00,Others,Commerce,54.38,Comm&Mgmt,No,57.00,Mkt&Fin,56.13,Not Placed,NaN
189,190,1,54.00,Central,77.60,Others,Commerce,69.20,Comm&Mgmt,No,95.65,Mkt&Fin,66.94,Not Placed,NaN
190,191,1,64.00,Others,70.20,Central,Commerce,61.00,Comm&Mgmt,No,50.00,Mkt&Fin,62.50,Not Placed,NaN
194,195,0,52.00,Others,55.00,Others,Commerce,56.30,Comm&Mgmt,No,59.00,Mkt&Fin,64.74,Not Placed,NaN
198,199,1,67.00,Central,70.00,Central,Commerce,65.00,Others,No,88.00,Mkt&HR,71.96,Not Placed,NaN
201,202,0,54.20,Central,63.00,Others,Science,58.00,Comm&Mgmt,No,79.00,Mkt&HR,58.44,Not Placed,NaN
206,207,0,41.00,Central,42.00,Central,Science,60.00,Comm&Mgmt,No,97.00,Mkt&Fin,53.39,Not Placed,NaN
208,209,1,43.00,Central,60.00,Others,Science,65.00,Comm&Mgmt,No,92.66,Mkt&HR,62.92,Not Placed,NaN
214,215,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.00,Mkt&HR,60.22,Not Placed,NaN

In [23]:
#20. Show students who studied in “Others” board in ssc_b.
data[data['ssc_b']=="Others"]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.0,Others,91.0,Others,Commerce,58.00,Sci&Tech,No,55.00,Mkt&HR,58.80,Placed,270000.0
5,6,0,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.00,Mkt&Fin,51.58,Not Placed,NaN
6,7,1,46.0,Others,49.2,Others,Commerce,79.00,Comm&Mgmt,No,74.28,Mkt&Fin,53.29,Not Placed,NaN
19,20,0,60.0,Others,67.0,Others,Arts,70.00,Comm&Mgmt,Yes,50.48,Mkt&Fin,77.89,Placed,236000.0
20,21,0,62.0,Others,65.0,Others,Commerce,66.00,Comm&Mgmt,No,50.00,Mkt&HR,56.70,Placed,265000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,206,0,61.0,Others,62.0,Others,Commerce,65.00,Comm&Mgmt,No,62.00,Mkt&Fin,56.81,Placed,250000.0
210,211,0,80.6,Others,82.0,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
211,212,0,58.0,Others,60.0,Others,Science,72.00,Sci&Tech,No,74.00,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.0,Others,67.0,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0
213,214,1,74.0,Others,66.0,Others,Commerce,58.00,Comm&Mgmt,No,70.00,Mkt&HR,60.23,Placed,204000.0

In [24]:
#21. Display students who have exactly 50 in hsc_p.
data[data["hsc_p"]==50]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
106,107,0,61.08,Others,50.0,Others,Science,54.0,Sci&Tech,No,71.0,Mkt&Fin,65.69,Not Placed,NaN
144,145,0,52.00,Others,50.0,Others,Arts,61.0,Comm&Mgmt,No,60.0,Mkt&Fin,58.52,Not Placed,NaN

In [25]:
#22. Retrieve students whose salary is above average salary.
avg_salary=data["salary"].mean()

In [26]:
data[data["salary"]>avg_salary]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.80,Mkt&Fin,55.50,Placed,425000.0
16,17,0,63.00,Central,66.20,Central,Commerce,65.60,Comm&Mgmt,Yes,60.00,Mkt&Fin,62.54,Placed,300000.0
21,22,1,79.00,Others,76.00,Others,Commerce,85.00,Comm&Mgmt,No,95.00,Mkt&Fin,69.06,Placed,393000.0
22,23,1,69.80,Others,60.80,Others,Science,72.23,Sci&Tech,No,55.53,Mkt&HR,68.81,Placed,360000.0
23,24,1,77.40,Others,60.00,Others,Science,64.74,Sci&Tech,Yes,92.00,Mkt&Fin,63.62,Placed,300000.0
24,25,0,76.50,Others,97.70,Others,Science,78.86,Sci&Tech,No,97.40,Mkt&Fin,74.01,Placed,360000.0
28,29,0,76.76,Others,76.50,Others,Commerce,67.50,Comm&Mgmt,Yes,73.35,Mkt&Fin,64.15,Placed,350000.0
35,36,1,69.00,Central,78.00,Central,Commerce,72.00,Comm&Mgmt,No,71.00,Mkt&HR,62.74,Placed,300000.0
37,38,1,79.00,Central,76.00,Central,Science,65.60,Sci&Tech,No,58.00,Mkt&HR,55.47,Placed,320000.0
39,40,0,81.00,Others,68.00,Others,Science,64.00,Sci&Tech,No,93.00,Mkt&Fin,62.56,Placed,411000.0
43,44,0,87.00,Others,87.00,Others,Commerce,68.00,Comm&Mgmt,No,95.00,Mkt&HR,62.90,Placed,300000.0
53,54,0,80.00,Others,70.00,Others,Science,72.00,Sci&Tech,No,87.00,Mkt&HR,71.04,Placed,450000.0
57,58,0,68.00,Central,76.00,Central,Commerce,74.00,Comm&Mgmt,No,80.00,Mkt&Fin,63.59,Placed,360000.0
61,62,0,84.20,Central,73.40,Central,Commerce,66.89,Comm&Mgmt,No,61.60,Mkt&Fin,62.48,Placed,300000.0
70,71,0,82.00,Others,61.00,Others,Science,62.00,Sci&Tech,No,89.00,Mkt&Fin,65.45,Placed,360000.0
74,75,0,56.60,Central,64.80,Central,Commerce,70.20,Comm&Mgmt,No,84.27,Mkt&Fin,67.20,Placed,336000.0
77,78,0,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,Yes,69.00,Mkt&Fin,57.65,Placed,500000.0
81,82,0,81.70,Others,63.00,Others,Science,67.00,Comm&Mgmt,Yes,86.00,Mkt&Fin,70.20,Placed,300000.0
83,84,0,84.00,Others,79.00,Others,Science,68.00,Sci&Tech,Yes,84.00,Mkt&Fin,66.69,Placed,300000.0
84,85,0,70.00,Central,63.00,Others,Science,70.00,Sci&Tech,Yes,55.00,Mkt&Fin,62.00,Placed,300000.0
85,86,1,83.84,Others,89.83,Others,Commerce,77.20,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
90,91,1,85.00,Others,90.00,Others,Commerce,82.00,Comm&Mgmt,No,92.00,Mkt&Fin,68.03,Placed,300000.0
95,96,0,73.00,Central,78.00,Others,Commerce,65.00,Comm&Mgmt,Yes,95.46,Mkt&Fin,62.16,Placed,420000.0
96,97,1,76.00,Central,70.00,Central,Science,76.00,Comm&Mgmt,Yes,66.00,Mkt&Fin,64.44,Placed,300000.0
101,102,0,63.00,Central,72.00,Central,Commerce,68.00,Comm&Mgmt,No,78.00,Mkt&HR,60.44,Placed,380000.0
102,103,1,77.00,Others,61.00,Others,Commerce,68.00,Comm&Mgmt,Yes,57.50,Mkt&Fin,61.31,Placed,300000.0
104,105,0,69.00,Central,63.00,Others,Science,65.00,Comm&Mgmt,Yes,55.00,Mkt&HR,58.23,Placed,360000.0
108,109,0,61.00,Central,82.00,Central,Commerce,69.00,Comm&Mgmt,No,84.00,Mkt&Fin,58.31,Placed,300000.0
116,117,0,68.20,Central,72.80,Central,Commerce,66.60,Comm&Mgmt,Yes,96.00,Mkt&Fin,70.85,Placed,300000.0
119,120,0,60.80,Central,68.40,Central,Commerce,64.60,Comm&Mgmt,Yes,82.66,Mkt&Fin,64.34,Placed,940000.0
125,126,1,84.00,Central,73.00,Central,Commerce,73.00,Comm&Mgmt,No,75.00,Mkt&Fin,73.33,Placed,350000.0
128,129,0,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,Yes,81.20,Mkt&HR,76.26,Placed,400000.0
131,132,1,74.90,Others,57.00,Others,Science,62.00,Others,Yes,80.00,Mkt&Fin,60.78,Placed,360000.0
132,133,0,67.00,Others,68.00,Others,Commerce,64.00,Comm&Mgmt,Yes,74.40,Mkt&HR,53.49,Placed,300000.0
143,144,0,77.67,Others,64.89,Others,Commerce,70.67,Comm&Mgmt,No,89.00,Mkt&Fin,60.39,Placed,300000.0
145,146,0,89.40,Others,65.66,Others,Science,71.25,Sci&Tech,No,72.00,Mkt&HR,63.23,Placed,400000.0
147,148,0,70.00,Central,74.00,Central,Commerce,65.00,Comm&Mgmt,No,83.00,Mkt&Fin,62.28,Placed,300000.0
150,151,0,71.00,Central,58.66,Central,Science,58.00,Sci&Tech,Yes,56.00,Mkt&Fin,61.30,Placed,690000.0
153,154,0,49.00,Others,59.00,Others,Science,65.00,Sci&Tech,Yes,86.00,Mkt&Fin,62.48,Placed,340000.0
157,158,0,66.50,Central,62.50,Central,Commerce,60.90,Comm&Mgmt,No,93.40,Mkt&Fin,55.03,Placed,300000.0
160,161,0,87.00,Central,74.00,Central,Science,65.00,Sci&Tech,Yes,75.00,Mkt&HR,72.29,Placed,300000.0
163,164,0,63.00,Others,67.00,Others,Science,64.00,Sci&Tech,No,75.00,Mkt&Fin,66.46,Placed,500000.0
171,172,0,80.00,Others,80.00,Others,Commerce,72.00,Comm&Mgmt,Yes,63.79,Mkt&Fin,66.04,Placed,290000.0
172,173,0,73.00,Others,58.00,Others,Commerce,56.00,Comm&Mgmt,No,84.00,Mkt&HR,52.64,Placed,300000.0
174,175,0,73.24,Others,50.83,Others,Science,64.27,Sci&Tech,Yes,64.00,Mkt&Fin,66.23,Placed,500000.0
177,178,1,73.00,Central,97.00,Others,Commerce,79.00,Comm&Mgmt,Yes,89.00,Mkt&Fin,70.81,Placed,650000.0
178,179,0,68.00,Others,56.00,Others,Science,68.00,Sci&Tech,No,73.00,Mkt&HR,68.07,Placed,350000.0
193,194,1,60.00,Central,63.00,Central,Arts,56.00,Others,Yes,80.00,Mkt&HR,56.63,Placed,300000.0
200,201,0,69.00,Others,60.00,Others,Commerce,65.00,Comm&Mgmt,No,87.55,Mkt&Fin,52.81,Placed,300000.0
207,208,0,83.33,Central,78.00,Others,Commerce,61.00,Comm&Mgmt,Yes,88.56,Mkt&Fin,71.55,Placed,300000.0
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.00,Mkt&Fin,69.72,Placed,295000.0

In [27]:
#23. Show records where both hsc_p and ssc_p are above 80.
data[(data["hsc_p"]>80) & (data["ssc_p"]>80)]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
43,44,0,87.00,Others,87.00,Others,Commerce,68.0,Comm&Mgmt,No,95.00,Mkt&HR,62.90,Placed,300000.0
78,79,0,84.00,Others,90.90,Others,Science,64.5,Sci&Tech,No,86.04,Mkt&Fin,59.42,Placed,270000.0
85,86,1,83.84,Others,89.83,Others,Commerce,77.2,Comm&Mgmt,Yes,78.74,Mkt&Fin,76.18,Placed,400000.0
90,91,1,85.00,Others,90.00,Others,Commerce,82.0,Comm&Mgmt,No,92.00,Mkt&Fin,68.03,Placed,300000.0
107,108,0,82.00,Others,90.00,Others,Commerce,83.0,Comm&Mgmt,No,80.00,Mkt&HR,73.52,Placed,200000.0
210,211,0,80.60,Others,82.00,Others,Commerce,77.6,Comm&Mgmt,No,91.00,Mkt&Fin,74.49,Placed,400000.0

In [28]:
#24. Find students with etest_p exactly equal to 100.
data[data["etest_p"]==100]

Empty DataFrame
Columns: [sl_no, gender, ssc_p, ssc_b, hsc_p, hsc_b, hsc_s, degree_p, degree_t, workex, etest_p, specialisation, mba_p, status, salary]
Index: []

In [29]:
#25. Display students with either hsc_b = “Central” or ssc_b = “Others”.
data[(data["hsc_b"]=="Central") | (data["ssc_b"]=="Others")]

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,0,67.0,Others,91.0,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
2,3,0,65.0,Central,68.0,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,0,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,0,85.8,Central,73.6,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
5,6,0,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,Yes,55.0,Mkt&Fin,51.58,Not Placed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,0,62.0,Central,72.0,Central,Commerce,65.00,Comm&Mgmt,No,67.0,Mkt&Fin,56.49,Placed,216000.0
210,211,0,80.6,Others,82.0,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,0,58.0,Others,60.0,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,0,67.0,Others,67.0,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,1,74.0,Others,66.0,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0

In [30]:
#26. Add a new column overall_avg = (ssc_p + hsc_p + degree_p + mba_p) / 4.
data["overall_avg"]=(data["ssc_p"]+data["hsc_p"]+data["degree_p"]+data["mba_p"])/4

In [31]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800
213,214,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575
214,215,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050

In [32]:
#27. Rename the column degree_p to degree_percentage.
data.rename(columns={"degree_p":"degree_percentage"})

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_percentage,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800
213,214,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575
214,215,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050

In [33]:
data["degree_percentage"]=data["degree_p"]

In [34]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00
213,214,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00
214,215,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00

In [35]:
#28. Create a new column placement_status = “Hired” if status = “Placed” else “Not Hired”.
data["placement_status"]=data["status"].apply(lambda x:"Hired" if x=="Placed" else "Not Hired")

In [36]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00,Not Hired
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired
213,214,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired
214,215,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00,Not Hired

In [37]:
#29. Drop the column sl_no.
data.drop("sl_no",axis=1)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status
0,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired
1,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired
2,0,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired
3,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00,Not Hired
4,0,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,0,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired
211,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired
212,0,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired
213,1,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired
214,0,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00,Not Hired

In [38]:
#30. Replace all “Comm&amp;Mgmt” in degree_t with “Commerce”.
data["degree_t"]=data["degree_t"].replace("Comm&Mgmt","Commerce")

In [39]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status
0,1,0,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired
1,2,0,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired
2,3,0,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired
3,4,0,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00,Not Hired
4,5,0,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,0,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired
211,212,0,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired
212,213,0,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired
213,214,1,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired
214,215,0,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00,Not Hired

In [40]:
#31. Convert gender column values “M” → “Male”, “F” → “Female”.
data["gender"]=data['gender'].replace((0,1),("F","M"))

In [41]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status
0,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired
1,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired
2,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired
3,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00,Not Hired
4,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired
211,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired
212,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired
213,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired
214,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00,Not Hired

In [42]:
#32. Create a new column above_80_ssc = True if ssc_p &gt; 80 else False.
data["above_80_ssc"]=data["ssc_p"].apply(lambda x:True if x>80 else False)

In [43]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status,above_80_ssc
0,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired,False
1,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired,False
2,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired,False
3,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00,Not Hired,False
4,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired,True
211,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired,False
212,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired,False
213,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired,False
214,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00,Not Hired,False

In [44]:
#33. Round all percentage columns to 1 decimal place.
data.round(1)

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status,above_80_ssc
0,1,F,67.0,Others,91.0,Others,Commerce,58.0,Sci&Tech,No,55.0,Mkt&HR,58.8,Placed,270000.0,68.7,58.0,Hired,False
1,2,F,79.3,Central,78.3,Others,Science,77.5,Sci&Tech,Yes,86.5,Mkt&Fin,66.3,Placed,200000.0,75.4,77.5,Hired,False
2,3,F,65.0,Central,68.0,Central,Arts,64.0,Commerce,No,75.0,Mkt&Fin,57.8,Placed,250000.0,63.7,64.0,Hired,False
3,4,F,56.0,Central,52.0,Central,Science,52.0,Sci&Tech,No,66.0,Mkt&HR,59.4,Not Placed,NaN,54.9,52.0,Not Hired,False
4,5,F,85.8,Central,73.6,Central,Commerce,73.3,Commerce,No,96.8,Mkt&Fin,55.5,Placed,425000.0,72.0,73.3,Hired,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.6,Others,82.0,Others,Commerce,77.6,Commerce,No,91.0,Mkt&Fin,74.5,Placed,400000.0,78.7,77.6,Hired,True
211,212,F,58.0,Others,60.0,Others,Science,72.0,Sci&Tech,No,74.0,Mkt&Fin,53.6,Placed,275000.0,60.9,72.0,Hired,False
212,213,F,67.0,Others,67.0,Others,Commerce,73.0,Commerce,Yes,59.0,Mkt&Fin,69.7,Placed,295000.0,69.2,73.0,Hired,False
213,214,M,74.0,Others,66.0,Others,Commerce,58.0,Commerce,No,70.0,Mkt&HR,60.2,Placed,204000.0,64.6,58.0,Hired,False
214,215,F,62.0,Central,58.0,Others,Science,53.0,Commerce,No,89.0,Mkt&HR,60.2,Not Placed,NaN,58.3,53.0,Not Hired,False

In [45]:
#34. Convert all column names to lowercase.
data.columns.str.lower()

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary', 'overall_avg', 'degree_percentage',
       'placement_status', 'above_80_ssc'],
      dtype='object')

In [46]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status,above_80_ssc
0,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired,False
1,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired,False
2,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired,False
3,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00,Not Hired,False
4,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired,True
211,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired,False
212,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired,False
213,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired,False
214,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00,Not Hired,False

In [47]:
#35. Add a new column salary_in_lpa = salary / 100000.
data["salary_in_lpa"]=data["salary"]/100000

In [48]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa
0,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired,False,2.70
1,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired,False,2.00
2,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired,False,2.50
3,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00,Not Hired,False,NaN
4,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired,True,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired,True,4.00
211,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired,False,2.75
212,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired,False,2.95
213,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired,False,2.04
214,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00,Not Hired,False,NaN

In [49]:
#36. Replace NaN values in salary with 0.
data["salary"].replace("NaN",0.0)

0      270000.0
1      200000.0
2      250000.0
3           NaN
4      425000.0
         ...
210    400000.0
211    275000.0
212    295000.0
213    204000.0
214         NaN
Name: salary, Length: 215, dtype: float64

In [50]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa
0,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired,False,2.70
1,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired,False,2.00
2,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired,False,2.50
3,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN,54.8575,52.00,Not Hired,False,NaN
4,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired,True,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired,True,4.00
211,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired,False,2.75
212,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired,False,2.95
213,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired,False,2.04
214,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,60.22,Not Placed,NaN,58.3050,53.00,Not Hired,False,NaN

In [51]:
data['salary'] = data['salary'].fillna(0)

In [52]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa
0,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired,False,2.70
1,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired,False,2.00
2,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired,False,2.50
3,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0,54.8575,52.00,Not Hired,False,NaN
4,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired,True,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired,True,4.00
211,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired,False,2.75
212,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired,False,2.95
213,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired,False,2.04
214,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,60.22,Not Placed,0.0,58.3050,53.00,Not Hired,False,NaN

In [53]:
#37. Drop all duplicate rows from the dataset.
data.drop_duplicates()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa
0,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0,68.7000,58.00,Hired,False,2.70
1,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0,75.3550,77.48,Hired,False,2.00
2,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,57.80,Placed,250000.0,63.7000,64.00,Hired,False,2.50
3,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0,54.8575,52.00,Not Hired,False,NaN
4,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,55.50,Placed,425000.0,72.0500,73.30,Hired,True,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,74.49,Placed,400000.0,78.6725,77.60,Hired,True,4.00
211,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0,60.9050,72.00,Hired,False,2.75
212,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0,69.1800,73.00,Hired,False,2.95
213,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,60.23,Placed,204000.0,64.5575,58.00,Hired,False,2.04
214,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,60.22,Not Placed,0.0,58.3050,53.00,Not Hired,False,NaN

In [54]:
#38. Increase all mba_p scores by 5 points.
data["mba_p"]=data["mba_p"]+5

In [55]:
data

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa
0,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,63.80,Placed,270000.0,68.7000,58.00,Hired,False,2.70
1,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,71.28,Placed,200000.0,75.3550,77.48,Hired,False,2.00
2,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,62.80,Placed,250000.0,63.7000,64.00,Hired,False,2.50
3,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,64.43,Not Placed,0.0,54.8575,52.00,Not Hired,False,NaN
4,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,60.50,Placed,425000.0,72.0500,73.30,Hired,True,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,79.49,Placed,400000.0,78.6725,77.60,Hired,True,4.00
211,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,58.62,Placed,275000.0,60.9050,72.00,Hired,False,2.75
212,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,74.72,Placed,295000.0,69.1800,73.00,Hired,False,2.95
213,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,65.23,Placed,204000.0,64.5575,58.00,Hired,False,2.04
214,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,65.22,Not Placed,0.0,58.3050,53.00,Not Hired,False,NaN

In [56]:
#39. Convert salary column to integer type.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sl_no              215 non-null    int64
 1   gender             215 non-null    object
 2   ssc_p              215 non-null    float64
 3   ssc_b              215 non-null    object
 4   hsc_p              215 non-null    float64
 5   hsc_b              215 non-null    object
 6   hsc_s              215 non-null    object
 7   degree_p           215 non-null    float64
 8   degree_t           215 non-null    object
 9   workex             215 non-null    object
 10  etest_p            215 non-null    float64
 11  specialisation     215 non-null    object
 12  mba_p              215 non-null    float64
 13  status             215 non-null    object
 14  salary             215 non-null    float64
 15  overall_avg        215 non-null    float64
 16  degree_percentage  215 non-null    float64
 17  placement_status   215 non-null    object
 18  above_80_ssc       215 non-null    bool
 19  salary_in_lpa      148 non-null    float64
dtypes: bool(1), float64(9), int64(1), object(9)
memory usage: 32.3+ KB

In [57]:
data["salary"].astype("int")

0      270000
1      200000
2      250000
3           0
4      425000
        ...
210    400000
211    275000
212    295000
213    204000
214         0
Name: salary, Length: 215, dtype: int64

In [58]:
#40. Reorder columns to make status the first column.
status_data=data.pop("status")
data.insert(0,"status",status_data)

In [59]:
data

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,63.80,270000.0,68.7000,58.00,Hired,False,2.70
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,71.28,200000.0,75.3550,77.48,Hired,False,2.00
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,No,75.0,Mkt&Fin,62.80,250000.0,63.7000,64.00,Hired,False,2.50
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,64.43,0.0,54.8575,52.00,Not Hired,False,NaN
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,No,96.8,Mkt&Fin,60.50,425000.0,72.0500,73.30,Hired,True,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,No,91.0,Mkt&Fin,79.49,400000.0,78.6725,77.60,Hired,True,4.00
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,58.62,275000.0,60.9050,72.00,Hired,False,2.75
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,Yes,59.0,Mkt&Fin,74.72,295000.0,69.1800,73.00,Hired,False,2.95
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,No,70.0,Mkt&HR,65.23,204000.0,64.5575,58.00,Hired,False,2.04
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,No,89.0,Mkt&HR,65.22,0.0,58.3050,53.00,Not Hired,False,NaN

In [60]:
#41. Replace all “Yes”/“No” in workex with 1/0.
data["workex"]=data["workex"].replace(("Yes","No"),(1,0))

C:\Users\rames\AppData\Local\Temp\ipykernel_30088\3262946218.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["workex"]=data["workex"].replace(("Yes","No"),(1,0))

In [61]:
data

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,0,55.0,Mkt&HR,63.80,270000.0,68.7000,58.00,Hired,False,2.70
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,1,86.5,Mkt&Fin,71.28,200000.0,75.3550,77.48,Hired,False,2.00
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,0,75.0,Mkt&Fin,62.80,250000.0,63.7000,64.00,Hired,False,2.50
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,0,66.0,Mkt&HR,64.43,0.0,54.8575,52.00,Not Hired,False,NaN
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,0,96.8,Mkt&Fin,60.50,425000.0,72.0500,73.30,Hired,True,4.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,0,91.0,Mkt&Fin,79.49,400000.0,78.6725,77.60,Hired,True,4.00
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,0,74.0,Mkt&Fin,58.62,275000.0,60.9050,72.00,Hired,False,2.75
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,1,59.0,Mkt&Fin,74.72,295000.0,69.1800,73.00,Hired,False,2.95
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,0,70.0,Mkt&HR,65.23,204000.0,64.5575,58.00,Hired,False,2.04
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,0,89.0,Mkt&HR,65.22,0.0,58.3050,53.00,Not Hired,False,NaN

In [62]:
#42. Create a new column performance_tag: “Excellent” if degree_p &gt; 80 else “Average”.
data["performance_tag"]=data["degree_p"].apply(lambda x:"Excellent" if x>80 else "Average")

In [63]:
data

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,etest_p,specialisation,mba_p,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,55.0,Mkt&HR,63.80,270000.0,68.7000,58.00,Hired,False,2.70,Average
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,86.5,Mkt&Fin,71.28,200000.0,75.3550,77.48,Hired,False,2.00,Average
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,75.0,Mkt&Fin,62.80,250000.0,63.7000,64.00,Hired,False,2.50,Average
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,...,66.0,Mkt&HR,64.43,0.0,54.8575,52.00,Not Hired,False,NaN,Average
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,96.8,Mkt&Fin,60.50,425000.0,72.0500,73.30,Hired,True,4.25,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,91.0,Mkt&Fin,79.49,400000.0,78.6725,77.60,Hired,True,4.00,Average
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,74.0,Mkt&Fin,58.62,275000.0,60.9050,72.00,Hired,False,2.75,Average
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,59.0,Mkt&Fin,74.72,295000.0,69.1800,73.00,Hired,False,2.95,Average
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,70.0,Mkt&HR,65.23,204000.0,64.5575,58.00,Hired,False,2.04,Average
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,89.0,Mkt&HR,65.22,0.0,58.3050,53.00,Not Hired,False,NaN,Average

In [64]:
#43. Standardize all column names to snake_case (e.g., ssc_p → ssc_percentage).
#data.rename(columns={"degree_t":"degree_type","ssc_p":"ssc_percentage"})

In [65]:
#44. Create a new column combining degree_t and specialisation (e.g., “Sci&amp;Tech_Mkt&amp;HR”).
data["degree_and_specialization"]=data["degree_t"]+"_"+data["specialisation"]

In [66]:
data

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,specialisation,mba_p,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,Mkt&HR,63.80,270000.0,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,Mkt&Fin,71.28,200000.0,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,Mkt&Fin,62.80,250000.0,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,...,Mkt&HR,64.43,0.0,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,Mkt&Fin,60.50,425000.0,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,Mkt&Fin,79.49,400000.0,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,Mkt&Fin,58.62,275000.0,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,Mkt&Fin,74.72,295000.0,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,Mkt&HR,65.23,204000.0,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,Mkt&HR,65.22,0.0,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR

In [67]:
#45. Fill missing etest_p values with mean of that column.
data["etest_p"].unique()

array([55.  , 86.5 , 75.  , 66.  , 96.8 , 74.28, 67.  , 91.34, 54.  ,
       62.  , 60.  , 68.  , 76.  , 72.  , 50.48, 50.  , 95.  , 55.53,
       92.  , 97.4 , 94.  , 73.35, 77.  , 52.  , 64.  , 50.89, 88.  ,
       68.44, 71.  , 58.  , 53.7 , 93.  , 65.  , 63.  , 89.  , 78.  ,
       71.2 , 87.  , 80.  , 74.  , 57.6 , 61.6 , 59.  , 68.5 , 61.  ,
       89.69, 68.92, 68.71, 79.  , 70.  , 95.5 , 86.  , 84.27, 69.  ,
       86.04, 82.  , 84.  , 78.74, 53.88, 95.46, 93.91, 56.39, 57.5 ,
       85.  , 57.2 , 72.15, 96.  , 97.  , 82.66, 73.  , 55.67, 80.4 ,
       55.5 , 81.2 , 90.  , 74.4 , 55.6 , 56.  , 83.  , 57.  , 64.25,
       98.  , 56.15, 93.4 , 57.63, 75.2 , 53.04, 58.1 , 54.48, 58.06,
       63.79, 87.5 , 75.5 , 95.65, 59.32, 87.55, 61.28, 88.56, 92.66,
       91.  ])

In [68]:
data["etest_p"].mean()

np.float64(72.10055813953488)

In [69]:
#46. Create a new column total_score = ssc_p + hsc_p + degree_p + mba_p.
data["total_score"]=data["ssc_p"]+data["hsc_p"]+data["degree_p"]+data["mba_p"]

In [70]:
data

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,mba_p,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,63.80,270000.0,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,71.28,200000.0,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,62.80,250000.0,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,...,64.43,0.0,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,60.50,425000.0,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,79.49,400000.0,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,58.62,275000.0,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,74.72,295000.0,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,65.23,204000.0,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,65.22,0.0,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22

In [71]:
#47. Drop students whose hsc_p &lt; 40.
data.drop(data[data["hsc_p"]<40].index,inplace=True)

In [72]:
data

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,mba_p,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,63.80,270000.0,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,71.28,200000.0,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,62.80,250000.0,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,...,64.43,0.0,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,60.50,425000.0,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,79.49,400000.0,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,58.62,275000.0,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,74.72,295000.0,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,65.23,204000.0,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,65.22,0.0,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22

In [73]:
#48. Create a boolean column is_placed = True if status = “Placed”.
data["is_placed"]=data["status"].apply(lambda x:True if x=="Placed" else False)

In [74]:
data

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,salary,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,270000.0,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,200000.0,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,250000.0,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,...,0.0,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,425000.0,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,400000.0,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,275000.0,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,295000.0,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,204000.0,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,0.0,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False

In [75]:
#49. Add a column mba_grade = “A” if mba_p ≥ 75 else “B”.
data["mba_grade"]=data["mba_p"].apply(lambda x:"A" if x>=75 else "B")

In [76]:
data

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,...,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False,B
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True,B
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True,B
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [77]:
#50. Replace NaN salaries for non-placed students with 0.
data["status"].value_counts()

status
Placed        148
Not Placed     65
Name: count, dtype: int64

In [78]:
#51. Count how many students are in each gender.
data["gender"].value_counts()

gender
F    138
M     75
Name: count, dtype: int64

In [79]:
#52. Find the average mba_p for each specialisation.
data.groupby("specialisation")["mba_p"].mean()

specialisation
Mkt&Fin    67.923277
Mkt&HR     66.644894
Name: mba_p, dtype: float64

In [80]:
data["specialisation"].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [81]:
#53. Get the mean degree_p for placed vs non-placed students.
data.groupby("status")["degree_p"].mean()

status
Not Placed    61.215231
Placed        68.740541
Name: degree_p, dtype: float64

In [82]:
#54. Find the maximum salary for each specialisation.
data.groupby("specialisation")["salary"].max()

specialisation
Mkt&Fin    940000.0
Mkt&HR     450000.0
Name: salary, dtype: float64

In [83]:
#55. Count the number of students with and without workex.
data.groupby("workex")["sl_no"].count()

workex
0    139
1     74
Name: sl_no, dtype: int64

In [84]:
#56. Calculate the average etest_p for each degree_t.
data.groupby("degree_t")["etest_p"].mean()

degree_t
Commerce    71.985241
Others      74.382222
Sci&Tech    72.310508
Name: etest_p, dtype: float64

In [85]:
#57. Find the total number of placed students per degree_t.
data1=data[data["status"]=="Placed"]

In [86]:
data1.groupby("degree_t")["status"].count()

degree_t
Commerce    102
Others        5
Sci&Tech     41
Name: status, dtype: int64

In [87]:
#58. Get the minimum hsc_p for each hsc_b.
data.groupby("hsc_b")["hsc_p"].min()

hsc_b
Central    42.0
Others     40.0
Name: hsc_p, dtype: float64

In [88]:
#59. Count of students in each specialisation grouped by gender.
data.groupby(["gender","specialisation"])["sl_no"].count()

gender  specialisation
F       Mkt&Fin           82
        Mkt&HR            56
M       Mkt&Fin           37
        Mkt&HR            38
Name: sl_no, dtype: int64

In [89]:
#60. Find the highest mba_p among placed students.
data[data["status"]=="Placed"]["mba_p"].max()

82.89

In [90]:
#61. Calculate mean, min, and max ssc_p for each gender.
g_gender=data.groupby("gender")

In [91]:
g_gender["ssc_p"].mean()

gender
F    66.881159
M    68.555067
Name: ssc_p, dtype: float64

In [92]:
g_gender["ssc_p"].min()

gender
F    41.00
M    40.89
Name: ssc_p, dtype: float64

In [93]:
g_gender["ssc_p"].max()

gender
F    89.4
M    88.0
Name: ssc_p, dtype: float64

In [94]:
#62. Count how many students have each unique combination of degree_t and workex.
data.groupby(["degree_t","workex"])["sl_no"].count()

degree_t  workex
Commerce  0         100
          1          45
Others    0           5
          1           4
Sci&Tech  0          34
          1          25
Name: sl_no, dtype: int64

In [95]:
#63. Find the number of placed students per hsc_b.
placed=data[data["status"]=="Placed"]

In [96]:
placed.groupby("hsc_b")["sl_no"].count()

hsc_b
Central    57
Others     91
Name: sl_no, dtype: int64

In [97]:
#64. Get average salary for each specialisation grouped by workex.
data.groupby(["workex","specialisation"])['salary'].mean()

workex  specialisation
0       Mkt&Fin           200411.764706
        Mkt&HR            136394.366197
1       Mkt&Fin           289470.588235
        Mkt&HR            202000.000000
Name: salary, dtype: float64

In [98]:
#65. Calculate the average of all numeric columns for each degree_t.
g_degree=data.groupby("degree_t").mean(numeric_only=True)

In [99]:
g_degree

,sl_no,ssc_p,hsc_p,degree_p,workex,etest_p,mba_p,salary,overall_avg,degree_percentage,above_80_ssc,salary_in_lpa,total_score,is_placed
degree_t,,,,,,,,,,,,,,
Commerce,106.275862,65.955586,67.185379,66.203103,0.310345,71.985241,66.865379,196000.000000,65.302362,66.203103,0.096552,2.786275,266.209448,0.703448
Others,143.444444,67.500000,65.111111,61.147778,0.444444,74.382222,68.088889,155777.777778,64.211944,61.147778,0.111111,2.804000,261.847778,0.555556
Sci&Tech,108.915254,71.189322,65.385593,67.844237,0.423729,72.310508,68.461186,218627.118644,66.970085,67.844237,0.237288,3.146098,272.880339,0.694915

In [100]:
#66. Find the number of students with etest_p &gt; 80 grouped by workex.
etest=data[data["etest_p"]>80]

In [101]:
etest.groupby("workex")["sl_no"].count()

workex
0    37
1    24
Name: sl_no, dtype: int64

In [102]:
#67. Display count of placed and not placed students per degree_t.
data.groupby(["degree_t","status"])["sl_no"].count()

degree_t  status
Commerce  Not Placed     43
          Placed        102
Others    Not Placed      4
          Placed          5
Sci&Tech  Not Placed     18
          Placed         41
Name: sl_no, dtype: int64

In [103]:
#68. Show mean mba_p for each specialisation and gender.
data.groupby(["specialisation","gender"])["mba_p"].mean()

specialisation  gender
Mkt&Fin         F         66.578293
                M         70.904054
Mkt&HR          F         65.290536
                M         68.640789
Name: mba_p, dtype: float64

In [104]:
#69. Find how many students from each hsc_b got placed.
placed

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
7,Placed,8,F,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,...,68.5350,66.00,Hired,True,2.52,Average,Sci&Tech_Mkt&Fin,279.14,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,Placed,210,F,62.00,Central,72.00,Central,Commerce,65.00,Commerce,...,63.8725,65.00,Hired,False,2.16,Average,Commerce_Mkt&Fin,260.49,True,B
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True,B
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True,B

In [105]:
placed.groupby('hsc_b')["sl_no"].count()

hsc_b
Central    57
Others     91
Name: sl_no, dtype: int64

In [106]:
#70. Get both min and max salary for each specialisation.
g_sp=data.groupby("specialisation")

In [107]:
g_sp["salary"].min()

specialisation
Mkt&Fin    0.0
Mkt&HR     0.0
Name: salary, dtype: float64

In [108]:
g_sp["salary"].max()

specialisation
Mkt&Fin    940000.0
Mkt&HR     450000.0
Name: salary, dtype: float64

In [109]:
#71. Display number of unique degree_t values for each workex group.
data.groupby(["workex","degree_t"])["sl_no"].count()

workex  degree_t
0       Commerce    100
        Others        5
        Sci&Tech     34
1       Commerce     45
        Others        4
        Sci&Tech     25
Name: sl_no, dtype: int64

In [110]:
data.groupby(["workex"])["degree_t"].unique()

workex
0    [Sci&Tech, Commerce, Others]
1    [Sci&Tech, Commerce, Others]
Name: degree_t, dtype: object

In [111]:
#72. Find average degree_p per hsc_b and ssc_b.
data.groupby(["hsc_b","ssc_b"])["degree_p"].mean()

hsc_b    ssc_b
Central  Central    65.547922
         Others     68.521667
Others   Central    67.225641
         Others     66.730440
Name: degree_p, dtype: float64

In [112]:
#73. Calculate total number of students grouped by specialisation and status.
data.groupby(["specialisation","status"])["sl_no"].count()

specialisation  status
Mkt&Fin         Not Placed    24
                Placed        95
Mkt&HR          Not Placed    41
                Placed        53
Name: sl_no, dtype: int64

In [122]:
#74. Find which degree_t has the highest average placement rate.
aa=data.groupby(["degree_t","status"])["is_placed"].count().reset_index()

In [123]:
data.groupby('degree_t').mean(numeric_only=True)

,sl_no,ssc_p,hsc_p,degree_p,workex,etest_p,mba_p,salary,overall_avg,degree_percentage,above_80_ssc,salary_in_lpa,total_score,is_placed
degree_t,,,,,,,,,,,,,,
Commerce,106.275862,65.955586,67.185379,66.203103,0.310345,71.985241,66.865379,196000.000000,65.302362,66.203103,0.096552,2.786275,266.209448,0.703448
Others,143.444444,67.500000,65.111111,61.147778,0.444444,74.382222,68.088889,155777.777778,64.211944,61.147778,0.111111,2.804000,261.847778,0.555556
Sci&Tech,108.915254,71.189322,65.385593,67.844237,0.423729,72.310508,68.461186,218627.118644,66.970085,67.844237,0.237288,3.146098,272.880339,0.694915

In [124]:
aa

   degree_t      status  is_placed
0  Commerce  Not Placed         43
1  Commerce      Placed        102
2    Others  Not Placed          4
3    Others      Placed          5
4  Sci&Tech  Not Placed         18
5  Sci&Tech      Placed         41

In [125]:
aa1=data.groupby(["degree_t"])["sl_no"].count().reset_index()

In [126]:
aa1

   degree_t  sl_no
0  Commerce    145
1    Others      9
2  Sci&Tech     59

In [127]:
merge=pd.merge(aa,aa1,left_on="degree_t",right_on="degree_t",how="inner")

In [128]:
merge

   degree_t      status  is_placed  sl_no
0  Commerce  Not Placed         43    145
1  Commerce      Placed        102    145
2    Others  Not Placed          4      9
3    Others      Placed          5      9
4  Sci&Tech  Not Placed         18     59
5  Sci&Tech      Placed         41     59

In [129]:
my_placed=merge[merge["status"]=="Placed"]

In [130]:
my_placed

   degree_t  status  is_placed  sl_no
1  Commerce  Placed        102    145
3    Others  Placed          5      9
5  Sci&Tech  Placed         41     59

In [131]:
my_placed["place_rate"]=(my_placed['is_placed']/my_placed["sl_no"])*100

C:\Users\rames\AppData\Local\Temp\ipykernel_30088\808229152.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_placed["place_rate"]=(my_placed['is_placed']/my_placed["sl_no"])*100

In [132]:
my_placed

   degree_t  status  is_placed  sl_no  place_rate
1  Commerce  Placed        102    145   70.344828
3    Others  Placed          5      9   55.555556
5  Sci&Tech  Placed         41     59   69.491525

In [133]:
my_placed["place_rate"].max()

70.34482758620689

In [135]:
#75. Display how many students scored more than 70 in mba_p for each specialisation.
mba=data[data["mba_p"]>70]

In [137]:
mba

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
12,Not Placed,13,M,47.00,Central,55.00,Others,Science,65.00,Commerce,...,58.0100,65.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,237.04,False,B
13,Placed,14,M,77.00,Central,87.00,Central,Commerce,59.00,Commerce,...,72.9075,59.00,Hired,False,2.18,Average,Commerce_Mkt&Fin,296.63,True,B
17,Not Placed,18,M,55.00,Central,67.00,Central,Commerce,64.00,Commerce,...,63.3200,64.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,258.28,False,B
19,Placed,20,F,60.00,Others,67.00,Others,Arts,70.00,Commerce,...,68.7225,70.00,Hired,False,2.36,Average,Commerce_Mkt&Fin,279.89,True,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,Not Placed,199,M,67.00,Central,70.00,Central,Commerce,65.00,Others,...,68.4900,65.00,Not Hired,False,NaN,Average,Others_Mkt&HR,278.96,False,A
204,Placed,205,M,74.00,Others,73.00,Others,Commerce,73.00,Commerce,...,71.9225,73.00,Hired,False,2.10,Average,Commerce_Mkt&Fin,292.69,True,B
207,Placed,208,F,83.33,Central,78.00,Others,Commerce,61.00,Commerce,...,73.4700,61.00,Hired,True,3.00,Average,Commerce_Mkt&Fin,298.88,True,A
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B

In [136]:
mba.groupby("specialisation")['sl_no'].count()

specialisation
Mkt&Fin    44
Mkt&HR     25
Name: sl_no, dtype: int64

In [138]:
#76. Sort dataset by salary in descending order.
data.sort_values(by="salary",ascending=False)

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
119,Placed,120,F,60.80,Central,68.40,Central,Commerce,64.60,Commerce,...,64.5350,64.60,Hired,False,9.4,Average,Commerce_Mkt&Fin,263.14,True,B
150,Placed,151,F,71.00,Central,58.66,Central,Science,58.00,Sci&Tech,...,62.2400,58.00,Hired,False,6.9,Average,Sci&Tech_Mkt&Fin,253.96,True,B
177,Placed,178,M,73.00,Central,97.00,Others,Commerce,79.00,Commerce,...,79.9525,79.00,Hired,False,6.5,Average,Commerce_Mkt&Fin,324.81,True,A
163,Placed,164,F,63.00,Others,67.00,Others,Science,64.00,Sci&Tech,...,65.1150,64.00,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,265.46,True,B
77,Placed,78,F,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,...,66.6625,65.00,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,271.65,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Not Placed,185,M,56.28,Others,62.83,Others,Commerce,59.79,Commerce,...,59.0475,59.79,Not Hired,False,NaN,Average,Commerce_Mkt&HR,241.19,False,B
206,Not Placed,207,F,41.00,Central,42.00,Central,Science,60.00,Commerce,...,49.0975,60.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.39,False,B
201,Not Placed,202,F,54.20,Central,63.00,Others,Science,58.00,Commerce,...,58.4100,58.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.64,False,B
208,Not Placed,209,M,43.00,Central,60.00,Others,Science,65.00,Commerce,...,57.7300,65.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,235.92,False,B
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [140]:
#77. Sort by degree_p and then by mba_p.
data.sort_values(by=["degree_p","mba_p"])

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
14,Not Placed,15,F,62.00,Central,47.0,Central,Commerce,50.0,Commerce,...,53.4900,50.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,218.96,False,B
25,Not Placed,26,M,52.58,Others,54.6,Central,Commerce,50.2,Commerce,...,55.6775,50.2,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,227.71,False,B
91,Not Placed,92,F,52.00,Central,57.0,Central,Commerce,50.8,Commerce,...,55.6475,50.8,Not Hired,False,NaN,Average,Commerce_Mkt&HR,227.59,False,B
3,Not Placed,4,F,56.00,Central,52.0,Central,Science,52.0,Sci&Tech,...,54.8575,52.0,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False,B
34,Not Placed,35,F,62.00,Others,51.0,Others,Science,52.0,Others,...,56.9425,52.0,Not Hired,False,NaN,Average,Others_Mkt&HR,232.77,False,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Placed,91,M,85.00,Others,90.0,Others,Commerce,82.0,Commerce,...,81.2575,82.0,Hired,True,3.00,Excellent,Commerce_Mkt&Fin,330.03,True,B
107,Placed,108,F,82.00,Others,90.0,Others,Commerce,83.0,Commerce,...,82.1300,83.0,Hired,True,2.00,Excellent,Commerce_Mkt&HR,333.52,True,A
152,Placed,153,M,75.40,Others,60.5,Central,Science,84.0,Sci&Tech,...,71.2875,84.0,Hired,False,2.40,Excellent,Sci&Tech_Mkt&Fin,290.15,True,B
21,Placed,22,M,79.00,Others,76.0,Others,Commerce,85.0,Commerce,...,77.2650,85.0,Hired,False,3.93,Excellent,Commerce_Mkt&Fin,314.06,True,B
197,Placed,198,M,83.96,Others,53.0,Others,Science,91.0,Sci&Tech,...,74.4175,91.0,Hired,True,2.60,Excellent,Sci&Tech_Mkt&HR,302.67,True,B

In [141]:
#78. Sort all placed students by salary.
placed

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
7,Placed,8,F,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,...,68.5350,66.00,Hired,True,2.52,Average,Sci&Tech_Mkt&Fin,279.14,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,Placed,210,F,62.00,Central,72.00,Central,Commerce,65.00,Commerce,...,63.8725,65.00,Hired,False,2.16,Average,Commerce_Mkt&Fin,260.49,True,B
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True,B
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True,B

In [142]:
placed.sort_values(by="salary",ascending=False)

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
119,Placed,120,F,60.80,Central,68.40,Central,Commerce,64.60,Commerce,...,64.5350,64.60,Hired,False,9.4,Average,Commerce_Mkt&Fin,263.14,True,B
150,Placed,151,F,71.00,Central,58.66,Central,Science,58.00,Sci&Tech,...,62.2400,58.00,Hired,False,6.9,Average,Sci&Tech_Mkt&Fin,253.96,True,B
177,Placed,178,M,73.00,Central,97.00,Others,Commerce,79.00,Commerce,...,79.9525,79.00,Hired,False,6.5,Average,Commerce_Mkt&Fin,324.81,True,A
77,Placed,78,F,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,...,66.6625,65.00,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,271.65,True,B
163,Placed,164,F,63.00,Others,67.00,Others,Science,64.00,Sci&Tech,...,65.1150,64.00,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,265.46,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,75.3550,77.48,Hired,False,2.0,Average,Sci&Tech_Mkt&Fin,306.42,True,B
107,Placed,108,F,82.00,Others,90.00,Others,Commerce,83.00,Commerce,...,82.1300,83.00,Hired,True,2.0,Excellent,Commerce_Mkt&HR,333.52,True,A
44,Placed,45,M,77.00,Others,73.00,Others,Commerce,81.00,Commerce,...,75.1750,81.00,Hired,False,2.0,Excellent,Commerce_Mkt&Fin,305.70,True,B
50,Placed,51,M,75.20,Central,73.20,Central,Science,68.40,Commerce,...,69.9450,68.40,Hired,False,2.0,Average,Commerce_Mkt&HR,284.78,True,B
135,Placed,136,M,72.00,Central,56.00,Others,Science,69.00,Commerce,...,65.6575,69.00,Hired,False,2.0,Average,Commerce_Mkt&HR,267.63,True,B

In [143]:
#79. Sort the entire dataset by ssc_p ascending.
data.sort_values(by="ssc_p")

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
52,Not Placed,53,M,40.89,Others,45.83,Others,Commerce,53.00,Commerce,...,51.3025,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,210.21,False,B
206,Not Placed,207,F,41.00,Central,42.00,Central,Science,60.00,Commerce,...,49.0975,60.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.39,False,B
208,Not Placed,209,M,43.00,Central,60.00,Others,Science,65.00,Commerce,...,57.7300,65.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,235.92,False,B
149,Not Placed,150,F,44.00,Central,58.00,Central,Arts,55.00,Commerce,...,53.8850,55.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,220.54,False,B
100,Not Placed,101,M,45.00,Others,57.00,Others,Commerce,58.00,Commerce,...,56.2375,58.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,229.95,False,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,Placed,44,F,87.00,Others,87.00,Others,Commerce,68.00,Commerce,...,76.2250,68.00,Hired,True,3.00,Average,Commerce_Mkt&HR,309.90,True,B
33,Placed,34,M,87.00,Others,65.00,Others,Science,81.00,Commerce,...,76.4450,81.00,Hired,True,2.60,Excellent,Commerce_Mkt&Fin,310.78,True,A
160,Placed,161,F,87.00,Central,74.00,Central,Science,65.00,Sci&Tech,...,74.5725,65.00,Hired,True,3.00,Average,Sci&Tech_Mkt&HR,303.29,True,A
185,Placed,186,M,88.00,Central,72.00,Central,Science,78.00,Others,...,77.3575,78.00,Hired,True,2.52,Average,Others_Mkt&HR,314.43,True,A
145,Placed,146,F,89.40,Others,65.66,Others,Science,71.25,Sci&Tech,...,72.3850,71.25,Hired,True,4.00,Average,Sci&Tech_Mkt&HR,294.54,True,B

In [144]:
#80. Set sl_no as the index.
data.set_index("sl_no")

,status,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
sl_no,,,,,,,,,,,,,,,,,,,,,
1,Placed,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,0,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
2,Placed,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,1,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
3,Placed,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,0,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
4,Not Placed,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,0,...,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False,B
5,Placed,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,0,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,Placed,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,0,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
212,Placed,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,0,...,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True,B
213,Placed,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,1,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
214,Placed,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,0,...,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True,B
215,Not Placed,F,62.00,Central,58.00,Others,Science,53.00,Commerce,0,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [145]:
#81. Reset index to default.
data.reset_index()

,index,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
1,1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
2,2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
3,3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,...,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False,B
4,4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
209,211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,...,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True,B
210,212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
211,213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,...,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True,B
212,214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [146]:
#82. Sort students first by status, then by salary (descending).
data.sort_values(by=["status","salary"],ascending=False)

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
119,Placed,120,F,60.8,Central,68.40,Central,Commerce,64.6,Commerce,...,64.5350,64.6,Hired,False,9.4,Average,Commerce_Mkt&Fin,263.14,True,B
150,Placed,151,F,71.0,Central,58.66,Central,Science,58.0,Sci&Tech,...,62.2400,58.0,Hired,False,6.9,Average,Sci&Tech_Mkt&Fin,253.96,True,B
177,Placed,178,M,73.0,Central,97.00,Others,Commerce,79.0,Commerce,...,79.9525,79.0,Hired,False,6.5,Average,Commerce_Mkt&Fin,324.81,True,A
77,Placed,78,F,64.0,Others,80.00,Others,Science,65.0,Sci&Tech,...,66.6625,65.0,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,271.65,True,B
163,Placed,164,F,63.0,Others,67.00,Others,Science,64.0,Sci&Tech,...,65.1150,64.0,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,265.46,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,Not Placed,199,M,67.0,Central,70.00,Central,Commerce,65.0,Others,...,68.4900,65.0,Not Hired,False,NaN,Average,Others_Mkt&HR,278.96,False,A
201,Not Placed,202,F,54.2,Central,63.00,Others,Science,58.0,Commerce,...,58.4100,58.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.64,False,B
206,Not Placed,207,F,41.0,Central,42.00,Central,Science,60.0,Commerce,...,49.0975,60.0,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.39,False,B
208,Not Placed,209,M,43.0,Central,60.00,Others,Science,65.0,Commerce,...,57.7300,65.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,235.92,False,B
214,Not Placed,215,F,62.0,Central,58.00,Others,Science,53.0,Commerce,...,58.3050,53.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [147]:
#83. Retrieve top 5 students with highest mba_p.
data.sort_values(by="mba_p",ascending=False).head(5)

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
19,Placed,20,F,60.00,Others,67.00,Others,Arts,70.00,Commerce,...,68.7225,70.00,Hired,False,2.36,Average,Commerce_Mkt&Fin,279.89,True,A
128,Placed,129,F,80.40,Central,73.40,Central,Science,77.72,Sci&Tech,...,76.9450,77.72,Hired,True,4.00,Average,Sci&Tech_Mkt&HR,312.78,True,A
85,Placed,86,M,83.84,Others,89.83,Others,Commerce,77.20,Commerce,...,81.7625,77.20,Hired,True,4.00,Average,Commerce_Mkt&Fin,332.05,True,A
167,Not Placed,168,F,67.90,Others,62.00,Others,Science,67.00,Sci&Tech,...,68.1525,67.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&Fin,277.61,False,A
165,Not Placed,166,M,63.30,Central,78.33,Others,Commerce,74.00,Commerce,...,72.5475,74.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,295.19,False,A

In [148]:
#84. Retrieve bottom 10 students with lowest degree_p.
data.sort_values(by="degree_p",ascending=False).tail(10)

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
188,Not Placed,189,F,61.80,Others,47.00,Others,Commerce,54.38,Commerce,...,54.8275,54.38,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,224.31,False,B
93,Not Placed,94,F,52.00,Central,62.00,Central,Commerce,54.00,Commerce,...,55.8525,54.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,228.41,False,B
106,Not Placed,107,F,61.08,Others,50.00,Others,Science,54.00,Sci&Tech,...,57.6925,54.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&Fin,235.77,False,B
52,Not Placed,53,M,40.89,Others,45.83,Others,Commerce,53.00,Commerce,...,51.3025,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,210.21,False,B
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B
34,Not Placed,35,F,62.00,Others,51.00,Others,Science,52.00,Others,...,56.9425,52.00,Not Hired,False,NaN,Average,Others_Mkt&HR,232.77,False,B
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,...,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False,B
91,Not Placed,92,F,52.00,Central,57.00,Central,Commerce,50.80,Commerce,...,55.6475,50.80,Not Hired,False,NaN,Average,Commerce_Mkt&HR,227.59,False,B
25,Not Placed,26,M,52.58,Others,54.60,Central,Commerce,50.20,Commerce,...,55.6775,50.20,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,227.71,False,B
14,Not Placed,15,F,62.00,Central,47.00,Central,Commerce,50.00,Commerce,...,53.4900,50.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,218.96,False,B

In [149]:
#85. Use .nlargest() to get top 5 salaries.
data.nlargest(5,"salary")

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
119,Placed,120,F,60.8,Central,68.40,Central,Commerce,64.6,Commerce,...,64.5350,64.6,Hired,False,9.4,Average,Commerce_Mkt&Fin,263.14,True,B
150,Placed,151,F,71.0,Central,58.66,Central,Science,58.0,Sci&Tech,...,62.2400,58.0,Hired,False,6.9,Average,Sci&Tech_Mkt&Fin,253.96,True,B
177,Placed,178,M,73.0,Central,97.00,Others,Commerce,79.0,Commerce,...,79.9525,79.0,Hired,False,6.5,Average,Commerce_Mkt&Fin,324.81,True,A
77,Placed,78,F,64.0,Others,80.00,Others,Science,65.0,Sci&Tech,...,66.6625,65.0,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,271.65,True,B
163,Placed,164,F,63.0,Others,67.00,Others,Science,64.0,Sci&Tech,...,65.1150,64.0,Hired,False,5.0,Average,Sci&Tech_Mkt&Fin,265.46,True,B

In [150]:
#86. Use .nsmallest() to get 3 lowest etest_p values.
data.nsmallest(3,"etest_p")

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
20,Placed,21,F,62.0,Others,65.0,Others,Commerce,66.0,Commerce,...,62.4250,66.0,Hired,False,2.65,Average,Commerce_Mkt&HR,254.70,True,B
99,Not Placed,100,F,54.0,Central,82.0,Others,Commerce,63.0,Sci&Tech,...,64.6175,63.0,Not Hired,False,NaN,Average,Sci&Tech_Mkt&Fin,263.47,False,B
190,Not Placed,191,M,64.0,Others,70.2,Central,Commerce,61.0,Commerce,...,64.4250,61.0,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,262.70,False,B

In [152]:
#87. Select rows using .loc[] for index 10 to 20.
data.loc[10:20]

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
10,Placed,11,F,58.0,Central,61.0,Central,Commerce,60.0,Commerce,...,59.9625,60.0,Hired,False,2.60,Average,Commerce_Mkt&HR,244.85,True,B
11,Placed,12,F,69.6,Central,68.4,Central,Commerce,78.3,Commerce,...,70.0000,78.3,Hired,False,2.50,Average,Commerce_Mkt&Fin,285.00,True,B
12,Not Placed,13,M,47.0,Central,55.0,Others,Science,65.0,Commerce,...,58.0100,65.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,237.04,False,B
13,Placed,14,M,77.0,Central,87.0,Central,Commerce,59.0,Commerce,...,72.9075,59.0,Hired,False,2.18,Average,Commerce_Mkt&Fin,296.63,True,B
14,Not Placed,15,F,62.0,Central,47.0,Central,Commerce,50.0,Commerce,...,53.4900,50.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,218.96,False,B
15,Placed,16,M,65.0,Central,75.0,Central,Commerce,69.0,Commerce,...,68.4150,69.0,Hired,False,2.00,Average,Commerce_Mkt&Fin,278.66,True,B
16,Placed,17,F,63.0,Central,66.2,Central,Commerce,65.6,Commerce,...,64.3350,65.6,Hired,False,3.00,Average,Commerce_Mkt&Fin,262.34,True,B
17,Not Placed,18,M,55.0,Central,67.0,Central,Commerce,64.0,Commerce,...,63.3200,64.0,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,258.28,False,B
18,Not Placed,19,M,63.0,Central,66.0,Central,Commerce,64.0,Commerce,...,64.2700,64.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,262.08,False,B
19,Placed,20,F,60.0,Others,67.0,Others,Arts,70.0,Commerce,...,68.7225,70.0,Hired,False,2.36,Average,Commerce_Mkt&Fin,279.89,True,A
20,Placed,21,F,62.0,Others,65.0,Others,Commerce,66.0,Commerce,...,62.4250,66.0,Hired,False,2.65,Average,Commerce_Mkt&HR,254.70,True,B

In [157]:
#88. Use .iloc[] to get first 3 columns and first 10 rows.
data.iloc[0:10,0:3]

       status  sl_no gender
0      Placed      1      F
1      Placed      2      F
2      Placed      3      F
3  Not Placed      4      F
4      Placed      5      F
5  Not Placed      6      F
6  Not Placed      7      M
7      Placed      8      F
8      Placed      9      F
9  Not Placed     10      F

In [158]:
#89. Sort dataset alphabetically by degree_t.
data.sort_values(by="degree_t")

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
108,Placed,109,F,61.0,Central,82.0,Central,Commerce,69.00,Commerce,...,67.5775,69.00,Hired,False,3.00,Average,Commerce_Mkt&Fin,275.31,True,B
120,Not Placed,121,F,58.0,Others,40.0,Others,Science,59.00,Commerce,...,53.9525,59.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,220.81,False,B
122,Placed,123,M,66.5,Central,66.8,Central,Arts,69.30,Commerce,...,68.4000,69.30,Hired,False,2.36,Average,Commerce_Mkt&Fin,278.60,True,A
123,Placed,124,F,74.0,Others,59.0,Others,Commerce,73.00,Commerce,...,65.6750,73.00,Hired,False,2.40,Average,Commerce_Mkt&HR,267.70,True,B
125,Placed,126,M,84.0,Central,73.0,Central,Commerce,73.00,Commerce,...,75.8325,73.00,Hired,True,3.50,Average,Commerce_Mkt&Fin,308.33,True,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,Placed,54,F,80.0,Others,70.0,Others,Science,72.00,Sci&Tech,...,73.2600,72.00,Hired,False,4.50,Average,Sci&Tech_Mkt&HR,298.04,True,A
128,Placed,129,F,80.4,Central,73.4,Central,Science,77.72,Sci&Tech,...,76.9450,77.72,Hired,True,4.00,Average,Sci&Tech_Mkt&HR,312.78,True,A
126,Placed,127,M,79.0,Others,61.0,Others,Science,75.50,Sci&Tech,...,70.9250,75.50,Hired,False,2.10,Average,Sci&Tech_Mkt&Fin,288.70,True,B
121,Placed,122,M,64.0,Central,67.0,Others,Science,69.60,Sci&Tech,...,68.0225,69.60,Hired,False,2.50,Average,Sci&Tech_Mkt&HR,277.09,True,A
0,Placed,1,F,67.0,Others,91.0,Others,Commerce,58.00,Sci&Tech,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B

In [159]:
#90. Display all columns except sl_no and salary.
data_f=data.drop(columns=["sl_no","salary"])

In [160]:
data_f

,status,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,Placed,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,0,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
1,Placed,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,1,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
2,Placed,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,0,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
3,Not Placed,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,0,...,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False,B
4,Placed,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,0,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Placed,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,0,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
211,Placed,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,0,...,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True,B
212,Placed,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,1,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
213,Placed,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,0,...,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True,B
214,Not Placed,F,62.00,Central,58.00,Others,Science,53.00,Commerce,0,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [163]:
#91. Select only gender, status, salary, and specialisation columns.
data[["gender","status",'salary',"specialisation"]]

    gender      status    salary specialisation
0        F      Placed  270000.0         Mkt&HR
1        F      Placed  200000.0        Mkt&Fin
2        F      Placed  250000.0        Mkt&Fin
3        F  Not Placed       0.0         Mkt&HR
4        F      Placed  425000.0        Mkt&Fin
..     ...         ...       ...            ...
210      F      Placed  400000.0        Mkt&Fin
211      F      Placed  275000.0        Mkt&Fin
212      F      Placed  295000.0        Mkt&Fin
213      M      Placed  204000.0         Mkt&HR
214      F  Not Placed       0.0         Mkt&HR

[213 rows x 4 columns]

In [164]:
#92. Filter dataset for first and last 5 rows together.
first=data.head(5)
tail=data.tail(5)

In [166]:
concat=pd.concat([first,tail])

In [167]:
concat

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
3,Not Placed,4,F,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,...,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False,B
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True,B
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True,B
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [168]:
#93. Reorder columns alphabetically.
data.sort_index(axis=1)

,above_80_ssc,degree_and_specialization,degree_p,degree_percentage,degree_t,etest_p,gender,hsc_b,hsc_p,hsc_s,...,placement_status,salary,salary_in_lpa,sl_no,specialisation,ssc_b,ssc_p,status,total_score,workex
0,False,Sci&Tech_Mkt&HR,58.00,58.00,Sci&Tech,55.0,F,Others,91.00,Commerce,...,Hired,270000.0,2.70,1,Mkt&HR,Others,67.00,Placed,279.80,0
1,False,Sci&Tech_Mkt&Fin,77.48,77.48,Sci&Tech,86.5,F,Others,78.33,Science,...,Hired,200000.0,2.00,2,Mkt&Fin,Central,79.33,Placed,306.42,1
2,False,Commerce_Mkt&Fin,64.00,64.00,Commerce,75.0,F,Central,68.00,Arts,...,Hired,250000.0,2.50,3,Mkt&Fin,Central,65.00,Placed,259.80,0
3,False,Sci&Tech_Mkt&HR,52.00,52.00,Sci&Tech,66.0,F,Central,52.00,Science,...,Not Hired,0.0,NaN,4,Mkt&HR,Central,56.00,Not Placed,224.43,0
4,True,Commerce_Mkt&Fin,73.30,73.30,Commerce,96.8,F,Central,73.60,Commerce,...,Hired,425000.0,4.25,5,Mkt&Fin,Central,85.80,Placed,293.20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,True,Commerce_Mkt&Fin,77.60,77.60,Commerce,91.0,F,Others,82.00,Commerce,...,Hired,400000.0,4.00,211,Mkt&Fin,Others,80.60,Placed,319.69,0
211,False,Sci&Tech_Mkt&Fin,72.00,72.00,Sci&Tech,74.0,F,Others,60.00,Science,...,Hired,275000.0,2.75,212,Mkt&Fin,Others,58.00,Placed,248.62,0
212,False,Commerce_Mkt&Fin,73.00,73.00,Commerce,59.0,F,Others,67.00,Commerce,...,Hired,295000.0,2.95,213,Mkt&Fin,Others,67.00,Placed,281.72,1
213,False,Commerce_Mkt&HR,58.00,58.00,Commerce,70.0,M,Others,66.00,Commerce,...,Hired,204000.0,2.04,214,Mkt&HR,Others,74.00,Placed,263.23,0
214,False,Commerce_Mkt&HR,53.00,53.00,Commerce,89.0,F,Others,58.00,Science,...,Not Hired,0.0,NaN,215,Mkt&HR,Central,62.00,Not Placed,238.22,0

In [172]:
#94. Sort dataset based on the rounded value of etest_p.
data.sort_values(by='etest_p',key=lambda col: col.round(0))

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
20,Placed,21,F,62.0,Others,65.0,Others,Commerce,66.00,Commerce,...,62.4250,66.00,Hired,False,2.65,Average,Commerce_Mkt&HR,254.70,True,B
19,Placed,20,F,60.0,Others,67.0,Others,Arts,70.00,Commerce,...,68.7225,70.00,Hired,False,2.36,Average,Commerce_Mkt&Fin,279.89,True,A
99,Not Placed,100,F,54.0,Central,82.0,Others,Commerce,63.00,Sci&Tech,...,64.6175,63.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&Fin,263.47,False,B
190,Not Placed,191,M,64.0,Others,70.2,Central,Commerce,61.00,Commerce,...,64.4250,61.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,262.70,False,B
32,Placed,33,M,61.0,Central,81.0,Central,Commerce,66.40,Commerce,...,67.6525,66.40,Hired,False,2.78,Average,Commerce_Mkt&HR,275.61,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Placed,119,F,76.0,Central,80.0,Central,Science,78.00,Sci&Tech,...,76.1200,78.00,Hired,False,2.76,Average,Sci&Tech_Mkt&HR,309.48,True,A
4,Placed,5,F,85.8,Central,73.6,Central,Commerce,73.30,Commerce,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
24,Placed,25,F,76.5,Others,97.7,Others,Science,78.86,Sci&Tech,...,81.7675,78.86,Hired,False,3.60,Average,Sci&Tech_Mkt&Fin,332.07,True,A
206,Not Placed,207,F,41.0,Central,42.0,Central,Science,60.00,Commerce,...,49.0975,60.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.39,False,B
152,Placed,153,M,75.4,Others,60.5,Central,Science,84.00,Sci&Tech,...,71.2875,84.00,Hired,False,2.40,Excellent,Sci&Tech_Mkt&Fin,290.15,True,B

In [171]:
data.sort_values(by="etest_p")

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
20,Placed,21,F,62.0,Others,65.0,Others,Commerce,66.00,Commerce,...,62.4250,66.00,Hired,False,2.65,Average,Commerce_Mkt&HR,254.70,True,B
99,Not Placed,100,F,54.0,Central,82.0,Others,Commerce,63.00,Sci&Tech,...,64.6175,63.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&Fin,263.47,False,B
190,Not Placed,191,M,64.0,Others,70.2,Central,Commerce,61.00,Commerce,...,64.4250,61.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,262.70,False,B
19,Placed,20,F,60.0,Others,67.0,Others,Arts,70.00,Commerce,...,68.7225,70.00,Hired,False,2.36,Average,Commerce_Mkt&Fin,279.89,True,A
32,Placed,33,M,61.0,Central,81.0,Central,Commerce,66.40,Commerce,...,67.6525,66.40,Hired,False,2.78,Average,Commerce_Mkt&HR,275.61,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Placed,5,F,85.8,Central,73.6,Central,Commerce,73.30,Commerce,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
118,Placed,119,F,76.0,Central,80.0,Central,Science,78.00,Sci&Tech,...,76.1200,78.00,Hired,False,2.76,Average,Sci&Tech_Mkt&HR,309.48,True,A
206,Not Placed,207,F,41.0,Central,42.0,Central,Science,60.00,Commerce,...,49.0975,60.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.39,False,B
24,Placed,25,F,76.5,Others,97.7,Others,Science,78.86,Sci&Tech,...,81.7675,78.86,Hired,False,3.60,Average,Sci&Tech_Mkt&Fin,332.07,True,A
152,Placed,153,M,75.4,Others,60.5,Central,Science,84.00,Sci&Tech,...,71.2875,84.00,Hired,False,2.40,Excellent,Sci&Tech_Mkt&Fin,290.15,True,B

In [173]:
#95. Extract all rows with even index numbers only.
data.iloc[::2]

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,Placed,1,F,67.0,Others,91.0,Others,Commerce,58.0,Sci&Tech,...,68.7000,58.0,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
2,Placed,3,F,65.0,Central,68.0,Central,Arts,64.0,Commerce,...,63.7000,64.0,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
4,Placed,5,F,85.8,Central,73.6,Central,Commerce,73.3,Commerce,...,72.0500,73.3,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
6,Not Placed,7,M,46.0,Others,49.2,Others,Commerce,79.0,Commerce,...,56.8725,79.0,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,232.49,False,B
8,Placed,9,F,73.0,Central,79.0,Central,Commerce,72.0,Commerce,...,71.3225,72.0,Hired,False,2.31,Average,Commerce_Mkt&Fin,290.29,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,Not Placed,207,F,41.0,Central,42.0,Central,Science,60.0,Commerce,...,49.0975,60.0,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.39,False,B
208,Not Placed,209,M,43.0,Central,60.0,Others,Science,65.0,Commerce,...,57.7300,65.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,235.92,False,B
210,Placed,211,F,80.6,Others,82.0,Others,Commerce,77.6,Commerce,...,78.6725,77.6,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
212,Placed,213,F,67.0,Others,67.0,Others,Commerce,73.0,Commerce,...,69.1800,73.0,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
214,Not Placed,215,F,62.0,Central,58.0,Others,Science,53.0,Commerce,...,58.3050,53.0,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [174]:
#96. Concatenate two subsets: one for Placed and one for Not Placed.
placed

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
7,Placed,8,F,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,...,68.5350,66.00,Hired,True,2.52,Average,Sci&Tech_Mkt&Fin,279.14,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,Placed,210,F,62.00,Central,72.00,Central,Commerce,65.00,Commerce,...,63.8725,65.00,Hired,False,2.16,Average,Commerce_Mkt&Fin,260.49,True,B
210,Placed,211,F,80.60,Others,82.00,Others,Commerce,77.60,Commerce,...,78.6725,77.60,Hired,True,4.00,Average,Commerce_Mkt&Fin,319.69,True,A
211,Placed,212,F,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,...,60.9050,72.00,Hired,False,2.75,Average,Sci&Tech_Mkt&Fin,248.62,True,B
212,Placed,213,F,67.00,Others,67.00,Others,Commerce,73.00,Commerce,...,69.1800,73.00,Hired,False,2.95,Average,Commerce_Mkt&Fin,281.72,True,B
213,Placed,214,M,74.00,Others,66.00,Others,Commerce,58.00,Commerce,...,64.5575,58.00,Hired,False,2.04,Average,Commerce_Mkt&HR,263.23,True,B

In [175]:
Not_placed=data[data["status"]=="Not Placed"]

In [176]:
Not_placed

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
3,Not Placed,4,F,56.0,Central,52.0,Central,Science,52.00,Sci&Tech,...,54.8575,52.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&HR,224.43,False,B
5,Not Placed,6,F,55.0,Others,49.8,Others,Science,67.25,Sci&Tech,...,55.9075,67.25,Not Hired,False,NaN,Average,Sci&Tech_Mkt&Fin,228.63,False,B
6,Not Placed,7,M,46.0,Others,49.2,Others,Commerce,79.00,Commerce,...,56.8725,79.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,232.49,False,B
9,Not Placed,10,F,58.0,Central,70.0,Central,Commerce,61.00,Commerce,...,60.3025,61.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,246.21,False,B
12,Not Placed,13,M,47.0,Central,55.0,Others,Science,65.00,Commerce,...,58.0100,65.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,237.04,False,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,Not Placed,199,M,67.0,Central,70.0,Central,Commerce,65.00,Others,...,68.4900,65.00,Not Hired,False,NaN,Average,Others_Mkt&HR,278.96,False,A
201,Not Placed,202,F,54.2,Central,63.0,Others,Science,58.00,Commerce,...,58.4100,58.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.64,False,B
206,Not Placed,207,F,41.0,Central,42.0,Central,Science,60.00,Commerce,...,49.0975,60.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.39,False,B
208,Not Placed,209,M,43.0,Central,60.0,Others,Science,65.00,Commerce,...,57.7300,65.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,235.92,False,B
214,Not Placed,215,F,62.0,Central,58.0,Others,Science,53.00,Commerce,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [179]:
pd.concat([placed,Not_placed])

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
0,Placed,1,F,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,...,68.7000,58.00,Hired,False,2.70,Average,Sci&Tech_Mkt&HR,279.80,True,B
1,Placed,2,F,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,...,75.3550,77.48,Hired,False,2.00,Average,Sci&Tech_Mkt&Fin,306.42,True,B
2,Placed,3,F,65.00,Central,68.00,Central,Arts,64.00,Commerce,...,63.7000,64.00,Hired,False,2.50,Average,Commerce_Mkt&Fin,259.80,True,B
4,Placed,5,F,85.80,Central,73.60,Central,Commerce,73.30,Commerce,...,72.0500,73.30,Hired,True,4.25,Average,Commerce_Mkt&Fin,293.20,True,B
7,Placed,8,F,82.00,Central,64.00,Central,Science,66.00,Sci&Tech,...,68.5350,66.00,Hired,True,2.52,Average,Sci&Tech_Mkt&Fin,279.14,True,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,Not Placed,199,M,67.00,Central,70.00,Central,Commerce,65.00,Others,...,68.4900,65.00,Not Hired,False,NaN,Average,Others_Mkt&HR,278.96,False,A
201,Not Placed,202,F,54.20,Central,63.00,Others,Science,58.00,Commerce,...,58.4100,58.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.64,False,B
206,Not Placed,207,F,41.00,Central,42.00,Central,Science,60.00,Commerce,...,49.0975,60.00,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,201.39,False,B
208,Not Placed,209,M,43.00,Central,60.00,Others,Science,65.00,Commerce,...,57.7300,65.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,235.92,False,B
214,Not Placed,215,F,62.00,Central,58.00,Others,Science,53.00,Commerce,...,58.3050,53.00,Not Hired,False,NaN,Average,Commerce_Mkt&HR,238.22,False,B

In [180]:
#97. Merge two DataFrames — one containing gender, salary; another with gender, mba_p.
d1=data[["gender","salary"]]
d2=data[["gender","mba_p"]]

In [182]:
d1

    gender    salary
0        F  270000.0
1        F  200000.0
2        F  250000.0
3        F       0.0
4        F  425000.0
..     ...       ...
210      F  400000.0
211      F  275000.0
212      F  295000.0
213      M  204000.0
214      F       0.0

[213 rows x 2 columns]

In [183]:
d2

    gender  mba_p
0        F  63.80
1        F  71.28
2        F  62.80
3        F  64.43
4        F  60.50
..     ...    ...
210      F  79.49
211      F  58.62
212      F  74.72
213      M  65.23
214      F  65.22

[213 rows x 2 columns]

In [181]:
pd.merge(d1,d2,left_on="gender",right_on="gender",how="inner")

      gender    salary  mba_p
0          F  270000.0  63.80
1          F  270000.0  71.28
2          F  270000.0  62.80
3          F  270000.0  64.43
4          F  270000.0  60.50
...      ...       ...    ...
24664      F       0.0  61.49
24665      F       0.0  79.49
24666      F       0.0  58.62
24667      F       0.0  74.72
24668      F       0.0  65.22

[24669 rows x 3 columns]

In [185]:
#98. Join two small DataFrames on specialisation.
data1 = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'specialisation': ['Physics', 'Chemistry', 'Math', 'Physics'],
    'Age': [24, 27, 22, 32]}

In [186]:
data2 = {
    'specialisation': ['Physics', 'Chemistry', 'Biology'],
    'Department': ['Science', 'Science', 'Science'],
    'Building': [101, 102, 103]
}

In [195]:
data1

{'Name': ['Alice', 'Bob', 'Charlie', 'David'],
 'specialisation': ['Physics', 'Chemistry', 'Math', 'Physics'],
 'Age': [24, 27, 22, 32]}

In [196]:
data2

{'specialisation': ['Physics', 'Chemistry', 'Biology'],
 'Department': ['Science', 'Science', 'Science'],
 'Building': [101, 102, 103]}

In [197]:
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)

In [198]:
df1

      Name specialisation  Age
0    Alice        Physics   24
1      Bob      Chemistry   27
2  Charlie           Math   22
3    David        Physics   32

In [199]:
df2

  specialisation Department  Building
0        Physics    Science       101
1      Chemistry    Science       102
2        Biology    Science       103

In [200]:
pd.merge(df1,df2,on="specialisation",how="inner")

    Name specialisation  Age Department  Building
0  Alice        Physics   24    Science       101
1    Bob      Chemistry   27    Science       102
2  David        Physics   32    Science       101

In [201]:
#99. Sort records by specialisation and then by descending degree_p.
data.sort_values(by=["specialisation","degree_p"],ascending=False)

,status,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,...,overall_avg,degree_percentage,placement_status,above_80_ssc,salary_in_lpa,performance_tag,degree_and_specialization,total_score,is_placed,mba_grade
197,Placed,198,M,83.96,Others,53.0,Others,Science,91.00,Sci&Tech,...,74.4175,91.00,Hired,True,2.60,Excellent,Sci&Tech_Mkt&HR,302.67,True,B
107,Placed,108,F,82.00,Others,90.0,Others,Commerce,83.00,Commerce,...,82.1300,83.00,Hired,True,2.00,Excellent,Commerce_Mkt&HR,333.52,True,A
118,Placed,119,F,76.00,Central,80.0,Central,Science,78.00,Sci&Tech,...,76.1200,78.00,Hired,False,2.76,Average,Sci&Tech_Mkt&HR,309.48,True,A
185,Placed,186,M,88.00,Central,72.0,Central,Science,78.00,Others,...,77.3575,78.00,Hired,True,2.52,Average,Others_Mkt&HR,314.43,True,A
128,Placed,129,F,80.40,Central,73.4,Central,Science,77.72,Sci&Tech,...,76.9450,77.72,Hired,True,4.00,Average,Sci&Tech_Mkt&HR,312.78,True,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,Not Placed,195,F,52.00,Others,55.0,Others,Commerce,56.30,Commerce,...,57.0100,56.30,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,233.04,False,B
148,Placed,149,M,77.00,Central,86.0,Central,Arts,56.00,Others,...,70.7700,56.00,Hired,False,2.40,Average,Others_Mkt&Fin,288.08,True,B
188,Not Placed,189,F,61.80,Others,47.0,Others,Commerce,54.38,Commerce,...,54.8275,54.38,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,224.31,False,B
106,Not Placed,107,F,61.08,Others,50.0,Others,Science,54.00,Sci&Tech,...,57.6925,54.00,Not Hired,False,NaN,Average,Sci&Tech_Mkt&Fin,235.77,False,B
25,Not Placed,26,M,52.58,Others,54.6,Central,Commerce,50.20,Commerce,...,55.6775,50.20,Not Hired,False,NaN,Average,Commerce_Mkt&Fin,227.71,False,B

In [202]:
#100.Retrieve top 10 highest salaries and display only gender, degree_t, specialisation, and salary.
s_sal=data.sort_values(by="salary",ascending=False)

In [203]:
s_gr=s_sal[["gender","degree_t","specialisation",'salary']]

In [204]:
s_gr.head(10)

    gender  degree_t specialisation    salary
119      F  Commerce        Mkt&Fin  940000.0
150      F  Sci&Tech        Mkt&Fin  690000.0
177      M  Commerce        Mkt&Fin  650000.0
163      F  Sci&Tech        Mkt&Fin  500000.0
77       F  Sci&Tech        Mkt&Fin  500000.0
174      F  Sci&Tech        Mkt&Fin  500000.0
53       F  Sci&Tech         Mkt&HR  450000.0
4        F  Commerce        Mkt&Fin  425000.0
95       F  Commerce        Mkt&Fin  420000.0
39       F  Sci&Tech        Mkt&Fin  411000.0